### ISSUE TITLE
Error when calling overloaded opUnary on opIndex return value

### ISSUE THREAD

**Issue by Mihail-K** [ldc-developers/ldc#1029]
I've noticed a problem with unary operator overloads, but I'm not sure of the exact conditions that cause it. I first noticed the issue in LDC 0.15.0, but it is still present in 0.15.2-beta1.

Consider this statement where we increment (with opUnary) the result of an opIndex call.
```d
counters[sequence][tokens[index + Count]]++; // This produces an error.
```

While this statement compiles correctly in DMD, LDC produces the following error text.
```
Error: CounterRef __dop2421 = this.counters.opIndex(sequence);
 , __dop2421.opIndex(tokens[index + 1LU]) is not an lvalue
```

In the given case, a slight rewrite can be made to work around the error,
```d
auto frequencyRef = counter[sequence][tokens[index + Count]];
frequencyRef++; // This compiles just fine.
```

I first observed the bug [in this commit](https://github.com/Mihail-K/Upset-Waffle/blob/3976d15561e3b3b689f040d23c8891cf9075714c/source/markov.d#L92) of one of my projects.

My current version of LDC, for reference.
```
LDC - the LLVM D compiler (0.15.2):
  based on DMD v2.066.1 and LLVM 3.6.1
  Default target: x86_64-apple-darwin14.3.0
  Host CPU: x86-64
```

**Comment by redstar** [comment]
I checked against commit https://github.com/Mihail-K/Upset-Waffle/commit/3976d15561e3b3b689f040d23c8891cf9075714c. The error message is indeed produced, but dmd 2.066.1 produces the same error message. Does not look like a genuine ldc problem...

**Comment by Mihail-K** [comment]
This is odd. The error doesn't occur in DMD for me, although I am currently building with 2.068.1.

**Comment by redstar** [comment]
The error occurs with dmd 2.067.1 but not with dmd 2.068.1.

**Comment by kinke** [comment]
I'm 99.99% sure this has been working for quite some time now, so I'm closing this.
