### ISSUE TITLE
[Win64] unresolved external symbol __imp___stdio_common_vsprintf

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#1086]
Compile the following project with DUB: https://github.com/p0nce/dplug/tree/master/examples/distort

**OS:** Win64
**Compiler:** Version: LDC 0.16.0-alpha3
**VS linker:** Microsoft Visual Studio 12.0 linker with "-Llegacy_stdio_definitions.lib" commented in `ldc2.conf`

**How to reproduce:**
`$  dub build --build=debug --arch=x86_64 --compiler=ldc2  --force --combined`
(I use `--combined` to avoid #1084 )

**You'll need many 64-bit libraries from the Visual Studio  installation (here, they are in C:\Program Files (x86)\Microsoft Visual Studio 12.0\vc\lib\amd64)**
- AdvAPI32.Lib
- ComCtl32.Lib
- ComDlg32.Lib
- Gdi32.Lib
- kernel32.Lib
- libcmt.lib
- msvcrt.lib
- odbc32.lib
- oldnames.lib
- Ole32.Lib
- OleAut32.Lib
- RpcRT4.Lib
- shell32.lib
- User32.Lib
- Uuid.Lib
- WinMM.Lib
- WinSpool.Lib
- WS2_32.Lib
- WSock32.Lib

(Unrelated: I hit many link warning like this: 
```
phobos2-ldc-debug.lib(crc-debug.obj) : warning LNK4006: Th24_D3std6digest6digest42__T13WrapperDigestTS3std6digest3crc5CRC32Z13WrapperDigest6finishMFNbMAhZAh already defined in imageformats.obj; second definition ignored
```
)

Then I hit the following error: 
```
phobos2-ldc-debug.lib(gzlib.c.obj) : error LNK2019: unresolved external symbol __imp___stdio_common_vsprintf referenced in function _snprintf
```

Not sure how to avoid this one.

**Comment by redstar** [comment]
I think that the problem here is that I created the libraries with VS2015. As far as I remember from development the unresolved symbol is from the VS2015 libraries. The only way out of this is to recompile the libraries with VS2012. This also explains the long list of needed libraries - they are not automatically pulled in.
The warning is issue #988 (and resolved in master).

**Comment by p0nce** [comment]
No problem, I will try to use VS2015 instead.

**Comment by kinke** [comment]
Wrt. to the unresolved symbol: seems like the Phobos C parts don't enjoy the weakly-linked `(v)snprintf` magic in druntime's `rt\stdio_msvc.d`, as here `gzlib.c` uses MS-specific `_snprintf`. We'd need to eliminate the leading underscore.

**Comment by kinke** [comment]
Wrt. the libraries: the ones you listed seem like the absolute basic ones (kernel32.lib, libcmt.lib etc.). What did you have to do to include them, adjust the LIB environment variable? If so, try running dub etc. in a `VS x64 Native Tools Command Prompt` (or invoking `"C:\Program Files (x86)\Microsoft Visual Studio 1x.0\VC\vcvarsall.bat" amd64`) to get properly set-up environment variables.

**Comment by p0nce** [comment]
fyi I just copied them in LDC lib/ directory as needed, done that for 0.15.2-b2 months ago, I believe most were to be found with VS but some might come from the Win SDK.

**Comment by kinke** [comment]
Okay, but that shouldn't be necessary with a properly set `LIB` environment variable, as that one includes the MSVC and WinSDK lib directories.

**Comment by p0nce** [comment]
I now use VS2015 and fixed the LIB variable. I was able to build an executable o/
