### ISSUE TITLE
[0.16.0 alpha4] missing upstream patch(es?) for 2.067.1

### ISSUE THREAD

**Issue by Daniel-N** [ldc-developers/ldc#1099]
I identified one missing patch in order for us to be equivalent with 2.067.1

Issue 14396
https://github.com/D-Programming-Language/phobos/commit/99da04d9af3a4e44d8576445c06d701fe6fdada4

**Comment by Daniel-N** [comment]
std\algorithm\iteration.d also looks slightly out of date...

**Comment by redstar** [comment]
Thanks!

**Comment by Daniel-N** [comment]
Awesome, thanks!

**Comment by redstar** [comment]
Fixed in master.
