### ISSUE TITLE
[Win64] How to avoid the reliance on Visual C++ runtime?

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#1133]
http://forum.dlang.org/post/upebxrwumidxzwwbojom@forum.dlang.org

Programs made with LDC on Win64 require the Visual C++ runtime to run.
http://i.imgur.com/xbU1VeS.png

I wish to avoid that. What to do? Use DMD?
Can we link the runtime statically like in C++?

**Comment by kinke** [comment]
I don't think static linking is the way to go, but that's your choice - but it's definitely not an issue per se. Build LDC yourself using the additional CMake switch `-DLINK_WITH_MSVCRT=OFF`. That will link druntime and Phobos against libcmt.lib instead of msvcrt.lib, and the size of your binary will consequently explode. ;)

**Comment by p0nce** [comment]
> it's the default with MSVC as well.

It's the default with MSVC but in Visual Studio you can use "Statically Linked Runtime" and that doesn't involved rebuilding MSVC. The same MSVC can be used for dynamically linked or statically linked runtime.

**Comment by kinke** [comment]
You actually don't really need to rebuild LDC, just the druntime and Phobos libs only (incl. their C++ parts). You'd need to figure out the commands yourself though, so it's probably less work building LDC as whole by following http://wiki.dlang.org/Building_and_hacking_LDC_on_Windows_using_MSVC and using my pre-built [LLVM 3.7](https://dl.dropboxusercontent.com/s/5cok3dvmohtduy6/llvm-x64-release.7z?dl=0) to speed up the process. You may also have a look at the commands in the [AppVeyor script](https://github.com/ldc-developers/ldc/blob/master/appveyor.yml) used by the Win64 CI builds.

**Comment by p0nce** [comment]
OK thanks. One more question: do you think DMD is also affected by this runtime dependency?

**Comment by kinke** [comment]
I don't know. You can always check a binary's dependencies with a tool like [CFF Explorer](http://www.ntcore.com/exsuite.php). If it has a msvc*.dll dependency, it's been linked dynamically.

**Comment by p0nce** [comment]
Cool. I would use Dependency Walker, but it's not very clear.

**Comment by redstar** [comment]
The question is if we could customize `runtime/CMakeLists.txt` to build both kinds of libraries.

**Comment by p0nce** [comment]
I've tested with DMD and VS2015 linker, CFF Explorer says the output does not depend on msvc140.dll. The MS runtime seems to be statically linked in the 26mb `phobos64.lib` which ship with DMD. 

However the resulting executable is not much larger than in 32-bit (I get 1.9mb vs 2.4mb for a project). I suspect a lot of symbols get pruned by the linker.

**Comment by kinke** [comment]
@redstar: Yeah that's what I've been thinking about too. ;) In combination with something like `-link-[static][debug]lib` - dynamic by default, release by default.

**Comment by kinke** [comment]
@p0nce: Sure, the linker only takes what it needs. A .lib doesn't contain anything from another .lib, so phobos64.lib is just phobos alone. It just contains references to libcmt.lib instead of msvcrt.lib when the C++ parts are compiled with `/MT`. When you link your binary (exe/dll), libcmt.lib will then pull in all functions needed from the MS C runtime by (a) your code directly and indirectly by (b) the Phobos parts your code uses, instead of just referring to the runtime DLL via msvcrt.lib.

**Comment by d-random-contributor** [comment]
What are C++ parts? zlib?

**Comment by kinke** [comment]
Yes, for example (it's C actually iirc) - basically all .*c[pp] files in the druntime/Phobos source directories.

**Comment by kinke** [comment]
There *may* be no need to recompile druntime/Phobos: you can link directly to `libcmt.lib` via `ldc2 bla.d -Llibcmt.lib -L/nodefaultlib:msvcrt.lib`. That works for a hello-word-style program at least.
I'm not sure the MS C headers are independent of that setting though (`/MD` defines `_DLL`, `/MT` doesn't), so I'd be cautious. ;)

**Comment by d-random-contributor** [comment]
DLL should call library functions with dllimport ABI: instead of `call func` uses `call [_imp_func]` - goes through IAT, though last I checked llvm ignored the dllimport attribute on x86-64, maybe it was fixed recently.

**Comment by p0nce** [comment]
OK I've had some success avoiding the Visual C++ runtime.
With `-Llibcmt.lib -L/nodefaultlib:msvcrt.lib -L/nodefaultlib:vcruntime.lib`

In DUB that means:
```
    "lflags-windows-ldc": [
        "libcmt.lib",
        "/nodefaultlib:msvcrt.lib",
        "/nodefaultlib:vcruntime.lib"
    ],
```

Works with both 32-bit and 64-bit LDC.

Analyzing DLL exports, it hasn't any more than an executable made with DMD, and I made one test on another machine (must test more).

**Comment by JohanEngelen** [comment]
@p0nce Good that you found a solution. Do you have an idea how we can test that this will not regress?

Perhaps something like this (the RUN: line will be executed):
```D
// Test that MSVC runtime is not included for the given cmdline switches
// REQUIRES: windows
// RUN:  not %ldc -Llibcmt.lib -L/nodefaultlib:msvcrt.lib -L/nodefaultlib:vcruntime.lib %s

extern(C) someFunctionThatIsOnlyInMSVCRuntime();

void main() {
  return someFunctionThatIsOnlyInMSVCRuntime();
}
```
`not` fails when the following command succeeds. This way, the test only succeeds when LDC does not. So when ldc can link this program, it means MSVC runtime is included, and the test will fail.
Not a waterproof test, but better than nothing.

**Comment by JohanEngelen** [comment]
PR #1296 is needed for such a test.
