### ISSUE TITLE
Large (but not actually memory-filling) allocations throw errors

### ISSUE THREAD

**Issue by nriddick** [ldc-developers/ldc#1140]
```
import std.concurrency;
import std.range;
import std.conv;
void main(string[] args) {
	auto len = 2 ^^ parse!long(args[1]);
	foo(len);
	//auto tids = new Tid[](3);
	//foreach(ref t; tids) t = spawn(&foo, len);
}

void foo(long len) {
	auto x = iota(len).array;
}
```
On my Win64 machine with 16GB RAM, I get an out of memory error at 2 ^^ 27 on one thread. With the two commented lines, 2 ^^ 25 is fine but 26 causes a deadlock. Both work fine on DMD 2.067.1. Using 0.16.0beta1 LDC.

**Comment by kinke** [comment]
Did you check with x86 or x64 DMD? Coz DMD uses the MSVC runtime for x64 and its own on x86.

**Comment by kinke** [comment]
Works for me (32 GB of memory) with 31, but not with 32. I guess it's just a question of whether there's enough contiguous memory for such big allocations, which depends heavily on what other processes are doing etc.

**Comment by nriddick** [comment]
x64, I had problems with static assertions on size_t vs ulong on x86 DMD. After switching everything to size_t's I can also cause x86 DMD to OOM and deadlock. I guess the difference is the background Microsoft magic.

**Comment by kinke** [comment]
I think all druntime allocations boil down to the C runtime's `malloc()` and friends, so that one should be the limiting factor. In that case, the LDC issue can be closed.
