### ISSUE TITLE
[Win64] How to create a dynamic library with exported symbols?

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#1158]
I don't see how to export functions when creating a Windows DLL with LDC.
I've tried to pass a .def file, and to use the `export` attribute before the function definition.
Is there a way?

**Comment by d-random-contributor** [comment]
Try to pass .def file to the linker directly.

**Comment by p0nce** [comment]
Found a DUB solution
` "lflags": ["/DEF:.\\source\\module.def"],`
