### ISSUE TITLE
Frame pointer issue compiling things from std.parallelism

### ISSUE THREAD

**Issue by russel** [ldc-developers/ldc#1166]
Using the code in this file:

https://github.com/russel/Pi_Quadrature/blob/master/D/pi_parallel_batched_parallelMapSequentialReduce.d

compiling with DMD 2.068.2 everything is fine:

|> dmd -I=. -O -release -ofpi_parallel_batched_sequentialMapParallelReduce pi_parallel_batched_sequentialMapParallelReduce.d outputFunctions.d
|> 

However, using LDC compiled from the 2.068 branch (b63a5e3cf8c340a7bd48a7681bddacdf0a5e936c):

|> ldc2 -I=. -O -release -of=pi_parallel_batched_sequentialMapParallelReduce pi_parallel_batched_sequentialMapParallelReduce.d outputFunctions.d
/home/users/russel/Built/include/d/std/parallelism.d(2637): Error: cannot access frame pointer of pi_parallel_batched_sequentialMapParallelReduce.execute.MapResult!(__lambda2, Result).MapResult
/home/users/russel/Built/include/d/std/parallelism.d(2433): Error: function std.parallelism.TaskPool.reduce!"a + b".reduce!(MapResult!(partialSum, MapResult!(__lambda2, Result))).reduce no return exp; or assert(0); at end of function
pi_parallel_batched_sequentialMapParallelReduce.d(30): Error: template instance std.parallelism.TaskPool.reduce!"a + b".reduce!(MapResult!(partialSum, MapResult!(__lambda2, Result))) error instantiating
|>

**Comment by russel** [comment]
I just compiled LDC master (34529d61a574a7cec5edd750f0a967249ebe443d) and it works fine, so the issue is definitely in the 2.068 branch.

**Comment by kinke** [comment]
`fail_compilation/fail39.d` fails due to a related issue. In that case, we miss an invalid nested function call in a function literal (the nested function being in the same scope as the function literal).

**Comment by kinke** [comment]
This leads to https://github.com/D-Programming-Language/dmd/commit/e891688d80a398be2fc41366184cd26e8229406e which fixed DMD bugzilla 14973, related to `std.algorithm.map`.

**Comment by kinke** [comment]
Resolved in master, probably since a while.
