### ISSUE TITLE
Atomic RMW operations emit subpar x86 assembly

### ISSUE THREAD

**Issue by rsw0x** [ldc-developers/ldc#1195]
System: Arch Linux
Architecture: x86_64
LLVM: 3.7.0
LDC: 0.16.1 from Arch repos
Issue description:
All RMW operations seem to use a CAS implementation on x86.

Test case(s), stack traces and other relevant information:
```
shared size_t var = 0;
atomicOp!"+="(var, 1);
```
⇒
```
        ....(omitted)
        lea     rcx, [rax + 1]
        lock
        cmpxchg qword ptr [rsp - 8], rcx

```
expected:
I believe this should be using the xadd op like dmd

**Comment by kinke** [comment]
Thanks, good point. https://github.com/ldc-developers/druntime/pull/37 should fix this.

**Comment by rsw0x** [comment]
@kinke Thanks! That should fix it, closing the issue.
