### ISSUE TITLE
ldmd2 does not default to same executable name as DMD

### ISSUE THREAD

**Issue by ufm** [ldc-developers/ldc#1203]
Simple test:
File "a.d" contained this:

```
module tst;
import std.stdio;
void main() {
     writeln("Hello world");
}
 ```

After compiling this file by "dmd a.d" I get executable with name "a".
After compiling by "ldc2 a.d" - executable with name "tst".

Comment by Kai Nacke on dlang forum :
> ldc2 does not have the goal to be compatible in all aspects with dmd.
> So this behaviour is ok. But: ldmd2 is meant to be compatible with dmd.
> This tool has the same problem which is clearly a bug.

WBR,
    Fyodor.

**Comment by kinke** [comment]
Both ldmd2 and ldc2 now use DMD's name after #1726 and #1771.
