### ISSUE TITLE
Invalid bitcast error

### ISSUE THREAD

**Issue by SiegeLord** [ldc-developers/ldc#1211]
While compiling Tango on 64 bits, LDC 0.16.1 gives me an error (see log here https://travis-ci.org/SiegeLord/Tango-D2/jobs/86535484):

```
Invalid bitcast

  %6 = bitcast %tango.core.Time.seconds.DurationClone %5 to %core.time.Duration

LLVM ERROR: Broken function found, compilation aborted!
```

This code compiled fine with LDC 0.15.1.

**Comment by redstar** [comment]
Confirmed. Happens with 0.17.0-beta2, too.

**Comment by redstar** [comment]
Reduced test case:

    struct Foo
    {
        long baz;
    }
    
    Foo foo(long x)
    {
        struct Bar
        {
            long y;
        }
    
        return cast(Foo)Bar(x);
    }
