### ISSUE TITLE
Microsoft new timezones break Windows testbuilds

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1213]
This commit from dlang/phobos should be applied to LDC's fork:
https://github.com/D-Programming-Language/phobos/commit/e3a239e79a7d0283210ad004260111c480d0fe8d

That should fix one of the build problems on AppVeyor.

I don't know how to apply/merge/? the commit, thanks!

**Comment by kinke** [comment]
Thanks Johan for finding the commit. That Eastern Mexican time was getting on my nerves. ;)
I'll cherry-pick it.

**Comment by kinke** [comment]
AppVeyor is green again, and we have a fresh downloadable Win64 build.
