### ISSUE TITLE
Integrate android patches

### ISSUE THREAD

**Issue by joakim-noah** [ldc-developers/ldc#1264]
I've uploaded [my patch against ldc to build natively on Android itself](https://gist.github.com/joakim-noah/b3362d71b1a0d748e8a5).  It's instructive because it has all the changes I made for the ldc cross-compiler but _leaving out_ Kai and Dan's longdouble commits.  I'm opening this issue so we can coordinate merging my patches back upstream.

There are three additional small changes for native compilation: removing some glibc-specific headers from `dmd2/root/port.c`, removing linker flags that aren't used on Android from `driver/linker.cpp`, and making PIC the default in `driver/targetmachine.cpp`.  Otherwise, the cross-compilation patch for ldc is identical, just with the longdouble changes added in.

I can clean up and submit most of this patch, with two exceptions:

1. The TLS section bracketing I used in `driver/codegenerator.cpp` is a hack: it doesn't quite work right for the tbss zero-initialized section, likely because of the `_tlsend` symbol.  When I tried to do it differently, the symbols were getting stripped out during compilation, not sure why.  If anybody knows how to quickly add those symbols [similarly](https://github.com/D-Programming-Language/dmd/blob/master/src/backend/elfobj.c#L1878) to [dmd](https://github.com/D-Programming-Language/dmd/blob/master/src/backend/elfobj.c#L1643), I'd appreciate if you submitted a PR to do it.  Otherwise, I'll pore over those llvm/ELF details more.  The way I do it now causes the linker to print this warning, though it ultimately works: `bin/ld.bfd: warning: section '.tbss' type changed to PROGBITS`

2. I don't know if the changes to `runtime/CMakeLists.txt` to add Android test-runner targets are wanted.  I added those to make building Android test runners as easy as possible, but I'm not sure if they belong upstream.

Most of the druntime and phobos patches are also useful in the main repos upstream, so that's where I'll submit them.  They can be merged here early or cherry-picked from upstream later.

That raises the question of timeline: should we try to get working Android support into one of the official 0.17 releases or hold off till 0.18?  The update to the D frontend with 0.18 shouldn't affect this effort, as essentially nothing from the frontend directory `dmd2/` is modified by my Android patch.  However, this ldc patch also requires [a small llvm patch to disable native TLS](https://gist.github.com/joakim-noah/1fb23fba1ba5b7e87e1a), so I'll need to add a flag to easily turn that on and off in llvm if we want to release a ldc built against a slightly patched llvm.

Alternately, lvm 3.8 comes with emulated TLS support, but last I used it there were two issues with that new feature: it was pulling in some non-PIC symbols somewhere, which causes a warning on Android before 6.0 and I believe would segfault on 6.0, and I need to figure out how to pass that emulated TLS data to the GC.

So, several decisions need to be made, appreciate some feedback on these.

**Comment by smolt** [comment]
I'll digest bit by bit as I have time.

> I don't know if the changes to runtime/CMakeLists.txt to add Android test-runner targets are wanted.

I am sure they are wanted.  I too have lengthy changes to runtime/CMakeLists.txt.  Maybe for clarity CMakeLists can be broken up in to modules?  Who has cmake experience enough to know good style?

**Comment by joakim-noah** [comment]
I've submitted most of my druntime and phobos patches for Android upstream.  [Druntime PR #1490](https://github.com/D-Programming-Language/druntime/pull/1490) and [Phobos PR #3977](https://github.com/D-Programming-Language/phobos/pull/3977) can be cherry-picked and merged into the ldc branches, as I doubt I'll need to modify them anymore, along with [the older merged Phobos PR #3555](https://github.com/D-Programming-Language/phobos/pull/3555).  All require some minor backporting to be merged.

As for ldc itself, that TLS bracketing issue needs to be fixed before the linked gist can be merged.

**Comment by joakim-noah** [comment]
Now that #1447 was merged, my [remaining](https://gist.github.com/joakim-noah/63693ead3aa62216e1d9) [patches](https://gist.github.com/joakim-noah/d936d6a339426ad1fac3) are [fairly minimal](https://gist.github.com/joakim-noah/5c03801fa6c59b1e90df), mostly avoiding a few remaining ldc issues or working around some older versions of Android.
