### ISSUE TITLE
make install problem

### ISSUE THREAD

**Issue by Temtaime** [ldc-developers/ldc#1289]
> CMake Error at runtime/cmake_install.cmake:116 (file):
>   file INSTALL cannot find "/workshop/ldc/runtime/gccbuiltins_x86.di".
> Call Stack (most recent call first):
>   cmake_install.cmake:109 (include)
> 
> Makefile:148: recipe for target 'install' failed
> make: *** [install] Error 1
> 
> \# find . -name gccbuiltins_x86.di
> ./ldc/build/runtime/gccbuiltins_x86.di

I followed an installation guide, created "build" directory inside "ldc" and then run a cmake && make && make install.
But there seems to be a problem with paths on installing. A script ignores build directory and tries to find a file directly in ldc's directory

**Comment by redstar** [comment]
Confirmed. I now get this error, too.

**Comment by redstar** [comment]
Fixed in master and v0.17.0. Thanks for the report.
