### ISSUE TITLE
Would it be possible to merge the Windows releases for LDC, now that they both use MS linker?

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#1299]
One archive could be good for DUB compatibility.

Right now, LDC doesn't work well within DUB since it will only recognize one LDC executable in PATH.
One needs another build tool to set the right PATH.

DUB sends `-march=x86` or `-march=x86-64` depending on its own command-line `-a x86` or `-a x86_64`.

**Comment by kinke** [comment]
That's the plan for the next release of course, as 32-bit MSVC support isn't official yet, and the required LLVM 3.8 isn't finished yet either. ;)
Compiling 64-bit code should work with the 32-bit build though (`-m64`), but linking will most likely fail due to missing 64-bit .libs.

**Comment by p0nce** [comment]
OK! Nice that it's coming :) No urgent need
