### ISSUE TITLE
Linker error with LLVM_BUILD_LLVM_DYLIB=ON (affects Fedora Rawhide)

### ISSUE THREAD

**Issue by russel** [ldc-developers/ldc#1301]
I just pulled master 894d3a8d12ac371dd34ab7d6a69dfcfbe15ee2df and did the "git submodule update --recursive" thing. Then in a new CMake build repository (I had tried the old one first but thought "must try a clean build". The CMake set up seemed to be fine, no errors, but the build… I think this may be a GCC 6.0 thing:

|> make -j 8
Scanning dependencies of target not
Scanning dependencies of target ldmd2
Scanning dependencies of target impcnvgen
Scanning dependencies of target FileCheck
Scanning dependencies of target idgen
Scanning dependencies of target gen_gccbuiltins
[  1%] Building CXX object CMakeFiles/not.dir/utils/not.cpp.o
[  1%] Building CXX object CMakeFiles/idgen.dir/dmd2/idgen.c.o
[  1%] Building CXX object CMakeFiles/ldmd2.dir/dmd2/root/man.c.o
[  1%] Building CXX object CMakeFiles/FileCheck.dir/utils/FileCheck-3.7.cpp.o
[  1%] Building CXX object CMakeFiles/ldmd2.dir/driver/exe_path.cpp.o
[  1%] Building CXX object CMakeFiles/ldmd2.dir/driver/ldmd.cpp.o
[  1%] Building CXX object CMakeFiles/impcnvgen.dir/dmd2/impcnvgen.c.o
[  1%] Building CXX object CMakeFiles/gen_gccbuiltins.dir/utils/gen_gccbuiltins.cpp.o
[  1%] Linking CXX executable dmd2/idgen
[  1%] Building CXX object CMakeFiles/ldmd2.dir/driver/response.cpp.o
[  1%] Built target idgen
[  1%] Linking CXX executable bin/not
/usr/bin/ld: cannot find -lLLVMOption
/usr/bin/ld: cannot find -lLLVMLTO
/usr/bin/ld: cannot find -lLLVMObjCARCOpts
/usr/bin/ld: cannot find -lLLVMLinker
/usr/bin/ld: cannot find -lLLVMIRReader
/usr/bin/ld: cannot find -lLLVMDebugInfoPDB
/usr/bin/ld: cannot find -lLLVMDebugInfoDWARF
/usr/bin/ld: cannot find -lLLVMBitWriter
/usr/bin/ld: cannot find -lLLVMAsmParser
/usr/bin/ld: cannot find -lLLVMCppBackendCodeGen
/usr/bin/ld: cannot find -lLLVMCppBackendInfo
/usr/bin/ld: cannot find -lLLVMBPFCodeGen
/usr/bin/ld: cannot find -lLLVMBPFDesc
/usr/bin/ld: cannot find -lLLVMBPFInfo
/usr/bin/ld: cannot find -lLLVMBPFAsmPrinter
/usr/bin/ld: cannot find -lLLVMARMDisassembler
/usr/bin/ld: cannot find -lLLVMARMCodeGen
/usr/bin/ld: cannot find -lLLVMARMAsmParser
/usr/bin/ld: cannot find -lLLVMARMDesc
/usr/bin/ld: cannot find -lLLVMARMInfo
/usr/bin/ld: cannot find -lLLVMARMAsmPrinter
/usr/bin/ld: cannot find -lLLVMAArch64Disassembler
/usr/bin/ld: cannot find -lLLVMAArch64CodeGen
/usr/bin/ld: cannot find -lLLVMAArch64AsmParser
/usr/bin/ld: cannot find -lLLVMAArch64Desc
/usr/bin/ld: cannot find -lLLVMAArch64Info
/usr/bin/ld: cannot find -lLLVMAArch64AsmPrinter
/usr/bin/ld: cannot find -lLLVMAArch64Utils
/usr/bin/ld: cannot find -lLLVMSystemZDisassembler
/usr/bin/ld: cannot find -lLLVMSystemZCodeGen
/usr/bin/ld: cannot find -lLLVMSystemZAsmParser
/usr/bin/ld: cannot find -lLLVMSystemZDesc
/usr/bin/ld: cannot find -lLLVMSystemZInfo
/usr/bin/ld: cannot find -lLLVMSystemZAsmPrinter
/usr/bin/ld: cannot find -lLLVMNVPTXCodeGen
/usr/bin/ld: cannot find -lLLVMNVPTXDesc
/usr/bin/ld: cannot find -lLLVMNVPTXInfo
/usr/bin/ld: cannot find -lLLVMNVPTXAsmPrinter
/usr/bin/ld: cannot find -lLLVMPowerPCDisassembler
/usr/bin/ld: cannot find -lLLVMPowerPCCodeGen
/usr/bin/ld: cannot find -lLLVMPowerPCAsmParser
/usr/bin/ld: cannot find -lLLVMPowerPCDesc
/usr/bin/ld: cannot find -lLLVMPowerPCInfo
/usr/bin/ld: cannot find -lLLVMPowerPCAsmPrinter
/usr/bin/ld: cannot find -lLLVMAMDGPUCodeGen
/usr/bin/ld: cannot find -lLLVMipo
/usr/bin/ld: cannot find -lLLVMVectorize
/usr/bin/ld: cannot find -lLLVMAMDGPUAsmParser
/usr/bin/ld: cannot find -lLLVMAMDGPUUtils
/usr/bin/ld: cannot find -lLLVMAMDGPUDesc
/usr/bin/ld: cannot find -lLLVMAMDGPUInfo
/usr/bin/ld: cannot find -lLLVMAMDGPUAsmPrinter
/usr/bin/ld: cannot find -lLLVMX86Disassembler
/usr/bin/ld: cannot find -lLLVMX86AsmParser
/usr/bin/ld: cannot find -lLLVMX86CodeGen
/usr/bin/ld: cannot find -lLLVMSelectionDAG
/usr/bin/ld: cannot find -lLLVMAsmPrinter
/usr/bin/ld: cannot find -lLLVMCodeGen
/usr/bin/ld: cannot find -lLLVMTarget
/usr/bin/ld: cannot find -lLLVMScalarOpts
/usr/bin/ld: cannot find -lLLVMProfileData
/usr/bin/ld: cannot find -lLLVMInstCombine
/usr/bin/ld: cannot find -lLLVMInstrumentation
/usr/bin/ld: cannot find -lLLVMTransformUtils
/usr/bin/ld: cannot find -lLLVMipa
/usr/bin/ld: cannot find -lLLVMAnalysis
/usr/bin/ld: cannot find -lLLVMX86Desc
/usr/bin/ld: cannot find -lLLVMObject
/usr/bin/ld: cannot find -lLLVMMCParser
/usr/bin/ld: cannot find -lLLVMBitReader
/usr/bin/ld: cannot find -lLLVMMCDisassembler
/usr/bin/ld: cannot find -lLLVMX86Info
/usr/bin/ld: cannot find -lLLVMX86AsmPrinter
/usr/bin/ld: cannot find -lLLVMMC
/usr/bin/ld: cannot find -lLLVMX86Utils
/usr/bin/ld: cannot find -lLLVMCore
/usr/bin/ld: cannot find -lLLVMSupport
collect2: error: ld returned 1 exit status
CMakeFiles/not.dir/build.make:94: recipe for target 'bin/not' failed
make[2]: **\* [bin/not] Error 1

**Comment by russel** [comment]
I can't try clang and clang++ just now as they are broken on Rawhide.

**Comment by redstar** [comment]
This is from my memory, may be wrong: LLVM is compiled as a single shared library `libLLVM.so`. This change is not reflected in the `llvm-config` tool which still prints the original library names. IMHO this is a bug in Rawhide. I think a quick work around was to install the static libraries of LLVM.

**Comment by russel** [comment]
Hummm… I think Rawhide actually forced a removal of the static libraries at one point recently. At least for a while, maybe that package is available again. I forgot to check. This is Rawhide of course so stability is not exactly a thing. :-)

**Comment by redstar** [comment]
If LLVM is built with `LLVM_BUILD_LLVM_DYLIB=ON` then we have a similar issue.

**Comment by kinke** [comment]
This was almost certainly resolved at some point - Fedora Rawhide has an LDC v1.25.1 package at the moment: https://fedora.pkgs.org/rawhide/fedora-x86_64/ldc-1.25.1-1.fc35.x86_64.rpm.html

We also have some CI jobs using a distro LLVM, compiled as `libLLVM.so`.
