### ISSUE TITLE
Windows: LDC cannot build itself (DDMD front-end)

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1311]
On Windows, LDC cannot be used to build itself with DDMD front-end (merge-2.069 branch).

The first problem is a linking problem: see #1310 .
This can be circumvented by removing the function definitions in the C++ header files, and adding `/O2 /Zc:inline` to the MSVC compile flags.

However, then `ldc2` immediately crashes on line `  global.params.color = isConsoleColorSupported();` inside `parseCommandLine(...)`. It is the first call into D code, I believe. So perhaps there is also a C++-D interop issue on windows.

**Comment by kinke** [comment]
> So perhaps there is also a C++-D interop issue on windows.

The dmd-testsuite results would suggest that's basically okay.
But we may run into ABI issues, e.g., dynamic arrays aren't rewritten yet (having a size of 16 bytes, they need to be returned via sret). That's still the old runtime-functions-aren't-rewritten yet (when calling them) issue, which is blocking the ABI fix...

**Comment by kinke** [comment]
#1317 will take care of this. Its first commit (built with DMD) was able to build and link itself and then build the stdlibs (tested yesterday on 32-bit MSVC).

**Comment by JohanEngelen** [comment]
Awesome

**Comment by kinke** [comment]
Well LDC can build itself now for quite some time.
