### ISSUE TITLE
Outdated Copyright notice in LICENSE file

### ISSUE THREAD

**Issue by tosttost** [ldc-developers/ldc#1322]
All copyright timespans in the LICENSE file ( ldc2-1.0.0-alpha1-linux-x86_64.tar.xz ) end 2012. 

Example

Copyright (c) 2007-2012 LDC Team.

As the development continues, they should be updated to "-2016"

**Comment by mstahlberg** [comment]
Another issue with the LICENSE file is that it refers to to GPL v1 and Artistic License for the DMD frontend. However DMD is released under Boost License 1.0 since version 2.066.

**Comment by redstar** [comment]
Thanks for reporting. Fixed in master and release-1.0.0 branch. I update ltsmaster branch later.

**Comment by kinke** [comment]
Fixed for good?

**Comment by kinke** [comment]
Bumped to 2017 (master, release-1.2.x and ltsmaster).
