### ISSUE TITLE
Bug with CTFE and unions

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1324]
The following code outputs "LEN:0" (wrong) instead of "LEN:3" (correct):

``` D
struct TestArray
{
    this(T...)(T vals)  { append(vals); }

    void append(T...)(T vals)
    {
        foreach(v; vals)
            value ~= TestValue();
    }

    import std.typecons;
    mixin Proxy!value;

    TestValue[] value;
}

struct TestValue
{
    union TestType
    {
        int asInt;
        TestArray asTestArray;
    }
    TestType value;

    this(TestArray val) { assign(val); }
    void assign(TestArray val) { value.asTestArray = val; }
    auto get() { return value.asTestArray; }
}

void main()
{
    import std.stdio;
    enum ctObj = TestValue(TestArray(1,2,3));
    writeln("LEN:", ctObj.get.length);
}
```

Changing `union` to `struct` fixes the problem. It's also fixed by changing `enum` to `auto` (CTFE->runtime).

**Comment by kinke** [comment]
Is this still the case? If so, does it work for DMD? CTFE is front-end territory afaik...

**Comment by JohanEngelen** [comment]
I found the culprit.
https://issues.dlang.org/show_bug.cgi?id=16471

**Comment by JohanEngelen** [comment]
https://forum.dlang.org/thread/jzfalivqsvtrnnaubpdh@forum.dlang.org

**Comment by kinke** [comment]
https://github.com/ldc-developers/ldc/pull/1846 moved to DMD behavior in this regard, giving preference to the latest initializer in field declaration order. This should be it from the LDC side; the exact semantics (i.e., no overlapping initializers) should be clearly defined in the front-end.

**Comment by thewilsonator** [comment]
This prints LEN:3 now
