### ISSUE TITLE
Can't build dfmt any more in windows 10 64bit

### ISSUE THREAD

**Issue by soarowl** [ldc-developers/ldc#1328]
git pull lastest dfmt project and ldc is version 1.0.990 in ci
When I compile dfmt use following command:

` dub build -b release --compiler ldc2`

I got:

`Performing "release" build using ldc2 for x86.
experimental_allocator 2.70.0-b1: building configuration "library"...
libdparse 0.5.0: building configuration "library"...
dfmt 0.5.0-beta3+commit.14.g2145766: building configuration "application"...
Error: unrecognized file extension a

ldc2 failed with exit code 1.`

Because compile output library with .a extension.

**Comment by redstar** [comment]
Did it work previously for you? IMHO this is https://github.com/D-Programming-Language/dub/issues/618.

**Comment by kinke** [comment]
Closing this firstly due to lack of feedback and secondly as it really seems to be a dub issue. Please reopen if it isn't.
