### ISSUE TITLE
out contract breaks returning non-copyable structs from functions.

### ISSUE THREAD

**Issue by epi** [ldc-developers/ldc#1335]
The following code compiles with DMD 2.069.2 and works, but fails to compile with ldc2-1.0.0-alpha1-linux-x86_64:
```
Error: struct test.Bar is not copyable because it is annotated with @disable
```
It compiles when the out contract is removed.

```
struct Bar
{
	@disable this(this);
}

auto foo()
out {}
body
{
	return Bar();
}

void main()
{
	auto x = foo();
}
```

**Comment by kinke** [comment]
Confirmed with current master.
We're apparently calling the postblit ctor on the return value because the return expression's type (op) is `TOKvar` if there's an out contract and `TOKstructliteral` if there's no contract.
