### ISSUE TITLE
TypeInfo is stored read-only, but mutable from D

### ISSUE THREAD

**Issue by cym13** [ldc-developers/ldc#1337]
Reduced (thanks dustmite) test case:

    struct A{}
    void main(){
        A a;
        auto y = typeid(a);
        y.name = "Nope, I'm not A";
    }

LDC segfaults when compiling the test case without flag.

Version:

    LDC - the LLVM D compiler (0.17.0):
      based on DMD v2.068.2 and LLVM 3.7.1
      Default target: x86_64-unknown-linux-gnu
      Host CPU: sandybridge

Arguably one shouldn't be able to even try to change a typeid's name but
dmd2.068.2 -> 2.070.2 (last version at the time) accepts it.

**Comment by cym13** [comment]
Sorry, just saw the "Reporting LDC issues" section of the wiki:

System: GNU/Linux Archlinux
Architecture: x86_64
LLVM: 3.7.1-1 (from package)
LDC: 0.17.0 (from package)

**Comment by redstar** [comment]
Hm. LDC does not segfault but the resulting binary.

**Comment by cym13** [comment]
Sorry, I don't know why I confused the two, you are perfectly right.

**Comment by JohanEngelen** [comment]
Is this UB or an LDC bug?

**Comment by UplinkCoder** [comment]
Woohoo a leet issue.

**Comment by redstar** [comment]
Fixed in all branches.
