### ISSUE TITLE
AppVeyor does not execute the dmd-testsuite

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1338]
I just noticed that our AppVeyor script explicitly excludes dmd-testsuite from the tests.

**Comment by kinke** [comment]
There isn't/wasn't enough time - the AppVeyor jobs get killed after 50 mins, and these Azure VMs are quite slow (and their timings used to vary quite wildly). It may work for the debug job now, but release won't be fast enough.
We could factor dmd-testsuite out into its own job(s), but that obviously hurts the overall timings (only 1 concurrent VM, not 5 as for Travis), especially as 32-bit support is coming very soon and we'll need 32-bit jobs too...

**Comment by kinke** [comment]
Will be fixed by https://github.com/ldc-developers/ldc/pull/1354.
