### ISSUE TITLE
Undefined identifier __va_list_tag

### ISSUE THREAD

**Issue by Rikarin** [ldc-developers/ldc#1397]
Hello,
 I have problem with varargs.

/usr/include/dlang/ldc/core/stdc/stdarg.d(42): Error: undefined identifier '__va_list_tag'
/usr/include/dlang/ldc/core/stdc/stdarg.d(314): Error: undefined identifier '__va_list_tag'

Im running on arch linux. Here is my machine info:
LDC - the LLVM D compiler (0.17.0):
  based on DMD v2.068.2 and LLVM 3.7.1
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell
  http://dlang.org - http://wiki.dlang.org/LDC

**Comment by smolt** [comment]
Hmm, that is strange.  `__va_list_tag` is defined in object.d, line 58 for tag v0.17.0.

https://github.com/ldc-developers/druntime/blob/540e1811e7de28e15155f9fec0a8692f16bc6c97/src/object.d#L58

Could you check to see if that is so on your system?  Perhaps another object.d is getting pulled in first.

**Comment by redstar** [comment]
`ldc2 -v` tells you which `object.d` is loaded. This problem typically arises if the include paths are mixed between dmd and ldc.

**Comment by Rikarin** [comment]
Oh, thanks. I am using my custom object file and I missed that fact it is "compiler dependant" file.
