### ISSUE TITLE
Cannot build MS VC projects for LDC

### ISSUE THREAD

**Issue by rainers** [ldc-developers/ldc#1408]
Running cmake (version 3.3.2) to build projects for Visual Studio fails:

```
>cmake -G "Visual Studio 14 Win64"
CMake Error at CMakeLists.txt:588 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE_DIR:ldc2>

  Target "ldc2" is not an executable or library.
```

The offending line is specific to MSVC_IDE:

```
if(MSVC_IDE)
    # the IDE generator is a multi-config one
    # so copy the config file into the correct bin subfolder
    add_custom_command(TARGET ${LDC_EXE} POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy ${PROJECT_BINARY_DIR}/bin/${LDC_EXE}.conf $<TARGET_FILE_DIR:${LDC_EXE}> COMMENT "Copy config file ${LDC_EXE}.conf")
endif()
```

My cmake-expertise is non-existent, but it seems to me that the target is assumed to be an executable name.

**Comment by JohanEngelen** [comment]
I don't understand what this is supposed to do. To me it looks like it is trying to copy
${PROJECT_BINARY_DIR}/bin/ldc2.conf to the same location.
$<TARGET_FILE_DIR:${LDC_EXE}> used to point to ${PROJECT_BINARY_DIR}/bin (the output folder is explicitly set to that)

If you comment-out that offending line, does anything not work for Visual Studio generator?

**Comment by rainers** [comment]
VS builds used to generate the exe into bin/Release, bin/Debug or bin/RelWithDebInfo, but does not do now. 
I guess it is trying to copy ldc2.conf into these directories. It builds just fine with the line commented.

**Comment by JohanEngelen** [comment]
Should we try to restore the bin/Release, bin/Debug, etc, behavior? Does the ltsmaster cmake script still work like that?

**Comment by rainers** [comment]
I currently only build RelWithDebInfo, so it doesn't make a big difference for me. Debugging is sometimes a bit bad with optimizations, though. Before, I used Debug and Release configurations, but that caused trouble at some point, too (IIRC undefining NDEBUG didn't always match what LLVM does).

> Does the ltsmaster cmake script still work like that?

I haven't tried that yet.

**Comment by kinke** [comment]
This works now, i.e., both the CMake invocation as well as building the `ldc2` project, nowadays requiring Visual D for the D parts (https://github.com/ldc-developers/ldc/pull/3494#issuecomment-655098807).
