### ISSUE TITLE
readln(buf) + slicing reads wrong data / segmentation fault

### ISSUE THREAD

**Issue by zoodyy** [ldc-developers/ldc#1433]
Dear LDC-Team,
I've just stumbled across a nasty issue..
readln(buf) in combination with direct slicing produces wrong data on Windows and segfaults on Linux (tested with 0.17.1 and 1.0 alpha).
`char[] line = buf[0..readln(buf)].chomp();`
Attached is a minimal example as well as some input data.
The example works totally fine on DMD and GDC (in debug and release).

[input.txt](https://github.com/ldc-developers/ldc/files/219737/input.txt)
[readlnError.d.txt](https://github.com/ldc-developers/ldc/files/219738/readlnError.d.txt)

LDC works if you change above line to something like:
`ptrdiff_t length = readln(buf); char[] line = buf[0..length].chomp();`

Best regards!

**Comment by kinke** [comment]
Thanks for the report. I guess this is related to https://github.com/ldc-developers/ldc/issues/1327 in the sense that the rvalue `readln(buf)` is probably evaluated **after** evaluating `buf` for slicing.

**Comment by kinke** [comment]
Fixed by #1566.
