### ISSUE TITLE
Wrong template filter on atomicOp

### ISSUE THREAD

**Issue by d-random-contributor** [ldc-developers/ldc#1454]
```d
core.atomic.atomicOp(string op, T, V1)(ref shared T val, V1 mod) if (__traits(compiles, mixin("val" ~ op ~ "mod")))
```
RMW operations on shared data are deprecated. Will the template compile when deprecations are treated as errors? [The filter in docs](https://dlang.org/phobos/core_atomic.html#.atomicOp) is different. See also [this message](https://forum.dlang.org/post/gvzgecxrhdxrqchekijz@forum.dlang.org).

**Comment by JohanEngelen** [comment]
Thanks for reporting the issue. Can you provide a minimal test case that fails with the outdated LDC filter? Thanks.

**Comment by d-random-contributor** [comment]
```d
import std.atomic;
unittest
{
  shared int a;
  atomicOp!"+="(a,1);
}
```
