### ISSUE TITLE
tests fail for the 1.0.0 beta on Arch linux

### ISSUE THREAD

**Issue by joakim-noah** [ldc-developers/ldc#1463]
[As I reported on the forum earlier](http://forum.dlang.org/post/uugnamnegvquugjuufrb@forum.dlang.org), I'm having tests fail on Arch linux/x64 when using ldc 1.0.0.  I tried it again recently, and while `std.math` and the base `object` module don't have failures anymore, the rest persist from `std.datetime`, `std.regex.internal.tests`, `std.net.curl` in debug and release mode and `std.regex` only in debug mode.

I also tried using the official beta1 ldc2 binary release for linux/x64, which has its ddmd frontend compiled by ldc 0.17 as opposed to the dmd 2.071 that I normally use to compile 1.0.0, and saw no difference when compiling the druntime/phobos unit tests from the git branch for 1.0.0.  This suggests that the problem is in ldc itself, though I have no idea why it shows up for me only, or conversely that it's in something else specific to my environment, though I'm stumped as to what that might be.

Here are the test results:

std.datetime
``` 
STARTING std.datetime
****** FAIL release64 std.datetime
core.time.TimeException@/home/mux/ldc/runtime/phobos/std/datetime.d(699): Fractional seconds must be less than one second.
```
std.net.curl
```
STARTING std.net.curl
0.027s PASS release64 std.net.curl

Thread 1 "phobos2-test-ru" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fe8880 (LWP 23868)]
0x0000000000c663d7 in std.concurrency.MessageBox.put(ref std.concurrency.Message) ()
(gdb) bt
#0  0x0000000000c663d7 in std.concurrency.MessageBox.put(ref std.concurrency.Message) ()
#1  0x0000000000c638a0 in std.concurrency.ThreadInfo.cleanup()
    ()
#2  0x00000000010d6fd4 in rt.minfo.rt_moduleTlsDtor().__foreachbody1(ref rt.sections_elf_shared.DSO) ()
#3  0x00000000010d7485 in rt.sections_elf_shared.DSO.opApplyReverse(scope int(ref rt.sections_elf_shared.DSO) delegate) ()
#4  0x00000000010dd27b in rt_term ()
#5  0x00000000010dd510 in _d_run_main ()
#6  0x00007ffff6f14710 in __libc_start_main ()
   from /usr/lib/libc.so.6
#7  0x0000000000404839 in _start ()
```
std.regex.internal.tests
```
STARTING std.regex.internal.tests

Program received signal SIGSEGV, Segmentation fault.
0x00000000010d47a8 in gc.gc.Gcx.smallAlloc(ubyte, ref ulong, uint) ()
(gdb) bt
#0  0x00000000010d47a8 in gc.gc.Gcx.smallAlloc(ubyte, ref ulong, uint) ()
#1  0x00000000010d28da in gc.gc.GC.malloc(ulong, uint, ulong*, const(TypeInfo)) ()
#2  0x00000000010d194c in gc_qalloc ()
#3  0x00000000010c4e7b in core.memory.GC.qalloc(ulong, uint, const(TypeInfo)) ()
#4  0x00000000004248c6 in std.array.Appender!(immutable(wchar)[]).Appender.ensureAddable(ulong) ()
#5  0x0000000000424656 in std.array.Appender!(immutable(wchar)[]).Appender.put!(immutable(char)[]).put(immutable(char)[]) ()
#6  0x000000000109460d in std.regex.internal.tests.__unittestL57_2().run_tests!(std.regex.bmatch).run_tests().__lambda2() ()
#7  0x00000000010aaf0b in std.regex.internal.tests.__unittest
    ()
#8  0x00000000010c3690 in test_runner.tester() ()
#9  0x00000000010c7422 in runModuleUnitTests ()
#10 0x00000000010dd4df in _d_run_main ()
#11 0x00007ffff6f14710 in __libc_start_main ()
   from /usr/lib/libc.so.6
#12 0x0000000000404839 in _start ()
```
I'll dig deeper to see why they might be failing, but I'll need some help from those for whom it's not failing, to compare output.

**Comment by kinke** [comment]
Are you still experiencing these weird errors with current master?

**Comment by joakim-noah** [comment]
It was [fixed a little later by Rainer](https://github.com/ldc-developers/druntime/commit/740c1bb86b36725cf2d671a7ac8f77de692899be), which I verified at the time.  I forgot about this issue, closing.
