### ISSUE TITLE
[CMake] DDMD source files missing in Visual Studio solution

### ISSUE THREAD

**Issue by redstar** [ldc-developers/ldc#1465]
`CMakeList.txt` is not yet ready for `msbuild` target. Obviously, the `ninja` target is ok.

**Comment by redstar** [comment]
E.g.:

    CMake Error at CMakeLists.txt:602 (add_custom_command):
      Error evaluating generator expression:

      $<TARGET_FILE_DIR:ldc2>

    Target "ldc2" is not an executable or library.

There are several of these error messages.

**Comment by rainers** [comment]
See also https://github.com/ldc-developers/ldc/issues/1408.

I've commented the line with the error message locally. This works for building, but the multiple configurations don't work too well. I have made a few tweaks to get better debug builds.

**Comment by redstar** [comment]
Thanks for the hint!

**Comment by rainers** [comment]
I've made a PR with my changes: https://github.com/ldc-developers/ldc/pull/1466

**Comment by redstar** [comment]
I'll try your changes. I think there is one more problem: the install dir may not have spaces in it:

    2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(356,5): error MSB6001: Invalid command line switch for "CL.exe". The value [LDC_INSTALL_PREFIX="C:/My] contains an odd number of double-quote characters. Only even numbers of literal double-quote characters are acceptable to command line tools.

This worked with 0.17.x, too.

**Comment by rainers** [comment]
I've never used the install project.
AFAICT it just spawns `cmake.exe -DBUILD_TYPE=$(Configuration) -P cmake_install.cmake` with `cmake_install.cmake` very much the same as with the ninja build. Does the latter work?

**Comment by redstar** [comment]
This is now fixed in master. Last issue is that I can't see the D source in VisualStudio. I guess the root cause is that there is no `add_custom_target()` specifying the D sources.

**Comment by kinke** [comment]
D files now included with https://github.com/ldc-developers/ldc/pull/2272.
