### ISSUE TITLE
Would be practical to have merged Windows releases

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#1493]
Sorry to bring this up again, will LDC 1.0.0 merge its Windows releases?

As of now, to build the same program in both 32-bit and 64-bit you need to dance with PATH and that rules out using simply `dub --compiler ldc2 --arch x86` and `dub --compiler ldc2 --arch x86_64`.

No such problem with the OSX version.

**Comment by kinke** [comment]
Simply use `-m32` or `-m64`, this should work with both 32-bit and 64-bit LDC builds. I don't know how this works with dub.

**Comment by JohanEngelen** [comment]
Relevant PR: https://github.com/ldc-developers/ldc/pull/1469

**Comment by kinke** [comment]
See https://github.com/ldc-developers/ldc/pull/1523#issuecomment-222143121.

**Comment by kinke** [comment]
Closing this as there's the multilib CI build now. @redstar: How about a single LDC for Windows release in the future? x64 binaries + 32/64 bit stdlibs and patched ldc2.conf. Hardly anyone will still be using a 32-bit Windows for development. And so we'd be aligned with DMD for Windows which is also able to compile and link both 32- and 64-bit code...
