### ISSUE TITLE
Incomplete IEEE 128-bit FP (e.g., aarch64) support in Phobos

### ISSUE THREAD

**Issue by nullr0ute** [ldc-developers/ldc#1516]
I'm seeing the following failure when trying to build ldc 0.17.1 on aarch64 (I've not tried 1.0 pre releases as it looks like I need a bootstrapped ldc to build it now so I think I need to start with 0.17.x). The platform is Fedora 24, llvm 3.8, gcc 6.1

cd /builddir/build/BUILD/ldc-0.17.1-src && /builddir/build/BUILD/ldc-0.17.1-src/build/bin/ldc2 --output-o -c -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/druntime/src -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/druntime/src/gc /builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos/std/cstream.d -of/builddir/build/BUILD/ldc-0.17.1-src/build/runtime/std/cstream-debug.o -w -d -relocation-model=pic -g -link-debuglib -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos
/builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos/std/internal/math/gammafunction.d(251): Error: static assert  "missing MAXGAMMA for other real types"
runtime/CMakeFiles/phobos2-ldc-debug.dir/build.make:148: recipe for target 'runtime/std/mathspecial-debug.o' failed
make[2]: **\* [runtime/std/mathspecial-debug.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make -f runtime/CMakeFiles/phobos2-ldc.dir/build.make runtime/CMakeFiles/phobos2-ldc.dir/depend
cd /builddir/build/BUILD/ldc-0.17.1-src && /builddir/build/BUILD/ldc-0.17.1-src/build/bin/ldc2 --output-o -c -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/druntime/src -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/druntime/src/gc /builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos/std/functional.d -of/builddir/build/BUILD/ldc-0.17.1-src/build/runtime/std/functional.o -w -d -relocation-model=pic -O3 -release -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos
/builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos/std/internal/math/gammafunction.d(251): Error: static assert  "missing MAXGAMMA for other real types"
runtime/CMakeFiles/phobos2-ldc.dir/build.make:148: recipe for target 'runtime/std/mathspecial.o' failed
make[2]: **\* [runtime/std/mathspecial.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/ldc-0.17.1-src/build'
CMakeFiles/Makefile2:397: recipe for target 'runtime/CMakeFiles/phobos2-ldc-debug.dir/all' failed
make[1]: **\* [runtime/CMakeFiles/phobos2-ldc-debug.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/build/BUILD/ldc-0.17.1-src/build'
CMakeFiles/Makefile2:474: recipe for target 'runtime/CMakeFiles/phobos2-ldc.dir/all' failed
make[1]: Leaving directory '/builddir/build/BUILD/ldc-0.17.1-src/build'
make[1]: **\* [runtime/CMakeFiles/phobos2-ldc.dir/all] Error 2
make: **\* [all] Error 2

**Comment by redstar** [comment]
This is an upstream problem: 128bit math functions are not fully implemented. See https://github.com/dlang/phobos/pull/4047 and https://github.com/dlang/phobos/pull/4036 for some solutions.

**Comment by nullr0ute** [comment]
That gets me further along then I get the following 

cd /builddir/build/BUILD/ldc-0.17.1-src && /builddir/build/BUILD/ldc-0.17.1-src/build/bin/ldc2 --output-o -c -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/druntime/src -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/druntime/src/gc /builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos/std/numeric.d -of/builddir/build/BUILD/ldc-0.17.1-src/build/runtime/std/numeric.o -w -d -relocation-model=pic -O3 -release -I/builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos
/builddir/build/BUILD/ldc-0.17.1-src/runtime/phobos/std/math.d(1705): Error: static assert  "Not implemented for this architecture"
runtime/CMakeFiles/phobos2-ldc.dir/build.make:192: recipe for target 'runtime/std/math.o' failed

**Comment by kalev** [comment]
I'm still running into the assert above,  "Not implemented for this architecture" when building 0.17.x/ltsmaster on aarch64 for 1.1.0 bootstrapping purposes.

As I understand it, https://github.com/ldc-developers/ldc/issues/1853 suggests that it should be possible to not build all of phobos just for boostrapping. Is that something I could easily try?

**Comment by kinke** [comment]
I wouldn't recommend going that route (very hacky and I guess the chances for success are very low - a successful compilation doesn't mean the `ltsmaster` host compiler can then compile the newest LDC...). We should first verify that a 128-bit `real` is a sensible choice on AArch64 (I highly doubt that and would much prefer a normal 64-bit double, which would get rid of all of these problems). It should be very simple to implement as well.

**Comment by JohanEngelen** [comment]
Does 128bit `real` actually work well on other platforms? I think a lot of the `real` constants given in unittests and elsewhere in std.math do not have 128 precision, so I would expect std.math unittest failures because of that.
So +1 for carefully looking at whether 64-bit `real` may be the better choice on AArch64.

**Comment by kinke** [comment]
After a quick search, I don't find anything about the IEEE quadruple format being supported by AArch64, e.g., [ARM docs](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/CEGDJGGC.html) and [Wikipedia](https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format#Hardware_support).

**Comment by nullr0ute** [comment]
IEEE 754 quadruple-precision binary floating-point format is part of the NEON SIMD extensions:
See page 8 of this slide deck: https://www.arm.com/files/downloads/ARMv8_Architecture.pdf

**Comment by nullr0ute** [comment]
The VFP (ARMv7 and ARMv8) supports single and double precision IEEE754

**Comment by kinke** [comment]
Sorry but I don't see any mention of that on page 8. All I keep seeing is 128-bit registers for SIMD.

**Comment by nullr0ute** [comment]
@kinke 128 bit quad precision is part of the  IEEE754-2008  revision, there's a number of mentions of improvements to that support on that page. There's more details of those requirements here: https://en.wikipedia.org/wiki/IEEE_754_revision#Clause_3:_Formats

**Comment by JohanEngelen** [comment]
@nullr0ute If it's part of the NEON _extensions_, that means that it is not available on all AArch64, right?

**Comment by nullr0ute** [comment]
@JohanEngelen incorrect, NEON is a requirement of ARMv8 (and I think on ARMv7 too) and is guaranteed to be there on aarch64

**Comment by JohanEngelen** [comment]
I see.
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/CJHECGIH.html

**Comment by kinke** [comment]
Thanks, I finally found something concrete from Apple now: 'Generally, long double is a quad-precision IEEE754 binary floating-point type. In iOS, however, it is a double-precision IEEE754 binary floating-point type. In other words, long double is identical to double in iOS.' ([link](https://developer.apple.com/library/content/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html))

So iOS has its own ABI, further diversifying the ARM ecosystem... oh well. If the C runtime (`cosl()` and friends) on non-iOS really uses these quadruple `long doubles` and the performance loss compared to doubles isn't huge, using quadruple D `reals` seems sensible to me (I'd still be interested in the performance compared to doubles). Then someone will have to sit down and make Phobos support the quadruple format (upstream).

**Comment by kalev** [comment]
https://github.com/llvm-mirror/clang/blob/master/test/CodeGen/aarch64-type-sizes.c#L47 has some unit tests and ```long double``` seems to be 8*16=128 bits:

```
int check_longdouble() {
  return sizeof(long double);
// CHECK: ret i32 16
}
```

**Comment by smolt** [comment]
If your clang has AArch64 as a target (OSX does), you can have it spit out all the C long double properties LDC would need to target aarch64-linux-gnu.  Yeah LDC would need 128-bit real.
```
$ clang -target aarch64-linux-gnu -dM -E -x c /dev/null
...
#define __LDBL_DECIMAL_DIG__ 36
#define __LDBL_DENORM_MIN__ 6.47517511943802511092443895822764655e-4966L
#define __LDBL_DIG__ 33
#define __LDBL_EPSILON__ 1.92592994438723585305597794258492732e-34L
#define __LDBL_HAS_DENORM__ 1
#define __LDBL_HAS_INFINITY__ 1
#define __LDBL_HAS_QUIET_NAN__ 1
#define __LDBL_MANT_DIG__ 113
#define __LDBL_MAX_10_EXP__ 4932
#define __LDBL_MAX_EXP__ 16384
#define __LDBL_MAX__ 1.18973149535723176508575932662800702e+4932L
#define __LDBL_MIN_10_EXP__ (-4931)
#define __LDBL_MIN_EXP__ (-16381)
#define __LDBL_MIN__ 3.36210314311209350626267781732175260e-4932L
```

**Comment by joakim-noah** [comment]
Largely done, see #2153 and report any problems you have there.
