### ISSUE TITLE
ldc.simd: storeUnaligned is missing

### ISSUE THREAD

**Issue by 9il** [ldc-developers/ldc#1518]

**Comment by MartinNowak** [comment]
You can use `__builtin_ia32_storeups`, `__builtin_ia32_storeupd`, and `__builtin_ia32_storedqu`.

**Comment by 9il** [comment]
> You can use __builtin_ia32_storeups, __builtin_ia32_storeupd, and __builtin_ia32_storedqu.

Yes, but they are no crossplatform

**Comment by JohanEngelen** [comment]
Closing because of #1526.
