### ISSUE TITLE
Lit tests fail when space in pathname

### ISSUE THREAD

**Issue by smolt** [ldc-developers/ldc#1536]
Something in CMakeLists or related just needs quotes to protect from a space in path.
This is with master as of 5/29 commit e058ab783761ec35b117ea6572afccb1b263bde7.

Background:

Log is confusing because I have a USB hard drive with a space in its label "Tranquility Base" where I do all my work on Raspian.  It is symlinked as `/mnt/usbhd` so my build dir is `/mnt/usbhd/armv7/ldc-master/build` and ldc git repo lives at `/mnt/usbhd/armv7/ldc-master/ldc`.  Something ends up resolving the symlink and lit test commands see path with space as: `/media/pi/Tranquility Base/armv7/ldc-master/build`.  See...

```
747/747 Test: lit-tests
Command: "/usr/bin/python" "runlit.py" "-v" "."
Directory: /mnt/usbhd/armv7/ldc-master/build/tests
"lit-tests" start time: May 30 20:35 UTC
Output:
----------------------------------------------------------
-- Testing: 14 tests, 4 threads --
FAIL: LDC :: codegen/align.d (1 of 14)
******************** TEST 'LDC :: codegen/align.d' FAILED ********************
Script:
--
/mnt/usbhd/armv7/ldc-master/build/bin/ldc2 -c -output-ll -of=/media/pi/Tranquility Base/armv7/ldc-master/build/tests/codegen/Output/align.d.tmp.ll /media/pi/Tranquility Base/armv7/ldc-master/ldc/tests/codegen/align.d && FileCheck /media/pi/Tranquility Base/armv7/ldc-master/ldc/tests/codegen/align.d < /media/pi/Tranquility Base/armv7/ldc-master/build/tests/codegen/Output/align.d.tmp.ll
--
Exit Code: 1

Command Output (stdout):
--
Command 0: "/mnt/usbhd/armv7/ldc-master/build/bin/ldc2" "-c" "-output-ll" "-of=/media/pi/Tranquility" "Base/armv7/ldc-master/build/tests/codegen/Output/align.d.tmp.ll" "/media/pi/Tranquility" "Base/armv7/ldc-master/ldc/tests/codegen/align.d"
Command 0 Result: 1
Command 0 Output:


Command 0 Stderr:
Error: multiple source files, but only one .obj name
```

**Comment by JohanEngelen** [comment]
Conclusion after search+fiddling:
This is a Lit bug / feature (LLVM doesn't seem to support spaces in the source path, so it's ok for them). Lit determines the paths for %t and %s using Python's os.path.realpath, which resolves symlinks...
Can you try to hack your Lit installation a little? In file `discovery.py`, replace all three occurrences of `os.path.realpath` with `os.path.abspath`. Does that work?
Another way to support spaces in paths is for us to quote all file paths in the test string, e.g. change
`// RUN: %ldc -c -output-ll -of=%t.ll %s && FileCheck %s < %t.ll`
to
`// RUN: %ldc -c -output-ll -of='%t.ll' '%s' && FileCheck '%s' < '%t.ll'`
which may have its own problems with different platforms.
:(

(or rename to TranquilityBase ? ;)

**Comment by smolt** [comment]
I have no problem getting rid of space in my path.  But I do think ldc build system should strive to deal with spaces in pathnames.  I'll poke at it when I get a chance.

**Comment by smolt** [comment]
Changing to `os.path.abspath` doesn't stop resolution of the symlink because abspath('.') behaves differently and gets resolved no matter what.

Looking at lit code, this is really a lit issue, not ldc.  TestRunner.py has its own simple cmd line processing and would know if it should quote pathnames.  Looks like Bourne shell syntax, but it is not.  Quoting paths in the RUN: command does work but no guarantee of portability.
