### ISSUE TITLE
All dub library builds ending in .a extension

### ISSUE THREAD

**Issue by Straivers** [ldc-developers/ldc#1563]
In attempting to compile DCD with ldc, I received the following error: `Error: unrecognized file extension a`. All of the build dependencies end in .a.

**Comment by redstar** [comment]
Are you building on Windows? This is a DUB issue, not from LDC. It should be fixed in the current DUB 1.0.0 beta.

**Comment by jairov4** [comment]
Please check if this can be linked to https://github.com/dlang/dub/issues/835

**Comment by redstar** [comment]
@jairov4 Please, can you add some more details? Which DUB version do you use? Which application do you try to compile?

Using `dub --compiler=ldmd2` I have no problem to create and use a library on Win64.

**Comment by kinke** [comment]
dub v1.1.1 is guaranteed to work.
