### ISSUE TITLE
Regression: recent PR in master breaks variadics on Android/ARM

### ISSUE THREAD

**Issue by joakim-noah** [ldc-developers/ldc#1590]
If I revert #1533, `runnable/variadic.d` from the dmd-testsuite works fine again.  I can't reproduce on linux/x64, so this is related to the ARM ABI and how variadics are done there.  LLVM's IR verifier flags some instructions in the `copya` function from `runnable/variadic.d`, with the following error output:
```
Error: Load operand must be a pointer.
%7 = load i8*, %ldc.internal.vararg.std.__va_list %6
Stored value type does not match pointer operand type!
store i8* %7, %ldc.internal.vararg.std.__va_list* %ap2
```
I had to turn off basic IR verification [to dump this faulty IR output](https://github.com/ldc-developers/ldc/files/334733/var.ll.txt), see lines 3962 and 3963.

**Comment by kinke** [comment]
Please try to produce a minimal testcase - I guess something like

```D
void foo(...) { auto ap = _argptr; }
void main() {}
```

should do the trick.

**Comment by JohanEngelen** [comment]
@joakim-noah What is the ARM triple that you are using? (it's nice to know for testing)

**Comment by joakim-noah** [comment]
It's listed at the top of the IR file I linked, `armv7-none-linux-android`.  I can provide a build of ldc master for that target, for poking at this bug: would that be helpful?

**Comment by JohanEngelen** [comment]
No special build needed for me: `ldc2 -mtriple=armv7-none-linux-android -c -output-ll ../tests/d2/dmd-testsuite/runnable/variadic.d` reproduces it.

What I was thinking: should we set up an automated tester that cross-compiles druntime/phobos unittests (without running them) to catch this kind of problem? Or is this a rare kind of bug?

**Comment by joakim-noah** [comment]
I think it's uncommon.  I need to look at using the Android/ARM emulator on Travis to run all the tests, that's a better route.

**Comment by kinke** [comment]
This crashes too, this time due to getRVal() for a memory-only type (apparently ARM uses a struct with special mangling containing a pointer):

```
import core.vararg;

void foo(...)
{
    va_list ap;
    va_copy(ap, _argptr);
}
```

I'll have a look and may need to switch to DValue for `TargetABI::vaCopy()` and friends.

**Comment by kinke** [comment]
Looks like the ARM TargetABI relied on the `va_list` DValues (structs, otherwise mostly naked pointers for other platforms) returning their address in (old) `DValue::getRVal()`.

**Comment by kinke** [comment]
https://github.com/ldc-developers/ldc/pull/1592 hopefully fixes this and similar issues.

**Comment by joakim-noah** [comment]
Everything passes natively with the linked PR and the cross-compiler compiles that test module fine.  Thanks for fixing.
