### ISSUE TITLE
ICE on returning struct with zero-length static array

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1611]
```d
struct AAA {
    ubyte[0] data;
}

auto foo() {
    return AAA();
}
```

This crashes the compiler (`ldc2 -c`).

@kinke Is it related to your recent NRVO work?

**Comment by JohanEngelen** [comment]
So far, I found that in `DtoArrayAssign`
`rhs->type->toChars` is just "ubyte" for `ubyte[11] data`, but is "ubyte[0]" for `ubyte[0] data`

**Comment by kinke** [comment]
> Is it related to your recent NRVO work?

Nope, I don't think so, as the merged part only concerned variable declarations, not return statements (that's still a PR and most likely has an effect on this as there should be no assignment anymore, just a blit from the struct literal).

**Comment by JohanEngelen** [comment]
I'm on it. Is a simple fix I think. The crash happens in `DtoArrayAssign`, but there is nothing to be done for a zero length array, so it can bail out quickly.

**Comment by JohanEngelen** [comment]
Fixed by https://github.com/ldc-developers/ldc/pull/1612
