### ISSUE TITLE
ldc2.conf not working for x86 in x64

### ISSUE THREAD

**Issue by Stretto** [ldc-developers/ldc#1639]
I would like to be able to switch between x86 and x64. The problem is that when I switch over ldc2x64 uses the x64 libs for x86 creating link errors. The ldc2.conf has a default hard coded path to the x64 libs(in the ../lib dir).

How to setup ldc2.conf to use /lib32 for the 32-bit libs when compiling 32-bit code? I can manually rename stuff each build but this desirable.

**Comment by kinke** [comment]
Simply use the multilib build from the CI GitHub release page...

**Comment by JohanEngelen** [comment]
https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master
