### ISSUE TITLE
How to install ldc 1.1.0 on FreeBSD.

### ISSUE THREAD

**Issue by zoujiaqing** [ldc-developers/ldc#1643]
use FreeBSD's ports or pkgng?

**Comment by kinke** [comment]
I have no idea whether there are any binary packages for FreeBSD, but why not build it from source yourself? See http://wiki.dlang.org/Building_LDC_from_source.

And please use the [forum](http://forum.dlang.org/group/ldc) for future questions like that, as this is really no issue.

**Comment by zoujiaqing** [comment]
Don't good idea

**Comment by redstar** [comment]
There is no FreeBSD port of ldc available. Maintainers are welcome. :-)

Building LDC yourself, you first need to build ldc 0.17.x and then bootstrap use this compiler to bootstrap LDC 1.1.0.

**Comment by zoujiaqing** [comment]
can use dmd compile ldc 1.1.0 ?

**Comment by JohanEngelen** [comment]
Yes you can use DMD to build LDC 1.1.0.
