### ISSUE TITLE
No local variables in GDB/LLDB

### ISSUE THREAD

**Issue by sambrightman** [ldc-developers/ldc#1651]
I posted about this on D forums (https://forum.dlang.org/thread/yjcmjnrvtsyuntzbumkm@forum.dlang.org) and not sure how to investigate further. I'm posting an issue here as it seems likely to be an incompatibility between LDC output and expected debugger input (I have no knowledge of DWARF or debugging it), with multiple debuggers failing perhaps LDC is doing something wrong.

I don't get local variables in either GDB or LLDB across multiple versions and platforms (examples in the forum post). Correct de-mangling, line numbers etc. seem to work with certain combinations but not all at once.

Target is compiled with -g. Is anything else required? What can go wrong to prevent arguments/locals from being available?

**Comment by kinke** [comment]
> What can go wrong to prevent arguments/locals from being available?

Quite a lot. ;) But we're working on it, e.g., https://github.com/ldc-developers/ldc/pull/1598, https://github.com/ldc-developers/ldc/pull/1633 and https://github.com/ldc-developers/ldc/pull/1646.
So using a very recent build from source is greatly encouraged. We're always happy about concrete bug reports with minimal test cases.

**Comment by sambrightman** [comment]
Okay, so currently LDC 1.0.0 built with LLVM >= 3.8 is expected to have broken debugging but fixes are going in for 1.1.0? Does that imply LDC 1.0.0 built with LLVM 3.7 is expected to have working debugging? New reports should presumably only be against master (i.e. if LDC 1.0.0 with LLVM 3.7 doesn't in fact work well, not much point reporting)?

**Comment by kinke** [comment]
> Does that imply LDC 1.0.0 built with LLVM 3.7 is expected to have working debugging?

I'd have expected that at least most locals and params work on Linux and OSX. But as I'm working exclusively on Windows, where LLVM is about to get .pdb support, I can't really tell.

> New reports should presumably only be against master?

Yep. LDC 1.1 will be released soon, so you may just wait for the next release in case building from source is not an option (although it's absolutely no rocket science and doesn't take long, see http://wiki.dlang.org/Building_LDC_from_source).

**Comment by sambrightman** [comment]
Yes, I'm building from source.

1.0.0 built with LLVM 3.7.1 seems to provide demangled names, line numbers and locals with GDB 7.11. LLDB 3.7.1 and LLDB 3.8 both struggle still. I get some non-primitive variables with incomplete type (Tuples, not sure if this is expected). GDB 7.6.1 is less good but can still show some variables.

Closing in light of linked issues/1.1.0 release.
