### ISSUE TITLE
LDC enforces suffix for `-of` option to generate object files

### ISSUE THREAD

**Issue by tom-tan** [ldc-developers/ldc#1666]
I reproduce it with LDC 1.0.0 on Linux 64bit systems.
I also see a similar issue when I try to make a cross compiler whose target is Windows system and whose host is Linux system.

The following command generates `foo.o` instead of `foo.obj`.

```
$ ldc2 -c sample.d -offoo.obj
```

Also, the following command generates `foo.i_want_this_suffix.o` instead of `foo.i_want_this_suffix`.

```
$ ldc2 -c sample.d -offoo.i_want_this_suffix
```

**Comment by kinke** [comment]
Fixed by #1726.

**Comment by tom-tan** [comment]
Thanks!

**Comment by JohanEngelen** [comment]
No tests for this though.
