### ISSUE TITLE
Possible to populate Win64 COFF objects with CodeView dbginfo?

### ISSUE THREAD

**Issue by TurkeyMan** [ldc-developers/ldc#167]
Since LLVM doesn't look like it will support PDB any time soon, and DWARF isn't particularly useful to most windows dev environments, is it possible to populate the COFF objects with CodeView debug info?

MSVC has the (legacy) /Z7 option, which populates the objects with CV debuginfo, which the MS link.exe is still capable if parsing and inserting into the final PDB while linking...

If LLVM/LDC were able to populate the windows objects with CV debuginfo, they may be much more useful when used in typical MSVC dev environments.

**Comment by redstar** [comment]
There is still work on this topic in LLVM: http://reviews.llvm.org/D7153

**Comment by redstar** [comment]
Some more news: Microsoft is going to provide CodeView symbols to LLVM.
See the announcement: http://permalink.gmane.org/gmane.comp.compilers.clang.devel/45575
LLVM: http://reviews.llvm.org/D14209
clang: http://reviews.llvm.org/D14210

**Comment by TurkeyMan** [comment]
Oh, god almighty, thank you! :P
I see that their patch comes with as 'Clang portion' along with an 'LLVM portion'. I guess this implies an LDC portion. How complex is that?

**Comment by redstar** [comment]
I just discover the announcement. It says that they want to introduce new metadata nodes. This could mean that we have to create a 2nd DIBuilder. But I hope that a more generic design emerges. Debug info generation is centralized in the DIBuilder class which should therefore the only class which needs to be enhanced.

**Comment by TurkeyMan** [comment]
Reading those articles, it looks like they generate CV metadata in clang independently from DWARF. Kinda looks like the Clang patch is significant, and also requires full duplication in LDC... :/

**Comment by redstar** [comment]
Yes, that's the approach of the RFC. But the first comments in the discussion about the RFC points out that it is better to have an uniform solution.

**Comment by TurkeyMan** [comment]
That's nice, I didn't read that far.
I saw he made a comment where he made a change to the Microsoft mangler to support some stuff; this means he's making changes to the MS codebase (Visual Studio?) to complete this work. If you can get in on details required to nicely support D; ie, things like local functions, which MS might not support, then perhaps you can influence him to add support for these cases to MS's CodeView description while he's at it...
Ie, being involved with this guy while he's on this task might lead to influence in the MS toolchain, and that means we might be able to slip technology in there required by D (local functions? D closures?) that he would have otherwise ignored ;)

Do you know what this means for de-mangling? Does VS use the prettyName field he refers to to display function names, which we can populate correctly, or would some work be required by MS to have good support?

**Comment by redstar** [comment]
I have a different understanding here: he changed the Microsoft Mangler in *clang*, see http://reviews.llvm.org/D14210#e4b48f2a.

**Comment by redstar** [comment]
See #1716 for current state.

**Comment by kinke** [comment]
Let's close this then and continue with #1716, as (incomplete) debuginfos are already generated.
