### ISSUE TITLE
[REG ldc-1.1.0-beta2] ICE with templated classes

### ISSUE THREAD

**Issue by lodo1995** [ldc-developers/ldc#1677]
```
interface IBar(T)
{
    IFoo!T ownerDocument();
}

interface IFoo(T): IBar!T
{
    // un-commenting the following line solves the issue
    //IList!T getList();
}

interface IList(T) {}

class DOMImplementation(T)
{
    class BarImpl: IBar!T
    {
        FooImpl ownerDocument() { return null; }
    }
    class FooImpl: BarImpl, IFoo!T
    {
        IList!T getList() { return null; }
    }
}

void main()
{
    auto impl = new DOMImplementation!string();
}
```

This code compiles fine with 1.1.0-alpha1, but fails with beta-2.

**Comment by kinke** [comment]
ICE, here's my unreliable RelWithDebInfo call stack:
```
TypeClass::semantic(struct Loc,struct Scope *) C:\LDC\ldc\ddmd\mtype.d:8676:0
ClassDeclaration::semantic(struct Scope *) C:\LDC\ldc\ddmd\dclass.d:448:0
Module::runDeferredSemantic(void) C:\LDC\ldc\ddmd\dmodule.d:1239:0
TemplateInstance::tryExpandMembers(struct Scope *) C:\LDC\ldc\ddmd\dtemplate.d:7950:0
TemplateInstance::semantic(struct Scope *,struct Array<class Expression *> *) C:\LDC\ldc\ddmd\dtemplate.d:7783:0
TemplateInstance::semantic(struct Scope *) C:\LDC\ldc\ddmd\dtemplate.d:6334:0
TypeInstance::resolve(struct Loc,struct Scope *,class Expression * *,class Type * *,class Dsymbol * *,bool) C:\LDC\ldc\ddmd\mtype.d:7475:0
TypeInstance::semantic(struct Loc,struct Scope *) C:\LDC\ldc\ddmd\mtype.d:7497:0
TypeFunction::semantic(struct Loc,struct Scope *) C:\LDC\ldc\ddmd\mtype.d:5945:0
FuncDeclaration::semantic(struct Scope *) C:\LDC\ldc\ddmd\func.d:3429:0
ClassDeclaration::semantic(struct Scope *) C:\LDC\ldc\ddmd\dclass.d:1458:0
ClassDeclaration::semantic(struct Scope *) C:\LDC\ldc\ddmd\dclass.d:1458:0
TemplateInstance::tryExpandMembers(struct Scope *) C:\LDC\ldc\ddmd\dtemplate.d:7950:0
TemplateInstance::semantic(struct Scope *,struct Array<class Expression *> *) C:\LDC\ldc\ddmd\dtemplate.d:7783:0
TemplateInstance::semantic(struct Scope *) C:\LDC\ldc\ddmd\dtemplate.d:6334:0
TypeInstance::resolve(struct Loc,struct Scope *,class Expression * *,class Type * *,class Dsymbol * *,bool) C:\LDC\ldc\ddmd\mtype.d:7475:0
TypeInstance::semantic(struct Loc,struct Scope *) C:\LDC\ldc\ddmd\mtype.d:7497:0
NewExp::semantic(struct Scope *) C:\LDC\ldc\ddmd\expression.d:5765:0
ExpInitializer::inferType(struct Scope *) C:\LDC\ldc\ddmd\init.d:776:0
VarDeclaration::semantic(struct Scope *) C:\LDC\ldc\ddmd\declaration.d:1068:0
DeclarationExp::semantic(struct Scope *) C:\LDC\ldc\ddmd\expression.d:6939:0
ExpStatement::semantic(struct Scope *) C:\LDC\ldc\ddmd\statement.d:1166:0
CompoundStatement::semantic(struct Scope *) C:\LDC\ldc\ddmd\statement.d:1427:0
FuncDeclaration::semantic3(struct Scope *) C:\LDC\ldc\ddmd\func.d:1772:0
Module::semantic3(void) C:\LDC\ldc\ddmd\dmodule.d:1089:0
cppmain(int,char * *) c:\ldc\ldc\driver\main.cpp:1397:0
```

**Comment by lodo1995** [comment]
GDB confirms that the segfault happens in `TypeClass::semantic(Loc, Scope*)`, although my stack trace is a bit different (probably because it's a release LDC build without complete degub info).

Removing line 3 (the declaration of `ownerDocument()` in `IBar`) strangely removes the issue.
Also having `FooImpl` and `BarImpl` not nested inside `DOMImplementation` removes the issue.

So it looks like the segfault is caused by the interaction of nested classes and inheritance of interfaces.

**Comment by JohanEngelen** [comment]
Git bisect points to this front-end change:
bc09f8169ebf3c8c507bf194976af6f45d80d886 is the first bad commit
commit bc09f8169ebf3c8c507bf194976af6f45d80d886
Author: Kai Nacke <kai@redstar.de>
Date:   Sat Jun 25 20:57:42 2016 +0200

    Fix forward reference bug with extern(C++, class).
    
    Depending on the position in the source file, the
    cppmangle value is not set correct.
    
    "Cherry-picked" from https://github.com/dlang/dmd/pull/5883

**Comment by JohanEngelen** [comment]
@redstar Can you have a look?

**Comment by JohanEngelen** [comment]
Apparently `sc` can be `null` in `TypeClass.semantic`. 
and thus this fixes the ICE:
```diff
-if (sc.cppmangle != CPPMANGLE.def)
+if (sc && sc.cppmangle != CPPMANGLE.def)
```

**Comment by kinke** [comment]
It compiles fine with DMD 2.071.1 though...

**Comment by JohanEngelen** [comment]
The `extern(c++, class)` additions are not in 2.071.

**Comment by kinke** [comment]
Thanks Johan, confirmed - DMD nightly crashes too, your proposed fix works fine. @redstar: It would be great if you could upstream the fix before it makes it into a DMD release.

**Comment by lodo1995** [comment]
@JohanEngelen @kinke if `sc` can be null then also `this.cppmangle = sc.cppmangle;` needs to be changed (the one outside the `if`, just before the `return` statement).

Should I file a bug report on DMD bugzilla linking to this thread or will you take care of fixing both LDC and the upstream DMD frontend?

**Comment by redstar** [comment]
I take care for upstreaming the fix.

**Comment by redstar** [comment]
See https://github.com/dlang/dmd/pull/6056

**Comment by kinke** [comment]
Thanks Kai, grazie Lodovico!

**Comment by redstar** [comment]
@kinke Thanks for cherry-picking!

**Comment by lodo1995** [comment]
Thanks to all of you for the great work!
