### ISSUE TITLE
ICE: function not fully analyzed; previous unreported errors compiling std.variant.VariantN!(16LU, int, string).VariantN.__xopEquals?

### ISSUE THREAD

**Issue by ximion** [ldc-developers/ldc#1698]
This is a "spinoff" of issue #1696 

I am split-compiling a project. After fixing a lot of issues in the form of:
```error: module utils from file /path/to/project/source/mod/utils.d conflicts with another module utils from file source/mod/utils.d```

I "fixed" them by manually defining `module` for those projects. This smells like another bug, since there was no actual conflict - the paths are the same, the only exception is that one is absolute and the other one is relative.

After resolving these issues, LDC now runs into an ICE when compiling the project:
```
ldc2  '-Iasgen@exe' '-I..' '-I.' '-Isource/' '-I../source/' '-Isource/bindings/auto' '-I../source/bindings/auto' '-I/usr/include/d/mustache-d/src/' '-I/usr/include/d/mustache-d/src/' '-w' '-g'  -of 'asgen@exe/source_engine.d.o' -c ../source/engine.d
Error: Internal Compiler Error: function not fully analyzed; previous unreported errors compiling std.variant.VariantN!(16LU, int, string).VariantN.__xopEquals?
```

Any idea what could be wrong here? Can I get LDC to show the "unreported errors" somehow?

**Comment by kinke** [comment]
What you're running into is [this](https://github.com/ldc-developers/ldc/blob/master/gen/functions.cpp#L774), so apparently the automatically generated `__xopEquals()` functions is missing some semantic passes. Sounds interesting, and a reduced test case would be nice (dustmite?).

**Comment by ximion** [comment]
First of all, Dustmite is amazing! It's an incredibly helpful tool!
Here is a minimized testcase, reproducing this ICE: [ldc_testcase-ICE_1698.zip](https://github.com/ldc-developers/ldc/files/425957/ldc_testcase-ICE_1698.zip)

**Comment by kinke** [comment]
Hmm this is a strange one. I reduced it to:

M.d:
```D
import N;

void foo(C) {}
```

N.d:
```D
import std.variant;

class E {
    this(void delegate() ) {}
}

class R
{
    Algebraic!int[string][] W;

    auto Y()
    {
        new E(
        {
            foreach (AB; W) AB["path"].get!string;
        });
    }
}

class C
{
    R DB;
}
```

1. `ldc2 -c M.d` results in the ICE.
2. As soon as the return type of method `N.R.Y()` is changed to `void`, it compiles fine.
3. If the return type is left at `auto` and the lambda is rewritten from `{ <body> }` to `() => { <body> }`, LDC complains: `N.d(13): Error: constructor N.E.this (void delegate()) is not callable using argument types (void delegate() @system delegate() pure nothrow @nogc @safe)`. If the return type of `Y()` is again changed to `void`, it compiles fine again.
4. DMD nightly from a week ago or so compiles all these cases without issues.

**Comment by kinke** [comment]
Hmm it gets a bit stranger when actually using `Y()` in module `M`. M.d:
```D
import N;

void foo(C c) { c.DB.Y(); }
```

1. LDC's ICE is gone with original N.d.
2. When using the `() =>` lambda prefix, DMD shows the same error message as LDC. Changing the return type of `Y()` to `void` fixes things.

So there seems to be at least one front-end bug wrt. return type deduction and the full lambda syntax.

**Comment by kinke** [comment]
N.d, a bit shorter and still causing the LDC ICE:

```D
import std.variant;

class C
{
    Algebraic!int[string][] W;

    auto foo()
    {
        auto d = {
            foreach (w; W)
                w["path"].get!string;
        };
    }
}
```

**Comment by kinke** [comment]
The difference between `auto` and `void` return types, in the `-vv` log, is that we're doing an additional `semantic3` pass for `auto` [here](https://github.com/ldc-developers/ldc/blob/master/ir/irtypeclass.cpp#L168) when generating the vtable.

**Comment by ximion** [comment]
Nice, thank you for investigating & resolving this issue!

**Comment by kinke** [comment]
You're welcome; thanks for the report, as I'm sure others would have run into this sooner or later too (or already had).
