### ISSUE TITLE
pragma(inline, false) is incompatible with store/loadUnaligned

### ISSUE THREAD

**Issue by 9il** [ldc-developers/ldc#1711]
`Attributes 'noinline and alwaysinline' are incompatible!`
A function may has either pragma(inline, false) or store/loadUnaligned.

**Comment by 9il** [comment]
This is required for BLAS

**Comment by kinke** [comment]
> This is required for BLAS

If the aim is to emphasize the urgent need for a fix, then a ready-to-paste testcase is 10x as effective on the way to getting there, seriously. ;)

**Comment by 9il** [comment]
```d
void pack(size_t length, double* from, double* to)
{
    pragma(inline, false);
    do
    {
            import ldc.simd;
            alias V = __vector(double[4]);
            storeUnaligned!V(loadUnaligned!V(from), to);
            from += s;
            to += s;
     }
    while(--length);
}
```

**Comment by kinke** [comment]
Thanks, a fix is on its way.

**Comment by ZombineDev** [comment]
@9il I'm just curious, why do you want to disable inlining in this case?

**Comment by kinke** [comment]
See https://github.com/ldc-developers/ldc/pull/1713.

**Comment by 9il** [comment]
> @9il I'm just curious, why do you want to disable inlining in this case?

This code can be large if unrolled.

**Comment by 9il** [comment]
> See #1713.

Thank you for the quick fix!
