### ISSUE TITLE
Shared Library Not Exporting Symbols on Windows

### ISSUE THREAD

**Issue by marktrz** [ldc-developers/ldc#1745]
It doesn't seem as though anything is being exported, even "gc_setProxy" which rt_LoadLibrary() from core.runtime tries to access to link the garbage collectors. This also includes functions with "export", not  actually being exported.

**Comment by kinke** [comment]
Thx for bringing this up. This would entail translating `export` to one of the 2 [LLVM DLL storage classes](http://llvm.org/docs/LangRef.html#dll-storage-classes), I guess depending on whether the module containing the symbol definition is part of the DLL (`dllexport`) or just referenced via an import (`dllimport`).

I'm not too keen on tackling this in the near future, so you may want to resort to using a [.def file](https://msdn.microsoft.com/en-us/library/d91k01sh.aspx) when linking for the time being.

**Comment by captaindet** [comment]
just for the record: this is blocking apps that generate callback functions at CT, as discussed here
https://forum.dlang.org/thread/numj80$2q3s$1@digitalmars.com
https://forum.dlang.org/post/nuoiqm$vk$1@digitalmars.com
as the use of .def files is not an option. DMD + MS linker master this fine.

**Comment by kinke** [comment]
@captaindet: Could you please give [this Win64 CI build](https://ci.appveyor.com/api/buildjobs/p6whmnp1huwi3h94/artifacts/LDC-master-2644-x64.7z) a shot and post your findings?

**Comment by captaindet** [comment]
@kinke
sorry for the belated response, the notification got stuck in my spam filter. testing results:

good: the linked Win64CI build did work alright  with a minimal test program, i.e. the export-declared functions were visible to the GTK runtime. 

bad: my main project does not compile with this build, see below for error. it does compile with DMD-2.071.2 (and works) and LDC2-1.1.0b3 (but does not function properly w/o exposed callbacks).
'''
Assertion failed: llSize <= dSize && "LLVM type is bigger than the corresponding D type, " "might lead to aggregate layout mismatch.", file C:\projects\ldc\gen\llvmhelpers.cpp, line 1341
Wrote crash dump file "b:\TEMP\ldc2.exe-6c3bbd.dmp"
0x0000000001802735 (0x0000000000000501 0x000000000104718C 0x0000000000000000 0x00000000041FCB10)
0x0000000004258B68 (0x0000000000000501 0x0000000000000000 0x0000000000000000 0x000000000087E8C0), raise() + 0x1E8 bytes(s)
0x00000000042598E1 (0x0000000000000003 0x0000000000000003 0x000000000254B4D0 0x000000000254A2E0), abort() + 0x31 bytes(s)
0x000000000425B5C1 (0x000000000000053D 0x000000000254B4D0 0x000000007A9DC3A8 0x0000000000000000), _get_wpgmptr() + 0x1BF1 bytes(s)
0x000000000425B8CF (0x0000000000001020 0x000000000000101E 0x000000007A9DC3A8 0x000000000313B9C0), _wassert() + 0x3F bytes(s)
0x000000000104718C (0x000000000670B6B0 0x000000007A9DC3A8 0x000000000087EA60 0x00000000009783FC)
0x00000000010B882B (0x000000000670B050 0x000000007AB66BE0 0x000000000670B050 0xFFFFFFFFFFFFFFFE)
0x0000000001087D83 (0x00000000725DE280 0x000000000670B050 0x000000000087EE80 0x000000000087EE80)
0x000000000103D499 (0x00000000067514E0 0x000000007AB66BE0 0x000000000087EE80 0x00000000067514E0)
0x000000000103CEA9 (0x000000007AB66BE0 0xFFFFFFFFFFFFFFFE 0x00000000067514E0 0x000000000087EE80)
0x0000000001086182 (0x000000050000024D 0x000000007AA9CAC8 0x0000000006751430 0x00000000067514E0)
0x000000000103D39F (0x00000000067514E0 0x000000007AB66BE0 0x000000000087EE80 0x00000000067514E0)
0x000000000104615C (0x000000000254ACA0 0x00000000067514E0 0x000000000087EFA0 0x000000000087EE80)
0x000000000104377A (0x000000000087EED0 0x0000000006751640 0x000000000087EE80 0x00000000014C9B9C)
0x0000000001097A38 (0x0000000006751640 0x000000000087EFA0 0x000000000087EED0 0x0000000006F74380)
0x0000000001093E4D (0x00000000725DE280 0x000000000087EFA0 0x0000000000000000 0x000000007AA39FF0)
0x00000000010C1800 (0x0000000000A6FEF0 0x0000000000000012 0x000000000676A7A0 0x0000000000000000)
0x00000000010C1024 (0x000000007924CF98 0x000000000087EFA0 0x0000000000000001 0x000000007AA7F070)
0x00000000010C1024 (0x000000007AA39FF0 0x000000000087F0C0 0x00000000067504A0 0x000014A5085AFF7E)
0x00000000010C0863 (0x000000007AA39FF0 0x000000000087F0C0 0x00000000067504A0 0x00000000066D51B0)
0x00000000010B1599 (0x00000000067504A0 0x0000000000000000 0x0000000100000000 0x000000001D1947F0)
0x000000000108F81A (0x0000000006F74040 0x0000000000000000 0x0000000000000002 0x000000007A4022A0)
0x000000000104CEE0 (0x0000000000000003 0x0000000000000002 0x0000000000000002 0x0000000000E0DD3F)
0x000000000106FC6A (0x0000000000000002 0x0000000000000000 0x000000000000000A 0x000000000087F470)
0x0000000001034540 (0x0000000000000000 0x0000000000000B98 0x000000000000000A 0x0000000076E6DB18)
0x0000000000F1C2A7 (0x0000000000A1DFA0 0x000000000087F600 0x0000000000000002 0x000000000313B9C0)
0x0000000001034C17 (0x000000000087F6C0 0x000000000087F600 0x0000000000000000 0x000000000087FB08)
0x0000000000F94D51 (0x00000000009704E8 0x0000000000974984 0x0000000002F73BF0 0x0000000000970000)
0x0000000000FC3575 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00000000021B5BC9 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x0000000076C159CD (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0xD bytes(s)
0x0000000076E4A2E1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
Compilation failed.
'''
[ldc2.exe-6c3bbd.zip](https://github.com/ldc-developers/ldc/files/570429/ldc2.exe-6c3bbd.zip)

**Comment by captaindet** [comment]
@kinke 
so the CI build you linked to was LDC-master-2644-x64, i have just checked out the latest, LDC-master-2675-x64:

worst of both worlds: export is not working anymore (GTK runtime does not find my callbacks) and i get the same compilation failure as w/ 2644:
Assertion failed: llSize <= dSize && "LLVM type is bigger than the corresponding D type, " "might lead to aggregate layout mismatch.", file C:\projects\ldc\gen\llvmhelpers.cpp, line 1329

**Comment by kinke** [comment]
Let me clear this up - I linked to a CI build for PR #1856. You don't find PR builds on the CI release page. So build 2675 (based on the master branch) doesn't export.

All CI builds have assertions enabled (as opposed to the regular LDC release builds), that's why you get the crash. It's a sign that you may get nasty runtime problems with that code using a regular LDC build. It's an interesting error and it'd be great if you could dig some more into it. I'll have a look at the minidump over the weekend and see if it contains enough info to be of any use.

**Comment by captaindet** [comment]
i had the suspicion that the export feature was a 1-off test build and that the error message might not be related to the export story. i had no clue about the en/disabled asserts, though - so it is likely that 1.1.0b3 would have crashed the same way with them being enabled. my project is several k LOC and i have no clue what to look for, as the crash message did not reference module nor line number in my code. don't know how to read the minidump.
anyhow, i appreciate that you made an attempt in adding export functionality, and it seems like it was a very promising one, as it was working in my smaller test progs.
