### ISSUE TITLE
TryCatchFinallyScopes::popTryCatch() fails to link with LDC_LLVM_VER < 308

### ISSUE THREAD

**Issue by thewilsonator** [ldc-developers/ldc#1782]
isCatchSwitchBlock is declared in ms-cxx-helper.h but only defined in ms-cxx-helper.cpp if LDC_LLVM_VER >= 308. all other uses of `isCatchSwitchBlock` are in `#if` blocks. This break compilation for LDC_LLVM_VER < 308.

Solution guard the `if (useMSVCEH()){...} else` with LDC_LLVM_VER >= 308

**Comment by kinke** [comment]
LDC for Windows requires LLVM 3.9.

**Comment by thewilsonator** [comment]
yes but this causes failure on non windows systems on 3.7 or less.

**Comment by kinke** [comment]
Just looked at it; it's in an assert, that's why it's no problem for our CI builds (which do test LLVM 3.5, 3.6 and 3.7 on Linux).

**Comment by thewilsonator** [comment]
Ahh, maybe I was building debug. Also I'm on OSX.

**Comment by thewilsonator** [comment]
Thanks!

**Comment by kinke** [comment]
Well, thank you for letting us know. :)
