### ISSUE TITLE
llvm_* intrinsics not marked pure

### ISSUE THREAD

**Issue by EyalIO** [ldc-developers/ldc#1785]
There's no reason for llvm_prefetch, for example, to be impure. Cache accesses are completely invisible effects.

**Comment by kinke** [comment]
Only the first 8 intrinsics in druntime's `ldc/intrinsics.di` are impure. For those, only a pure `llvm_prefetch` seems to make sense to me. It and `llvm_readcyclecounter` may also be made `safe` IMO.

**Comment by kinke** [comment]
In druntime/ldc now, soon used officially by LDC.
