### ISSUE TITLE
Add function instrumentation and profiling options

### ISSUE THREAD

**Issue by uvm** [ldc-developers/ldc#1839]
This tool https://github.com/bisco/uftrace.git needs function profiling information for generating nice profile graphs. Also look at this CppCon 2016 presentation video https://youtu.be/LNav5qvyK7I

@JohanEngelen says it should be easy to implement in LDC :-) We need something equivalent to -pg option of GCC.

**Comment by JohanEngelen** [comment]
For uftrace, we just need `-finstrument-functions` which is easy to implement.  (don't know about `-pg`)
