### ISSUE TITLE
Can't build 0.17.2 on Windows

### ISSUE THREAD

**Issue by rtbo** [ldc-developers/ldc#1857]
I get compile error due because `UNICODE`is defined somewhere by the build chain (Ninja/MSVC15).
Passing `-DCMAKE_CXX_FLAGS="/D_UNICODE"` to cmake does not solve it.
Errors are in:
- `driver/configfile.cpp` (`RegOpenKey`and `RegGetValue`)
- `driver/linker.cpp` (`CreateProcess`)

I fixed it by explicitely calling the `"A"` version of the functions. I think it is the correct thing to do because plain `const char*` parameters are passed and there is not `#ifdef UNICODE` of any kind in the code.

This is with ldc-0.17.2 source package from the release page.

**Comment by kinke** [comment]
The way I see it, there's no need for ltsmaster/0.17.x on Windows. There are more than enough prebuilt Windows x86 and x86_64 LDC packages (one per commit in master) which are perfectly fine for bootstrapping, and there are pre-built DMD releases too.
In ltsmaster, we 'only' need to continue supporting generic (i.e., non-Windows) stuff to be built on when adding support for new platforms for which there's no D compiler yet.
