### ISSUE TITLE
Can't build master with ldc-0.17.2 on Windows

### ISSUE THREAD

**Issue by rtbo** [ldc-developers/ldc#1858]
from `driver/cache_pruning.d`:
`import core.sys.windows.winbase;`, which is not available with ldc-0.17.2

**Comment by kinke** [comment]
Same here, no need to use ltsmaster/0.17.x for bootstrapping on Windows, there are plenty of pre-built D host compilers to choose from for x86 and x86_64 architectures. I guess Windows on ARM (dead?) is quite different than x86 Windows.
