### ISSUE TITLE
Os misoptimized ?

### ISSUE THREAD

**Issue by Temtaime** [ldc-developers/ldc#1867]
Consider

https://godbolt.org/g/xtFmhL

And

https://goo.gl/j3Tj0m

**Comment by kinke** [comment]
The loop vectorizer is still enabled for `-Os`, but not for `-Oz` (which somehow doesn't work with the online compiler, but I've verified the assembly locally).

**Comment by JohanEngelen** [comment]
Online compiled with LDC -Oz: https://godbolt.org/g/fuKQVv
