### ISSUE TITLE
Compiler switch for applying @fastmath throughout a compilation unit

### ISSUE THREAD

**Issue by dextorious** [ldc-developers/ldc#1874]
Opening an issue here as [requested](http://forum.dlang.org/post/szxizxxebxqtqyeerflt@forum.dlang.org).

Basically, a significant amount of performance sensitive numerical code is written under the assumption of associative and finite floating point arithmetic rather than strict IEEE compliance. In many real world cases this is a matter of performance difference by a factor of 3 or more due to the resulting vectorization opportunities. While the existing @fastmath attribute is very useful and sometimes function-level control is the appropriate choice, having a compiler switch analogous to the --ffast-math of GCC/Clang is very convenient for code that does not require IEEE compliance anywhere (in my line of work, most of the code I write). It would also greatly simplify benchmarking the effects of changing the floating point model quickly.

**Comment by JohanEngelen** [comment]
Things to change: change initialization of IrFunction::FMF, and of llvm::TargetMachine::Options (see `applyTargetMachineAttributes` in function.cpp)

**Comment by p0nce** [comment]
Wow, fantastic! Annotating everywhere would have been a lot of work and difficult to test for samey results too. Thanks!
