### ISSUE TITLE
nightly Windows build does not work with file access tracking

### ISSUE THREAD

**Issue by rainers** [ldc-developers/ldc#1876]
I'm trying to integrate LDC with Visual D using file tracking for automatic dependency handling. Using the nightly build from https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master causes an error, though:
```
C:\tmp>"C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\Tracker.exe" /i c:\tmp /d "C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\filetracker64.dll" /c c:\tmp\ldc-x64\bin\ldc2.exe
FileTracker : error FTK0001: could not attach tracking. Not enough storage is available to process this command.
```
This does not happen with my own built ldc2.exe or ldmd2.exe. Fortunately, it also doesn't happen with 1.1.0-beta-3. It also does not happen with the 32-bit built ldc2.exe.
It is unlikely that it actually has something to do with the size of the executable (the appveyor build is the only to include a lot of target architectures), as it also happens with ldmd2.exe.

**Comment by kinke** [comment]
AppVeyor uses the `RelWithDebInfo` CMake config, so featuring debug infos. Its LLVM is built using `Release`, but includes assertions, so the LDC assertions are enabled too. All targets are enabled for that LLVM.

> Not enough storage is available to process this command.

Are you sure it's not just your HDD/SSD filling up?

**Comment by rainers** [comment]
> AppVeyor uses the RelWithDebInfo CMake config, so featuring debug infos. Its LLVM is built using Release, but includes assertions, so the LDC assertions are enabled too. All targets are enabled for that LLVM.

My local ninja build is RelWithDebInfo with assertions for both LLVM and LDC. I also tried the debug build by VS. Both can be run with the file tracker. Maybe there is something about the other targets?

> Are you sure it's not just your HDD/SSD filling up?

Pretty sure. I even started the Sysinternals process monitor to find the difference to cl.exe before noticing that it works with other builds of LDC. I couldn't spot any real difference in the logs, though.

**Comment by kinke** [comment]
I can reproduce it - my own (`RelWithDebInfo`) builds work fine, an older 64-bit AppVeyor one doesn't. A msgbox with `application was unable to start correctly (0xc0000142)` pops up; that error is apparently related to failed DLL initialization. My builds use the dynamic MSVCRT libs, so does AppVeyor...

**Comment by rainers** [comment]
Sorry, forgot to mention: I get that message box, too. I've build with all (?) targets now, too. No problem with the tracker. DLL dependencies are pretty much the same as with the Appveyor build.

**Comment by rainers** [comment]
Seems to happen when LDC is not built with DMD, but LDC (tried 1.1.0-beta3).

**Comment by kinke** [comment]
Oh interesting. AppVeyor uses LDC 1.0 for the x64 job. I just compared the ldmd2 DLL dependencies; they are identical, but the order slightly differs, in case that can make a difference.

**Comment by kinke** [comment]
Btw, wouldn't `-deps=<file>` be an option to get a list of the dependencies?

**Comment by rainers** [comment]
> Btw, wouldn't -deps=<file> be an option to get a list of the dependencies?

That's what Visual D is doing for ages, but the dependency file has become so bloated due to local imports that reading and parsing it causes noticable slowdowns.

More importantly, the new VC project integration uses MSbuild that has some support for the tracker files, so using it seems natural.

**Comment by rainers** [comment]
Shrinking ldmd down to an empty main, I could reduce this to being caused by building with debug info. Any D program compiled with `ldc2 -g hello.d` seems to have this problem.

**Comment by rainers** [comment]
It seems calling the linker with /DEBUG and /OPT:REF or /OPT:ICF at the same time doesn't work too well. It causes negative offsets for some symbols according to the map file, e.g.:
```
 0004:fffb9000       $pdata$??1?$__crt_unique_heap_ptr@_WU__crt_internal_free_policy@@@@QEAA@XZ 0000000000400000     libucrt:getlocaleinfoa.obj
 0002:fffc9000       $unwind$?release@?$__crt_unique_heap_ptr@_WU__crt_internal_free_policy@@@@QEAAXXZ 0000000000400000     libucrt:getlocaleinfoa.obj
 0000:fffb4000       .debug$S                   0000000000400000     kernel32:KERNEL32.dll
 0000:fffb4000       .debug$S                   0000000000400000     kernel32:KERNEL32.dll
```

**Comment by rainers** [comment]
> It seems calling the linker with /DEBUG and /OPT:REF or /OPT:ICF at the same time doesn't work too well.

Still doesn't work without these optimizations. Instead `/LARGEADDRESSAWARE:NO` on the linker command line seems to be the culprit. It seems it's a workaround for troubles with DWARF debug info, so I'll disable it for CodeView.

**Comment by kinke** [comment]
Glad you figured that one out. That switch was previously required. So this will also enable closing https://github.com/ldc-developers/ldc/issues/442.

**Comment by kinke** [comment]
Thx Rainer, fixed by #1880.

**Comment by Stretto** [comment]
Having the same issue.

FileTracker : error FTK0001: could not attach tracking. Not enough storage is available to process this command.

I'm running it run Visual D and Visual 2017. Not doing anything out of the ordinary. Works on a different install of windows that I have. LDC is probably older on that install. Not using file tracker but maybe it is carrying over. LDC works fine from the command line directly for a simple hello world.

Maybe a regression or some conflict? I don't even know what FileTracker is... and I have plenty of free space(50+gigs on every HD). The same project compiles fine with dmd in Visual D.

**Comment by JohanEngelen** [comment]
@Stretto What version of LDC are you using?
(i know nothing about this, but providing more details will help resolve the issue by those that do)

**Comment by Stretto** [comment]
LDC - the LLVM D compiler (1.4.0git-c5354d6):
  based on DMD v2.074.1 and LLVM 4.0.1
  built with LDC - the LLVM D compiler (1.0.0)
  Default target: x86_64-pc-windows-msvc
  Host CPU: skylake

**Comment by rainers** [comment]
I can reproduce the problem, 1.3.0 is still ok.

The nightly build is actually quite a bit larger (44 MB vs. 27 MB), and it is built with VS2017 (instead of VS2015). I could not produce a similar problem with a tiny example linked with VS2017, though.
Does it use LLD for linking?

**Comment by kinke** [comment]
Main diffs compared to a release package are the included debug infos and LLVM/LDC assertions, VS 2017 (although the LLVM has been built with VS 2015) and LLVM 4.0.1 instead of 3.9.1. LLD is only used with `-link-internally`.

**Comment by rainers** [comment]
https://github.com/ldc-developers/ldc/pull/2268 fixes it for me using LDC 1.3.0 instead of LDC 1.0.0 to compile LDC itself. I suspect there have been some tweaks to MSVC/druntime interaction that avoids the issue.

What version is used to build the LDC releases?

**Comment by kinke** [comment]
Ah nice, I forgot to update the AppVeyor host compiler (tried it multiple times in the past, but newer versions needed the recent floating-point init fix).
The release builds itself.

**Comment by kinke** [comment]
@Stretto: Thanks for the letting us know; CI builds >= 4154 should work.
