### ISSUE TITLE
libLTO in bin

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#1901]
`libLTO-ldc.dylib` is a library, why is it being installed in `bin`, not in `lib`?

**Comment by thewilsonator** [comment]
Because it's a plugin for the linker.

**Comment by John-Colvin** [comment]
The reason I ask is that homebrew only allows executables in `bin`.

**Comment by John-Colvin** [comment]
https://github.com/Homebrew/homebrew-core/pull/7308

**Comment by JohanEngelen** [comment]
See https://github.com/ldc-developers/ldc/issues/1897

I'll work on a fix today.

**Comment by kinke** [comment]
Fixed by #1902. It will be installed into `lib`, unless you specify a suffix via CMake, e.g., `-DLIB_SUFFIX=64` => `lib64`.
