### ISSUE TITLE
Windows: Data segment for GC not initialized when using shared MSVCRT

### ISSUE THREAD

**Issue by sprinkle131313** [ldc-developers/ldc#1908]
Well I have an associative array that holds an array of integers, ```int[][int]``` basically. For one frame that is run the contents are valid and the code functions normally. The second time around, most of the contents of the array are empty only one valid entry. Then after a few seconds the program fails trying to access an invalid pointer, for the associative array. It was a global variable using `__gshared`, when I removed that and used thread local storage, it functioned correctly. The code that's affected is in a DLL file (on windows) that is loaded at runtime using Runtime.loadLibrary. I'm also using the SimpleDllMain mixin from core.sys.windows.dll. So it seems that it is being garbage collected for some reason, even though it still exists and is valid. I'm using LDC 1.1.0-beta5.

**Comment by rainers** [comment]
Are you expecting to share the GC between the DLL and the host application, i.e. does your DLL export gc_setProxy? I don't think this works but in very simple cases, e.g. only for single threaded applications.
Proper DLL support with a shared druntime is being worked on.

Using separate statically linked versions of druntime should work (with 2 GCs), but pointers have to be added as roots to the GC if the only reference to a memory block is passed to the other binary. While a globl variable is usually as good as adding an explicit root, the memory must be allocated by the same GC that knows about the global data segment. Is this the case here, i.e. the associative array is not modified by the executable?

If this does not help, please try to reduce the issue to a reproducable test case.

**Comment by sprinkle131313** [comment]
@rainers I tried exporting gc_setProxy, didn't seem to work. The array never leaves the DLL, it is only used as a global variable in the DLL.

I tried reducing the code but the error doesn't exist anymore when reduced. Is there any way to debug the GC?

**Comment by kinke** [comment]
I tried to reproduce it using 2 methods - dynamic loading of the DLL at runtime via `rt_loadLibrary()` (without the DLL exporting `gc_setProxy()`) and importing the function directly via import lib. Both work.

```
import core.memory, core.stdc.stdio;

version(DLL)
{
    import core.sys.windows.dll;

    mixin SimpleDllMain;

    __gshared int[][int] global;

    export extern(C) void foo()
    {
        for (int i = 0; i < 1_000_000; i += 2)
            global[i] = new int[256];

        GC.collect();

        printf("%d entries\n", global.length);
        foreach (i, ref int[] a; global)
            printf("  %d: length = %d, %d\n", i, a.length, a[0]);
    }
}
else
{
    version(USE_IMPORT_LIB) export extern(C) void foo();

    void main()
    {
        version(USE_IMPORT_LIB)
        {
            foo();
        }
        else
        {
            import rt.dmain2, core.sys.windows.windows;
            void* handle = rt_loadLibrary("my.dll");
            alias Action = void function();
            auto f = cast(Action) GetProcAddress(handle, "foo");
            printf("handle: %p, foo(): %p\n", handle, f);
            f();
        }
    }
}
```

**Comment by sprinkle131313** [comment]
@kinke Yah I don't have a problem with it when I reduce it as simple as it can be. It must be a problem with the interaction with something else. I have a function (exists in DLL) that gets called every update from the executable. This is where it uses the associative array. If I do the following:

```D

__gshared int[][int] globalArray;

export extern(C) void update()
{
    int[][int] keepIt = globalArray; // remove this and no longer works

    // use globalArray (not keepIt)

}
```

The above code works, if a reference is kept on the stack. Which makes me think the garbage collector isn't finding the pointer for the __gshared variable. So it seems like it is the garbage collector collecting it as garbage. When it shouldn't be. Something else must be interfering with it?

**Comment by rainers** [comment]
If you suspect bad GC ranges, you can print them and compare to the addess of your global:

```
import gc.gc;
import core.demangle;
import core.stdc.stdio;

enum name = mangle!GC("gc.proxy._gc");
extern __gshared pragma(mangle, name) GC xgc;

__gshared int[][int] globalArray;

void main()
{
    printf("&globalArray = %p\n", &globalArray);

    foreach (r; xgc.rangeIter)
        printf("range %p - %p\n", r.pbot, r.ptop);
    foreach (r; xgc.rootIter)
        printf("root  %p\n", r);
}
```
You need to add the import path to the druntime sources to the compilation command line, though. Unfortunately, these are not included in the prebuilt packages, so grab them here: https://github.com/ldc-developers/druntime/tree/release-1.1.0

**Comment by sprinkle131313** [comment]
Well it doesn't seem to be in the range. The ranges seem to be only for the executable.

```
global - 7FFD623E1068

range 000001C2D4B281F0 - 000001C2D4B28208
range 000001C2D4B2F220 - 000001C2D4B2F238
range 000001C2D4B2F310 - 000001C2D4B2F328
range 000001C2D4B2F400 - 000001C2D4B2F418
range 000001C2D4B2F4F0 - 000001C2D4B2F508
range 000001C2D4B2F5E0 - 000001C2D4B2F5F8
range 000001C2D4B2F6D0 - 000001C2D4B2F6E8
range 000001C2D4B2F7C0 - 000001C2D4B2F7D8
range 000001C2D4B2F8B0 - 000001C2D4B2F8C8
range 000001C2D4B2F9A0 - 000001C2D4B2F9B8
```

**Comment by kinke** [comment]
I can't confirm this with my trivial sample above:
```
global 00007FFE707FA3B0
range 00007FFE707F5000 - 00007FFE707FBAD0
```
Just to make sure: you do link both binaries (exe + DLL) statically against druntime, right?

**Comment by sprinkle131313** [comment]
Yah I should be, I'm not setting it to use any other library, I'm just using whatever ldmd2 defaults to. Also for the code above it works when set to a local variable on the stack. That local variable isn't in the ranges either. But it still works, it's a bit puzzling. 
```
global = 00007FFD58A00068
local  = 0000001B155BF4D8
range 00000136C0B37FE0 - 00000136C0B37FF8
range 00000136C0B3F140 - 00000136C0B3F158
range 00000136C0B3F230 - 00000136C0B3F248
range 00000136C0B3F320 - 00000136C0B3F338
range 00000136C0B3F410 - 00000136C0B3F428
range 00000136C0B3F500 - 00000136C0B3F518
range 00000136C0B3F5F0 - 00000136C0B3F608
range 00000136C0B3F6E0 - 00000136C0B3F6F8
range 00000136C0B3F7D0 - 00000136C0B3F7E8
range 00000136C0B3F8C0 - 00000136C0B3F8D8
range 00000136C0B3F9C0 - 00000136C0B3F9D8
range 00000136C0B3FAB0 - 00000136C0B3FAC8
range 00000136C0B3FBA0 - 00000136C0B3FBB8
range 00000136C0B3FC90 - 00000136C0B3FCA8
```

**Comment by rainers** [comment]
I guess what you see are the ranges of the executable's GC that include main, not the GC of the DLL. You have to add the code somewhere in your DLL, e.g. inside the update function.

Thread local data is not added to the ranges, but is scanned seperately.

**Comment by rainers** [comment]
Is your pasted output the full list or just a snippet? There doesn't seem to be a sensible data segment included, neither for the executable nor the DLL. Maybe you actually have a DLL export of the broken gc_setProxy (check with `dumpbin /EXPORTS`).

**Comment by sprinkle131313** [comment]
Yah that was the entire list. The dumpbin didn't show any gc_setProxy, so "export" doesn't seem to be working there. I added a .def file to export it and now it prints nothing for the ranges. I might just stick with DMD until a shared library is built for LDC. There's another issue where it crashes when unloading the DLL as well.. Thanks for the help, if you have any more suggestions I'll keep trying.

**Comment by rainers** [comment]
Please do not export gc_setProxy, it's just asking for trouble.

I suspect that the data segment initialization (https://github.com/ldc-developers/druntime/blob/release-1.1.0/src/ldc/msvc.c#L31) is never run (to be called as C++-style initializers). This should show up as an empty range with this:
```
import rt.sections;
import core.stdc.stdio;

void main() // add this to some code inside the DLL, e.g. update()
{
    foreach (ref sg; SectionGroup)
    {
        foreach (r; sg.gcRanges)
            printf("sgrange %p - %p\n", r.ptr, r.ptr + r.length);
    }
}
```

**Comment by sprinkle131313** [comment]
gc_setProxy is never exported then, calling `GetProcAddress(lib, "gc_setProxy")` returns null.

It prints the following, without gc_setProxy being exported.
`sgrange 0000000000000000 - 0000000000000000`

**Comment by kinke** [comment]
So Rainer's suspicion appears to be right. The question is why it's not initialized properly in your case. Can you confirm that my sample above works on your machine (incl. checking the GC ranges)?

**Comment by rainers** [comment]
Now my first guess is confirmed, I suspect that the C++ initialization does not run, i.e. https://github.com/ldc-developers/druntime/blob/release-1.1.0/src/ldc/msvc.c#L86 has no effect. Are you using special C init code? It would be nice if you could build the DLL with -L/MAP and make the resulting map file available.

BTW: What OS and VS/VC versions are you using?

**Comment by sprinkle131313** [comment]
@kinke What it outputs:

```
handle: 00007FFD750F0000, foo(): 00007FFD750F10F0
-- GC -------------------------------------------
&global = 00007FFD75118A30
sgrange 0000000000000000 - 0000000000000000
-------------------------------------------------
500000 entries
  0: length = 256, 0
  80028: length = 256, 0
  930880: length = 256, 0
  105334: length = 256, 0

...

  632288: length = 256, 0
  790716: length = 256, 0
  949368: length = 256, 0
  395358: length = 256, 0
-- GC -------------------------------------------
&global = 00007FFD75118A30
sgrange 0000000000000000 - 0000000000000000
-------------------------------------------------
```
[src.d](https://github.com/ldc-developers/ldc/files/627813/src.txt)

@rainers 
What do you mean by special C init code? I am using a D executable that's loading and calling code from a D shared library. There might be one or two module constructor `shared static this()` if that'd make a difference.

Is there anything specific you need from the map file, i'd have to remove a lot of my mangled names from it.

 Windows 10 and VS 2015.

**Comment by kinke** [comment]
On my machine, it works:

```
handle: 00007FFC037B0000, foo(): 00007FFC037B10F0
&global 00007FFC037FA3B0
sgrange 00007FFC037F5000 - 00007FFC037FBAD0
```

Win10, VS 2015 Update 3, WinSDK v10.0.14393. DLL compiled with `ldc2 -shared -d-version=DLL -of=my.dll bla.d`, executable with `ldc2 bla.d`.

**Comment by sprinkle131313** [comment]
I think I found the problem, I built phobos ldc to use the dynamic library for the vc runtime. I reinstalled ldc2 and it worked, all the values seemed to be what they were suppose to.

**Comment by kinke** [comment]
It's druntime to be precise, but yeah, this obviously explains everything. I can recommend free CFF Explorer (superseded by PE Insider) to check a binary's imports/exports/dependencies to quickly diagnose such stuff in the future.

**Comment by rainers** [comment]
> What do you mean by special C init code?

Before DllMain is called, there is usually some initialization code executed by the C runtime. If you did not tweak this, you are probably running the default which should be fine.

> I built phobos ldc to use the dynamic library for the vc runtime

You don't have to recompile phobos to use a different C runtime, you can also add `-L/NOD:libcmt -L/NOD:libvcruntime msvcrt.lib vcruntime.lib` to the command line. This works for an executable, haven't tried it in a DLL yet.

@kinke can you reproduce this with the dynamic runtime?

**Comment by kinke** [comment]
I can't when using your suggestion wrt. default libs. Will retry with using the CMake switch.

**Comment by kinke** [comment]
I can't reproduce it after rebuilding LDC with the CMake switch (`-DLINK_WITH_MSVCRT=ON`) either. ?

**Comment by sprinkle131313** [comment]
`-L/NOD:libcmt -L/NOD:libvcruntime msvcrt.lib vcruntime.lib `

This works, solved the other issue I was having with unloading the DLL.

**Comment by kinke** [comment]
So you're back to using the shared C runtime, and that works as well now. So what seems to have fixed it was reinstalling LDC. :)

**Comment by kinke** [comment]
Btw @rainers, I've been thinking about automating the dynamic/static MSVCRT via `-static` (already supported by LDC for gcc). The only problem I see is that `[lib]vcruntime.lib` is only available since VS 2015. I'm not really keen on parsing the linker output to deduce its version, and we can't rely on any preset environment variables. Do you think it'd be okay to have a hard VS 2015 requirement (i.e., hardcoded linker flags)?

**Comment by rainers** [comment]
Building with VS2013 and `-L/NOD:libvcruntime -L/NOD:legacy_stdio_definitions` yields:
```
druntime-ldc.lib(msvc.obj) : error LNK2019: unresolved external symbol __processing_throw referenced in function _D3ldc2eh4msvc17msvc_eh_terminateFNbZv
druntime-ldc.lib(msvc.obj) : error LNK2019: unresolved external symbol set_terminate referenced in function _d_throw_exception
druntime-ldc.lib(msvc.obj) : error LNK2019: unresolved external symbol __current_exception referenced in function _d_eh_swapContext
druntime-ldc.lib(msvc.obj) : error LNK2019: unresolved external symbol __current_exception_context referenced in function _d_eh_swapContext
phobos2-ldc.lib(gzlib.c.obj) : error LNK2019: unresolved external symbol __stdio_common_vsprintf referenced in function _snprintf
```

Exception handling very much relies on symbols not found within the VS2013 libraries (I suspect it could be made to work, but the lack of complaints about it shows it's probably not worth supporting it).

**Comment by rainers** [comment]
> I've been thinking about automating the dynamic/static MSVCRT via -static

DMD has moved towards removing any C runtime references from the library and added a switch `-mscrtlib`: https://github.com/dlang/dmd/pull/6244. There is still a druntime PR to be merged, though.
