### ISSUE TITLE
v1.1.0-beta6 not released properly

### ISSUE THREAD

**Issue by lindt** [ldc-developers/ldc#1916]
Each release normally has the compiler attached.
It is used to build a docker image.
With the latest release the release process changed or the compiler-zip will be attached later?

**Error Message:**
```
Failed to download 'https://github.com/ldc-developers/ldc/releases/download/v1.1.0-beta6/ldc2-1.1.0-beta6-linux-x86_64.tar.xz' 
```

**Broken Docker build:**
https://hub.docker.com/r/dlanguage/ldc/builds/bnmjjdy2hihnj6raw5x9sah/

**Comment by JohanEngelen** [comment]
It's because it is not released yet! ;-)

**Comment by JohanEngelen** [comment]
(thanks for testing the latest beta versions! just wait a little bit until beta6 is really released :))

**Comment by lindt** [comment]
sorry :) and thanks for the feedback
