### ISSUE TITLE
Description of -w/-wi flags is misleading

### ISSUE THREAD

**Issue by ximion** [ldc-developers/ldc#1923]
Using LDC 1.1.0 Beta6

It looks like when compiling a D file that has warnings, supplying the -w flag will make the compilation fail - AFAIR this hasn't happened with previous releases, and the documentation suggests that this will only show warnings and not stop the compilation.

So, is the documentation or the LDC behavior wrong?

**Comment by ximion** [comment]
DMD's help says:
```
-w             warnings as errors (compilation will halt)
-wi            warnings as messages (compilation will continue)
```
while LDC says:
```
-w              - Enable warnings
-wi             - Enable informational warnings
```

So, either LDC is wrong in making warnings fatal, or the documentation is highly misleading (personally, I think having a flag like -w make fatal warnings is bad, if you want to allow warnings which do not fail the compilation).

**Comment by kinke** [comment]
This is likely to have crept in while streamlining LDC's main() with DMD's. I guess LDMD was wrong then though and didn't abort when encountering a warning.

**Comment by ximion** [comment]
So, should the documentation be clarified then?
IMHO a "warning" is - by definition - non-fatal unless it is explicitly marked as "should be fatal". This is why I think the -w/-wi difference is a bit non-intuitive.

But either way, as long as it's clear what the flags do from the documentation, I am find with it.

**Comment by kinke** [comment]
I agree, I'd find `-w` (warnings as messages) and something like `-we` (warnings as errors) more intuitive. But as we already had these DMD-compatible options (with potentially unclear description), the best course of action is to just clarify the descriptions.
It's (almost) used exclusively by the front-end, LDC itself doesn't really use it. So I'm pretty sure the behavior hasn't changed recently.

**Comment by ximion** [comment]
Okay - the `-w` flag is even more confusing because all other compilers like GCC, GDC and Clang use the very same flat to *disable* warnings, while `-W` and `-Wall` enables them...
Fun stuff ^^
I updated the bug title to reflect the actual issue.
