### ISSUE TITLE
returned array-of-array literals share address

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#1924]
```D
auto make2d()
{
    return [[0.0]];
}

void main()
{
    auto a = make2d();
    auto b = make2d();
    assert (a.ptr !is b.ptr);
    assert (a[0].ptr !is b[0].ptr); // FAILS!!!
}
```

I'm 99% sure this bug wasn't present in 1.1.0-b2, but it's definitely there in b6. Seems likely to have been caused by https://github.com/ldc-developers/ldc/pull/1821/files

This is a pretty nasty bug that could cause all manner of pain. It currently breaks https://github.com/DlangScience/dstats tests.

**Comment by JohanEngelen** [comment]
Very nice catch, thanks!

**Comment by John-Colvin** [comment]
I feel like bug reports of this sort of should also lead to a test case in upstream. Is there any process for this currently?

**Comment by JohanEngelen** [comment]
We sometimes upstream test cases. 

Living downstream is very annoying and having bug fixes and their testcases in different commits, let alone repositories, is bad and I personally am much against that. Upstreaming a testcase is an afterthought and is often not done.

**Comment by JohanEngelen** [comment]
#1927 should fix this.
@John-Colvin I've tried to think of more examples where considering a literal as constant may lead to wrong initialization (see the testcase). Perhaps you can think a little about other corner cases too.
(I found another bug during the search https://github.com/ldc-developers/ldc/issues/1925)

**Comment by JohanEngelen** [comment]
Thanks again @John-Colvin
