### ISSUE TITLE
Regr 1.1.0: ICE on dynarray-dynarray-staticarray return

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1925]
```d
auto make2d()
{
    double[][][/+ remove 1 to "fix" ICE+/ 1] a = [ [ [1.0], [1.0], [1.0], [1.0], [1.0] ] ];
    return a;
}
```
asserts with (`ldc2 -c -vv`):
```
* DtoDefineFunction(a.make2d): a.d(1)
* * DtoFunctionType(pure nothrow @safe double[][][1]())
* * * Building type: double[][][1]
* * * * Building type: double[][]
* * * * * Building type: double[]
* * * * * * Building type: double
* * * x86-64 ABI: Transforming return type
* * * * SysV RegCount: assuming 1 GP register for type [1 x { i64, { i64, double* }* }] (128 bits)
Assertion failed: (sizeInBits > 0 && sizeInBits <= 64), function RegCount, file ../gen/abi-x86-64.cpp, line 134.
```

This is a regression since 1.0.0.

**Comment by thewilsonator** [comment]
The problem seems to be that RegCount does not correctly handle static arrays at all!

```D
    if (LLStructType *structTy = isaStruct(ty)) { //Fails this test. Not a struct.
           ...
      }
      assert(int_regs + sse_regs <= 2);
    } else { // not a struct
      if (ty->isIntegerTy() || ty->isPointerTy()) { //Fails this test
        ++int_regs;
      } else if (ty->isFloatingPointTy() || ty->isVectorTy()) { //And this one.
        // X87 reals are passed on the stack
        if (!ty->isX86_FP80Ty()) {
          ++sse_regs;
        }
      } else { // Ends up here with ty.sizeof == 128
        unsigned sizeInBits = gDataLayout->getTypeSizeInBits(ty);
        IF_LOG Logger::cout()
            << "SysV RegCount: assuming 1 GP register for type " << *ty << " ("
            << sizeInBits << " bits)\n";
        assert(sizeInBits > 0 && sizeInBits <= 64); // Fails assert
        ++int_regs;
      }
    }
```

I'm not sure why a static array ends up on this code path in the first place, git blame shows https://github.com/ldc-developers/ldc/commit/44b0f7b615e33e5fadf9e3025e2320be870fc0a6 and https://github.com/ldc-developers/ldc/commit/44b0f7b615e33e5fadf9e3025e2320be870fc0a6 as last commits touching relevant code, so I think this was possibly never correct, not a 1.1.0 regression.

**Comment by kinke** [comment]
DMD's `toArgTypes()` is supposed to return a tuple of register-friendly types if the D type is to be passed in registers on System V. So for `T[][1]`, I'd have expected a tuple of 2 64-bit integers; I guess it returns a single `T[]` instead for the 1-element static array, and doesn't recursively do a `toArgTypes(T[])` which should yield the 2 integers.

**Comment by kinke** [comment]
See #1938. Note that I can't reproduce this with 1.1 beta 6 (using the Linux x64 triple), but with master.

**Comment by JohanEngelen** [comment]
Awesome that you fixed it so quickly.
I also cannot reproduce with 1.1-beta6, but I _can_ reproduce it with release-1.1.0 branch (cc6b0fc3dbc008d330dfd31d78d67424d2eb27e3) with my earlier fix #1927 . :S

**Comment by kinke** [comment]
Oh damn, I performed the test with the release binary too - no assertions. ;)

**Comment by JohanEngelen** [comment]
> no assertions

Thanks, now I can go to sleep! :)
