### ISSUE TITLE
build error:  undefined reference to `llvm::Twine::str[abi:cxx11]() const'

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#1928]
```

git clone https://github.com/ldc-developers/ldc
cd ldc
git submodule update --recursive --init
mkdir build && cd build
CMAKE_PREFIX_PATH=`brew --prefix` cmake ..

git rev-parse HEAD
1155379b2775d440599c0c44a46ae0af0daf52b2

make

[  7%] Generating bin/ldc2
/home/timothee/git_clone/D/ldc/build/lib/libldc.a(ldctraits.cpp.o): In function `traitsTargetHasFeature(Dstring)':
/home/timothee/git_clone/D/ldc/gen/ldctraits.cpp:43: undefined reference to `llvm::Twine::str[abi:cxx11]() const'
```

on Ubuntu 14.04.5 LTS

**Comment by thewilsonator** [comment]
Hmmm, git blame shows the whole file was added in June (1 revision) so it can't have "Just broken", what version of llvm are you using? How long since you last rebuilt it? etc.

**Comment by timotheecour** [comment]
never built it on this machine; IIRC it used to work (a while ago, on other machines, probably w older versions of ldc)

looks like it's using llvm-3.8 (cf /usr/include/llvm-3.8/ in log below);

```
/home/timothee/git_clone/D/ldc/build/lib/libldc.a(modules.cpp.o): In function `ForcePassLinking':
/usr/include/llvm-3.8/llvm/LinkAllPasses.h:165: undefined reference to `llvm::createPrintModulePass(llvm::raw_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
```

**Comment by thewilsonator** [comment]
Were llvm and ldc built by the same compiler and are they linking to the same version of the c++ standard library/cxxabi? because I see a `std::__cxx11::`, its possible its looking in the wrong namespace and hence not finding the symbols.

**Comment by JohanEngelen** [comment]
Can you paste CMake's output?

**Comment by kinke** [comment]
What comes to mind is that we require gcc 4.9+ for building.

**Comment by timotheecour** [comment]
ok, how should i modify my build command?
btw, this is one more reason we need to support building ldc via linuxbrew (which allows to be more selfcontained, and more cross platform), cf https://github.com/ldc-developers/ldc/issues/1729

**Comment by thewilsonator** [comment]
Either re-build llvm with c++11 or build ldc with not c++11, assuming that gcc automatically defines _GLIBCXX_USE_CXX11_ABI properly.

It should be CMAKE_CXX_FLAGS set this to the relevant c++11 mode.

**Comment by timotheecour** [comment]
CMAKE_CXX_FLAGS shows as '' in ccmake (i don't see c++11)
CMAKE_CXX_COMPILER shows as /home/timothee/.linuxbrew/bin/c++
/home/timothee/.linuxbrew/bin/c++ --version
c++ (Homebrew gcc 5.3.0) 5.3.0

**Comment by thewilsonator** [comment]
what I meant was whatever the relevant flag to gcc to use (or not use) c++11.

**Comment by rainers** [comment]
On Ubuntu 16, I recently had to build with
`CC=clang CXX=clang++ cmake -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" ../ldc`

**Comment by timotheecour** [comment]
not sure I understand what you want me to try ; you said:
> Either re-build llvm with c++11 or build ldc with not c++11
so I'd like to try to build  `ldc with not c++11` ; all I did was `CMAKE_PREFIX_PATH=`brew --prefix` ccmake .. ` [no mention of c++11 in curses gui] followed by make; and it fails; at what point does it assume c++11 ?

**Comment by timotheecour** [comment]
> On Ubuntu 16, I recently had to build with
CC=clang CXX=clang++ cmake -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" ../ldc

just tried (on ubuntu 14.04.5)

```
[  9%] Generating gccbuiltins_x86.di
../bin/gen_gccbuiltins: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ../bin/gen_gccbuiltins)
```

**Comment by JohanEngelen** [comment]
Can you build LLVM manually first and use that to build LDC? To verify that there is nothing else broken somehow.

**Comment by timotheecour** [comment]
```
git clone git clone http://llvm.org/git/llvm.git
cd path/llvm/build
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=path/usr/local/ ..
ninja && ninja install
ls path/usr/local/bin/llvm-config
#ok
ls path/stage/usr/local/include/llvm/IR
#ok

cd ~/git_clone/D/ldc/build

CMAKE_PREFIX_PATH=`brew --prefix` ccmake ..

LLVM_CONFIG path/usr/local/bin/llvm-config
LLVM_INTRINSIC_TD_PATH path/usr/local/include/llvm/IR

make
path/ldc/gen/tollvm.cpp: In function 'llvm::Constant* DtoConstFP(Type*, longdouble)':
path/ldc/gen/tollvm.cpp:428:72: error: no matching function for call to 'llvm::APFloat::APFloat(const llvm::fltSemantics& (&)(), llvm::APInt)'
                                                      APInt(80, 2, bits)));

```

**Comment by JohanEngelen** [comment]
Did you make a mistake there? Setting LLVM_CONFIG should be done before running cmake on LDC's source. Try passing `-DLLVM_ROOT_DIR="path/usr/local"` to cmake.

**Comment by JohanEngelen** [comment]
(also, use LLVM 3.9, LLVM trunk has changed a bit and compilation fails)

**Comment by timotheecour** [comment]
> (also, use LLVM 3.9, LLVM trunk has changed a bit and compilation fails)

will try when i get a chance

>> Setting LLVM_CONFIG should be done before running cmake on LDC's source. Try passing -DLLVM_ROOT_DIR="path/usr/local" to cmake

does it matter? i'm editing via ccmake gui curses options to point LLVM_CONFIG to what i want, then press [c] configure and [g] generate

**Comment by JohanEngelen** [comment]
ah, ok, thought the "ccmake" was a typo :)

**Comment by JohanEngelen** [comment]
Just checked: I can build LLVM+LDC on Ubuntu 14 without troubles, without special cmake commandline flags. (if not, our industrial user would be in big trouble! ;)
`cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86`
`cmake -DLLVM_ROOT_DIR="/usr/local" -DCMAKE_BUILD_TYPE=Release`

**Comment by timotheecour** [comment]
indeed, building llvm 3.9 from source did work. The build instructions should be updated to avoid this pain for the next guy.

CMAKE_PREFIX_PATH=`brew --prefix` ccmake ..
(the CMAKE_PREFIX_PATH was needed because of https://github.com/ldc-developers/ldc/issues/952 )

then edit:
LLVM_CONFIG=/home/timothee/temp/stage/usr/local/bin/llvm-config
LLVM_INTRINSIC_TD_PATH=/home/timothee/temp/stage/usr/local/include/llvm/IR


Things that did *not* work:

* using linuxbrew
* using apt-get on ubuntu 14.04
* building from source using /usr/include/llvm-3.8/
* building from source using LLVM trunk
* using ldc/releases (no shared libs libphobos.so, which i needed)

**Comment by JohanEngelen** [comment]
> CMAKE_PREFIX_PATH 

This will no longer be necessary soon: https://github.com/ldc-developers/ldc/pull/1832

> using linuxbrew

Don't think this has something to do with LDC: to me it looks like linuxbrew builds LLVM in a "non standard" way?

> building from source using LLVM trunk

https://github.com/ldc-developers/ldc/pull/1936
But it's unavoidable that LDC releases will not build with LLVM trunk.


Please close this bug report if you agree that what you were seeing was a problem with the LLVM installation, and not something LDC can fix.

**Comment by timotheecour** [comment]
Feel free to close, but I think at very least instructions for `build ldc from source` should be upgraded to reflect this bug report, eg:
* using  /usr/include/llvm-3.8/ didn't work (was problably installed via apt-get, althouhg i'm not sure, on the system i'm using)
* building llvm39 from source and referring to that did work

**Comment by kinke** [comment]
Right, building LDC from source using a Ubuntu/Debian LLVM distro package ought to work. I can check that later at home.

**Comment by kinke** [comment]
I installed package `llvm-dev` on Ubuntu 16.04 (LLVM 3.8) and built LDC master successfully via

```
#!/bin/bash
mkdir build-ldc
cd build-ldc
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DD_COMPILER=dmd -DLLVM_ROOT_DIR=/usr/bin ../ldc
make -j3 all
```

I don't think my self-built LLVM 3.9 in `/usr/local/bin` played a role.

**Comment by timotheecour** [comment]
I confirm that building works in ubuntu 16.04 (docs could specify to add `sudo apt-get install libconfig++-dev` on ubuntu), simply with `brew install llvm  && cmake .. && make `

however, it does *not* work in ubuntu 14.04:

NOTE: unlike what docs seem to suggest, `-DLLVM_ROOT_DIR=/home/parallels/.linuxbrew/` was useless, what we need is `-DLLVM_CONFIG=/home/parallels/.linuxbrew//bin/llvm-config`

```
sudo apt-get install libconfig++

cmake -v  ..
# obscure error message: Failed to execute llvm-config ('/usr/bin/llvm-config-3.4',

cmake -v -DLLVM_ROOT_DIR=/home/parallels/.linuxbrew/ ..
# same obscure error message

cmake -v -DLLVM_CONFIG=/home/parallels/.linuxbrew//bin/llvm-config ..
#that succeeds but ...

make

[  0%] Generating ddmd/idgen
[  0%] Generating ddmd/id.d, ddmd/id.h
Scanning dependencies of target LDCShared
[  0%] Building CXX object CMakeFiles/LDCShared.dir/gen/aa.cpp.o
cc1plus: error: -Werror=date-time: no option -Wdate-time
make[2]: *** [CMakeFiles/LDCShared.dir/gen/aa.cpp.o] Error 1
make[1]: *** [CMakeFiles/LDCShared.dir/all] Error 2

```

**Comment by thewilsonator** [comment]
Does 14.04 come with llvm 3.4 by default? If so that would explain why it tries to use 3.4 (which is unsupported)

**Comment by timotheecour** [comment]
not sure when it comes by default, but it doesn't warn about `incompatible version`  (error message rather unhelpful); i've updated docs in https://wiki.dlang.org/Building_LDC_from_source regarding using LLVM_CONFIG.

But even with that, the make fails, as above. Any chance you could try?

**Comment by thewilsonator** [comment]
>Any chance you could try?

I'm on OSX with LLVM 3.6.1, so no.

**Comment by timotheecour** [comment]
via parallels or virtualbox ?

**Comment by JohanEngelen** [comment]
Note: `LLVM_ROOT_DIR` is _not_ ineffective: I use it always and only.

**Comment by kinke** [comment]
Well, the latest official `llvm-dev` for Ubuntu 14.04 is really 3.4, so there's no point in making sure LDC can be built using an official distro package for the 2nd last LTS. Additionally, the latest official `gcc` is 4.8, and afaik, we require at least 4.9. @timotheecour managed to build LDC using a self-built LLVM 3.9 and gcc. The `libconfig++-dev` package is already mentioned on https://wiki.dlang.org/Building_LDC_from_source.
On Ubuntu 16.04, building LDC with the official distro LLVM 3.8 and official gcc works fine.
I use `LLVM_ROOT_DIR` exclusively too, but I only use it with self-built LLVMs.
Afaik, the binary releases are built on Ubuntu 12.04 with a self-built LLVM and gcc 4.9.

Is there any issue left?

**Comment by timotheecour** [comment]
> Btw, did you clean the CMake working dir before each CMake invokation?

just did `make clean` each time

> Is there any issue left? Edit: Oh, I forgot the 'rather 

ya, making message more helpful would be nice; but I've added a few notes in https://wiki.dlang.org/Building_LDC_from_source

> I use LLVM_ROOT_DIR exclusively too, but I only use it with self-built LLVMs.

ya maybe it's different on ubuntu 14.04 for some reason

All in all, the provided instructions work great for ubuntu 16.04, but would be nice to make experience on ubuntu 14.04 a little bit better. Thanks!

**Comment by kinke** [comment]
> > Btw, did you clean the CMake working dir before each CMake invokation?
> just did make clean each time

That may be the explanation for the LLVM_ROOT_DIR/LLVM_CONFIG mess and cryptic error messages. I don't have good experiences with re-running CMake (some variables are cached, so not setting them explicitly in the 2nd command line uses the previous ones instead of defaulting etc.), so I always wipe the directory before re-running CMake.

**Comment by timotheecour** [comment]
indeed! that was the case for this particular issue, thanks for the tip! LLVM_ROOT_DIR does indeed work.

I've updated https://wiki.dlang.org/Building_LDC_from_source to reflect that.

NOTE[ubuntu 14.04]: besides the unhelpful error with llvm3.4, when /usr/bin/llvm-config-3.8 is installed, building ldc will result in later link errors IIRC.

This will work though:

```
ccmake -DLLVM_ROOT_DIR=`brew --repo`
```

**Comment by JohanEngelen** [comment]
> besides the unhelpful error with llvm3.4

Fix:  https://github.com/ldc-developers/ldc/pull/1940

**Comment by kinke** [comment]
Thanks for that Johan, I think it's safe to close this now.
