### ISSUE TITLE
`sudo apt-get install ldc` fails: E: Unable to locate package ldc

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#1930]
on:Ubuntu 14.04.5 LTS

https://www.bountysource.com/issues/1376870-create-debian-ubuntu-package shows the bounty for `Create Debian/Ubuntu package` was awarded but `sudo apt-get install ldc` fails: E: Unable to locate package ldc

https://github.com/ldc-developers/ldc also shows : Ubuntu	apt-get install ldc

**Comment by kinke** [comment]
Apparently no package for 14.04, but for 12.04, 16.04 and later. Not a LDC issue though, but a Ubuntu one, as we don't maintain the distro packages ourselves.

**Comment by markos** [comment]
https://packages.qa.debian.org/l/ldc.html

I do not maintain the ubuntu packages, ubuntu just picks from Debian.

**Comment by timotheecour** [comment]
so there's currently no way to get ldc with shared libraries on linux:

apt-get install ldc => not supported on ubuntu 14.04
build from source =>  #1928
linuxbrew => #1729
ldc/relases => https://github.com/ldc-developers/ldc/issues/1929

**Comment by kinke** [comment]
'No way' is vastly exaggerated. A normal CMake build with `-DBUILD_SHARED_LIBS=ON` suffices, as done for a Travis job. #1928 hasn't been reported before, so I doubt it's a common issue.
