### ISSUE TITLE
Does not compile versioned libraries anymore

### ISSUE THREAD

**Issue by ximion** [ldc-developers/ldc#1934]
Hi!
When split-compiling a software and later linking it with a command like
```
ldc2    -of libvibe-http.so.0.7.30 'vibe-http@sha/source_vibe_http_session.d.o' 'vibe-http@sha/source_vibe_http_proxy.d.o' 'vibe-http@sha/source_vibe_http_dist.d.o' 'vibe-http@sha/source_vibe_http_router.d.o' 'vibe-http@sha/source_vibe_http_common.d.o' 'vibe-http@sha/source_vibe_http_server.d.o' 'vibe-http@sha/source_vibe_http_log.d.o' 'vibe-http@sha/source_vibe_http_auth_basic_auth.d.o' 'vibe-http@sha/source_vibe_http_auth_digest_auth.d.o' 'vibe-http@sha/source_vibe_http_websockets.d.o' 'vibe-http@sha/source_vibe_http_client.d.o' 'vibe-http@sha/source_vibe_http_form.d.o' 'vibe-http@sha/source_vibe_http_fileserver.d.o' 'vibe-http@sha/source_vibe_http_status.d.o' '-O0' '-g' '-release' '-wi' '-L-z' '-Lrelro' '-shared' '-relocation-model=pic' '-L' 'libvibe-core.so.0.7.30' 'libvibe-data.so.0.7.30' 'libvibe-utils.so.0.7.30' '-L-lz' '-L-rpath=/build/vibe.d-0.7.30/build/'
```
LDC complains with `Error: unrecognized file extension 30`.
Versioning shared libraries is very, very common, and this has worked before - so maybe this check can be relaxed to allow building versioned libraries?

**Comment by kinke** [comment]
I don't think this `'-L' 'libvibe-core.so.0.7.30' 'libvibe-data.so.0.7.30' 'libvibe-utils.so.0.7.30'` has ever worked (correctly). The versioned .so libraries are just input files (`-L` doesn't magically apply to all of them), and LDC, just like DMD has some primitive file extension check to discriminate between .d source files, object files and libraries. I guess using the `-L` prefix for these 3 libs works, please try that.

**Comment by ximion** [comment]
Indeed it works, sorry for the noise here... It worked before, so I was quick to blame LDC, while actually it looks like this is the build system's fault.
Thanks for pointing me at the issue ^^

**Comment by ximion** [comment]
The real bug was in Meson cleaning up build flags now and removing the `-L` flags I put in place... That issue is fixed now.
