### ISSUE TITLE
Issue with main.cpp::parseCommandLine

### ISSUE THREAD

**Issue by xiren7** [ldc-developers/ldc#1941]
When command line arguments of ldc2 passed by file, via something like "ldc2 @path/to/file.rsp" used by dub.

The two function called by parseCommandLine would not get the real "argc" and "argv", only get "argv[1] == @path/to/file.rsp":

```C
  const char *explicitConfFile = tryGetExplicitConfFile(argc, argv);
  std::string cfg_triple = tryGetExplicitTriple(argc, argv).getTriple();
```

So the actual problem is when ldc2 used with dub, if the host system is x86_64, and when run this command "dub -a=x86", the tryGetExplicitTriple will always return x86_64(via default value) instead of i686 triple.

**Comment by kinke** [comment]
Thanks for the detailed analysis, fixed now.
