### ISSUE TITLE
ldc installation version problem

### ISSUE THREAD

**Issue by jiafuzhang** [ldc-developers/ldc#1951]
environment:
 macOS 10.12
 HomeBrew 1.1
Installation process:
 brew install ldc
complete:
 version is ldc-1.0.1-alpha1
can be update new version?
thank you!

**Comment by kinke** [comment]
We don't maintain that stuff (incl. Linux distro packages), as the few of us can't do all of these little bits and pieces. http://braumeister.org/formula/ldc lists v1.1-beta3 as latest version, but some guy uploaded a 1.0.1-alpha1 recipe 5 days later as most recent recipe.
