### ISSUE TITLE
Fix emplace for inner classes

### ISSUE THREAD

**Issue by mmcomando** [ldc-developers/ldc#1964]
It seems that Phobos provided with LDC hasn't merged commit fixing [this issue](https://github.com/dlang/phobos/commit/b96a330b77d2c947c7c9f50e9d954b31cdf3c82e).

**Comment by JohanEngelen** [comment]
That's because LDC's Phobos is at dlang version 2.071 at the moment, and the bug fix happened in a later Phobos version. We have not merged later versions yet.

Please reopen if you think it is so important that it should be backported to our Phobos imminently.
