### ISSUE TITLE
Can't use rt_options

### ISSUE THREAD

**Issue by yosupo06** [ldc-developers/ldc#1970]
System: OSX(10.11.6)
Architecture: x86_64
LDC: 1.1.0-beta6, 0.17.2
LLVM: 3.8.0

https://dlang.org/spec/garbage.html#gc_config

I try to use this URL's rt_options.

Source code:

```
extern(C) __gshared string[] rt_options = ["gcopt=profile:1"];

import std.stdio;
int main(string[] args) {
	writeln("Hello.");
	return 0;
}

```

This code print profile with dmd(I checked v2.072.2 and v2.070.2), but don't print profile with ldc2.

**Comment by rainers** [comment]
Works for me with x64, but not x86.

**Comment by rainers** [comment]
Works with -m32, too, if you change `rt_options` to `_rt_options`.

The trouble is that the `cPrefix` in `core.demangle` is `_` while LDC adds duplicate underscores `__` for Win32. Why is that?

**Comment by yosupo06** [comment]
I try to `_rt_options`, and work with OSX(with or without -m32).

**Comment by kinke** [comment]
The extra OSX underscore is https://github.com/ldc-developers/ldc/issues/114. I guess druntime's `core.demangle` is to be fixed then.
Wrt. 32-bit Windows, I thought Rainer would know. ;)

**Comment by kinke** [comment]
Fixed in https://github.com/ldc-developers/ldc/pull/2354.
