### ISSUE TITLE
[1.1.0-beta6] dub fails to invoke the compiler

### ISSUE THREAD

**Issue by Daniel-N** [ldc-developers/ldc#1971]
cd
export PATH=~/ldc2-1.1.0-beta6-linux-x86_64/bin/:$PATH                                                                            ~
dub                                                                                                                               ~
Failed to invoke the compiler ../bin/ldc2 to determine the build platform: /bin/sh: ../bin/ldc2: No such file or directory

if I run...
cd ~/ldc2-1.1.0-beta6-linux-x86_64/bin
dub
...then it works.

**Comment by kinke** [comment]
Please open a dub issue.

**Comment by kinke** [comment]
Oh sry that's probably due to our default dub config which does specify [that relative path](https://github.com/ldc-developers/ldc-scripts/blob/master/ldc2-packaging/pkgfiles/dub/settings.json).

**Comment by Daniel-N** [comment]
Confirmed, I edited the file...
"defaultCompiler" : "ldc2"
... worked just fine!

**Comment by kinke** [comment]
Fixed (sort of) by https://github.com/ldc-developers/ldc-scripts/commit/ace4e9827fa486037263095f0cec53f2734f721b for now. A placeholder (à la `%%dubbinarypath%%`) would be a nice DUB addition though in order to tie the bundled DUB executable properly to LDC.

**Comment by JohanEngelen** [comment]
Does that change still choose the package's `ldc2` over the `ldc2` in the path?
(the relative path in the config file was intentional, but perhaps it is no longer needed)

**Comment by kinke** [comment]
As the commit msg says, it doesn't, as it *uses* the `ldc2` in the path (to at least choose ldc2 over dmd), and forcing the package's `ldc2` isn't feasible without extending DUB afaict.

**Comment by JohanEngelen** [comment]
Dub was changed to do exactly what we want, so I am surprised it doesn't work. 
@s-ludwig Can you shine some light on this? When we worked on this, I remember it worked, but I guess I was just lucky to be in a dir in which `../bin/ldc2` existed. Is there a reason the relative lookup has not been added yet?  Doing a compiler binary lookup relative to the dub executable / relative to the config file in case a relative defaultCompiler path is specified is easy to add I reckon.
