### ISSUE TITLE
ldc fails to compile unit-threaded with bizarre error

### ISSUE THREAD

**Issue by atilaneves** [ldc-developers/ldc#1975]
As seen on [this Travis CI build](https://travis-ci.org/atilaneves/unit-threaded/jobs/193478191), running `dub test` on the [unit-threaded](https://github.com/atilaneves/unit-threaded) library with LDC currently outputs this:

```
Instruction does not dominate all uses!
  %ex = alloca %object.Throwable*, align 8
  %14 = load %object.Throwable*, %object.Throwable** %ex, !dbg !360
LLVM ERROR: Broken function found, compilation aborted!
ldc failed with exit code 1.
```

**Comment by kinke** [comment]
Works fine with LDC 1.1-beta6 on Linux x86_64. Please close once confirmed.

**Comment by atilaneves** [comment]
Yep, works fine with 1.1.0-beta6.
