### ISSUE TITLE
Incorrect return value

### ISSUE THREAD

**Issue by gnunn1** [ldc-developers/ldc#1996]
I'm having an issue with GtkD that seems to be caused by LDC doing an optimization that is returning an incorrect value. In GtkD there is a class called Timeout that when created starts a timer and periodically invokes a passed function until the function returns false. This is simply a wrapper around the glib g_timeout_add function (https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-timeout-add).

The GtkD function that manages it appears as follows:

```
private bool callAllListeners()
{
	bool runAgain = false;

	int i = 0;

	while ( i<timeoutListeners.length )
	{
		if ( !timeoutListeners[i]() )
		{
			timeoutListeners = timeoutListeners[0..i] ~ timeoutListeners[i+1..timeoutListeners.length];
		}
		else
		{
			runAgain = true;
			++i;
		}
	}

	// Set timeoutID to 0 if all delegates are removed
	if (timeoutListeners.length == 0) {
		timeoutID = 0;
	}
	return runAgain;
}
```
What this code does is call the listeners (which is in my software terminix) and return true/false depending on whether any of the listeners want the timer to continue. In my case, the listener always returns false which should result in runAgain returning false. However I can see the timeout continues to be invoked by GTK which indicates it got true as a return value.

My thinking is that LDC is erroneously optimizing runAgain to return true. If I modify the function to add one line below runAgain as follows, it works as expected:

```
private bool callAllListeners()
{
	bool runAgain = false;

	int i = 0;

	while ( i<timeoutListeners.length )
	{
		if ( !timeoutListeners[i]() )
		{
			timeoutListeners = timeoutListeners[0..i] ~ timeoutListeners[i+1..timeoutListeners.length];
		}
		else
		{
			runAgain = true;
			++i;
		}
	}

	// Set timeoutID to 0 if all delegates are removed
	if (timeoutListeners.length == 0) {
		timeoutID = 0;
	}
	if (!runAgain) writeln("Run again is false");
	return runAgain;
}
```
Notice the only change is the new line explicitly checking the runAgain variable, it has no impact on it's value. With this change everything runs as expected. I've also tried using the ```-O0 ``` switch to disable optimization but it didn't make any difference.

The code works fine in DMD with no change required. Running ```ldc2 --version``` outputs the following:

```
LDC - the LLVM D compiler (1.0.0):
  based on DMD v2.070.2 and LLVM 3.8.0
  built with DMD64 D Compiler v2.071.0
  Default target: x86_64-unknown-linux-gnu
  Host CPU: haswell
  http://dlang.org - http://wiki.dlang.org/LDC
```

The original terminix bug report is located here https://github.com/gnunn1/terminix/issues/745

**Comment by kinke** [comment]
Please check with latest v1.1.

**Comment by gnunn1** [comment]
I tried LDC 1.1 beta 6 from the releases, no change in behavior from 1.0.

**Comment by kinke** [comment]
Thanks for checking. 1.1 final is out btw (but won't change the behavior).

**Comment by JohanEngelen** [comment]
> `while ( i<timeoutListeners.length )`

Perhaps LDC generates code that assumes `timeoutListeners.length` is constant?

**Comment by JohanEngelen** [comment]
Is this still an issue? If so, can you give a full reproducing testcase (or description of it)?

**Comment by kinke** [comment]
Nothing actionable here.
