### ISSUE TITLE
inconsistent behavior of ldmd with -of, missing extension

### ISSUE THREAD

**Issue by BBasile** [ldc-developers/ldc#2001]
`dmd somefile.d -lib -ofdir/somelib` outputs `somelib.a` in `dir`
`ldmd somefile.d -lib -ofdir/somelib` outputs `somelib` in `dir`

DMD adds a extension when no `.` is present in the filename part of the `-of` argument.

**Comment by timotheecour** [comment]
* behavior of dmd/ldmd
* arguably dmd's behavior is too magical though

**Comment by BBasile** [comment]
I don't thing it's a good idea at all to change DMD. LDMD should layer its behavior on DMD. DMD way of handling this case is good because extensions are system specific. In my example the same command line can be used on win or on linux, in one case to prduce a _.lib_, in the other a _.a_. This is something my IDE relies on BTW.

**Comment by kinke** [comment]
Thanks for noticing, although I don't think any tool should rely on automatic file extensions.

**Comment by kinke** [comment]
Fixed by #2002.
