### ISSUE TITLE
Pooled identifiers for LDC specific symbols & modules

### ISSUE THREAD

**Issue by thewilsonator** [ldc-developers/ldc#2011]
We should extend upstream with a mechanism for adding backend-specific members to Identifier (probably also refactoring DMD-specific stuff into that). Also do something similar for "magic modules"  like `ldc.attributes` to allow detection by pointer comparison.

Should help optimise `gen/uda.cpp` and `gen/dcomputetypes.cpp`.

**Comment by ibuclaw** [comment]
Should be a simple `#include "id.defs"` added to the C++ idgen generator, and `mixin(import("id.defs"))` in the D idgen generator.

Contents and name of file just needs to be disputed.

**Comment by ibuclaw** [comment]
Actually I changed my mind, this is an optimization that we can do locally without changing frontend sources.
