### ISSUE TITLE
Is there a way to code generate differently per-block or per-function?

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#2035]
I read complaints on Internet forums on how clang doesn't allow to generate "mixed" SSE (compatible with older processors) and AVX in the same file.

Q: Is it possible in LDC to have something like this?

```d
if (core.cpuid.avx2())
{
    pragma(ldc.attr.enable, "avx2");
    // do stuff, codegen targets AVX2 or below
}
else 
{
     // do stuff, codegen targets whatever was passed on cmdline
}
```

Us app developers must support sometimes very old processors.

**Comment by JohanEngelen** [comment]
Per function,  yes: for example `@target`, `@fastmath`, `@optStrategy`
https://wiki.dlang.org/LDC-specific_language_changes#Attributes

**Comment by p0nce** [comment]
Sorry, didn't read enough.
