### ISSUE TITLE
Release 0.17.4

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2053]
A checklist of things to do before tagging 0.17.4.

- [x] Support LLVM 3.5 - 4.0
- [x]  Use https:// instead of git:// for submodules, similar to https://github.com/ldc-developers/ldc/pull/2051
- [x] Cherry-pick solution for #2042 (see #2052 )

**Comment by WebDrake** [comment]
Will these changes also make it to a 1.1.2 release and into 1.2.x?

**Comment by JohanEngelen** [comment]
For 1.2.x, yes.
For 1.1.2, meh... is it really needed?

**Comment by WebDrake** [comment]
Can you clarify what the differences will be between 1.1.1 and 1.2.0, and when the latter is expected to be released?

The patches are useful for 1.1.x in order to be able to integrate the build for the 1.1.x snap package into Launchpad CI.  But if 1.2.0 will be released soon, it might be better to go straight for that (saving everyone some hassle of an extra release).

**Comment by JohanEngelen** [comment]
1.2.0 is based on a newer frontend. We plan to release 1.2.0 soon and already have a 1.2.0-beta1 release out.

**Comment by WebDrake** [comment]
Yes, I've seen the betas.  I just remember there was a long gap between betas of 1.1.0 and the final release, so wanted to check whether this was expected to be a matter of a week or two, or many weeks.  (Yes, I know, it's ready when it's ready:-)

Assuming 1.2.0 is expected to not be more than a couple of weeks away, I'm happy to drop the request for a 1.1.2.  But of course I understand the hassle of a point release, so no problem you just don't want to do that anyway.

**Comment by JohanEngelen** [comment]
@redstar wants to create beta2 this weekend, and push for the final release soon after.
The 1.1.x release cycle was indeed very long, but that is (and was) not how we'd like things to be.

**Comment by WebDrake** [comment]
All good, then.  Let's not worry about any 1.1.x patch releases. :-)

**Comment by WebDrake** [comment]
Question: what LLVM version will be used for the 0.17.4 and 1.2.0 releases?

**Comment by JohanEngelen** [comment]
Probably LLVM 4.0.  (0.17.4 is I think only a source release, if you are downloading a precompiled binary you may better download the latest release instead)

**Comment by WebDrake** [comment]
That's fine, I build everything fresh from source. Just wanted to confirm whether 4.0 was considered recommended for use (as opposed to, possible to use).

**Comment by WebDrake** [comment]
Is there a branch already in place for the upcoming 0.17.4 release ... ?

**Comment by kinke** [comment]
No branch, it's gonna be a tag (`ltsmaster` at the time it is tagged).

**Comment by WebDrake** [comment]
Gotcha. `ltsmaster` is fine for the test purposes I have in mind.

**Comment by kinke** [comment]
I cherry-picked your commit onto `ltsmaster`, so I think we're ready to roll.

**Comment by WebDrake** [comment]
Can you give me tonight just to verify that some things work before tagging 0.17.4...?

**Comment by kinke** [comment]
Of course :D, thanks for testing.

**Comment by WebDrake** [comment]
Both ltsmaster and release-1.2.x are looking good from my side of things!  Thanks for the patience :-)

**Comment by WebDrake** [comment]
The slightly more extended version: I was able to set up successful Launchpad automated builds of the snap package using ltsmaster for the bootstrap and 1.2.x for the packaged compiler.  This built successfully for both amd64 and i386; I'm currently running some armhf and arm64 builds just to see what will happen.

Once 1.2.0-beta2 is out, I'll start actually publishing development builds via the 'edge' channel of the snap store.

**Comment by JohanEngelen** [comment]
I've tagged v0.17.4 and am finalizing the release.
