### ISSUE TITLE
enhancement: LLVM 5.0 supports "contract" FMF

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2059]
LLVM 5.0 gained the `contract` FastMathFlag, that enables fusing ops without having to enable all kinds of other fastmath options. (see e.g. https://reviews.llvm.org/D31169)

First step is for us to extend the magic `@ldc.attributes.llvmFastMathFlags` attribute implementation to support `"contract"`.  (the implementation is trivial, and probably less work than typing this issue :( )

Perhaps we can add a convenience attribute similar to `@fastmath`, something like `@fusedmath`. I don't know whether `contract` it is useful enough without the other FMFs. Hope @9il could do some testing ;-)

**Comment by JohanEngelen** [comment]
For reference: https://reviews.llvm.org/D31169

**Comment by JohanEngelen** [comment]
@9il  So, with some very rudimentary testing, the `contract` flag gives you operator fusing, but not reassociation. Is that helpful for some of your algorithms?

**Comment by 9il** [comment]
Yes

**Comment by kinke** [comment]
Implemented by https://github.com/ldc-developers/ldc/pull/2060.
