### ISSUE TITLE
std.process not working in Docker

### ISSUE THREAD

**Issue by jacob-carlborg** [ldc-developers/ldc#2078]
Trying to use the latest release of LDC (1.2.0) in a Docker container (tried with both Ubuntu 16.10 and 16.04). As soon as I'm trying to execute a process using one of the functions in `std.process`, the process always exit with the code `-11`. Example:

```d
root@d2a50b23a626:~# cat main.d
module main;

import std.process;
import std.stdio;

void main()
{
    auto a = executeShell("ls");
    writeln(a.status);
}
root@d2a50b23a626:~# ./ldc2-1.2.0-linux-x86_64/bin/ldc2 -run main.d
-11
root@d2a50b23a626:~#
```

DMD seems to have the same problem if I use 2.072.2 which LDC 1.2.0 is based on. The latest version of DMD 2.074.0 does not have the same problem. So I guess this is a bug in std.process that has been fixed.

I cannot reproduce the issue in a virtual machine running Lubuntu 16.04 (this is what I already had installed).

If this bug is fixed in upstream, would it be possible to backport it and release in a minor version?

**Comment by kinke** [comment]
1.3, based on 2.073.2, is around the corner (first beta this weekend) and 2.074 is currently being merged (branch `merge-2.074`), so I think a backport to 1.2 and a new minor release is rather unlikely.
If the fix is not in 2.073 already, we may backport it to 1.3 before the final release, please check.

**Comment by kinke** [comment]
If [that](https://github.com/dlang/phobos/commit/aec837beca951d6e7194e93a08de6cb375230e42) is the fix, it's in 2.073 (and LDC master).

**Comment by jacob-carlborg** [comment]
Yes, DMD 2.073.0 works. I didn't know that the next version of LDC was so close.

**Comment by kinke** [comment]
I'll close this then since it should be fixed in LDC master already.
