### ISSUE TITLE
Windows: EH crashes when using shared C runtime (-mscrtlib=msvcrt)

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#2080]
See https://github.com/ldc-developers/ldc/pull/2041#issuecomment-287617489. Some more Rainer-voodoo is needed in https://github.com/ldc-developers/druntime/blob/ldc/src/ldc/eh/msvc.d#L323.

**Comment by rainers** [comment]
> Some more Rainer-voodoo is needed

See https://github.com/ldc-developers/druntime
