### ISSUE TITLE
`-output-ll -of test.s` outputs `test.ll` and `test.s`

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2105]
When specifying an output file together with `-output-ll`, LLVM IR is written to the specified output file:
`ldc2 -c -output-ll test.d -of dummy.blah` creates the file `dummy.blah` and writes LLVM IR to that file.
 But if the output filename ends with `.s`, 
`ldc2 -c -output-ll test.d -of dummy.s`
_two_ files are created: `dummy.ll` and `dummy.s`. Clearly a bug, and I do not know how to write LLVM IR to a `.s` file. (one of the effects of this bug is that we cannot see LLVM IR output at d.godbolt.org)

**Comment by kinke** [comment]
This is a 'feature': https://github.com/ldc-developers/ldc/blob/master/driver/main.cpp#L533-L558

It recognizes the output extension as assembly and thus enables `-output-s`. As we then have 2 output files for that module (but only a single output filename), they each get the default extension for uniqueness, and so the .ll contains the IR and .s the assembly.

**Comment by kinke** [comment]
The autodetection should at least not enforce this behavior as it currently does, so that an explicit `-output-s=false` could be used under such rather special circumstances.

**Comment by kinke** [comment]
Fixed by #2118.

**Comment by JohanEngelen** [comment]
Thanks @kinke
