### ISSUE TITLE
No DWARF symbols in .obj/.exe files on Windows with '-g'

### ISSUE THREAD

**Issue by Delthas** [ldc-developers/ldc#2145]
LDC (I'm using ldc2-1.3.0-beta1-win64-msvc) does not generate DWARF debugging symbols in object or executable files.
Here's the sample file I tried to compile:
```d
void main()
{
    import std.stdio;
    writeln("cc");
    return;
}
```

Here's the command I ran:
```ldc2.exe -march=x86 -c -g app.d```

It created an ```app.obj``` file as expected, however when running ```objdump --dwarf app.obj``` from a linux system, only ```app.obj:     file format pe-i386``` is printed without any other information, whereas when doing the same for a ```app.o``` file compiled from the same app.d example on a linux system, a lot of lines are printed (meaning there is a lot of debug information).

The same happens (as expected) when creating an exe, using ```ldc2.exe -march=x86 -g app.d```. ```objdump --dwarf app.exe``` only prints ```app.exe:     file format pei-i386``` whereas a lot of lines are printed for an ```app``` executable created on a linux system.

And as expected running gdb app.exe on Windows prints ```Reading symbols from app.exe...(no debugging symbols found)...done.``` whereas on Linux it simply prints ```Reading symbols from app...done.```.

This means debugging is impossible on Windows, except maybe with Visual Studio when asking LDC to create .pdb files, since these seem to get created (afaik GDB doesn't support PDB files). But I'd like to keep using DDT/Eclipse as I'm more used to Eclipse interface.

**Comment by kinke** [comment]
> ldc2-1.3.0-beta1-win64-msvc

**msvc** stands for Windows' native Microsoft Visual C(++) toolchain, which uses CodeView (.pdb) debuginfos. If that's unsupported by gdb, you'd have to target the GNU toolchain via `ldc2 -mtriple=i686-pc-windows-gnu`, but MinGW support in druntime/Phobos has been neglected for some time and doesn't work anymore. See [this thread](http://forum.dlang.org/thread/mailman.2298.1494866833.31550.digitalmars-d-ldc@puremagic.com) for some more context if you're interested.

**Comment by kinke** [comment]
You may want to give LLVM's `lldb` a try.
