### ISSUE TITLE
Unable to link when introducing a class

### ISSUE THREAD

**Issue by danwalmsley** [ldc-developers/ldc#2169]
Hey guys, I'm basically trying to compile a minimal bare-metal D application for STM32.

https://github.com/VitalElement/STM32DBlinky contains all the code.

My compile commands look like this.
```
ldc2  -c -O0 -march=thumb -mcpu=cortex-m4 -mtriple=thumb-none-linux-eabi  -g -betterC  C:\dev\repos\STM32DBlinky\Blinky\main.d -ofC:\dev\repos\STM32DBlinky\Blinky\build\obj\main.o
ldc2  -c -O0 -march=thumb -mcpu=cortex-m4 -mtriple=thumb-none-linux-eabi  -g -betterC  C:\dev\repos\STM32DBlinky\Blinky\gcc\attribute.d -ofC:\dev\repos\STM32DBlinky\Blinky\build\obj\attribute.o
ldc2  -c -O0 -march=thumb -mcpu=cortex-m4 -mtriple=thumb-none-linux-eabi  -g -betterC  C:\dev\repos\STM32DBlinky\Blinky\stm32f4xx_startup.d -ofC:\dev\repos\STM32DBlinky\Blinky\build\obj\stm32f4xx_startup.o
```

but I get errors when linking (see the output)
(my link command is)
```
arm-none-eabi-gcc -mcpu=cortex-m4 -Wl,-Map,output.map -nostdlib  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -nostartfiles -Wl,--gc-sections  -O0 -Wl,-T"C:\dev\repos\STM32DBlinky\Blinky\link.ld"  -oC:\dev\repos\STM32DBlinky\Blinky\build\bin\Blinky.elf C:\dev\repos\STM32DBlinky\Blinky\build\obj\main.o C:\dev\repos\STM32DBlinky\Blinky\build\obj\attribute.o C:\dev\repos\STM32DBlinky\Blinky\build\obj\stm32f4xx_startup.o   -Wl,--start-group   -Wl,--end-group
```

where would it normally get those missing symbols from?

![image](https://user-images.githubusercontent.com/4672627/27227255-9f6fdf36-529a-11e7-9550-52e67a0f722e.png)

**Comment by kinke** [comment]
Please don't spam our issue tracker as what you're after has nothing to do with LDC issues - you're simply having a hard time reducing druntime to something minimal. A NG/forum post seems more adequate and will get more attention from non-LDC devs.

> where would it normally get those missing symbols from?

As I already stated in one of your other issues, most of these symbols are in vanilla `object.d`; this time you have some additional missing symbols from other druntime parts. If you're unfamiliar with D mangling, you can use the `ddemangle` tool like this: `echo _D6object6Object8toStringMFZAya | ldc2-1.3.0-beta2-win64-msvc\bin\ddemangle`, which results in `object.Object.toString()`. Then just simply grep the [druntime](https://github.com/ldc-developers/druntime) source for the missing symbols and work from there.
