### ISSUE TITLE
fabs() slower than llvm_fabs

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#2182]
So I'm getting a bit of speed-up replacing some of the phobos functions by ldc.intrinsics.
The most curious was `abs(float)`, it's not replaced by `ldc.intrinsics.lvm_fabs` and it wins something like 10% speed-up in a real application.
Note that these intrinsics better be aliased rather than called from a trampoline function, else I don't manage to have full inlining.

**Comment by kinke** [comment]
Don't know at which `fabs()` you looked at, but `std.math.fabs()` already is an alias for `llvm_fabs`: https://github.com/ldc-developers/phobos/blob/ldc/std/math.d#L3756-L3760

**Comment by kinke** [comment]
Using aliases instead should be trivial - PR maybe? ;)

**Comment by p0nce** [comment]
OK. To illustrate the bigger problem with intrinsics. https://godbolt.org/g/nD6Axt
They never get inlined in wrapper functions...

**Comment by JohanEngelen** [comment]
cross-module inlining... :(   haven't worked on that for a while :(

**Comment by kinke** [comment]
Well that's where LTO should shine, right? Is `-enable-cross-module-inlining` still worth to be worked on?

**Comment by JohanEngelen** [comment]
Yeah LTO should do the same, but depending on your build setup, buildtime is slower. It'd be nice not having to depend on LTO.

**Comment by Kozzi11** [comment]
LTO does not help much here for some reasons.
This [code](https://dpaste.dzfl.pl/16c565e3ce5e)

with lto:

    real	0m7,805s
    user	0m7,803s
    sys	0m0,000s

without lto:

    real	0m11,322s
    user	0m11,315s
    sys	0m0,007s

with using llvm_sqrt directly without lto

    real	0m7,185s
    user	0m7,182s
    sys	0m0,003s

with using llvm_sqrt directly with lto

    real	0m5,163s
    user	0m5,158s
    sys	0m0,003s

**Comment by kinke** [comment]
@Kozzi11: I guess you didn't compile druntime/Phobos with LTO and link against those libs?

**Comment by Kozzi11** [comment]
@kinke I am using default libs from archlinux, so it is possible I am not using LTO enabled libs.

**Comment by JohanEngelen** [comment]
`-DLDC_BUILD_WITH_LTO=thin` will build LDC itself with LTO enabled (so LDC itself will be more optimized), but does not build the runtime libs with LTO enabled. For that, you can use the `ldc-build-runtime` tool: https://wiki.dlang.org/Building_LDC_runtime_libraries

**Comment by kinke** [comment]
I had a go with aliases in `std.math` but got interrupted by some (IMO stupid) tests making sure they are real functions (and their address can be taken). I made some `core.math` symbols aliases and annotated the `std.math` wrappers with `pragma(inline, true)`, so the remaining issue is #2552.
