### ISSUE TITLE
unrestricted-unions invoke postblit

### ISSUE THREAD

**Issue by RosettaCoder** [ldc-developers/ldc#2185]
https://dlang.org/changelog/2.072.0.html#unrestricted_unions

Seems like postblits are still invoked for unions in ldc?

This prints 0 on dmd, but 1 on ldc. (occurs on all versions new enough to support unrestricted_unions)

```
import std.stdio;

long post = 0;

struct Node
{
  uint val;

  this(this) { ++post; }
}

union POD(T)
{
  T val;
}

POD!Node g;

void Put(ref Node val)
{
  g = cast(POD!Node)val;
}

void main()
{
  auto x = Node(5);
  x.Put();
  post.writeln;
}
```
**Update:**
Hmm interestingly, if I change the prototype of Put, I can get dmd to fail too?
void Put(ref Node val) // both ldc and dmd invoke postblit?
void Put(ref const(Node) val)  // only ldc invokes postblit

**Comment by kinke** [comment]
I love it how DMD changes specs and doesn't accompany it with appropriate tests. Not the first time of course. Thanks for bringing this to our attention.

**Comment by kinke** [comment]
Yep that's it more or less (no additional dtor call though). In the non-const ref case, the front-end generates an explicit postblit call for the temporary:
```
* * * * AssignExp::toElem: g = POD(((Node __copytmp56 = (__copytmp56 = val).__postblit();) , __copytmp56))
```

In the const ref case, the front-end generates a simple assignment from a new struct literal:
```
* * * * AssignExp::toElem: g = POD(val)
```
But LDC calls the postblit when assigning `val` to the single field of the temporary, which makes sense to me, as it cannot be moved from the `val` lvalue.

**Comment by kinke** [comment]
@RosettaCoder: This isn't testing what you want. You are only assigning fresh rvalues to the global, and those are moved anyway. You most likely expected a bitcast on the rhs, but that is expressed like this: `g = *cast(POD!Node*)&val;`. This works as expected, no postblit calls.

I keep the issue open because of the divergence wrt. DMD for the const-ref case.

**Comment by RosettaCoder** [comment]
Thank you for your thorough explanation!

Just for my understanding, what if I do like this:

union POD(T)
{
  T val;
  this(T) @disable;
}

Would that force the cast to be a proper bitcast?
cast(POD!(Node))val

It seems to give the result I wanted at least... does it have any drawback compared to your solution:
*cast(POD!Node*)&val

**Comment by kinke** [comment]
Yep, this seems to result in a bitcast too; the front-end emits
```
* * * * AssignExp::toElem: g = cast(POD!(Node))val
```

Note that you can check what the front-end spits out (and quite a lot more stuff :]) yourself via `ldc2 -vv`.

> does it have any drawback compared to your solution

[I'm not exactly a D expert when it comes to actually using it. ;)] I think it's fine, but I find it less intuitive, as one has to notice the disabled ctor and know that this then results in a bitcast, whereas `*cast(...*)&var` is a bit ugly but clearly a bitcast.
Your variant is `@safe` though (at least the compiler doesn't complain).

**Comment by kinke** [comment]
Your variant obviously prevents implicit convertibility of `Node`s to `POD!Node`s, so `POD!Node y = Node(3)` doesn't work and requires an explicit cast.

You could use this to only disallow implicit conversion from `Node` lvalues to prevent the unwanted implicit postblit for the field:
```D

union POD(T)
{
  T val;
  this(T v) {
    import std.algorithm.mutation: move;
    val = move(v);
  }
  this(ref T) @disable;
}

...

auto x = Node(5);
POD!Node y = Node(3); // works fine; no postblit
POD!Node z = x; // doesn't compile
```

**Comment by RosettaCoder** [comment]
> ldc2 -vv
Ahh, that is a great tool.

Fantastic, many thanks, now everything is clear.

**Comment by kinke** [comment]
You're welcome. You may also come to love `ldc2 -output-ll`, I for sure did. ;)

**Comment by kinke** [comment]
> I keep the issue open because of the divergence wrt. DMD for the const-ref case.

I looked deeper into DMD's const-ref anomaly, which seems to lead to a more general issue (missing postblit when casting away the constness of a rhs lvalue). I filed https://issues.dlang.org/show_bug.cgi?id=17920 with a reduced test case which also fails with LDC 1.5.

So we can close this now.
