### ISSUE TITLE
ldc.conf and switch order

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#2186]
switches in ldc.conf are added to `allArguments` in `parseCommandLine`, deliberately inserted before any command-line switches. What was the motivation for this order? AFAICT `dmd` does it the other way around.

**Comment by kinke** [comment]
Simple - being able to override the default switches in the config.

**Comment by John-Colvin** [comment]
Some things work the other way around though: e.g. linker flags are normally processed left to right, so if I add a path for the linker to search in it will always be searched *after* the paths in the config. That wouldn't be so bad if those were paths that only contained Phobos (because can use defaultlib to override), but it's common to have `/usr/bin` or `/usr/local/bin` used, which means you can't use -L flags to override system libraries like you can with `dmd` and `gcc/clang`.

**Comment by kinke** [comment]
Yep, the (few) list options obviously cannot be overridden and only appended to this way. For these few, the relative order only matters for `-L` and `-Xcc` afaict.
Selected libraries may be overridden by using their path as input (`ldc2 ... /path/to/libmine.a`), or, as a last resort, by specifying another config file with no lib paths.

Open for suggestions on how to improve this, but simply appending the default switches makes ~99% of those non-overridable (incl. `-defaultlib=` for the bare metal guys), so I'm against that.

**Comment by kinke** [comment]
(E.g., we could filter out all default switches beginning with `-L-L` and append those to the command line.)

**Comment by JohanEngelen** [comment]
@John-Colvin How about what @kinke proposed?  Filtering `-L-L` switches and adding those in front of ldc.conf switches?

**Comment by kinke** [comment]
> generalizable to a "post-switches = [ ... ]" section in ldc.conf

Hmm, tasty, I like it, making the process fully transparent. `pre/post-switches`? `switches-prefix/suffix`?

**Comment by JohanEngelen** [comment]
Do we have to be careful about backward compatibility? (i.e. we need to preserve the "switches" name?)

We can also add comments in the JSON making things clear if the names aren't.

**Comment by kinke** [comment]
We can simply fall back to `switches` for the prefix ones if the new name isn't found.

**Comment by JohanEngelen** [comment]
true. Go for it. Would be a nice addition :)

**Comment by kinke** [comment]
> Go for it.

It's not like I don't do enough here already. Way too much of my spare time actually.

**Comment by kinke** [comment]
Fixed by #2281.
