### ISSUE TITLE
Semaphore CI: Use custom LLVM build with enabled assertions and LTO plugin

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#2189]
As suggested in #2074. And don't forget LLD.
Semaphore is based on Ubuntu 14.04.

**Comment by kinke** [comment]
I used https://github.com/ldc-developers/ldc-scripts/pull/5 to build LLVM 4.0.1 with enabled assertions and use it for SemaphoreCI now, which already fails due to assertions, most if not all apparently caused by debuginfos: https://semaphoreci.com/ldc-developers/ldc/branches/master/builds/81

**Comment by JohanEngelen** [comment]
Oh wow, this is pretty bad :( great that you found it.

**Comment by kinke** [comment]
Assertions fixed; LTO plugin now included (https://github.com/ldc-developers/ldc-scripts/pull/5/commits/7f6f490fb59e0c7bb106335c387889fb56fc26ea) and working.
