### ISSUE TITLE
llvm version of druntime missing required object files when BUILD_BC_LIBS option is on

### ISSUE THREAD

**Issue by singularpoint** [ldc-developers/ldc#220]
Object files from C sources (targets DCRT_C and CORE_C at runtime/CMakeLists.txt) doesn't get included in druntime-ldc-bc.a.
It should be compiled by llvm-gcc (and it seems to work) and archived as library by llvm-ar.

**Comment by kinke** [comment]
The LTO libs include the few C parts (in machine code).
