### ISSUE TITLE
PPC64: Forward reference error with 1.3 release

### ISSUE THREAD

**Issue by redstar** [ldc-developers/ldc#2200]
Compiling on ppc64le (little endian) results in the error:

    [  3%] Generating src/core/bitop.o
    /home/ubuntu/ldc/runtime/druntime/src/core/bitop.d(105): Error: template instance llvm_cttz!ulong cannot resolve forward reference
    /home/ubuntu/ldc/runtime/druntime/src/core/bitop.d(171): Error: template instance llvm_ctlz!ulong cannot resolve forward reference
    /home/ubuntu/ldc/runtime/druntime/src/core/bitop.d(983): Error: template instance llvm_bitreverse!uint cannot resolve forward reference
    /home/ubuntu/ldc/runtime/druntime/src/core/bitop.d(1023): Error: template instance llvm_bitreverse!ulong cannot resolve forward reference

I get the same error but at a different module when compiling on ppc64 (bigendian).

**Comment by redstar** [comment]
For ppc64le, this error is fixed in release 1.5, using ldc 0.17.6 as bootstrap compiler.

**Comment by kinke** [comment]
If you have a bit of time, it'd be perfect if you could investigate https://github.com/ldc-developers/ldc/issues/2356 (ppc64) a little bit, that's currently blocking Debian/Ubuntu...

**Comment by redstar** [comment]
I try. :-) The buildbot (http://buildbot.ldc-developers.org/waterfall) still has a lot of crashes in the test log...

**Comment by kinke** [comment]
Ah thanks for the link. :) I looked into the first 4-5 failures, all varargs-related.

**Comment by redstar** [comment]
I first check if the forward reference error is gone on ppc64 (big endian), too. Then I have a closer look at the other failures. (The powerosl builder is little endian, the openpowerhub builder is big endian.)

**Comment by kinke** [comment]
Just curious, how does the endianness work on Power? Can you reboot with a different OS and switch endianness this way?

**Comment by redstar** [comment]
It depends on the CPU. Low-cost Power8 has only little endian (the boxes are sold only with Linux). The boxes which run AIX (which is big endian) can switch endianess on boot time per LPAR/VM.

**Comment by redstar** [comment]
Fixed on ppc64 (big endian), too.
