### ISSUE TITLE
Lit tests: stop using `%T`

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2274]
The `%T` expansion will be removed from Lit. See: https://lists.llvm.org/pipermail/llvm-dev/2017-August/116320.html
This means that each of our tests that use it will have to create there own temporary dir. To see how it's done: https://reviews.llvm.org/D36434
It boils down to doing
```
// RUN: rm -rf %t-dir
// RUN: mkdir -p %t-dir
```
before running the test, and using `%t-dir` instead of `%T`.  (I think `%t-dir` is nice, but any `%t*` would do of course)

I don't have time for this now, but it is important to know about and stop using %T in new tests to avoid having trouble with newer Lit versions. Hope to get around fixing this in existing tests soon. For now, I'll only update the wiki page.

**Comment by JohanEngelen** [comment]
Note that most of our tests were already using a test-specific subfolder of `%T`, so simply replacing `%T` with `%t-dir` would work there.

**Comment by kinke** [comment]
Such an inconvenience. [Windows doesn't have `rm` out of the box (but should come with git), and the shell intrinsic `mkdir` accepts no params.]

**Comment by JohanEngelen** [comment]
`linking/ir2obj_caching.d` and `linking/ir2obj_caching_retrieval.d` are using the same `%T/cachedirectory` output dir. That's probably the reason behind the occasion test failure.
