### ISSUE TITLE
Support cyclic dependencies with -cov

### ISSUE THREAD

**Issue by luismarques** [ldc-developers/ldc#2339]
I have a legacy codebase where I would like to run coverage analysis. Unfortunately the `-cov` option fails at runtime when the project has cyclic dependencies. This is mentioned in #2177. Would it be possible to make coverage analysis run even when there are cyclic imports?

**Comment by JohanEngelen** [comment]
@luismarques #2382

**Comment by luismarques** [comment]
Thanks for fixing this. You guys rock.

**Comment by JohanEngelen** [comment]
duplicate: #2177
