### ISSUE TITLE
Crash via "Assertion `decl->ir->irGlobal != NULL' failed"

### ISSUE THREAD

**Issue by ximion** [ldc-developers/ldc#2357]
We found this one in Debian/Ubuntu while building Sambamba[1]
```
ldc2: /build/ldc-1.4.0/ir/irvar.cpp:44: IrGlobal* getIrGlobal(VarDeclaration*, bool): Assertion `decl->ir->irGlobal != NULL' failed.
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x1a)[0x7f5d42064cea]
/usr/lib/x86_64-linux-gnu/libLLVM-5.0.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0x56)[0x7f5d42062fd6]
```
```
LDC - the LLVM D compiler (1.4.0):
  based on DMD v2.074.1 and LLVM 5.0.0
  built with LDC - the LLVM D compiler (0.17.5)
  Default target: x86_64-pc-linux-gnu
  Host CPU: haswell
  http://dlang.org - http://wiki.dlang.org/LDC
```
The issue appears to affect all architectures and did not happen with LDC 1.2.

Here is a slightly more minimized testcase, with no additional dependencies other than LDC: [ldc_assert_crash_test.tar.gz](https://github.com/ldc-developers/ldc/files/1354469/ldc_assert_crash_test.tar.gz) (could likely be reduced even further).

Cc @LocutusOfBorg

[1]: https://github.com/lomereiter/sambamba

**Comment by kinke** [comment]
Note that I mentioned and somewhat analyzed this already in https://github.com/ldc-developers/ldc/issues/2336. It's not clear whether that has to do with the general template culling issue or whether it's something different.

**Comment by ximion** [comment]
Ah, nice - so this likely is a duplicate then.

**Comment by kinke** [comment]
The crash should be fixed by #2366. I hope sambamba now builds fine on Debian. The fix is in v1.5.0-beta1 which will be released in a couple of hours.

**Comment by LocutusOfBorg** [comment]
thanks!

**Comment by ximion** [comment]
This is indeed fixed now, thank you! :-)
