### ISSUE TITLE
ICE when building phobos on mingw-w64(win64)

### ISSUE THREAD

**Issue by wirx6** [ldc-developers/ldc#2358]
I got following errors when was trying to build ldc f568aaf862b6fd45f06e1be58e6a4716f7e92178 on x86_64-w64-mingw32.
```
std/datetime.d
Attributes 'byval', 'inalloca', 'nest', 'sret', 'nocapture', 'returned', 'swiftself', and 'swifterror' do not apply to return values!
x86_fp80* (%std.datetime.ComparingBenchmarkResult*)* @_D3std8datetime24ComparingBenchmarkResult5pointMxFNaNbNdNfZe
LLVM ERROR: Broken function found, compilation aborted!

std/math.d
Attributes 'byval', 'inalloca', 'nest', 'sret', 'nocapture', 'returned', 'swiftself', and 'swifterror' do not apply to return values!
x86_fp80* (x86_fp80*)* @_D3std4math3cosFNaNbNiNfeZe
LLVM ERROR: Broken function found, compilation aborted

std/complex.d
Attributes 'byval', 'inalloca', 'nest', 'sret', 'nocapture', 'returned', 'swiftself', and 'swifterror' do not apply to return values!
  %7 = call noalias nocapture align 16 x86_fp80* @_D3std4math3cosFNaNbNiNfeZe(x86_fp80* noalias nocapture align 16 %.ExplicitByvalRewrite_putResult), !dbg !47
Attributes 'byval', 'inalloca', 'nest', 'sret', 'nocapture', 'returned', 'swiftself', and 'swifterror' do not apply to return values!
  %9 = call noalias nocapture align 16 x86_fp80* @_D3std4math3sinFNaNbNiNfeZe(x86_fp80* noalias nocapture align 16 %.ExplicitByvalRewrite_putResult2), !dbg !47
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by kinke** [comment]
Thanks for the report. LDC was once compatible with MinGW; I thought most (of the probably few) issues were in druntime/Phobos, but this is an ABI bug - x87 floating-point values not being passed and returned directly in registers, but indirectly in memory. [This line](https://github.com/ldc-developers/ldc/blob/master/gen/abi-win64.cpp#L50) looks very suspicious; on the other hand, at least the return type shouldn't be rewritten according to [this line](https://github.com/ldc-developers/ldc/blob/master/gen/abi-win64.cpp#L68).

**Comment by kinke** [comment]
Please retry with current master. I had to fix a `fild word ptr` to `fild dword ptr` in `std.math.scalbn()` and was then able to compile `std.math` for `-mtriple=x86_64-pc-windows-gnu`. [I also had to disable a static assert triggered by the 64-bit compile-time reals of my MSVC host compiler].
