### ISSUE TITLE
LDC "Getting stated" does not make it very clear for Windows users. 

### ISSUE THREAD

**Issue by WhatMeWorry** [ldc-developers/ldc#2370]
As a Windows user not using MinGW x86, it took me a long time to finally stumble across the page for "Latest LDC binaries for Windows"

To prevent this happening to other newbies, I believe the "Getting started" section of https://wiki.dlang.org/LDC should have a new bullet titled "Using LDC on Windows x86/x64" with a new link to the existing page, https://wiki.dlang.org/Latest_LDC_binaries_for_Windows

Thank you.

Note:  Just noticed the entry:
Building and hacking LDC on Windows using MSVC
but this takes you to
https://wiki.dlang.org/Building_and_hacking_LDC_on_Windows_using_MSVC
which seems like a page devoted to experimentation?

Maybe make two bullets where one says "Using LDC with Windows..." and the other says "Building/Hacking with Windows..."?

**Comment by kinke** [comment]
The intended flow would be clicking on the first bullet point ('Latest binary releases') and then downloading an official Windows package from GitHub. Would a 'download' in there have been clearer to you? The Wiki page you found is for the CI releases, which aren't always production-ready.
Or do you mean it wasn't clear that the archive just needs to be unzipped and the executables can then be found and used in the `bin` subdir? Unlike the CI packages, the release packages come with a README.txt in the archive's root directory with basic instructions and requirements.

**Comment by WhatMeWorry** [comment]
I clicked on the "About" instead of "Download".   That makes a world of difference.   Please close this or do I do that?   LDC looks like a cool project.  Sorry for the bandwidth.
