### ISSUE TITLE
Warning: skipping definition of function __entrypoint._Dmain (1.5.0-beta1)

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#2376]
I create a simple dub application via "dub init sample1" and execute command "dub build --compiler=ldc2"
Warning is shown:

```(5,15): Warning: skipping definition of function __entrypoint._Dmain due to previous definition for the same mangled name: _Dmain```

**Comment by kinke** [comment]
Nothing to worry about (only the warning is new) but should be eradicated at some point.

**Comment by kinke** [comment]
Stupid bug, fixed now.
