### ISSUE TITLE
Enhancement: Add '--resetOnly' to ldc-build-runtime

### ISSUE THREAD

**Issue by jondegenhardt** [ldc-developers/ldc#2384]
It would be convenient to be able to run `ldc-build-runtime` so that it only ran the `--reset` logic, without actually building. I'm finding this would be useful for trying to create makefiles that use `ldc-build-only`. Essentially, a `make clean` operation. I'm finding I want to reset once for series of builds, but not on every build.

**Comment by kinke** [comment]
If you want to implement it yourself, here's the file: https://github.com/ldc-developers/ldc/blob/master/runtime/ldc-build-runtime.d.in

**Comment by jondegenhardt** [comment]
Thanks. The code looks straightforward. I'll need know how/where ".in" file is getting processed. I'm sure I'll be able to figure it out by looking around the code, if there something you can point me to that'd be useful. Also, if there is automated testing  that should be updated.

**Comment by kinke** [comment]
The ".in" file is processed by CMake, replacing the `@VARIABLE@` occurrences. Those are used in string literals, so the file should compile as-is after renaming to .d, and those vars aren't required for your purpose here (used to figure out the source download URL after resetting the dir). The executable is built on CI, that's the only test. ;)
