### ISSUE TITLE
ICE on compiling Objective-C code in multiple files

### ISSUE THREAD

**Issue by jacob-carlborg** [ldc-developers/ldc#2388]
The following code fails to compile:

```
$ touch foo.d
$ cat main.d
```

```d
void alloc()
{
    NSObject o;
    o.alloc();
}

extern (Objective-C):

interface NSObject
{
    NSObject alloc() @selector("alloc");
}
```

Compiling the above code gives the following error:

```
$ ldc2 --version
LDC - the LLVM D compiler (1.5.0-beta1):
  based on DMD v2.075.1 and LLVM 5.0.0
  built with LDC - the LLVM D compiler (1.5.0-beta1)
  Default target: x86_64-apple-darwin16.7.0
  Host CPU: haswell

$ ldc2 foo.d main.d
module flag identifiers must be unique (or of 'require' type)
!"Objective-C Version"
module flag identifiers must be unique (or of 'require' type)
!"Objective-C Image Info Version"
module flag identifiers must be unique (or of 'require' type)
!"Objective-C Image Info Section"
module flag identifiers must be unique (or of 'require' type)
!"Objective-C Garbage Collection"
LLVM ERROR: Broken module found, compilation aborted!
```

There has to be at least two files for this error to occur. It might be related to this issue in DMD [1].

[1] https://issues.dlang.org/show_bug.cgi?id=17936

**Comment by kinke** [comment]
Thanks for testing. The are multiple LDC-specific issues here; in short, the current buggy Objective-C support only works when compiling a single D module per LDC invokation.

**Comment by kinke** [comment]
@jacob-carlborg: It would be perfect if you could do some more Objective-C testing with #2389.

**Comment by jacob-carlborg** [comment]
I tried to compile LDC but I get an error when I run `cmake`:

```
llvm-config: unknown component name: ipa
CMake Error at cmake/Modules/FindLLVM.cmake:140 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  cmake/Modules/FindLLVM.cmake:174 (llvm_set_libs)
  CMakeLists.txt:19 (find_package)
```

I've tried both LLVM 4.0 and 5.0. Pre-compiled binaries from http://releases.llvm.org/ and compiled myself.

**Comment by kinke** [comment]
I don't have OSX and have never seen that error, so I can't really help. Did you specify the path to your `llvm-config` in the CMake command line (`-DLLVM_CONFIG=/path/to/llvm-config-5.0`)?

**Comment by jacob-carlborg** [comment]
> Did you specify the path to your llvm-config in the CMake command line (-DLLVM_CONFIG=/path/to/llvm-config-5.0)?

Yes, otherwise it would complain that it cannot find `llvm-config`.

But I found an error log file where it complains that it cannot find `libtinfo` and `libterminfo`. I'm not sure if it's LDC or LLVM that require these libraries but running `./llvm-config --system-libs` on macOS gives back `-lcurses -lz -lm` while doing the same on Linux gives back `-lrt -ldl -ltinfo -lpthread -lz -lm`. Is LDC mistakenly requiring these libraries on macOS?

As far as I understand `libtinfo` is part of `ncurses` on Linux, but `ncurses` on macOS does not provide that library.

**Comment by kinke** [comment]
We had a report about that weird ncurses dependency on ARM Linux a while ago (#1827).

> llvm-config: unknown component name: ipa
> CMake Error at cmake/Modules/FindLLVM.cmake:140 (string):

`ipa` is supposed to be filtered out for LLVM >= 3.8. [Line 140](https://github.com/kinke/ldc/blob/objc/cmake/Modules/FindLLVM.cmake#L140) is a comment. So what LDC source are you building?

**Comment by jacob-carlborg** [comment]
I was on a branch that I'm guessing is really old. I thought I was on latest master. CMake worked now without any errors, building LDC now. Sorry, my bad.

**Comment by kinke** [comment]
Alright, just be sure to build my `objc` branch. ;)

**Comment by jacob-carlborg** [comment]
Absolutely, just verifying everything is building on master first.
