### ISSUE TITLE
LDC 1.5.0 crash

### ISSUE THREAD

**Issue by Temtaime** [ldc-developers/ldc#2411]
```
struct {
    enum STCundefined           = 0L;
}
```

ldc2 test.d
crashes on windows with:

Error: anonymous struct can only be a part of an aggregate, not module astbase
Wrote crash dump file ...

**Comment by kinke** [comment]
DMD 2.076.1 crashes too; DMD 2.077 doesn't, and LDC's `merge-2.077` neither. Closing as apparently fixed front-end issue.
