### ISSUE TITLE
LDC 1.5.0 wrong calling convention

### ISSUE THREAD

**Issue by Temtaime** [ldc-developers/ldc#2414]
[test.zip](https://github.com/ldc-developers/ldc/files/1484531/test.zip)

```
cl ctest.cpp -c
ldc2 test.d ctest.obj
test.exe
```
Outputs
2 4238349
and crashes

should
1 2

This is a blocker bug because dmd is not going to work on windows being built by ldc

**Comment by rainers** [comment]
>test.zip

Easier to just paste the source code here.

> D:
```
struct S { real r; }
```

> C++
```
struct S
{
    unsigned long long mantissa;
    unsigned short exponent:15;
    unsigned short sign:1;
};
```

real is not a 80-bit floating point in LDC for windows, but the same as a double.

**Comment by Temtaime** [comment]
So we ending that it is impossible to build dmd with ldc for windows.

**Comment by rainers** [comment]
> So we ending that it is impossible to build dmd with ldc for windows.

Not sure. It won't be 100% compatible with respect to real numbers, though. How is that dealt with on other platforms?

**Comment by Temtaime** [comment]
On other platforms there is real real so it works.
On windows there's too much hardcode in dmd code, so even fixing that bug doesn't change anything as it produces NaNs for reals.

**Comment by kinke** [comment]
> real is not a 80-bit floating point in LDC for windows, but the same as a double

Small correction: LDC uses 64-bit `real` for Windows MSVC targets only; i.e., MinGW uses 80-bit ones.

**Comment by rainers** [comment]
> So we ending that it is impossible to build dmd with ldc for windows.

I couldn't resist trying that: https://github.com/dlang/dmd/pull/7339 works for me and passes all tests.

**Comment by Temtaime** [comment]
Datz interesting.
As it replaces real with custom ops.
I'll give a try, thanks !
