### ISSUE TITLE
ldc2 exits silently when using class from foreign module in associative array literal

### ISSUE THREAD

**Issue by FeepingCreature** [ldc-developers/ldc#2422]
Testcase:

bar.d:

    class Empty { }

foo.d:

    import bar;
    void main() { auto foo = ["": new Empty]; }

Command: `ldc2 foo.d`
Expected result: linker error
Actual result: silent exit with error code 1.

What's happening here is that ldc attempts to *speculatively* generate the associative array literal as a constant expression, but fails because "new Empty" cannot be constant-evaluated because we do not pass bar.d on the commandline. As a result, global.errors is nonzero in `IrTypeClass::get()` (ir/irtypeclass.cpp:102), even though no error has been output. (The silent error can be seen by passing `-verrors-spec`.) I'm not sure why that error check is in there at all.

See also #2423

**Comment by thewilsonator** [comment]
Fixed by #2423
