### ISSUE TITLE
ldc-build-runtime: separating source versions and build directories

### ISSUE THREAD

**Issue by jondegenhardt** [ldc-developers/ldc#2427]
When using `ldc-build-runtime` I'm finding it useful to create separate build directories for different build settings. For example, rather than using the default directory `ldc-build-runtime.tmp`, I use `ldc-build-runtime.thin` and `ldc-build-runtime.full` for ThinLTO and FullLTO.

I'm also finding it would be useful to attach to ldc version numbers to these directories. That's because I'm often testing different LDC versions side-by-side. I can get the version using `ldc2 -version`. However, I'm wondering if there is a better way to do this, one that could be supported directly by `ldc-build-runtime`.

There are a number of ways such support could be organized. One possibility would be to have the default source directory outside the build directory and include the version number. And, there could be way to include the version number in the build directory names. In my builds, I might end up with a directory scheme something like:
```
./ldc-builds
    ldc-src_1.5.0
    ldc-src_1.6.0-beta1
    ldc-build-runtime_1.5.0_lto-thin
    ldc-build-runtime_1.5.0_lto-full
    ldc-build-runtime_1.6.0-beta1_lto-thin
    ldc-build-runtime_1.6.0-beta1_lto-full
```

I've haven't tried to identify a set of options to `ldc-build-runtime` that would support this. I'd be interested in feedback though. There are likely other basic things that should be considered first. For example, it might make more sense to associate the ldc source code directory with the ldc installation directory and have `ldc-build-runtime` know how to find it.

Any thoughts?

**Comment by kinke** [comment]
Heh, you're probably one of the few `ldc-build-runtime` power users. ;) As such I understand your needs, but what you propose here can be implemented in a few lines of bash script, so I'd propose not further complicating the command-line options.
I think the regular use case is a single run, either for a cross-compilation target or for LTO/sanitizer-enabled stdlibs. For these simple cases, a way to copy the generated libs to the LDC installation and optionally patching the `ldc2.conf` config file to make use of them is what I think `ldc-build-runtime` should take care of at some point.

**Comment by jondegenhardt** [comment]
What you suggest is quite reasonable, especially early on. Perhaps when there is more experience with `ldc-build-runtime` it'll make sense to revisit.
