### ISSUE TITLE
Global variable type does not match previous declaration

### ISSUE THREAD

**Issue by Rikarin** [ldc-developers/ldc#2453]
When I tried to compile minimal object.d I got 
`object.d(1569): Error: Function type does not match previously declared function with the same mangled name: _d_dynamic_cast`.

Compilation with DMD works fine.

https://github.com/Rikarin/Trinix/blob/master/Kernel/object.d#L1569

https://travis-ci.org/Rikarin/Trinix/builds/317288016?utm_source=github_status&utm_medium=notification

**Comment by kinke** [comment]
The [correct signature](https://github.com/dlang/druntime/blob/master/src/rt/cast_.d#L62) uses a `void*` return type, not an `Object`.

**Comment by Rikarin** [comment]
But, if the code is compilable by dmd shouldn't it be compilable by ldc too?

**Comment by kinke** [comment]
Just because DMD doesn't verify the signatures (the ones expected by the compiler and the actual definition's in druntime) doesn't mean that LDC should too. ;)
