### ISSUE TITLE
offsetof on raspberry pi

### ISSUE THREAD

**Issue by ariovistus** [ldc-developers/ldc#2456]
at https://github.com/ariovistus/raspi-ldc-issue, 
I have a struct with a number of fields, declared in D and C, which are meant to be equivalent.
Both D and C think the offset of `tp_as_buffer` is 80, and that the size of `tp_flags` is 4, but C thinks the offset of `tp_flags` is 84, and D thinks it is 88. I can see no reason for D to think that, but either way, this completely prevents PyD from working on the raspberry pi.

ldc 1.1.1, raspian 9, gcc 6.3

**Comment by kinke** [comment]
Current LDC is v1.6, so I strongly encourage trying that one.

**Comment by ariovistus** [comment]
original reporter did, and said it was the same

**Comment by kinke** [comment]
I did too and the original reporter was right. Reason is pretty simple, a C long in many cases isn't a D long (always 64 bits).

**Comment by kinke** [comment]
[I.e., use `int` or `core.stdc.config.c_long` for portability.]

**Comment by JohanEngelen** [comment]
@ariovistus See https://dlang.org/blog/2017/12/05/interfacing-d-with-c-getting-started/

**Comment by ariovistus** [comment]
wasn't focused on the size of tp_flags, was assuming offsetof would be the same as offsetof previous + sizeof previous. derp
