### ISSUE TITLE
1.7.0 release

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2469]
Checklist for things to be done before releasing 1.7.0.
Please add stuff that I missed.

- [x] create release-1.7.x branches
- [ ] https://github.com/ldc-developers/ldc/issues/2455 --> let's do the src zip fixup manually?
- [ ] check/improve release notes
- [x] https://github.com/ldc-developers/ldc/pull/2479
- [x] https://github.com/ldc-developers/ldc/pull/2478 or https://github.com/ldc-developers/ldc/pull/2482

**Comment by joakim-noah** [comment]
I removed the Android line taken from the beta release notes, as I don't post a package for that here, but simply submit a pull for [the ldc package in the official Termux repo](https://github.com/termux/termux-packages/tree/master/packages/ldc), once the final release source is up.

**Comment by kinke** [comment]
I think #2454 doesn't only apply to ELF, but to all Posixes, i.e., all platforms for which we support shared runtime libs.

**Comment by JohanEngelen** [comment]
OK, fixed that.

Anything else needed before tagging?

**Comment by kinke** [comment]
#2471 is a bit of a bummer as it appears to be a regression (not sure whether 1.6 was already affected too), but apart from that, we should be set.

**Comment by JohanEngelen** [comment]
I think we are set for the release?

**Comment by kinke** [comment]
Yes -> tagged.

**Comment by kinke** [comment]
The .tar.gz src archive seems fine this time (...).

**Comment by joakim-noah** [comment]
@kinke, no armhf build this time?

**Comment by kinke** [comment]
That's 4 hours worth of building I don't want to invest right now, without upgrading LLVM to 5.0.1, which would take another 24+ hours.

**Comment by joakim-noah** [comment]
Might be worth cross-compiling llvm and ldc, [as I do for Android](https://github.com/termux/termux-packages/blob/master/packages/ldc/build.sh), then just running and checking the stdlib tests in Qemu.

**Comment by kinke** [comment]
[I never even ran any tests for the ARM packages - except for building dub & dlang tools. ;)]

Cross-compiling would be surely a lot nicer than my current manual qemu adventure, letting CircleCI do that for us even better. We'd also need to cross-compile dub & dlang tools in that case and so wouldn't have to use qemu at all.

Or we just wait until an ARM CI box comes around and use that for release building then.
