### ISSUE TITLE
Download Detected as Virus

### ISSUE THREAD

**Issue by SrMordred** [ldc-developers/ldc#2495]
On Windows 10, Chrome browser, detects "ldc2-1.7.0-windows-x64.7z" as a virus.

**Comment by SrMordred** [comment]
I downloaded with curl, and on unzipping, windows give me the alert of virus on "ddemangle.exe" file.

**Comment by kinke** [comment]
Windows isn't an anti-virus program, so which one is it, and as which virus is it detected? Then please open an issue with that anti-virus program.

**Comment by SrMordred** [comment]
I´m using none.
Well, Chrome also is not an antivirus but it have some capabilities to disable potential threats.
In fact I never saw that windows message before.

Messages are in PT-BR it translates more or less as:

Chrome: 
Failure - Virus detected.

Windows popup: 
An unexpected error is keeping you from copying the file. If you continue to receive this error , you can use the error code to search for help with this problem.
Error 0x800700E1: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
![chrome](https://user-images.githubusercontent.com/1225019/34892953-506a7b94-f7c2-11e7-9890-df62e1562a59.png)
![windows](https://user-images.githubusercontent.com/1225019/34892962-5a60babe-f7c2-11e7-8666-fc6ddad82e06.PNG)

**Comment by SrMordred** [comment]
LDC 1.7.0-beta1 downloads and unzip without problems.

**Comment by kinke** [comment]
You're most likely unknowingly using Windows Defender then. It surely has a whitelist for false positives.

**Comment by SrMordred** [comment]
You´re right. 
I thought that I disabled it, but windows keeps re-enabling it!
