### ISSUE TITLE
Add an option to specify compiler-rt library path

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2536]
As noted in https://github.com/ldc-developers/ldc/pull/2345#issuecomment-356728379:
> Another, more flexible option (wrt. all the different distros) would be introducing a new (hidden) command-line option à la -llvm-compiler-rt-libdir, optionally specified in ldc2.conf or, if need be, by the user. Official packages and custom builds would use the copied libs in the main libs directory by default, and distro maintainers not shipping with copies could specify their compiler-rt libs directory in the config file. And the defaultlibs command-line help category would have an additional entry. ;)
It could also be useful for cross-linking scenarios, to make LDC pick up the correct libs dir for the target platform.

If the option is specified, it should override (but not replace) the current search logic (e.g. https://github.com/ldc-developers/ldc/blob/94c0d18d499de1b5d7715ca1a25cb17b3a2f6651/driver/linker-gcc.cpp#L248-L252).

**Comment by kinke** [comment]
Implemented as `lib-dirs` array in `ldc2.conf`, e.g.: https://github.com/ldc-developers/ldc/blob/033d513c457d0857d589c9f722005b88caa4fff2/driver/linker-gcc.cpp#L244-L250
