### ISSUE TITLE
PPC64: llvm_bitreverse returns wrong result

### ISSUE THREAD

**Issue by redstar** [ldc-developers/ldc#2557]
This code

    import ldc.intrinsics;
    import core.stdc.stdio : printf;

    int main()
    {
        auto exp =  1UL << 63;
    printf("%llx\n", exp);
        auto arg = 1UL << 0;
    printf("%llx\n", arg);
        auto val = llvm_bitreverse(arg);
    printf("%llx\n", val);
        return exp != val;
    }

generates this output:

    ubuntu@ldc:/tmp/unittest$ ldc2 -run bitop.d
    8000000000000000
    1
    80000000
    Error: /tmp/bitop-2fe7dae-afa21a failed with status: 1

Works on win64.

Compiler:
    ubuntu@ldc:/tmp/unittest$ ldc2 -version
    LDC - the LLVM D compiler (1.8.0git-49bb50c-dirty):
      based on DMD v2.078.1 and LLVM 5.0.1git-6af15925d78
      built with LDC - the LLVM D compiler (0.17.6git-52205e9)
      Default target: powerpc64le-unknown-linux-gnu
      Host CPU: pwr8
      http://dlang.org - http://wiki.dlang.org/LDC

      Registered Targets:
        nvptx   - NVIDIA PTX 32-bit
        nvptx64 - NVIDIA PTX 64-bit
        ppc32   - PowerPC 32
        ppc64   - PowerPC 64
        ppc64le - PowerPC 64 LE

**Comment by redstar** [comment]
Btw, this compiler version does the right thing:

    LDC - the LLVM D compiler (0.17.6git-52205e9):
      based on DMD v2.068.2 and LLVM 4.0.1git
      Default target: powerpc64le-unknown-linux-gnu
      Host CPU: pwr8
      http://dlang.org - http://wiki.dlang.org/LDC

      Registered Targets:
        ppc32   - PowerPC 32
        ppc64   - PowerPC 64
        ppc64le - PowerPC 64 LE

**Comment by redstar** [comment]
See https://bugs.llvm.org/show_bug.cgi?id=36253

This is my reduced test program:

    import ldc.intrinsics;
    import core.stdc.stdio : printf;

    int main()
    {
        auto exp =  1UL << 63;
        printf("%lx\n", exp);
        auto arg = 1UL << 0;
        printf("%lx\n", arg);
        auto val = llvm_bitreverse(arg);
        printf("%lx\n", val);
        return exp != val;
    }

I reduced the LLVM IR to:

    source_filename = "bitop.d"
    target datalayout = "e-m:e-i64:64-n32:64"
    target triple = "powerpc64le-unknown-linux-gnu"

    @.str = private unnamed_addr constant [5 x i8] c"%lx\0A\00"

    declare signext i32 @printf(i8*, ...)

    declare i64 @llvm.bitreverse.i64(i64)

    define signext i32 @main(i32 signext %argc_arg, i8** %argv_arg) {
      %exp = alloca i64, align 8
      %arg = alloca i64, align 8
      %val = alloca i64, align 8
      store i64 -9223372036854775808, i64* %exp
      %1 = load i64, i64* %exp
      %2 = call signext i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i32 0, i32 0), i64 %1)
      store i64 1, i64* %arg
      %3 = load i64, i64* %arg
      %4 = call signext i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i32 0, i32 0), i64 %3)
      %5 = load i64, i64* %arg
      %6 = call i64 @llvm.bitreverse.i64(i64 %5)
      store i64 %6, i64* %val
      %7 = load i64, i64* %val
      %8 = call signext i32 (i8*, ...) @printf(i8* getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i32 0, i32 0), i64 %7)
      %9 = load i64, i64* %exp
      %10 = load i64, i64* %val
      %11 = icmp ne i64 %9, %10
      %12 = zext i1 %11 to i32
      ret i32 %12
    }

This reproduces the failures. If the line

      %6 = call i64 @llvm.bitreverse.i64(i64 %5)

is changed to

      %6 = call i64 @llvm.bitreverse.i64(i64 %3)

or

      %6 = call i64 @llvm.bitreverse.i64(i64 1)

(reusing the previous loaded value or a constant) then everything is fine.

**Comment by kinke** [comment]
Oh wow, so the printf() call somehow manages to screw up the caller stack (`%arg`)?

**Comment by redstar** [comment]
Looks like. Currently I do not see a bug in my source. But how knows.

**Comment by redstar** [comment]
It is indeed an LLVM bug. It's fixed in LLVM 6 with this review: https://reviews.llvm.org/rL316916.

Therefore I close this issue.
