### ISSUE TITLE
[Meta] Release 1.8.0

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2577]
Todo list:
- [x] Make text for D blog (Johan)
- [x] 2.078.3 merge #2576
- [x] Musl patch #2604

**Comment by joakim-noah** [comment]
Would be nice if you could mention Android cross-compilation and the ongoing release of Android packages for the Termux app in the blog post, along with a link to the [wiki page on using it](https://wiki.dlang.org/Build_D_for_Android).  Also, send me the copy for the blog post beforehand and I'll suggest any edits I think would help polish it up, as I usually do with any typos or clarifications for blog posts that I post in the forum.

**Comment by kalev** [comment]
Would be awesome to have a matching ltsmaster release with llvm 6.0 support, so that we can easily bootstrap ldc.

**Comment by kinke** [comment]
v1.8 will not ship with LLVM 6.0 just yet (officially at least), that's stuff for v1.9. I encourage distros to use the same LLVM version as the official packages unless you're okay with abusing your users as beta testers. ;)

**Comment by kalev** [comment]
Fair enough!

**Comment by joakim-noah** [comment]
Ran the dmd testsuite on Alpine with Musl, had to patch LDC to get the betterC tests working with their assert function. Pull incoming later today, only 2-3 tests failing now, would like to get that in before this release.

**Comment by joakim-noah** [comment]
Added the Musl pull, #2604.
