### ISSUE TITLE
Inlining testcase fails with LLVM >= 6.0

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2579]
See https://github.com/ldc-developers/ldc/pull/2180#issuecomment-359175760

Perhaps remove the test case? Or find a better way to test our pass pipeline?

**Comment by kinke** [comment]
It wasn't that much about the pass pipeline, but rather about the default inlining thresholds. We have enough tests making sure that some sort of inlining is performed with  `-O`, and I'd hope the chance that we're ever reverting back to hardcoded inlining thresholds is almost 0, so I'm fine with just getting rid of the test.
