### ISSUE TITLE
a == b should use ptest for integer SIMD vectors

### ISSUE THREAD

**Issue by 9il** [ldc-developers/ldc#2591]
AVX: https://github.com/llvm-mirror/llvm/blob/master/test/CodeGen/X86/avx-brcond.ll
SSE41: https://github.com/Cisco-Talos/freesentry/blob/master/test/Bitcode/ptest-new.ll
`ptest` is faster and smaller then current packed compare

**Comment by kinke** [comment]
DMD doesn't even have semantics for vector comparisons:

```D
bool areEqual(int4 a, int4 b) { return a == b; }
```

dmd-nightly: Error: incompatible types for `(a) == (b)`: both operands are of type `__vector(int[4])`

I just defined a simple to-bool-reduce for the (in)equality operators for the time being for LDC, but IMO returning a vector mask would be much more useful. I think @ibuclaw expressed a similar opinion somewhere.

**Comment by ibuclaw** [comment]
@kinke - When you say returning a vector mask, do you mean this?
```
int4 mask(int4 a, int4 b)
{
    return a == b;
}
```

**Comment by kinke** [comment]
@ibuclaw: Yep.

**Comment by ibuclaw** [comment]
@kinke that idea was rejected at the time we discussed as its a different semantic to other types that instead evaluate a boolean value from comparison expressions.

**Comment by ibuclaw** [comment]
There's no problem making that an intrinsic, however, as other compilers (well I can only speak for gcc) expose this, and a couple others like permutation as vector primitives in codegen.

**Comment by kinke** [comment]
Alright, thanks for the heads-up Iain.

**Comment by 9il** [comment]
btw, ptest should not be used for a == b anyway because it does `a & b == 0`
