### ISSUE TITLE
LLVM 6: Win32 inline assembly regression

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#2629]
[core.cpuid](https://github.com/ldc-developers/druntime/blob/ldc/src/core/cpuid.d#L514-L521) fails to build on Win32 with LLVM 6.0.0 and enabled optimizations, with symptoms of issue #2257.

I tried replacing that DMD-style inline asm with LLVM asm:
```D
            import ldc.llvmasm;
            __asm(`mov %eax, 2
                   cpuid
                   mov $0, %eax
                   mov $1, %ebx
                   mov $2, %ecx
                   mov $3, %edx`, "=*m,=*m,=*m,=*m,~{eax},~{ebx},~{ecx},~{edx}",
                   &a[0], &a[1], &a[2], &a[3]);
```

That makes it work with enabled optimizations, but debug druntime fails to compile with `inline assembly requires more registers than available`. That error vanishes when dropping all clobbers...

What's strange is that it can apparently still be compiled fine for 32-bit Linux and OSX, the CircleCI multilib jobs with preliminary LLVM 6.0 are green.

**Comment by ZILtoid1991** [comment]
I'm getting errors like this one:

```
 <inline asm>:6:2: error: assembler label 'L7CPUblit9composing11blitter8bit_eightpixel' can not be   undefined
         jl L7CPUblit9composing11blitter8bit_eightpixel
```

This is the same on both Win32 and Win64, have not tried to build for Linux or OSX.

The project in question: https://github.com/ZILtoid1991/CPUblit

**Comment by kinke** [comment]
@ZILtoid1991: That's a separate issue as that 5k lines asm monster errors out with the same errors for LDC 1.8 and LLVM 5.0.1. Please try to come up with a nice small testcase and file a new issue.

**Comment by kinke** [comment]
Worked around in #2770.
