### ISSUE TITLE
Cross-compiling from Linux to Windows with mulitarch/crossbuild

### ISSUE THREAD

**Issue by wilzbach** [ldc-developers/ldc#2643]
So I gave this a quick shot with an approach analogous to Jacob's nice [docker-ldc-darwin](https://github.com/jacob-carlborg/docker-ldc-darwin/blob/master/Dockerfile) cross-compilation container.

However, it looks like there's still much to be done. So I post this here, because I believe it's quite nice use-case (e.g. Go is really strong in this) and maybe someone else finds this interesting too.

```docker
FROM multiarch/crossbuild

ENV CROSS_TRIPLE=x86_64-w64-mingw32

ARG LDC_VERSION=1.8.0

RUN wget -q https://github.com/ldc-developers/ldc/releases/download/v${LDC_VERSION}/ldc2-${LDC_VERSION}-linux-x86_64.tar.xz -O /root/ldc-linux.tar.xz
RUN wget -q https://github.com/ldc-developers/ldc/releases/download/v${LDC_VERSION}/ldc2-${LDC_VERSION}-windows-x64.7z -O /root/ldc-windows-x64.7z

RUN \
  mkdir /root/ldc-linux && \
  mkdir /root/ldc-windows

RUN apt-get update && apt-get install -y p7zip-full

RUN cd /root && tar --strip 1 -C /root/ldc-linux -x -f /root/ldc-linux.tar.xz
RUN cd /root && 7z x -o/root/ldc-windows2 /root/ldc-windows-x64.7z
RUN cd /root && mv /root/ldc-windows2/ldc2-${LDC_VERSION}-windows-x64/* /root/ldc-windows

RUN mkdir -p /usr/local/libexec/ldc

RUN cp -R /root/ldc-linux/bin /usr/local/libexec/ldc
RUN ln -s /usr/local/libexec/ldc/bin/* /usr/local/bin
RUN rm /usr/local/bin/ldc2

RUN cp -R /root/ldc-windows/lib /usr/local/libexec/ldc
RUN cp -R /root/ldc-windows/etc /usr/local/libexec/ldc
RUN cp -R /root/ldc-windows/import /usr/local/libexec/ldc

RUN echo '#!/bin/bash\n\nset -eu\n\n/usr/local/libexec/ldc/bin/ldc2 -mtriple ${CROSS_TRIPLE} $@' > /usr/local/bin/ldc2
RUN chmod +x /usr/local/bin/ldc2

RUN rm -rf /root/ldc*
```

There are still lots of errors. Maybe this is due to https://github.com/ldc-developers/ldc/issues/1121?

- [ ] `version(Windows)` in druntime (-> "/usr/local/libexec/ldc/bin/../import/core/stdc/wchar_.d(80): Error: undefined identifier FILE")
- [ ] undefined reference to `_Dmodule_ref'
- [ ] undefined reference to `__CxxFrameHandler3'

**Comment by kinke** [comment]
Cross-compiling to Windows/MSVC targets (yep, MinGW not fully supported) actually works very nicely as long as you have the MSVC libs, see https://github.com/ldc-developers/ldc/pull/2142#issuecomment-304472412. No external toolchain required at all, LDC takes care of linking via integrated LLD.

**Comment by wilzbach** [comment]
Oh wow that's pretty cool. I didn't know about this! Really awesome work!

For reference for other people finding this, Jacob created a Dockerfile that is based on https://github.com/ldc-developers/ldc/pull/2142#issuecomment-304472412:

https://forum.dlang.org/post/acjcrfvxloapdlapzygn@forum.dlang.org

Maybe LDC could adopt such cross-compilation Dockerfiles and auto-push them to Dockerhub on a new git tag?
(as mentioned there's a similar one for [Darwin](https://github.com/jacob-carlborg/docker-ldc-darwin/blob/master/Dockerfile)).
If that's something interesting to you, I'm happy to figure out the "CI legwork" to do so. I'm just not sure whether the MSVC libs can be officially bundled in a Docker image that's pushed to Dockerhub.

As an alternative, I guess you could make them semi-official by having a `docker` repo in the `ldc-developers` organization that collects such Dockerfiles.

(for those who didn't know) there's also another "just LDC" docker image too (-> https://github.com/lindt/docker-ldc)

**Comment by JohanEngelen** [comment]
> As an alternative, I guess you could make them semi-official by having a docker repo in the ldc-developers organization that collects such Dockerfiles.

I've recently started using docker more, and indeed this is what I was thinking about as well.
The docker image of https://github.com/lindt/docker-ldc doesn't work with Gitlab CI (yet, https://github.com/lindt/docker-ldc/pull/9)
You're help is always welcome ofcourse.

**Comment by wilzbach** [comment]
> The docker image of https://github.com/lindt/docker-ldc doesn't work with Gitlab CI 

Yep, it doesn't work in CircleCi either. That's why I maintain [my own Docker images](https://github.com/wilzbach/dlang-docker) so far.
Though atm that one is primarily used [for dmd's CircleCi](https://github.com/dlang/dmd/blob/master/.circleci/config.yml#L24) only.

> You're help is always welcome ofcourse.

So I was thinking about unifying the Docker images @lindt and I maintain into one "go stop" solution soon (maybe at the DConf hackathon). Perhaps the result of this could be moved to your org then?

**Comment by JohanEngelen** [comment]
> could be moved to your org then

You have my vote for sure. (we already have the snap packages in ldc-developers)

**Comment by trikko** [comment]
Any news? Now LDC 1.13 beta is self sufficient. Did anyone make a try?

**Comment by kinke** [comment]
I've hacked up a little Dockerfile for a regular Linux x86_64 package incl. the 32/64-bit Windows libs and an extended config file. It would still need some love (I'm no `sed` expert) and primarily some automation (deploy automatically, e.g., upon pushing to https://github.com/ldc-developers/ldc-developers.github.io).

Here's the mainly untested hack:
```Dockerfile
FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get install -yq curl p7zip sed xz-utils && \
  rm -rf /var/lib/apt/lists/*

RUN curl -SL -o ldc2.tar.xz https://github.com/ldc-developers/ldc/releases/download/v1.12.0/ldc2-1.12.0-linux-x86_64.tar.xz && \
  tar xf ldc2.tar.xz && \
  rm ldc2.tar.xz && \
  mv ldc2-1.12.0-linux-x86_64 ldc2 && \
  echo 'export PATH=/ldc2/bin:$PATH' >> ~/.bashrc && \
  curl -SL -o ldc2.7z https://github.com/ldc-developers/ldc/releases/download/v1.12.0/ldc2-1.12.0-windows-multilib.7z && \
  p7zip -d ldc2.7z && \
  cd ldc2-1.12.0-windows-multilib && \
  cp -r lib32 ../ldc2/lib-win32 && \
  cp -r lib64 ../ldc2/lib-win64 && \
  cat etc/ldc2.conf | sed -n '/^default:$/,/^};$/p' | sed -e 's|../lib64|../lib-win64|g' | sed -e 's|^default:$|x86_64-pc-windows-msvc:|g' >> ../ldc2/etc/ldc2.conf && \
  cat etc/ldc2.conf | sed -n '/^i686-pc-windows-msvc:$/,/^};$/p' | sed -e 's|../lib32|../lib-win32|g' >> ../ldc2/etc/ldc2.conf && \
  cd .. && \
  rm -rf ldc2-1.12.0-windows-multilib && \
  cat ldc2/etc/ldc2.conf

CMD [ "/bin/bash" ]
```

**Comment by kinke** [comment]
As I said, mainly untested - with the hopes that someone else steps up, as my personal interest in an LDC docker image is 0. Looks like the Ubuntu base image comes with no gcc, so you'll need to install it, or choose another base image (the single biggest issue I have with docker - which base image is the most suitable for all potential users? - that's why I personally prefer downloading the prebuilt archive and extracting it, that can be a single cmdline too).

**Comment by trikko** [comment]
Probably my fault. It was looking for gcc, but compiled object was in elf format. 
So using ldc and adding arch i686-pc-windows-multilib seems to compile fine (it creates a obj), but it looks for link.exe that obviusly is not there.

Wait a second, does prebuilt archive allow cross compilation from linux with target windows?

**Comment by kinke** [comment]
> It was looking for gcc, but compiled object was in elf format

Yeah but the image should still be usable for native Linux compilation/linking too.

> does prebuilt archive allow cross compilation from linux with target windows

Nope, and that's the only reason I played with a Dockerfile. Adding Windows cross-compilability is pretty simple in theory, just copy & rename the lib dirs and extend the config file by the 2 slightly modified sections, that's what the Dockerfile does. Versions prior to v1.13 additionally need `-link-internally` (that's apparently what you are missing) - when I created this prototype, there wasn't any v1.13 beta to be downloaded yet.

IIRC, the merged .conf file was still the original one, i.e., the last `cat` command didn't show the 2 additional Windows sections, so there must be something wrong with appending (`>>`).

In theory, one could additionally install gcc for aarch64 and armhf and merge in those prebuilt LDC packages too (libs + extend config file), possibly even the Android stuff, for a super-dupy heavy cross-compilation LDC image. For OSX, I guess the Apple C libs cannot be distributed.

**Comment by trikko** [comment]
Shame on me. I didn't know it was just ready for cross-compilation. I think we need to recompile it (like gcc...). That's great. I just did a test and I can compile easily :) I wonder how many people know that cross compilation works out of the box!

**Comment by kinke** [comment]
Yeah cross-*compiling* works for every target the used LLVM supports. The problem is cross-*linking*, that's where the libs and config file fiddling comes in.
