### ISSUE TITLE
Allow the user to overwrite a global `-link-defaultlib-shared` flag

### ISSUE THREAD

**Issue by wilzbach** [ldc-developers/ldc#2646]
Now that OS packers are starting to add the new `-link-defaultlib-shared` (see https://github.com/ldc-developers/ldc/pull/2443) to their global `ldc.conf` file, this option breaks release build scripts somehow.
What do you think about:

1) Adding a CLI flag to negate this, e.g. `-disable-link-defaultlib-shared`? (the last seen option would take precedence)
2) Let `-static` overwrite the global `-link-defaultlib-shared` preference? At the moment one just gets an error:

> Error: Can't use -link-defaultlib-shared and -static together

**Comment by wilzbach** [comment]
> -link-defaultlib-shared=false is working as expected, last seen option takes precedence as usual.

Great! Just missing documentation then?

```
> ldc -help
...
Linking options:

  -L=<linkerflag>                         - Pass <linkerflag> to the linker
  -Xcc=<ccflag>                           - Pass <ccflag> to GCC/Clang for linking
  -defaultlib=<lib1,lib2,...>             - Default libraries to link with (overrides previous)
  -disable-linker-strip-dead              - Do not try to remove unused symbols during linking
  -link-defaultlib-debug                  - Link with debug versions of default libraries
  -link-defaultlib-shared                 - Link with shared versions of default libraries
  -linker=<lld-link|lld|gold|bfd|...>     - Linker to use
  -mscrtlib=<libcmt[d]|msvcrt[d]>         - MS C runtime library to link with
  -static                                 - Create a statically linked binary, including all system dependencies
```

Maybe the boolean flags could be marked with e.g. `-link-defaultlib-shared=<true,false>` somehow?
Not sure what the standard on this is - DMD would do this
```
-link-defaultlib-shared
-link-defaultlib-shared=<on,off>
```

(e.g.`-color` -> https://dlang.org/dmd#switch-color)

BTW is there any reason why `ldc` without args and `ldc -help` print different pages?

**Comment by kinke** [comment]
> Maybe the boolean flags could be marked with e.g. -link-defaultlib-shared=<true,false> somehow?

It's just a default LLVM Boolean commandline option with default help formatting, which doesn't mark the Boolean options in a special way. `-static` is a bool too, as most other options are, so `-static[=<true|TRUE|True|1|false|FALSE|False|0>]` are all valid cmdline args.

> BTW is there any reason why ldc without args and ldc -help print different pages?

I must confess I probably never invoked ldc2 without args and so will have to check its output. ;)

**Comment by kinke** [comment]
`-static` now overriding `-link-defaultlib-shared` & `ldc2` without args printing categorized help (but still lacks the help footer, for which I didn't quickly find a solution).

**Comment by kinke** [comment]
The latter, assuming you don't want to enforce static C libs too.

**Comment by p0nce** [comment]
I hadn't thought about that. Indeed what we probably need is dynamic C libs, static D runtime.
