### ISSUE TITLE
Naked functions not being exported on Windows

### ISSUE THREAD

**Issue by TyroneLaney** [ldc-developers/ldc#2648]
Creating DLLs on Windows with functions that use the naked attribute results in export being ignored.
Example code:
```D
import core.runtime;
import core.sys.windows.windows;
import core.sys.windows.dll;

extern(C) export void TestFunc(){
	asm{
		naked;
		mov EAX, 42;
	}
}

extern (Windows)
BOOL DllMain( HINSTANCE hInstance, ULONG ulReason, LPVOID pvReserved) {
	switch (ulReason) {
		default: break;
	
		case DLL_PROCESS_ATTACH:
			dll_process_attach( hInstance, true );
			TestFunc();
		break;

		case DLL_PROCESS_DETACH: 
			dll_process_detach( hInstance, true );
			break;
	}
	return true;
}
```

**Comment by kinke** [comment]
For exported non-naked functions, LLVM generates a single combined linker cmdline string directive like this:
```
	.section	.drectve,"yn"

	.ascii	" /EXPORT:func1 /EXPORT:func2 /EXPORT:func3"
```

For naked functions, we emit the textual assembly for the whole function manually, and LLVM has no idea about any functions that piece of inline assembly contains, so its name doesn't make it into the linker cmdline string.

So you're probably best off exporting naked functions manually via `-L/EXPORT:TestFunc`.

**Comment by JohanEngelen** [comment]
We could add the `/EXPORT:<symbol name>` to `llvm.linker.options`.

**Comment by TyroneLaney** [comment]
Using /EXPORT works well and will be good enough for programs similar to the example I gave.

Unfortunately this approach isn't applicable(or at least not very easy to use) to some types of programs(luckily probably a very small subset.) I stumbled upon this issue while porting some projects from DMD to LDC2; One of the libraries in use makes heavy use of D's version attribute and static foreach to build these kind of naked functions at compile time in a fashion similar to:
```
static foreach(f; ListOfFunctionsDecidedAtCompileTime){
  //...
  mixin("extern(C) export void "~f~"(){asm{naked; //Some more asm stuff here}}");
  //..
}
```

**Comment by TyroneLaney** [comment]
Tested kinke's modifications and they work great on x86 and x64. You guys are awesome.
