### ISSUE TITLE
LDC 0.17.x with support for llvm 6.0.0

### ISSUE THREAD

**Issue by Alzimzim** [ldc-developers/ldc#2663]
Hello. When is LDC 0.17.x with support for llvm 6.0.0?

**Comment by kinke** [comment]
Branch `ltsmaster` (i.e., 0.17.x) supports it, but there's no tagged version available so far.

**Comment by Alzimzim** [comment]
Thanks!

**Comment by WebDrake** [comment]
@redstar is this what is blocking the 0.17.6 release?  I ask because this would be required for the bootstrap compiler of the LDC snap package.

**Comment by felixbuenemann** [comment]
The lack of an LLVM 6.0 compatible ldc-lts release is also currently causing the macOS homebrew packages to be build with llvm@5 (5.0.2) instead of llvm (6.0.1). Since the package cannot depend on llvm@5 and llvm at the same time, it can't build ldc-lts using llvm 5 and ldc using llvm 6.

**Comment by JohanEngelen** [comment]
https://forum.dlang.org/thread/zyslwqsnluftpzbdfdou@forum.dlang.org

**Comment by kinke** [comment]
v0.17.6 released, which is also ready for LLVM 7 and bootstrapping 2.082. Pinging @ximion, @kalev and @Vild.
