### ISSUE TITLE
Add support for Objective-C class/static methods (2.080 feature)

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#2670]
I.e., port https://github.com/dlang/dmd/pull/7762 and re-enable dmd-testsuite's `runnable/objc_call_static.d`.

**Comment by kinke** [comment]
This might be an excuse for getting your hands dirty at the LDC codebase. ;) Be warned - it's highly addictive. - My interest in Objective-C and Apple in general is 0, so don't count on me.

**Comment by kinke** [comment]
No idea how much more work that would be, as it currently seems to only trivially affect some section names in [gen/objcgen.cpp](https://github.com/ldc-developers/ldc/blob/master/gen/objcgen.cpp); but modern/non-fragile ABI support only is clearly better than none, so it's definitely no requirement to get a PR merged.

**Comment by jacob-carlborg** [comment]
Currently it's only segments/sections that are different. IIRC supporting class methods will require more differences for the different ABIs.

> but modern/non-fragile ABI support only is clearly better than none, so it's definitely no requirement to get a PR merged.

That's good to hear :+1:.

**Comment by s-ludwig** [comment]
https://www.bountysource.com/issues/57688078-add-support-for-objective-c-class-static-methods-2-080-feature

**Comment by MrcSnm** [comment]
Hello, I'm willing to cooperate at this stuff at some point in near future since I'm nearing the end of my engine port for MacOS, I also wish to make it run on iPhone (the main reason of the port), but LDC hasn't implemented that yet.

Would you give me some advice into how I could get started implementing that?

**Comment by kinke** [comment]
I'd suggest starting with an as-simple-as-possible example for clang and studying the produced textual IR (e.g., on godbolt or via `-emit-llvm` IIRC), to get an idea of what's needed. And then trying to replicate the relevant stuff in LDC codegen, probably somewhere in `gen/functions.cpp` (`Dto{Declare,Define}Function()`).

So you need this particular feature for iOS, but not for macOS?

**Comment by jacob-carlborg** [comment]
There's already a basic implementation available. LDC can do Objective-C method calls [1]. If you search for `objc_msgSend` you'll see there's an implementation for each of the architectures supported by Apple. I did the implementation in DMD so I can help out bit if there's any questions. But I don't think I have time to do implementation myself.

[1] https://github.com/ldc-developers/ldc/blob/906037988f064bc61dbd671abc820f87bc10d128/gen/abi/x86-64.cpp#L382

**Comment by MrcSnm** [comment]
@jacob-carlborg Thanks a lot! Okay I'll surely ask you :)

@thewilsonator Yup I can participate on it :D
Getting onto compiling things and starting to being able to test is the main concern I have, with help from both you I'm pretty sure I can implement that

**Comment by jacob-carlborg** [comment]
@MrcSnm as for getting started with the Objective-C parts, I suggest the following:

1. Start by having a look at the ABI specification [1]. Some parts of the text are more of a general information of how things work and some parts are more like detailed reference. The specification is x86-64 specific, but both x86-64 and ARM64 uses the modern ABI so I would expect most of it to be the same. What will be different is which and when the `objc_msgSend` functions are used. What could also be different are sizes and alignments. Keep in mind that the specification is reverse engineered so it might not be 100% correct.
2. Then look at what's already implemented in LDC and verify that's correct. For example, I doubt that [2] is implemented correctly.
3. Then continue and implemented the missing functionality, one feature at the time. Check the output with assembly/IR/object dumps and compare with what Clang outputs.

When it comes to tests, most of the existing tests in the DMD test suite are end to end tests. Some are implicit and some are explicit. I would suggest also writing IR tests, if that's something LDC is using (@kinke?).

Also, I wouldn't bother with any 32-bit platforms. They're all obsolete.

[1] https://github.com/dlang/dmd/blob/master/compiler/docs/objective-c_abi.md
[2] https://github.com/ldc-developers/ldc/blob/906037988f064bc61dbd671abc820f87bc10d128/gen/abi/aarch64.cpp#L177

**Comment by JohanEngelen** [comment]
> When it comes to tests, most of the existing tests in the DMD test suite are end to end tests. Some are implicit and some are explicit. I would suggest also writing IR tests, if that's something LDC is using (@kinke?).

Certainly, see e.g. [tests/codegen.](https://github.com/ldc-developers/ldc/tree/master/tests/codegen)

**Comment by kinke** [comment]
Resolved by #4777.
