### ISSUE TITLE
FreeBSD ASAN

### ISSUE THREAD

**Issue by jmdavis** [ldc-developers/ldc#2683]
I tried to use -fsanitize=address on FreeBSD with a locally built version of ldc 1.9.0, and I got this

```
/usr/ports/lang/ldc/work/ldc-1.8.0-src/build/lib/libdruntime-ldc.a(math.o): In function `lgammal':
math.d:(.text.lgammal[lgammal]+0x0): multiple definition of `lgammal'
/usr/ports/lang/ldc/work/ldc-1.8.0-src/build/lib/libldc_rt.asan-x86_64.a(asan_interceptors.cc.o):/wrkdirs/usr/ports/devel/llvm60/work/compiler-rt-6.0.0.src/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4662: first defined here
/usr/lib/crt1.o: In function `_start':
/usr/src/lib/csu/amd64/crt1.c:(.text+0x17b): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/clang failed with status: 1
```

and Johan wanted me to post the message here, so here it is.

**Comment by JohanEngelen** [comment]
@jmdavis Can you check whether FreeBSD defines `lgammal` in its C runtime? ASan tries to intercept it and defines it in the process.
If `lgammal` is present: we can change our definition to a declaration in FreeBSD's druntime.
if `lgammal` is not present: we can submit a patch to compiler-rt to not intercept a non-existant C runtime function.

**Comment by jmdavis** [comment]
It's definitely in math.h in FreeBSD 11. Looking at druntime, it looks like the bindings in core.stdc.math for FreeBSD need to be updated in general. They look like they we were written with FreeBSD 8 in mind (which is unfortunately what was running on the autotester until a few months ago) and even talk about versions older than FreeBSD 8. This sort of problem makes me wonder if I should come up with some sort of tool that looks at the .h file in the OS and the .d file in D and prints out possible inconsistencies. It couldn't do a perfect job (especially when we split stdc, posix, and non-posix stuff across different .d files), but without some sort of tooling solution, I don't know how we'll ever catch all of these little inconsistencies. :|

If I fix it so that `lgammal` is an `extern(C)` declaration rather than an `extern(D)` definition in core.stdc.math in my local ldc build, then the linker problem goes away. So, it looks like this is definitely a druntime bug.

**Comment by JohanEngelen** [comment]
News on sanitizer BSD support: https://blog.netbsd.org/tnf/entry/the_process_of_upstreaming_support

**Comment by JohanEngelen** [comment]
@jmdavis Can you check if ASan works for you now?

**Comment by myfreeweb** [comment]
ASan works fine for me on FreeBSD -CURRENT with ldc 1.19

**Comment by JohanEngelen** [comment]
thanks for checking
