### ISSUE TITLE
ARMv7: dynamiccompile failures

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2687]
@Hardcode84 Could you have a look at the ARMv7 buildbot Lit-test failures related to dynamicCompile? Thanks!
http://buildbot.ldc-developers.org/builders/armv7_builder/builds/3169/steps/testlit/logs/stdio
http://buildbot.ldc-developers.org/builders/armv7_builder/builds/3169

**Comment by Hardcode84** [comment]
@JohanEngelen 

I will add more logs to `asm_output` test to see actual output and probably just mark exception test as XFAIL.

Also, what LLVM version is there?

**Comment by JohanEngelen** [comment]
@Hardcode84 You can check the LLVM version in the "5. check" step. It's LLVM 5.0.

**Comment by Hardcode84** [comment]
@JohanEngelen thanks.

Do we have any other ARM systems where these tests are run (and pass)?

I am going to just write `XFAIL: target_ARM`.

**Comment by JohanEngelen** [comment]
> Do we have any other ARM systems where these tests are run (and pass)?

Not that I know of. :/

**Comment by Hardcode84** [comment]
lit is green now

http://buildbot.ldc-developers.org/builders/armv7_builder/builds/3189

**Comment by JohanEngelen** [comment]
fixed by #2723
