### ISSUE TITLE
[ldc2-1.10.0-beta1] ARM Cross compile errors

### ISSUE THREAD

**Issue by rracariu** [ldc-developers/ldc#2707]
Got this error when cross-compiling phobos for Linux ARMHF

```
std/math.d(5917): Error: pure function std.math.FloatingPointControl.hasExceptionTraps cannot call impure function std.math.FloatingPointControl.setControlState
std/math.d(5919): Error: pure function std.math.FloatingPointControl.hasExceptionTraps cannot call impure function std.math.FloatingPointControl.setControlState
std/math.d(6048): Error: @safe function std.math.FloatingPointControl.clearExceptions cannot call @system function ldc.llvmasm.__asm!().__asm
```

**Comment by kinke** [comment]
Addressed by https://github.com/ldc-developers/phobos/pull/65, depending on https://github.com/ldc-developers/druntime/pull/142.

**Comment by kinke** [comment]
Oh and there's https://github.com/dlang/phobos/pull/6512 you'll be interested in. LDC 1.10 final will presumably be released shortly after 2.080.1, so it'd be great if you could check out if there's anything left to do for MIPS/uClibc.

**Comment by joakim-noah** [comment]
Should be fixed now, just make sure to check out ldc branch of Phobos.

**Comment by joakim-noah** [comment]
Fixed in master branch.
