### ISSUE TITLE
Add UDA for LLVM's nonlazybind

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2716]
http://llvm.org/docs/LangRef.html#function-attributes

> This attribute suppresses lazy symbol binding for the function. This may make calls to the function faster, at the cost of extra program startup time if the function is not called during program startup.

See also: https://news.ycombinator.com/item?id=17165448

**Comment by JohanEngelen** [comment]
https://reviews.llvm.org/D39065

(`-fno-plt` may be worthwhile too)

**Comment by JohanEngelen** [comment]
@kubo39 Can I interest you in this one? ;)

**Comment by kubo39** [comment]
@JohanEngelen Yes, thank you for letting me know.
