### ISSUE TITLE
LLDB included with LDC releases?

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#2731]
It would be great if the LDC releases includes the LLDB. 
If this isn't possible maybe you could add a hint where e.g. the windows LLDB binary could be downloaded from.

I just installed LLVM and even here the LLDB executable is missing.

**Comment by kinke** [comment]
Did you manage to get ahold of a binary? Does it even work with CodeView (.pdb) as emitted by LDC? If https://lldb.llvm.org/status.html is up-to-date, it's untested on Win64 and only supports DWARF for Win32, which LDC doesn't emit (it might for MinGW, but that's not fully supported anyway).

I'm using Visual Studio (+ VisualD) for debugging on Windows and gdb on Linux.

**Comment by andre2007** [comment]
So far I didn't found any Windows binary. I was under the impression that LLDB is the tool for debugging binaries build using LLVM (LDC). But it seems this information is outdated. I try to find a way to debug D application in IntelliJ. Mago provides a tool MagoMI, which has a GDB compatible interface. But there are some bug here and there causing trouble.I hoped LLDB has also a GDB compatible interface.

**Comment by kinke** [comment]
Closing this as wont-fix. I find bundling a debugger with the compiler highly questionable, and LLDB wouldn't be my first choice anyway (apparently no MSVC support, and the commands are different than gdb's AFAIK). As it's binary code that is debugged, using LLDB probably doesn't provide any advantage over non-LLVM debuggers.
