### ISSUE TITLE
Intrinsics are disappearing

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#2759]
In LDC 1.9, the following intrinsics have disappeared from `gccbuiltins_x86.di`

```
__builtin_ia32_pavgw128;
__builtin_ia32_pavgb128;
```

In LDC 1.4, the following intrinsics have disappeared from `gccbuiltins_x86.di`(amongst hundred of others)
```
__builtin_ia32_cvtsi2ss
__builtin_ia32_cvtsi642ss
```

What is the rationale behind such intrinsics moving in and out?
It makes building upon such intrinsics a brittle work.

**Comment by p0nce** [comment]
Forgot this was a dupe. Still annoying :)

**Comment by kinke** [comment]
> In LDC 1.9, the following intrinsics have disappeared from gccbuiltins_x86.di
> __builtin_ia32_pavgw128;
> __builtin_ia32_pavgb128;

So they have with clang 6.0 apparently: https://godbolt.org/g/CtXiYo
