### ISSUE TITLE
ASM compilation failure trying to assign to field - "end of instruction expected, not this"

### ISSUE THREAD

**Issue by n8sh** [ldc-developers/ldc#2771]
This code fails to compile with LDC v1.10.0. It compiles and prints sane output with DMD v2.060 through v2.080.0.

https://run.dlang.io/is/8HH3tV
```d
void main()
{
    import core.stdc.stdio : printf;
    static struct TS
    {
        ulong state;
        void initialize()
        {
            version(D_InlineAsm_X86_64)
            {
                asm
                {
                    rdtsc;
                    // RAX: low 32 bits are low bits of timestamp, high 32 bits are 0.
                    // RDX: low 32 bits are high bits of timestamp, high 32 bits are 0.
                    shl RDX, 32;
                    xor RDX, RAX;
                    // Copy RDX to `this.state`.
                    mov RAX, this;
                    mov this.state.offsetof[RAX], RDX;
                }
            }
            else
            {
                static assert(0, "D_InlineAsm_X86_64 not supported");
            }
        }
    }
    TS s;
    s.initialize();
    printf("%ld\n", s.state);
}
```

**Comment by n8sh** [comment]
This seems to be a duplicate of https://github.com/ldc-developers/ldc/issues/950. Closing.

**Comment by kinke** [comment]
You may want to have a look at [ldc.intrinsics.llvm_readcyclecounter()](https://github.com/ldc-developers/druntime/blob/ldc/src/ldc/intrinsics.di#L137), which yields identical assembly for x86_64: https://run.dlang.io/is/V2jYQA

**Comment by kinke** [comment]
Apparently not, see https://llvm.org/docs/LangRef.html#llvm-readcyclecounter-intrinsic for the full reference.

Hitting 0 by accident should be extremely unlikely though. Hitting it twice consecutively should be a pretty robust way of detecting missing support. ARM and AArch64 apparently don't support it.
