### ISSUE TITLE
ldc 1.10.0 doesn't link the LLVM fuzzer library on Arch Linux

### ISSUE THREAD

**Issue by atilaneves** [ldc-developers/ldc#2789]
I tried following the [fuzzer example from the blog](http://johanengelen.github.io/ldc/2018/01/14/Fuzzing-with-LDC.html). It didn't work. I eventually used clang to link my object files instead, which worked as soon as I discovered that for ldc phobos and druntime are separate libraries.

Back to ldc, I realised that it wasn't passing the right linker flags for `fsanitize=fuzzer`,  so I tried adding `-L=-fsanitize=fuzzer`. That gave me a cryptic error message so I investigated with `ldc2 -v`, which made me realise what the problem is: ldc2 is calling gcc (instead of clang) as the linker, and gcc doesn't support `-fsanitize=fuzzer`.

So right now I either have to use clang to link (try doing that with dub) or pass in `/usr/lib/clang/6.0.1/lib/linux/libclang_rt.fuzzer-x86_64.a -L-lstdc++` as arguments to ldc2 when called as a linker, which depends on the version of clang installed on the system.

An easy solution would be to call clang instead.

**Comment by thewilsonator** [comment]
use the hidden option `-gcc=` e.g. `-gcc=/usr/bin/clang`
https://github.com/ldc-developers/ldc/blob/0e422af0c01c1eea184da7a4bf162625fa166241/driver/tool.cpp#L33

**Comment by atilaneves** [comment]
@thewilsonator That doesn't work either. It does use clang to link, but puts the `-fsanitize=address` after `-Xlinker` and ends up having the same error message as when it calls gcc: `/usr/bin/ld: fatal error: -f/--auxiliary may not be used without -shared`. Using `-shared` is even worse: it seems to work but doesn't, and the final binary doesn't have a `main` symbol.

Changing `-Xlinker -fsanitize=fuzzer` in the linker invocation to just `-fsanitize=address` fixes things.

**Comment by thewilsonator** [comment]
>Changing `-Xlinker -fsanitize=fuzzer` in the linker invocation to just `-fsanitize=address` fixes things.
was that with `-L=-fsanitize=fuzzer` or just `-fsanitize=fuzzer`?

Also ldc should copy and rename `libclang_rt.fuzzer-x86_64.a` to `libldc_rt.fuzzer-x86_64.a` in `/path/to/ldc/lib` if it was build against an LLVM with libFuzzer.

**Comment by atilaneves** [comment]
> was that with -L=-fsanitize=fuzzer or just -fsanitize=fuzzer?

It was with `-L-=-fsanitize=fuzzer`. Calling ldc2 as a linker and using `-fsanitize=fuzzer` does absolutely nothing to the gcc invocation.

**Comment by kinke** [comment]
`-L` is used for linker (`ld` etc.) args. If you want to pass `-fsanitize` to clang (linker **driver**), use `-Xcc=-fsanitize=fuzzer`.

What's the error when using LDC's `-fsanitize`? Are you using a self-built LDC or an official prebuilt package?

**Comment by atilaneves** [comment]
I'm using ldc from pacman. 

The errors when passing `-fsanitize=fuzzer` to ldc are undefined reference linker errors since it never links to `libclang_rt.fuzzer-x86_64.a`. Even when ldc is used to link, it doesn't pass `-fsanitize` to gcc/clang, as mentioned above. 

I can confirm that a workaround right now is to use _both_ `-Xcc=fsanitize=fuzzer` _and_ `--gcc=clang`.

To make things clear, I want to reiterate that `ldc2 -fsanitize=fuzzer foo.o` is equivalent to `ldc2 foo.o` . There are *no* differences whatsoever.

**Comment by kinke** [comment]
Try an official prebuilt release package pls.

**Comment by atilaneves** [comment]
@kinke I downloaded the binary 1.10 release and that ldc2 works.

I then passed `-vv` to the pacman version and it was looking for the library in `/usr/lib/clang/6.0.0/lib/linux/libclang_rt.fuzzer-x86_64.a`. In my case it was in `/usr/lib/clang/6.0.1/lib/linux/libclang_rt.fuzzer-x86_64.a` (6.0.0 -> 6.0.1).

I tried `-vv` again with the downloaded ldc and it was using its own libclang_rt.fuzzer-x86_64 in `ldc2-1.10.0-linux-x86_64/lib/libldc_rt.fuzzer-x86_64.a`. If I delete that file the downloaded ldc exhibits the same problem.

**Comment by atilaneves** [comment]
I just updated the system and the new ldc from pacman works as intended. I guess this can be closed.
