### ISSUE TITLE
WebAssembly build error

### ISSUE THREAD

**Issue by patrickkh7788** [ldc-developers/ldc#2792]
The source code is betterC and work fine for x86.
when try to build into wasm:

ldc2 -mtriple=wasm32-unknown-unknown-wasm -dip1008  -betterC src/*.d -link-internally

```
LLVM ERROR: Cannot select: 0x7f8b538651a8: i32,ch = load<LD1[%239], anyext from i8> 0x7f8b52d44590, 0x7f8b538650d8, undef:i64
  0x7f8b538650d8: i64 = add nuw 0x7f8b53864f38, Constant:i64<8>
    0x7f8b53864f38: i64,ch = load<LD8[%2](dereferenceable)> 0x7f8b52d44590, FrameIndex:i64<0>, undef:i64
      0x7f8b53864e00: i64 = FrameIndex<0>
      0x7f8b53864ed0: i64 = undef
    0x7f8b53865070: i64 = Constant<8>
  0x7f8b53864ed0: i64 = undef
In function: calconv
```

I also try wasm32-unknown-unknown-wasm, give this error:
```
./import/core/stdc/time.d(146): Error: undefined identifier time_t, did you mean function time?
./import/core/stdc/time.d(146): Error: undefined identifier time_t, did you mean function time?
./import/core/stdc/time.d(148): Error: undefined identifier time_t, did you mean function time?
....
```
the source code not use core.stdc.time, but it still give this error for wasm32.

how can i fix this ?

**Comment by patrickkh7788** [comment]
after I put the extern(C) void _start(){} to wasm32, it give this error:

```
lld: error: app.o: undefined symbol: __assert
Error: linking with LLD failed
```

I search the code and there is no assert used, I try work around by add `extern(C) __gshared void*  _assert`, but still give the same error.

same code build with wasm64

```
LLVM ERROR: Cannot select: 0x7fa7c70629a8: i32,ch = load<LD1[%239], anyext from i8> 0x7fa7c5732d90, 0x7fa7c70628d8, undef:i64
  0x7fa7c70628d8: i64 = add nuw 0x7fa7c7062738, Constant:i64<8>
    0x7fa7c7062738: i64,ch = load<LD8[%2](dereferenceable)> 0x7fa7c5732d90, FrameIndex:i64<0>, undef:i64
      0x7fa7c7062600: i64 = FrameIndex<0>
      0x7fa7c70626d0: i64 = undef
    0x7fa7c7062870: i64 = Constant<8>
  0x7fa7c70626d0: i64 = undef
In function: calconv
```

**Comment by patrickkh7788** [comment]
simple error example:

```d
enum T : ubyte  {
        A
}
T[1] S = [ T.A];

extern(C) void _start() {}
```
 ldc2 -mtriple=wasm32-unknown-unknown-wasm -dip1008 ./wasm.d -link-internally --betterC

```
lld: error: symbol not found in any segment: _D4wasm1SG1EQk1T
Error: linking with LLD failed
```

**Comment by kinke** [comment]
LLVM's wasm64 support is highly experimental apparently, I don't encourage using it yet.

Asserts are also inserted by the compiler; either try adding `-release` or provide a correct stub, e.g., https://github.com/ldc-developers/ldc/blob/master/tests/baremetal/wasm2.d#L10.

**Comment by kinke** [comment]
So can we close this? Wrt. wasm64, a quote from the [emscripten forum](https://groups.google.com/forum/#!topic/emscripten-discuss/nWmO3gi8_Jg) from March 2018:

> Also, wasm64 is not standardized yet, and support for wasm64 in the LLVM wasm backend and other tools is not yet complete.

**Comment by patrickkh7788** [comment]
thanks, we can close.
