### ISSUE TITLE
Noreturn functions?

### ISSUE THREAD

**Issue by araspik** [ldc-developers/ldc#2794]
I'm looking for a way to mark a function as `noreturn`.
Compiler: LDC 1.10.0 Gentoo (system ebuild) x86_64
Attempts:
1. Mark with `llvmAttr("noreturn")`: Failed, silently does not work.
```d
module test;
import ldc.attributes;
@llvmAttr("noreturn") void foo() {}
```
Generates single `ret` instruction.

2. Add `assert(0)` at end: Failed, produces `_d_assert` calls
```d
void foo() {assert(0);}
```

Any other method? If there is a pragma, where can I find a list of supported pragmas? If it's some other solution, why not one of these?

**Comment by kinke** [comment]
Adding the LLVM function attribute works with master (https://github.com/ldc-developers/ldc/commit/f2c718d7a41b9ce49c9f8361f80b88b79d7f576a), but LDC nevertheless appends the missing `ret void` (IR) as part of its 'epilogue'. What's your goal?

**Comment by araspik** [comment]
To not have that instruction. At this point, I'm curious. Why would it still produce that? The point of `noreturn` is to make sure that _doesn't_ happen.

**Comment by kinke** [comment]
If it doesn't return, it won't reach the instruction, right?

> Why would it still produce that?

Because a terminator is required and `@noreturn` would need to be treated specially (unreachable instead of `ret`). And there was no way for users to apply that attribute until 20 days ago, and nobody requested it.

**Comment by araspik** [comment]
All right. Thanks for explaining!

**Comment by kinke** [comment]
[You could resort to a `@naked @noreturn` function if you really need to get rid of the return instruction; an unreachable is appended for `@naked` ones.]
