### ISSUE TITLE
State of debugger support on Windows

### ISSUE THREAD

**Issue by ZILtoid1991** [ldc-developers/ldc#2796]
I've tried Mago-MI and Visual Studio's own debugger on VisualD with some success (Mago won't detect associative arrays, both get confused in case of access violation and have to make the software handle the exception first, etc), I only managed to do a few pretty basic stuff with LLDB.

I would like to help in the debugger support part if possible, since I've moved my main focus over LDC from DMD due to better SIMD support, which helped me to eliminate long assembly codes from my functions.

**Comment by kinke** [comment]
CodeView support (which LLVM has to reverse-engineer AFAIK) is tracked in https://github.com/ldc-developers/ldc/issues/1716 (and hasn't been updated in a while). Help is always welcome!

**Comment by kinke** [comment]
Closing as there's nothing actionable here. [Btw, LLDB doesn't support CodeView at all IIRC.] There are multiple specific (open & closed) debuginfo-related issues on our tracker besides #1716, so there should be enough context (linked PRs) to get started.

I'm also hoping LLVM 7 will enable fixes & simpler code with its new [llvm.dbg.addr](https://llvm.org/docs/SourceLevelDebugging.html#llvm-dbg-addr) intrinsic.
