### ISSUE TITLE
unrecognized pragma(mangle)

### ISSUE THREAD

**Issue by patrickkh7788** [ldc-developers/ldc#2804]
1.11.0-beta2 mac OSX.
```
void main(){
        pragma(mangle, "aaa") __gshared int a = 1;
}
```

./test.d(3): Error: unrecognized pragma(mangle)

```
void main(){
        int i = 9;
        pragma(mangle, "aaa") void add(int j){
                i += j;
        }
        add(3);
}
```

./test.d(3): Error: unrecognized pragma(mangle)
./test.d(6): Error: undefined identifier add

**Comment by thewilsonator** [comment]
Happens on linux too, https://run.dlang.io/is/2Sg4fq

**Comment by thewilsonator** [comment]
Actually this fails for dmd-beta on run.dlang.io as well

**Comment by thewilsonator** [comment]
https://issues.dlang.org/show_bug.cgi?id=19149

**Comment by kinke** [comment]
This has apparently never worked (at least not since v2.060). Thx Nick for filing the upstream issue, where it belongs.
