### ISSUE TITLE
parameter attributes like @noalias

### ISSUE THREAD

**Issue by Trass3r** [ldc-developers/ldc#2828]
It occurred to me that you can't (seem to) express something like C `restrict` or C++ `[[gnu::nonnull]]` in D.
I guess some of LLVM's [parameter attributes](https://llvm.org/docs/LangRef.html#paramattrs) like `@noalias` or `@nonnull` could/should be exposed to the user.

**Comment by kinke** [comment]
Just needs a lil bit of polishing: https://github.com/ldc-developers/ldc/pull/2681

**Comment by kinke** [comment]
Wrt. `@nonnull`, we add the `dereferenceable<type size>` attribute for `ref`/`out` params, which is stronger than nonnull. There's nothing for class objects though, and slices neither.

**Comment by kinke** [comment]
Implemented in #3043.
