### ISSUE TITLE
LDC fails to build when using DMD as the compiler

### ISSUE THREAD

**Issue by Valmar33** [ldc-developers/ldc#2838]
Terminal output:

https://paste.kde.org/pym6bsmxa/hnhwzh

**Comment by kinke** [comment]
We use latest DMD (currently 2.081.2) for building on Linux and OSX, no issues. Your link is worthless - `This paste is password protected`.

**Comment by Valmar33** [comment]
Eh? I'll fix that.

**Comment by Valmar33** [comment]
Should work now! :)

**Comment by kinke** [comment]
The problem isn't DMD, it's LLVM trunk. 7.0 should work (not released yet).

**Comment by Valmar33** [comment]
Is there a way to force it to work with LLVM master? Or is this a LLVM bug?

**Comment by kinke** [comment]
There are simply API diffs, renamed/relocated headers etc. as with each LLVM version. We support LLVM 3.5-7.0; trunk is generally not supported as it changes too frequently.

**Comment by Valmar33** [comment]
Fair enough. Thanks for the info. :)
