### ISSUE TITLE
Add support for MinGW libC under Windows

### ISSUE THREAD

**Issue by BBasile** [ldc-developers/ldc#2856]
Just like DMD64 for windows which can use it when `-m64` is passed and if MS build tools are not installed.

**Comment by BBasile** [comment]
The issue in background is for example if @dlang-community wants to build DCD under wine using TravisCI, looks like the MS deps cant be installed with a set of simple commands.

**Comment by kinke** [comment]
LDC is an implicit cross-compiler, you don't need to run it in an emulator/VM. For Win64 targets, there's a (probably somewhat outdated) Docker image one can use on Linux, incl. an inofficial MSVC libs package, see https://forum.dlang.org/post/acjcrfvxloapdlapzygn@forum.dlang.org. The cross-compiled binaries are linked against the static C libs, meaning that they won't depend on any MS DLLs, unlike a DMD MinGW build afaik.

**Comment by BBasile** [comment]
Thanks, I see you did it finally.

**Comment by kinke** [comment]
Well, it's not exactly the MinGW runtime (as they build on top of the MS runtime and extend/override it in some places), but I guess most people don't really care about such details. ;)
