### ISSUE TITLE
ldc2: Segmentation fault with -O

### ISSUE THREAD

**Issue by patrickkh7788** [ldc-developers/ldc#2885]
ldmd2 is run from termux32 with -O,  remove -O it work fine.

LDC - the LLVM D compiler (1.12.0):
  based on DMD v2.082.1 and LLVM 7.0.0
  built with LDC - the LLVM D compiler (1.12.0)

**Comment by kinke** [comment]
Without any code for reproducibility, such a report is quite obviously useless.

**Comment by joakim-noah** [comment]
Can you run `uname -m` in Termux and report what it says? Also, you can try [reducing the crashing code with the Dustmite tool](https://github.com/CyberShadow/DustMite/wiki).

**Comment by patrickkh7788** [comment]
Linux localhost 3.18.71-14176914 #1 SMP PREEMPT Wed Sep 19 10:57:01 KST 2018 armv8l Android

I will try Dustmite, not sure it can work on android.

**Comment by joakim-noah** [comment]
Hmm, haven't seen that reported before, ie `armv8l`, can you say what the device or CPU is? If it's a device running a 32-bit kernel, you may need to specify the CPU when building D code, ie add the `-mcpu=cortex-a8` flag to your D command-line. You can always choose another 32-bit CPU arch as the baseline instead, but may need to recompile the runtime libraries for it using `ldc-build-runtime`.

**Comment by patrickkh7788** [comment]
@joakim-noah  I forget to let you know, I am rung arm32 on a arm64 phone, because I can not find arm32 and I am not able to setup a cross build for arm32.  

to do this is modify the termux to make sure it always return arm32 type from Java.

**Comment by joakim-noah** [comment]
OK, in that case, does adding the 32-bit CPU flag fix the segfault? It usually does for me on 32-bit ARM.

**Comment by patrickkh7788** [comment]
@joakim-noah
to build with -mcpu=cortex-a8, it work.  Is the binary still can run on all arm32/arm64 android phone ?

**Comment by joakim-noah** [comment]
Yes, it should. If adding that flag fixes this issue for you, you can close it. I will more prominently emphasize it on the wiki.

**Comment by joakim-noah** [comment]
I've updated the wiki to emphasize that you should pass that cpu flag.
