### ISSUE TITLE
LDC for armel 

### ISSUE THREAD

**Issue by giulioz** [ldc-developers/ldc#2887]
Is there any support for armel (arm9) architecture?
I compiled the whole compiler and runtime from source but it yields SIGILL:

`Program received signal SIGILL, Illegal instruction.
0x0047f0d8 in _D4core6atomic__T8atomicOpVAyaa2_2b3dTkTiZQzFNaNbNiNeKOkiZk (val=@0xb6980884: 0,
    mod=1) at /usr/lib/ldc/x86_64-linux-gnu/include/d/core/atomic.d:321`

Can you give me any help?

**Comment by kinke** [comment]
That line is a call to an LLVM intrinsic, so you'll most likely need to play around with the `-mcpu` command-line option.
Judging by your import path, you built the compiler on an x64 machine and are cross-compiling to ARM? Which command-line flags are you using?

**Comment by kinke** [comment]
Ah, ARM9 is of course ARMv5 (sarcasm off); there are some issues with that, most notably the required usage of `-mattr=+strict-align` and patching a few places in druntime, like the enum [here](https://github.com/ldc-developers/druntime/blob/ldc/src/core/atomic.d#L15). See https://github.com/ldc-developers/ldc/issues/2058.

**Comment by kinke** [comment]
Closing, nothing actionable here.
