### ISSUE TITLE
Static arrays should be treated like structs ABI-wise

### ISSUE THREAD

**Issue by dnadlinger** [ldc-developers/ldc#289]
To [quote Walter](http://forum.dlang.org/post/4FD15EAA.1090504@digitalmars.com), `int[3]` should behave as if it was `struct S { int a,b,c; }`.

It would probably be wise to tackle #288 first and implement the fix in `argtypes.c` afterwards. This way, the fix could land in upstream DMD as well (although some backend work would probably be required for DMD as well).

**Comment by kinke** [comment]
I'm sure they are nowadays.
