### ISSUE TITLE
LDC 1.13.0 beta1 - vibed does not work on windows

### ISSUE THREAD

**Issue by Kozzi11** [ldc-developers/ldc#2900]
dub init -t vibe.d testproject
    cd testproject
    dub build

it ends with some missing symbol: fstat

lld-link: error: undefined symbol: fstat
>>> referenced by C:\Users\web\AppData\Local\dub\packages\eventcore-0.8.39\eventcore\source\eventcore\drivers\threadedfile.d:194
>>>               eventcore.lib(eventcore.drivers.threadedfile.obj):(_D9eventcore7drivers12threadedfile__T23ThreadedFileEventDriverHTCQClQCe5posix6events__T22PosixEventDriverEventsHTCQEiQEbQBx6select15SelectEventLoopHTCQFsQFlQDh7sockets__T23PosixEventDriverSocketsHTQDgZQBfZQEoZQGq7getSizeMFNbNfSQIr6driver__T6HandleVAyaa4_66696c65TSQKcQBl__TQBhVQBda2_6664TmVmN1ZQCcVQBjS1N1ZQCoZ9__lambda2MFNbNiNeZv)

Error: linking with LLD failed
C:\ldc2\bin\ldc2.exe failed with exit code 1.

**Comment by kinke** [comment]
Thx for the report; that's an issue with the new libs (missing some POSIX-compatible aliases, something that needs to be done manually).

**Comment by kinke** [comment]
Working with latest CI release.
