### ISSUE TITLE
localtime returns null (LDC 1.13.0-beta1 Win64)

### ISSUE THREAD

**Issue by SimonN** [ldc-developers/ldc#2903]
Windows 64-bit version of LDC 1.13.0-beta-1. Here is an example D program:

```
import core.stdc.time;

void main()
{
    time_t timestamp = time(null);
    tm*    loctime   = localtime(&timestamp);
    assert (loctime !is null, "OK on DMD, NG on LDC Win 64-bit 1.13.0-beta-1");
}
```
The C standard library's `localtime` function should return a pointer to a statically allocated non-threadsafe struct. With the returned pointer, we can then access the fields of the struct to get years, months, ...

The assert passes when this example program gets built with on DMD 64-bit on Linux, DMD 32-bit on Windows, LDC 1.12 on Linux.

The assert fails when the example is built with LDC 64-bit 1.13.0-beta1. Expected: The assert passes here, too.

**Comment by kinke** [comment]
Thx, that's a bug in the MinGW-w64 .def file, defining `localtime` as alias for `_localtime64` for the 64-bit libs, while it should be `_localtime32`. There seem to be more related bugs, e.g., `gmtime`. I'll have a look.

**Comment by kinke** [comment]
FIxed in master now, along with a few other wrong aliases.
