### ISSUE TITLE
Arithmetic_geometric_mean.d compiles but stays stcuk in ?????

### ISSUE THREAD

**Issue by sxkladi** [ldc-developers/ldc#2904]
import std.stdio, std.math, std.typecons, std.typetuple;

real agm(real a, real g, in int bitPrecision = 60) pure nothrow @nogc @safe
{
    do
    {
        //{a, g} = {(a + g) / 2.0, sqrt(a * g)};
        TypeTuple!(a, g) = tuple((a + g) / 2.0, sqrt(a * g));
    }
    while (feqrel(a, g) < bitPrecision);
    return a;
}

void main() @safe
{
    writefln("%0.19f", agm(1, 1 / sqrt(2.0)));
}

-- this code compiles  and in dmd runs immediately with a result . with the latest ldc2 it also compiles, b it never returns when executed. the cursor just sits there for hours. --> ldc2-1.13.0-beta1-windows-x64

**Comment by kinke** [comment]
DMD uses 80-bit x87 `real`, LDC for MSVC targets 64-bit double precision (corresponding to MSVC's `long double`); `feqrel` will not exceed `T.mant_digits` (= 53 for DP) IIRC, so a hardcoded default of 60 is bad and not portable. You should probably use an offset from `T.mant_digits` instead.
