### ISSUE TITLE
Does not see return statement even if it's there

### ISSUE THREAD

**Issue by Teashrock** [ldc-developers/ldc#2913]
Tried to compile a function, accidentaly maked a typo (forgot to dereference an array), but suddenly ran into another strange error.

Code:
int function(params, char[]* auth) {
	// Code
	foreach (digit; auth) // <-- Yes, it's a typo.
            msc.write(digit);
	// Code
	return 0;
}

Stdout:
Error: invalid foreach aggregate auth
Error: function storyteller.transmute no return exp; or assert(0); at end of function

It complains about return statement, which on it's place.

When i fixed a typo, return error gone too, and compiled smoothly, but it's still a bug. Compiling with DMD doesn't have this issue.

**Comment by thewilsonator** [comment]
What are the frontend versions of the compilers you are using? 
This looks like a DMD bug that was fixed but hasn't made it way into LDC yet.

**Comment by Teashrock** [comment]
DMD v2.083.0
LDC - the LLVM D compiler (1.0.0):
  based on DMD v2.071.2 and LLVM 3.8.0
  built with LDC - the LLVM D compiler (0.17.1)

**Comment by thewilsonator** [comment]
Thanks, please see if the issue is still present in LDC 1.13.0-beta1.

**Comment by kinke** [comment]
I checked it on run.dlang.io; our latest beta yields the same 6 errors as DMD 2.083.

**Comment by Teashrock** [comment]
Yes, there is no same bug on beta version. Closed.
