### ISSUE TITLE
Is it possible to static link phobos2 and druntime only?

### ISSUE THREAD

**Issue by stevefan1999-personal** [ldc-developers/ldc#2924]
I have traced this problem in the issues but it is a complete mess, I think we will need a clarification/IANS here.

I found that `ldc <file.d> -static` will statically link all libraries but I want to preserve libc, libm, but if I left `-static` out, `libphobos2-ldc.so` and `libdruntime-ldc`will stay. I think it is good to have a `-static-runtime` option that just substitute the two dlang runtime but not others.

**Comment by stevefan1999-personal** [comment]
and if I do this: `-defaultlib=druntime-ldc,phobos2-ldc`, the compiler already assumes that it is shared library (so that the actual required objects are `libdruntime-ldc-shared` and `libphobos2-ldc-shared`). 

```
ldc2 hello.d -O2 -defaultlib=druntime-ldc.a,phobos2-ldc.a
/usr/bin/ld: cannot find -ldruntime-ldc.a-shared
/usr/bin/ld: cannot find -lphobos2-ldc.a-shared
```

The only workaround is to link the object file manually and exclude libdruntime-ldc and libphobos2-ldc from dynamic linkage, but it is very silly.

**Comment by Vild** [comment]
You are probably looking for `-link-defaultlib-shared=false`. This one tells ldc to link to the .a version instead of .so for the runtime.

**Comment by kinke** [comment]
> I found that ldc <file.d> -static will statically link all libraries but I want to preserve libc, libm, but if I left -static out, libphobos2-ldc.so and libdruntime-ldcwill stay. I think it is good to have a -static-runtime option that just substitute the two dlang runtime but not others.

Yep, that's exactly why there's `-static` and `-link-defaultlib-shared`. The latter defaults to true when building a shared lib with `-shared`, at least with official prebuilt packages (some distro packages may ship with shared druntime/Phobos only).

**Comment by kinke** [comment]
Wrt. the `std.net.curl` warning with `-static` - Phobos' curl bindings were switched to supporting the shared curl lib only a while ago IIRC.

**Comment by kinke** [comment]
You're apparently using a non-official package, as the shared libs seem to be the default without `-shared` - check out your `etc/ldc2.conf` configuration file.

**Comment by stevefan1999-personal** [comment]
@kinke uh, I use Arch and indeed the packages in AUR is non-official.

**Comment by stevefan1999-personal** [comment]
> You are probably looking for `-link-defaultlib-shared=false`. This one tells ldc to link to the .a version instead of .so for the runtime.

Works like a charm! Closing this in favor of a documentation in future.

**Comment by kinke** [comment]
> in favor of a documentation in future

In what form? As distro defaults may differ from official packages, mentioning the default setting in the cmdline option description is dangerous (I doubt distros will patch that description).
