### ISSUE TITLE
Add LLVM saturation intrinsics

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2925]
See: https://reviews.llvm.org/rL347334

See druntime's `ldc/intrinsics.di`.

**Comment by kinke** [comment]
While at it, there's also new `llvm.{maximum,minimum}` with slightly different semantics than existing `llvm.{min,max}num`.

**Comment by baziotis** [comment]
I think better close this issue.

**Comment by kinke** [comment]
I left it open because of maximum, minimum and may finally get to it soon, adding it should be a matter of minutes.

**Comment by baziotis** [comment]
Right, I missed those.
This: https://llvm.org/docs/LangRef.html#llvm-minimum-intrinsic
and this: https://llvm.org/docs/LangRef.html#llvm-maximum-intrinsic
right?
