### ISSUE TITLE
LDC 1.11.0 miscompiles LDC 1.8.0

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2928]
LDC 1.11 (and newer) cannot build LDC 1.8, it miscompiles it.
I don't know whether this is a bug in LDC 1.8 code, or whether 1.11 introduced a miscompilation bug (perhaps C++-interop related).
When LDC 1.8 is built with LDC 1.11, compiling a simple file with `void foo() {}` crashes the compiler during codegen.

**Comment by JohanEngelen** [comment]
LDC 1.9 and 1.10 are also miscompiled by LDC 1.12. (1.11 is correctly compiled)

**Comment by kinke** [comment]
> I don't know whether this is a bug in LDC 1.8 code, or whether 1.11 introduced a miscompilation bug (perhaps C++-interop related).

I bet it's the first, in combination with different dtor semantics. Dtors of `extern(C++)` classes are now virtual by default (or even enforced, I don't remember exactly), so the vtbl layout is likely to be off - I had to patch something in this regard, as we have an LDC-specific dtor in one of the frontend classes.

**Comment by JohanEngelen** [comment]
Thanks for finding the fix. Not worth putting out point-releases. I hope whoever else hits this problem will find this github issue.
