### ISSUE TITLE
Incompatible system types

### ISSUE THREAD

**Issue by Teashrock** [ldc-developers/ldc#2945]
Tried to compile a project
@
Got:
/opt/ldc/bin/../import/object.d(394,17): Error: incompatible types for `(at(lhs, u)) != (at(rhs, u))`: `string` and `immutable(char)`
@
WTF

**Comment by Teashrock** [comment]
LDC version 1.13.0 Release.

**Comment by Teashrock** [comment]
I mean, "string" type must be an alias to "immutable(char)[]", but this last part isn't even an array.

**Comment by kinke** [comment]
That seems to be the problem - trying to compare a `string[]` for equality against a `string`. I suppose you get the same error with DMD 2.083? I bet this isn't a compiler issue.

**Comment by kinke** [comment]
Feel free to reopen with more information.
