### ISSUE TITLE
Build failure with ldc 1.13.0; ubuntu 14.04; -static

### ISSUE THREAD

**Issue by jondegenhardt** [ldc-developers/ldc#2956]
I'm seeing a build failure starting with ldc 1.13.0 on ubuntu 14.04 when building with `-static`.

This occurred on travis-ci cron builds for tsv-utils when ldc "latest" switched from 1.12.0 to 1.13.0. There were no other changes. Nature of the build failure was not clear from the logs.

Not all builds failed, only one of the builds failed, one running unit tests for the "common" subdirectory.

Thinking it might be related to the switch to the gold linker in ldc 1.13.0 combined with ubuntu 14.0.4, I switched the travis-ci builds to use ubuntu 16.0.4. This resolved the issue. Note that there were also issues with the gold linker, `-static`, and the gold linker in #2390.

This is a fairly different scenario that #2390. It occurs in a small section of code. It can most likely be narrowed quite a bit, though I don't have time to do this right now.

For now I suggest keeping lookout for other users having problems with the combination of 1.13.0, gold link, and `-static`. It may be sufficient to have people seeing problems switch to a more recent version of Utuntu.

Note that travis-ci now supports Ubuntu 16.04 without using docker images. See [Ubuntu Xenial 16.04 build environment is here!](https://changelog.travis-ci.com/ubuntu-xenial-16-04-build-environment-is-here!-79690)

**Comment by JohanEngelen** [comment]
Hey Jon, thanks for the report. I think we won't put effort into fixing ubuntu 14.04 issues any more because it reaches end-of-life early in 2019. I'm happy you could easily switch to 16.04.

**Comment by jondegenhardt** [comment]
Makes sense. Perhaps the main thing is simply to be able to tell others encountering an issue to switch to Ubuntu 16.04 or later, or perhaps to switch to a different linker. Or, don't build with `-static`.
