### ISSUE TITLE
32-bit OSX EOL

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#2959]
Just a note to say that (AFAIK) noone needs OSX 32-bit code generation anymore in any new D compiler.
We can always use an older compiler if need be, and **the latest Xcode update simply prevents 32-bit code to be linked**. Transition will happen very fast, and end users are **not** complaining.

**Comment by kinke** [comment]
For us, this means we can simplify the CMake script, as building those fat OSX libs has always been a PITA, and reduce CI times + package sizes.

**Comment by p0nce** [comment]
However macOS is supposed to transition to ARM starting 2020, it has been announced for a while. Perhaps fat binaries may need to be revived at one point.

**Comment by kinke** [comment]
Please don't tell me they'll start fresh in a year's time and still want to support 32-bit CPUs...

**Comment by p0nce** [comment]
Yes! Though I don't know at all in what form the transition will occur.

**Comment by thewilsonator** [comment]
Lets do this properly! https://forum.dlang.org/post/zqocomkmbbtykkpqwrwr@forum.dlang.org

**Comment by jacob-carlborg** [comment]
@p0nce you were the only one building for macOS 32bit (as far as I know) so if you don't need it we should definitely remove it.

**Comment by p0nce** [comment]
It's a solid rumor!

**Comment by wilzbach** [comment]
FYI: DMD now officially dropped OSX 32-bit (https://dlang.org/changelog/2.085.0.html#osx-32bit), so I guess LDC could follow?

**Comment by kinke** [comment]
With v1.15, 32-bit macOS isn't CI-tested anymore and the prebuilt macOS package contains x86_64 libs only.

Respective codegen/CMake/... special cases are still in place.
