### ISSUE TITLE
[windows] How to link with a static C runtime, for a shared library, when using lld-link or -link-internally

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#2967]
Making shared libraries, until then we used this to force linking with the static VC++ runtime.

```
    "lflags-windows-ldc": [
        "libcmt.lib",
        "/nodefaultlib:msvcrt.lib",
        "/nodefaultlib:vcruntime.lib"
    ],
```
For now we use a non-existing-dir envvar work-around to make LDC detect VS like previously, so that these flags still find their way to MS linker `link.exe`. But LDC is more flexible than that.

I see now that you can `-link-internally` and there is a `lld-link.exe` bundled: **Can we link to a static C runtime (ideally the MS's one, but really anything goes) using lld-link or -link-internally? Or we do have to use link.exe for this case?**

**Comment by kinke** [comment]
The static libs are the default option with the MS toolchain. So just use `-link-internally` and none of the 3 flags above. As always, running LDC with `-v` gives you the linker command line, where you'll see the corresponding `/DEFAULTLIB:libcmt` setting.

External `lld-link` is only required for LTO, where `-link-internally` fails. It's the default linker with `-flto`, so you shouldn't have to care.

**Comment by kinke** [comment]
To skip the VS detection/setup (`LDC_VSDIR=C:\__dummy`) and save another second, check out https://github.com/ldc-developers/ldc/blob/master/packaging/README.txt#L31-L36.

**Comment by p0nce** [comment]
Thanks for the information!

Will follow https://github.com/ldc-developers/ldc/blob/master/packaging/README.txt#L31-L36 eventually, when everyone is on LDC >= 1.13
