### ISSUE TITLE
Build of ldc 0.17.6 fails on OSX because of missing __inline_isnanl

### ISSUE THREAD

**Issue by ThomasMader** [ldc-developers/ldc#2982]
When building ldc 0.17.6 on Darwin with Nix I get the following error:

[  5%] Building CXX object CMakeFiles/LDCShared.dir/dmd2/root/port.c.o
/tmp/nix-build-ldcBuild-0.17.6.drv-3/ldc-0.17.6-src/dmd2/root/port.c:791:12: error: use of undeclared identifier '__inline_isnanl'
    return __inline_isnanl(r);

port.c had always this problem also when building dmd till it was removed in favor of port.d.
I always replaced __inline_isnanl with __inline_isnan to make it work. Would be nice if that could be fixed upstream.
I would have made a PR but I don't know if that is the proper fix.

**Comment by kinke** [comment]
So we're talking about:
https://github.com/ldc-developers/ldc/blob/c0dc6315db09a72cd5028f579e76b0805802020c/dmd2/root/port.c#L787-L794

I guess the `__MAC_OS_X_VERSION_MAX_ALLOWED` should actually be `MAC_OS_X_VERSION_MIN_REQUIRED`, but I don't use & know Mac.

**Comment by ThomasMader** [comment]
Yes you are probably right.
Don't know either where to find out which OSX version has __inline_isnanl. I will try to find out.

**Comment by ThomasMader** [comment]
A little history digging.
https://github.com/dlang/dmd/blob/f77efd17ecdfb65a2d6e7ea66b0be30d8e063199/src/root/port.c#L368 was the commit which introduced __inline_isnan on 3rd of July 2009.

Xcode 3.1.3 from 17.06.2019:

```
        #define isnan(x)        \
                (       sizeof (x) == sizeof(float )    ?       __inline_isnanf((float)(x))     \
                :       sizeof (x) == sizeof(double)    ?       __inline_isnand((double)(x))    \

        :       __inline_isnan ((long double)(x)))
```

Xcode 10.13:

```
#define isnan(x)                                                         \
    ( sizeof(x) == sizeof(float)  ? __inline_isnanf((float)(x))          \
    : sizeof(x) == sizeof(double) ? __inline_isnand((double)(x))         \
                                  : __inline_isnanl((long double)(x)))
```

So the macro was always there and to me it makes more sense to use the macro as the __inline_isnan* functions are internal details which are more likely to change.
