### ISSUE TITLE
[uClibc][regression] module constructors

### ISSUE THREAD

**Issue by rracariu** [ldc-developers/ldc#2994]
The following program compiles and runs when build with `LDC 1.10.0`

```test.d
import core.stdc.stdio;

int x;

shared static this()
{
    printf("Shared ctor.\n");
}

static this()
{
    printf("TLS ctor.\n");
    x++;
}

void main()
{
    printf("X is %d\n", x);
}
``` 

Compiled with `LDC 1.13.0` none of the module ctors gets called. The issues is observed on both ARM and MIPS32 tool-chains.

**Comment by kinke** [comment]
I guess that's because the linker wrongly strips the ModuleInfos, see #2870. To fix this, the default linker on Linux was changed to gold. Can you verify it's being used and play around with different linkers/versions?

**Comment by kinke** [comment]
Alright, that's the problem then. Well, you'll need a fixed cross-linker, e.g., a newer bfd if you can find one (the one from Ubuntu 18.04 for example works fine), gold or lld (I think the latter only works with a clang toolchain, as gcc refuses `-fuse-ld=lld`).

**Comment by kinke** [comment]
[Chromium apparently defaults to gold for MIPS Linux too, since > 2.5 years: https://codereview.chromium.org/2027173002]

**Comment by rracariu** [comment]
Trying a newer version of Ubuntu first. Wanna see if I can get it working with the stock MIPS cross linker. Hope that this doesn't require me building from source :(

Nevertheless, there needs to be a *BIG WARNING* on each release notes about this issue - it is a silent one that can give you tones of problem.

**Comment by kinke** [comment]
It shouldn't be that much of an issue, as we default to gold, and you had to explicitly use `-linker=bfd`. The only (internal) complaint so far was that Ubuntu 14.04's AArch64 cross-gcc package doesn't contain gold (and yep, aarch64 was the only one, and yes, all newer Ubuntu versions feature it).

Before building something from source yourself, I'd try `-link-ìnternally` (with ldc2.conf tweaking, e.g., see https://forum.dlang.org/post/snuevgoflgqdnmoqrkzu@forum.dlang.org).

**Comment by rracariu** [comment]
Upgraded to `Ubuntu 18.04.1 LTS` - got the `binutils-mips-linux-gnu`.

As I told you, I use a vendor toolchain, so warning - BIG HACK AHEAD.
I just symlink-ed vendor's `ld.bfd` to the `/usr/bin/mips-linux-gnu-ld.gold` provided by the Ubuntu package.
It works, but this is not a nice user experience.

**Comment by rracariu** [comment]
Is it possible to make `-link-internally` take an argument with a linker name? I'm thinking that maybe this way we can have a nice way of overriding the defaults.

**Comment by kinke** [comment]
> I just symlink-ed vendor's ld.bfd to the /usr/bin/mips-linux-gnu-ld.gold provided by the Ubuntu package.

Proper way: create a new symlink `ld.gold` in the vendor tree. As a nice side effect, you also don't have to use `-linker=bfd` anymore.

> but this is not a nice user experience

Well, your vendor toolchain ships with an ancient bfd *and* misses gold.

> Is it possible to make -link-internally take an argument with a linker name? I'm thinking that maybe this way we can have a nice way of overriding the defaults.

I'm not sure I follow. The idea certainly isn't to depend on some external gcc/clang as linker driver, extracting the actual linker flags it injects and then invoking the integrated LLD with it. The idea is to depend solely on external libraries and object files.

**Comment by rracariu** [comment]
Right, I tried that before and got an error. Probably messed the link. 
The `ld.gold` symlink works.

Well - this is the case most of the time :( vendors are always behind, the toolchain is based of `GCC 4.8-2014.04 r47072 - 4.8.3`

I'm trying to think of a way to make this semi-automatic, basically a command line or a shell script that invokes a different linker if the user requires it. Basically avoid the need to create the symlink.

**Comment by kinke** [comment]
I don't think that sounds promising. Something that could work pretty easily would be adding an optional `ldc2.conf` setting along the lines of `link-internally-template = "... <LDC ld flags> ..."`. A small external tool could spit it out, based on `gcc -v DUMMY.c`, parsing the linker args and replacing `DUMMY.o` with `<LDC ld flags>`. Then you don't even need a suitable cross-linker anymore (as long as LLD works fine for your target), i.e., a working gold in your case.

**Comment by kinke** [comment]
Closable? I added the known issue to the release notes; wrt. `-link-internally` inconvenience for Posix, there's #2717 already.
