### ISSUE TITLE
Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by Temtaime** [ldc-developers/ldc#2996]
Compile this on windows with latest ldc with llvm 7.0.1

[app.zip](https://github.com/ldc-developers/ldc/files/2835356/app.zip)

> ldc2 app.d

Instruction does not dominate all uses!
  %24 = extractvalue { i32, %app.GUIElement** } %17, 0
  store i32 %24, i32* %7
Instruction does not dominate all uses!
  %24 = extractvalue { i32, %app.GUIElement** } %17, 0
  %34 = icmp ult i32 %33, %24
LLVM ERROR: Broken function found, compilation aborted!

**Comment by kinke** [comment]
That's a beta regression; thanks for reporting just in time. Will be fixed shortly.
