### ISSUE TITLE
atomicOp wrong results for double or infinite loop

### ISSUE THREAD

**Issue by zoodyy** [ldc-developers/ldc#3000]
Hi everyone,
I just stumbled upon a weird bug with `atomicOp!"+="` on `double` variables. `float` is not affected. System: Arch Linux x64.
The following code works fine with dmd but fails with ldc (1.13 and 1.14 beta, both debug and optimized release):
```d
import core.atomic;
import std.stdio;
void main()
{
    shared double data = 0.1;
    data.atomicOp!"+="(0.1);
    writeln(data); // prints 0.2 with dmd, 0.6 with ldc
}
```
If you further change one line to `data.atomicOp!"+="(1.0);` computation is stuck in an infinite loop.

Edit: When only using values that can be exactly represented (like 1.0  or 0.5) in both initialization and the atomicOp, computation is both correct and fast.

**Comment by kinke** [comment]
Wow, thx for reporting.
