### ISSUE TITLE
Alpine archive for LDC 1.14.0

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3004]
Please add Alpine archive for LDC 1.14.0 release.
Thank you so much!

**Comment by kinke** [comment]
Joakim Noah has (hopefully only) taken a longer break (censorship issue in the forum), so don't expect any packages whose creation isn't automated. If interested, step up. ;)

**Comment by zoujiaqing** [comment]
@andre2007 use debian ? I add ldc for debian docker image:
https://github.com/dlangchina/docker-dlang

**Comment by andre2007** [comment]
@zoujiaqing thanks for the info. I do not know how it is handled in other companies, I have the experience that the security department rates Alpine docker images as more secure than Debian docker images. Some times you can decide on the image and some times the security department decides on the image.

**Comment by kinke** [comment]
I'm closing this, as I think it should 1) be a community effort and 2) be a proper Docker image based on Alpine or at least an archive without LLVM package dependencies.

**Comment by andre2007** [comment]
Ok, thanks for the feedback

**Comment by aliak00** [comment]
@andre2007  Did you manage to get/make/find an alpine linux version with ldc?

**Comment by andre2007** [comment]
@aliak00 I stopped using Alpine as it caused a lot of manual work (installing apache parquet or H5 on Alpine is almost impossible while it is a single line on Debian)

**Comment by aliak00** [comment]
@andre2007 Oh that's really good to know! Thank you!
