### ISSUE TITLE
ldc-build-runtime: -mtriple=arm-linux-musleabihf: command not found

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3006]
On Ubuntu 18.04 LTS (Windows subsystem for linux) I executed following commands:

```
sudo apt-get update && sudo apt-get install build-essential cmake
curl -LO https://musl.cc/arm-linux-musleabihf-cross.tgz
tar -xvzf arm-linux-musleabihf-cross.tgz

curl -LO https://github.com/ldc-developers/ldc/releases/download/v1.14.0/ldc2-1.14.0-linux-x86_64.tar.xz
tar -xf ldc2-1.14.0-linux-x86_64.tar.xz

export PATH=/home/user/arm-linux-musleabihf-cross/bin:/home/user/ldc2-1.14.0-linux-x86_64/bin:$PATH
export CC=arm-linux-musleabihf-gcc

ldc-build-runtime --dFlags=-w;-mtriple=arm-linux-musleabihf TARGET_SYSTEM=Linux;UNIX CMAKE_C_COMPILER_WORKS=True CMAKE_SYSTEM_NAME=Linux BUILD_SHARED_LIBS=OFF
```

Output of ldc-build-runtime doesn't look that bad:
```
[100%] Linking D static library lib/libphobos2-ldc-debug.a
[100%] Built target phobos2-ldc-debug
Runtime libraries built successfully into: /home/user/ldc-build-runtime.tmp
-mtriple=arm-linux-musleabihf: command not found
UNIX: command not found
```

only the last two lines seems strange. Did I anything wrong?
I want to cross compile from Ubuntu to Alpine Linux running on a Raspberry 
(or more specific a docker image based on Alpine running on Raspberry)

**Comment by kinke** [comment]
> `ldc-build-runtime --dFlags=-w;-mtriple=arm-linux-musleabihf ...`

You need to quote args with semicolons in them (`--dflags='...'), it's bash.

**Comment by andre2007** [comment]
Thank you:)

**Comment by andre2007** [comment]
I try now with following command ```ldc-build-runtime --dFlags="-w;-mtriple=arm-linux-musleabihf"```

```
Invoking: ["cmake", "-DLDC_EXE_FULL=/home/user/ldc2-1.14.0-linux-x86_64/bin/ldc2", "-DD_VERSION=2", "-DDMDFE_MINOR_VERSION=0", "-DDMDFE_PATCH_VERSION=84", "-DLDC_TARGET_PRESET=", "-DTARGET_SYSTEM=AUTO", "-DD_FLAGS=-w;-mtriple=arm-linux-musleabihf", "-DRT_CFLAGS=", "-DLD_FLAGS=", "-DBUILD_SHARED_LIBS=OFF", "/home/user/ldc-build-runtime.tmp/ldc-src/runtime"]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/ldc-build-runtime.tmp
Invoking: ["make", "all"]
```

but get the errors:
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/signal.d(3485): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(392): Error: undefined identifier pthread_mutex_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(393): Error: undefined identifier pthread_once_t, did you mean function pthread_once?
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(446): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(447): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(448): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(449): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(450): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(451): Error: undefined identifier pthread_attr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(717): Error: undefined identifier pthread_cond_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(718): Error: undefined identifier pthread_cond_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(719): Error: undefined identifier pthread_cond_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(719): Error: undefined identifier pthread_condattr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(720): Error: undefined identifier pthread_cond_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(721): Error: undefined identifier pthread_cond_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(721): Error: undefined identifier pthread_mutex_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(722): Error: undefined identifier pthread_cond_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(722): Error: undefined identifier pthread_mutex_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(723): Error: undefined identifier pthread_condattr_t
/home/user/ldc-build-runtime.tmp/ldc-src/runtime/druntime/src/core/sys/posix/pthread.d(724): Error: undefined identifier pthread_condattr_t

**Comment by andre2007** [comment]
As far as I understand CRuntime_Musl is missing the implementation for ARM.
I will create an issue for druntime.

**Comment by andre2007** [comment]
https://issues.dlang.org/show_bug.cgi?id=19709
