### ISSUE TITLE
Implement Objective-C improvements from DMD 2.085

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#3007]
As a follow-up to #2670, there'd be more Objective-C stuff to add (support for classes, instance variables & super calls, deprecate interfaces...). In the meantime, most Objective-C tests in dmd-testsuite have been disabled.

**Comment by adamdruppe** [comment]
fyi, I got most of this working in my opend fork and wrote up some info about it:

https://dpldocs.info/this-week-in-d/Blog.Posted_2024_10_14.html#how-it-works-in-opend

if you wanna pull code from the linked commits there in here i expect it wouldn't be too hard for you to adapt it here.

**Comment by kinke** [comment]
Oh wow, now that's a huge and detailed write-up! :+1:

Thx for letting us know; surely took some effort to get there, cool that you did.

**Comment by kinke** [comment]
Resolved by #4777.
