### ISSUE TITLE
CRuntime_Musl is missing ARM version

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3010]
As far as I understand, druntime is missing ARM version for CRuntime_Musl. Therefore you cannot cross compile to arm-linux-musleabihf.

```bash
sudo apt-get update && sudo apt-get install build-essential cmake
curl -LO https://musl.cc/arm-linux-musleabihf-cross.tgz
tar -xvzf arm-linux-musleabihf-cross.tgz

curl -LO https://github.com/ldc-developers/ldc/releases/download/v1.14.0/ldc2-1.14.0-linux-x86_64.tar.xz
tar -xf ldc2-1.14.0-linux-x86_64.tar.xz

export PATH=/home/user/arm-linux-musleabihf-cross/bin:/home/user/ldc2-1.14.0-linux-x86_64/bin:$PATH
export CC=arm-linux-musleabihf-gcc

ldc-build-runtime --dFlags="-w;-mtriple=arm-linux-musleabihf"
```

I created also an issue on issues.dlang.org but not sure whether it is correct as it seems such
enhancements are from LDC side and upstreamed to druntime.

**Comment by kinke** [comment]
Upstream is the right place for it. LDC just happens to be tested/implemented first when requiring bootstrapping via ltsmaster.

On a side note, tackling such things oneself is much more likely to result in success than hoping someone else is interested in the same new (sub)platform *and* willing to translate the missing C header parts to a druntime patch. ;)

**Comment by andre2007** [comment]
Thanks for the info. I already tried myself because I thought it's just adding some missing type definitions. Unfortunately then there are syntax errors all over phobos and my knowledge here is not that broad. If I have sone more time I will check whether I can have a second look.
