### ISSUE TITLE
unsupported reloc 42 against global symbol

### ISSUE THREAD

**Issue by jacob-carlborg** [ldc-developers/ldc#3020]
I have a project where I'm trying to compile with LDC 1.15.0-beta1. Everything works fine with LDC 1.14.0, but with 1.15.0-beta1 I get a bunch of linker errors like:

```
/usr/bin/ld.gold: error: /home/travis/dlang/ldc-1.15.0-beta1/bin/../lib/libphobos2-ldc.a(deflate.c.o): unsupported reloc 42 against global symbol _length_code
```

Full build log available here: https://travis-ci.com/jacob-carlborg/dvm/jobs/183678381.

**Comment by dnadlinger** [comment]
What's your `ld.gold --version`?

**Comment by dnadlinger** [comment]
It looks like `42`is `R_X86_64_REX_GOTPCRELX`, which seems to have only been around since 2015: https://groups.google.com/forum/#!topic/x86-64-abi/n9AWHogmVY0

We might need to disable generation of that in LLVM.

**Comment by jacob-carlborg** [comment]
The version of ld.gold is: `GNU gold (GNU Binutils for Ubuntu 2.24) 1.11`

**Comment by dnadlinger** [comment]
Oh, interestingly those relocations are in the C part of Phobos!

**Comment by jacob-carlborg** [comment]
Are the C parts in LDC 1.15 compiled with a later version of Clang?

**Comment by kinke** [comment]
See #3018 for the Travis workaround. The new package has been built on Xenial, with its gcc v5.5 (previously: Trusty and backported gcc v6.3).

**Comment by jacob-carlborg** [comment]
> See #3018 for the Travis workaround.

I'll give that a try.

**Comment by jacob-carlborg** [comment]
That worked, thanks.

**Comment by kinke** [comment]
No worries. Sorry for the inconvenience, that came unexpected, as did the libtinfo warning when running the binary on Trusty (tackled in #3019).
I've appended it as 'big news' in the 1.15.0-beta1 release log.
