### ISSUE TITLE
armhf build missing for 1.14.0 release

### ISSUE THREAD

**Issue by abraunegg** [ldc-developers/ldc#3027]
Hi all,

Just wondering, as it is not in the release notes, up to v1.13.0 there were separate builds for armhf & aarm64. From 1.14.0 onwards, the armhf build has been dropped.

The reason for the question is that I rely on armhf & aarm64 binary builds to validate the OneDrive Linux Client  which I maintain (https://github.com/abraunegg/onedrive) as part of the Travis CI process to ensure that the application builds & executes correctly under those environments.

Can you provide some insight to that? Will armhf binary build return?

**Comment by kinke** [comment]
I used to build those manually with qemu in a Linux VM and can't be bothered to keep that up, especially wrt. building newer LLVM in qemu (used to take ~36 hours, lately 'just' 12) - for v1.13, there have been 54 armhf downloads so far (and even less, 42, for AArch64). The AArch64 build (both LLVM and LDC) is automated though and so 0 hassle.

**Comment by abraunegg** [comment]
@kinke 
Thanks for the info. I was pinning the Travis CI against 1.11.0 however will now have to pin these against separate versions.
