### ISSUE TITLE
Since 1.13, lld-link fails to link with betterC on Windows

### ISSUE THREAD

**Issue by dd86k** [ldc-developers/ldc#3035]
Despite every attempt, lld-link seems to even fail when 
`ldc2 ggf -defaultlib="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64\ucrt"` is invoked, always with the same output, and I've set my user PATH to `C:\PROGRAMS\ldc\bin` as usual. (Also tried `-link-internally` and `-disable-linker-strip-dead`)

Following example output is using `import core.stdc.stdio : printf;` and `extern (C)` for the entirely of the program (including `main`).

Output (sample):
```
E:\DOCUMENTS\D projects\ggf>ldc2 ggf -link-internally
...
lld-link /NOLOGO /OPT:REF /OPT:ICF /DEFAULTLIB:vcruntime140 /OUT:ggf.exe ggf.obj C:/PROGRAMS/ldc/bin/../lib64\ldc_rt.builtins.lib /LIBPATH:C:/PROGRAMS/ldc/bin/../lib64 /LIBPATH:C:/PROGRAMS/ldc/bin/../lib64/mingw phobos2-ldc.lib druntime-ldc.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
lld-link: error: undefined symbol: printf
>>> referenced by ggf.obj:(version_)
>>> referenced by ggf.obj:(main)
>>> referenced by ggf.obj:(main)
>>> referenced by ggf.obj:(main)
>>> referenced by ggf.obj:(main)
...
```

I do have the Windows 10 SDK and VS2017 installed, obviously, but I am wondering do I have some extra configuration? Am I missing something? Do I need to add the SDK/VS paths into the config file? I checked through the older issues and wiki(s) and got through nothing of significance.

I am clearly lost.

**Comment by kinke** [comment]
v1.13 came with the MinGW libs, see the README.txt for more infos on how you can use the MS toolchain.

As to your actual error linking error, that obviously shouldn't happen (and I'm pretty sure I tested linking a tiny program with some `printf`). The lld-link invocation you pasted is from the `ldc2 -v` output, right?

> `-defaultlib="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64\ucrt"`

That's not what this switch is for. You're probably looking for `-mscrtlib`. But if you just want to use the MS libs, take a look at the README.

**Comment by WebFreak001** [comment]
can reproduce, wanted to do betterC on windows and thought I just had something setup wrong

**Comment by kinke** [comment]
Ah, `-betterC` is different, you won't get the implicit dependencies of druntime that way, and will need to include `legacy_stdio_definitions.lib` manually in the cmdline.

**Comment by kinke** [comment]
Ah, so the OP used `-betterC` too? ;) - That's not an irrelevant detail, and doesn't match the lld-link cmdline (including druntime and Phobos...).

Specifying that lib manually for betterC was required before 1.13 too if **not** using the (default) static MS runtime, but the dynamic one (`-mscrtlib=msvcrt`). So this only worked because libcmt (or libvcruntime) apparently have an embedded reference to that lib. And thus it still works when using the MS toolchain. The only difference since v1.13 is that the MinGW libs (and thus dynamic MS runtime) are used by default.

**Comment by kinke** [comment]
Note that linking `cl bla.cpp /MD`:
```C++
extern "C" int printf(const char *fmt, ...);

int main()
{
    printf("hello\n");
}
```

also requires adding the lib manually (since VS 2015, where MS converted the printf/scanf family to templates, with legacy symbols in `legacy_stdio_definitions.lib`).

So to me, this is working as intended.

**Comment by dd86k** [comment]
I changed the title because the entirely of the program uses `extern (C)` (including `main`), and is affected regardless of betterC usage (I've tried with and without the switch), but since main is still marked with a C extern (as the rest), I changed the title to better reflect the initial issue.

Last night, I've tried the four examples listed in `--help` (`libcmt`, `libcmtd`, `msvcrt`, and `msvcrtd`) without any success. I might try again to play with the configuration file (ldc.conf) to add `legacy_stdio_definitions.lib` later today.

**Comment by kinke** [comment]
Ah, I can reproduce the issue without `-betterC` now; linking should indeed work without it (due to https://github.com/ldc-developers/druntime/blob/ldc/src/rt/msvc.c#L91), so that's really a bug.

**Comment by kinke** [comment]
> Last night, I've tried the four examples listed in --help (libcmt, libcmtd, msvcrt, and msvcrtd) without any success.

That switch (`-mscrtlib`) only makes sense with the MS toolchain - e.g., in a VS command prompt (see https://github.com/ldc-developers/ldc/blob/master/packaging/README.txt#L15-L36 for other options).

**Comment by dd86k** [comment]
Awesome, thanks for the work!
