### ISSUE TITLE
ldc build error

### ISSUE THREAD

**Issue by changloong** [ldc-developers/ldc#3047]
I try build ldc follow https://wiki.dlang.org/Building_LDC_from_source from macOS:

```sh
git clone https://github.com/ldc-developers/llvm.git
cd llvm
git submodule update --init
mkdir build && cd build/
cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64;WebAssembly" -DLLVM_BUILD_TOOLS=OFF -DLLVM_BUILD_UTILS=OFF

CMake Error at cmake/modules/AddLLVM.cmake:1364 (add_dependencies):
  The dependency target "clang" of target "check-all" does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:931 (add_lit_target)


CMake Error at cmake/modules/AddLLVM.cmake:1364 (add_dependencies):
  The dependency target "clang-headers" of target "check-all" does not exist.
Call Stack (most recent call first):
  CMakeLists.txt:931 (add_lit_target)

# a lot error like this
-- Generating done
-- Build files have been written to: /opt/tools/llvm/build
```

get try run ninja
```sh
ninja
ninja: error: loading 'build.ninja': No such file or directory
```

 https://wiki.dlang.org/Building_LDC_from_source  seems outdated, is there some new document for build process ?

How can i fix this?

**Comment by kinke** [comment]
As the Wiki says, up-to-date information is contained in the Azure Pipelines CI scripts. But your problem occurs while building LLVM, so you'd need to look up the Azure scripts for our LLVM fork. - You need `-DCOMPILER_RT_INCLUDE_TESTS=OFF` in the CMake command-line, as mentioned in the GitHub release description.

**Comment by changloong** [comment]
thanks, I follow  https://github.com/ldc-developers/llvm/blob/ldc-release_80/.azure-pipelines/posix.yml with DCOMPILER_RT_INCLUDE_TESTS=OFF fix the problem.
