### ISSUE TITLE
termix linking errors (ldc v1.13.0)

### ISSUE THREAD

**Issue by Tapmemer** [ldc-developers/ldc#3049]
ldc2 on termux keeps giving me this:
`/data/data/com.termux/files/usr/bin/../lib/libdruntime-ldc.a(sections_android.o):sections_android.d:function _D2rt16sections_android12initSectionsFNbNiZv: error: undefined reference to '__bss_end__'
/data/data/com.termux/files/usr/bin/../lib/libdruntime-ldc.a(sections_android.o):sections_android.d:function _D2rt16sections_android12initSectionsFNbNiZv: error: undefined reference to '__bss_end__'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /data/data/com.termux/files/usr/bin/gcc failed with status: 1`  

this started happening randomly (probably after upgrade with apt two days ago)

**Comment by kinke** [comment]
So your LDC version wasn't upgraded, but your linker was? That symbol is supposed to be a magic linker symbol denoting the end of the BSS section, so a linker incompatibility seems likely. You may want to try different linkers with `-linker` and see if another one works.

**Comment by Tapmemer** [comment]
i have tried using gold and lld as linker but they both don't work, i'll see if reinstalling termux works else i'll upgrade ldc

**Comment by Tapmemer** [comment]
reinstalling termux worked
