### ISSUE TITLE
ldc-1.15.0 ubuntu-14: unsupported reloc 42 against global symbol

### ISSUE THREAD

**Issue by jondegenhardt** [ldc-developers/ldc#3054]
This appears similar to #3020, except occurring when making an instrumented build (PGO). Works fine in a normal build, and switching to Ubuntu-16 solves the problem.

This occurred on my travis-ci builds of tsv-utils after the ldc 1.15.0 release today (it builds from latest). The build log failure is [here](https://travis-ci.org/jondegenhardt/tsv-utils/jobs/516656433#L522).

The key part of the build line (omitting the files):
```
ldc2 -release -O3 -boundscheck=off -singleobj -flto=thin -odobj -d-version=LDC_PROFILE -fprofile-instr-generate=profile.%p.raw -defaultlib=phobos2-ldc-lto,druntime-ldc-lto
```
There were quite a few error lines listing individual symbols and some slightly different errors. Details can be seen in the log.

**Comment by kinke** [comment]
Ah, the profiling lib is one of the LLVM compiler-rt libraries, and those aren't built with that extra gcc switch.

**Comment by kinke** [comment]
> it builds from latest

No idea how frequently your CI runs, but if it does at least weekly or so, an `ldc-beta` Travis job would come in handy to prevent stuff like that from happening again.

**Comment by jondegenhardt** [comment]
Good idea. This occurrence made me wonder about that too. Specifically, if there was a beta target available from I could add. I do run a weekly cron build with a somewhat large set of configs, so I've got a place to put it. I'll add the `ldc-beta`. 

I could set up some additional targets if it'd be useful to ldc. For example, I could add a nightly target, and I could run both ubuntu-14 and 16. The other variable is static lib or not. (I use static libs for distribution builds).

**Comment by kinke** [comment]
> Specifically, if there was a beta target available in Travis I could add.

Sure, that's `d: ldc[-beta|-latest-ci]`.

Thx, beta surely makes sense; the latest CI build should be pretty stable too IMO (but slower at compilation due to enabled LLVM+LDC assertions). Not sure how much point there's still in Ubuntu 14.04 (we don't test it at all ourselves here anymore, EOL in a couple of weeks -> just 16.04 and newer). Shared libs might be interesting...

**Comment by jondegenhardt** [comment]
Added three `ldc-beta` builds to tsv-utils weekly cron CI build. [tsv-utils PR #208](https://github.com/eBay/tsv-utils/pull/208). May add `ldc-latest-ci` after checking the full run time.

**Comment by jondegenhardt** [comment]
> Added three ldc-beta builds to tsv-utils weekly cron CI build. tsv-utils PR #208. May add ldc-latest-ci after checking the full run time.

`tsv-utils` cron log here: [Build #480](https://travis-ci.org/eBay/tsv-utils/builds/518749930). Last three jobs  use `ldc-beta`. Cases covered include:
* Linux: Dub builds; debug and release. No LTO/PGO, no `-static`
* Linux:  `tsv-utils` makefile builds; debug and release; No LTO/PGO; with `-static`
* Linux: Debug and release builds; fullLTO; no `-static`
* Linux: LTO / PGO builds using thinLTO against application code and druntime/phobos; no `-static`
* OS X: LTO / PGO builds using thinLTO against application code and druntime/phobos

**Comment by jondegenhardt** [comment]
I think everything discussed here was taken care of long ago. Closing.
