### ISSUE TITLE
maxElement give wrong results with LDC only

### ISSUE THREAD

**Issue by zephyr111** [ldc-developers/ldc#3064]
Hello,

The following code give the result 4 with LDC while the correct result is 1.
GDC and DMD give the correct result.

The version tested is LDC 1.15.0 from the Nix package manager (last package update).
The same issue appear in LDC 1.12.0 from the Debian testing repository.

The latest CI version seems to produce the same result: https://godbolt.org/z/rdnwH3 .
In O3, the result is evaluated by the compiler itself so we can see the wrong value 4 in the assembly code directly.

```D
module main;
import std.stdio;
import std.range;
import std.algorithm.searching;

void main(string[] args)
{
	int[] tab = [1, 2, 3, 4];
	int[] arr = [23, 42, 17, 5, 31];
	tab.maxElement!((i) { return arr[i]; }).writeln;
}
```

**Comment by dnadlinger** [comment]
Huh?

```
$ dmd --version
DMD64 D Compiler v2.085.0

Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
$ dmd -run test.d
4
```

**Comment by zephyr111** [comment]
It might be an issue with a recent version of Phobos. As GDC tends to use an older version and a have an older DMD. The DMD on dlang.org give the result 4.

With GDC:
```
$ gdc --version
gdc (Debian 8.2.0-13) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ gdc tmp.d -o tmp && time ./tmp
1
```

With DMD
```
$ dmd --version
DMD64 D Compiler v2.079.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
$ dmd -run tmp.d
1
```

However, The documentation says that it  `iterates the passed range and returns the maximal element. A custom mapping function can be passed to map. In other languages this is sometimes called argmax.`
Thus, the result should be the value v of tab that maximize arr[v]. So v=1 here.

**Comment by MoonlightSentinel** [comment]
This only ocurs while using a lambda, a normal function works fine.

```
void main() {
	tab.maxElement!((i) { return arr[i]; }).writeln; // 4
	tab.maxElement!mapper.writeln; // 1
}

int[] arr = [23, 42, 17, 5, 31];
int[] tab = [1, 2, 3, 4];

int mapper(const int i) {
	return arr[i];
}
```

(DMD32 D Compiler v2.085.0)

**Comment by kinke** [comment]
> It might be an issue with a recent version of Phobos.

According to run.dlang.io, it worked for DMD up to version 2.079 (returning 1), but regressed since v2.080 (returning 4). So I don't think this is LDC-specific; please file an upstream issue.

**Comment by dnadlinger** [comment]
This has been filed as https://issues.dlang.org/show_bug.cgi?id=19828.
