### ISSUE TITLE
uClibc and -checkaction=C

### ISSUE THREAD

**Issue by sarneaud** [ldc-developers/ldc#3078]
uClibc's `assert()` implementation uses a 4-parameter `__assert()` function, like the `__assert_fail()` function in other libcs.

Currently ldc2 doesn't recognise uClibc and falls back to generating code for a 3-parameter `__assert()`.  I don't see an easy fix because LLVM's target triples don't seem to support uClibc.

**Comment by kinke** [comment]
> I don't see an easy fix because LLVM's target triples don't seem to support uClibc.

We have this as workaround for that: https://github.com/ldc-developers/ldc/blob/7474c1932ae2381544e251290e9a5074ecaf857b/driver/main.cpp#L536-L545

This `isUClibc` is currently only used to set the predefined version `CRuntime_UClibc`. We'd need to adapt this too: https://github.com/ldc-developers/ldc/blob/5e5ce199f493091e6aea39f7f19f609dcf683da2/gen/runtime.cpp#L378-L390

**Comment by rracariu** [comment]
uClibc will work at least ARM and MIPS were tested to some extent, see the status issues: https://github.com/ldc-developers/ldc/issues/2995 and https://github.com/ldc-developers/ldc/issues/2810 - MIPS still has issues with ABI compatibility but this is not related to uClibc.

To enable uClibc support the triple looks like `armv6-hardfloat-linux-uclibceabi` or `mipsel-unknown-linux-uclibc`

**Comment by sarneaud** [comment]
@rracariu Thanks, but this is specifically a problem with `-checkaction=C` and uClibc, not uClibc support in general.

**Comment by rracariu** [comment]
@sarneaud OK, got it. Then exposing `isUClibc` outside `main.cpp` should work.
Maybe have a helper function similar to `isMusl()`
