### ISSUE TITLE
CMake Error: Some (but not all) targets in this export set were already defined.

### ISSUE THREAD

**Issue by Robertorosmaninho** [ldc-developers/ldc#3079]
Hi all!

I just compiled the llvm 8.0.0 and I'm trying to get the ldc, but found this problem and I can't figure out how to solve this. I tried to compile on MacOS 10.12 and MacOS Mojave (same LLVM version).

**I've tried compiling it with the following commands:**

git clone --recursive https://github.com/ldc-developers/ldc.git
cd ldc
mkdir build && cd build
export DMD=/usr/local/Cellar/dmd/2.086.0/bin/dmd
cmake -G Ninja -DLLVM_CONFIG=../../llvm/build/bin/llvm-config ..

Available in: https://wiki.dlang.org/Building_LDC_from_source

**Then I get the following result:**

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found host D compiler /usr/local/Cellar/dmd/2.086.0/bin/dmd, with default flags ''
-- Host D compiler ID: DigitalMars
-- Host D compiler version: DMD64 D Compiler v2.086.0
-- Host D compiler front-end version: 2086
-- Found LLVM: /Users/robertorosmaninho/llvm/build (found suitable version "8.0.0", minimum required is "3.9")
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'LLVMSPIRVLib'
--   No package 'LLVMSPIRVLib' found
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- LDC version identifier: 1.16.0-beta2
-- Building LDC with dynamic compilation support: True (LDC_DYNAMIC_COMPILE=True)
-- Building LDC with integrated LLD: OFF (LDC_WITH_LLD=OFF)
-- Building LDC with plugin support: ON (LDC_ENABLE_PLUGINS=ON)
-- Host D compiler linker program: /Library/Developer/CommandLineTools/usr/bin/cc
-- Host D compiler linker flags: -m64;-Xlinker;-no_compact_unwind;-L/usr/local/opt/dmd/lib;-lphobos2;-lpthread;-lm
-- Looking for _SC_ARG_MAX
-- Looking for _SC_ARG_MAX - found
-- Also installing LTO binary: /Users/robertorosmaninho/llvm/build/lib/libLTO.dylib (LDC_INSTALL_LTOPLUGIN=ON)
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.asan_osx_dynamic.dylib --> libldc_rt.asan.dylib
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.osx.a --> libldc_rt.builtins.a
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.profile_osx.a --> libldc_rt.profile.a
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.fuzzer_osx.a --> libldc_rt.fuzzer.a
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.xray_osx.a --> libldc_rt.xray.a
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.xray-basic_osx.a --> libldc_rt.xray-basic.a
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.xray-fdr_osx.a --> libldc_rt.xray-fdr.a
-- Copying runtime library: /Users/robertorosmaninho/llvm/build/lib/clang/8.0.0/lib/darwin/libclang_rt.xray-profiling_osx.a --> libldc_rt.xray-profiling.a
-- Using path for Intrinsics.td: /Users/robertorosmaninho/llvm/include
-- The ASM compiler identification is AppleClang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Looking for unistd.h
-- Looking for unistd.h - found
CMake Error at /Users/robertorosmaninho/llvm/build/lib/cmake/llvm/LLVMBuildTreeOnlyTargets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: FileCheck;not

  Targets not yet defined:
  LLVMHello;LLVMTestingSupport;llvm-PerfectShuffle;count;yaml-bench;BugpointPasses;lli-child-target;TestPlugin;gtest;gtest_main

Call Stack (most recent call first):
  /Users/robertorosmaninho/llvm/build/lib/cmake/llvm/LLVMConfig.cmake:239 (include)
  runtime/jit-rt/DefineBuildJitRT.cmake:46 (include)
  runtime/CMakeLists.txt:775 (build_jit_runtime)

-- Configuring incomplete, errors occurred!
See also "/Users/robertorosmaninho/ldc/build/CMakeFiles/CMakeOutput.log".

**Could you help me solve this?**

**Comment by kinke** [comment]
I've never seen this (and don't use Mac). If you don't need the experimental JIT functionality, you can use `-DLDC_DYNAMIC_COMPILE=False` in the CMake cmdline as workaround.

**Comment by thewilsonator** [comment]
This seems to be caused by 
https://github.com/ldc-developers/ldc/blob/d95e0be904835df95aa12381c1bbdd65036d1209/utils/CMakeLists.txt#L31-L53
LLVM not liking that we have defined our own `not` and `FileCheck`.

**Comment by thewilsonator** [comment]
Commenting those out fixes this problem, I'm not sure what configurations it doesn't like the fact that we do this.

**Comment by thewilsonator** [comment]
https://github.com/ldc-developers/ldc/pull/3151

**Comment by foutrelis** [comment]
I'm not sure 25195fb36ccb2fd48a82116aa3a6b847f5d4f61e successfully addressed this. The targets do not appear to exist at that point so utils/CMakeLists.txt still creates them.

```
CMake Error at /usr/lib/cmake/llvm/LLVMExports.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: FileCheck;not

..

Call Stack (most recent call first):
  /usr/lib/cmake/llvm/LLVMConfig.cmake:243 (include)
  runtime/jit-rt/DefineBuildJitRT.cmake:54 (include)
  runtime/CMakeLists.txt:776 (build_jit_runtime)
```

(I came across this while trying to rebuild ldc against LLVM 9 on Arch Linux.)

**Comment by kinke** [comment]
Indeed, the utils subdir is added in https://github.com/ldc-developers/ldc/blob/master/CMakeLists.txt#L828, while the runtime subdir incl. problematic jit-rt further below in https://github.com/ldc-developers/ldc/blob/master/CMakeLists.txt#L860.

**Comment by JohanEngelen** [comment]
It is fixed by https://github.com/ldc-developers/ldc/pull/3187
