### ISSUE TITLE
scope(exit) doesn't link in -betterC mode

### ISSUE THREAD

**Issue by WalterBright** [ldc-developers/ldc#3101]
scope(exit) worked fine with dmd, but alloca didn’t. alloca worked with ldc, but scope(exit) didn’t (would fail at link-time). This was a couple months ago. scope(exit) was the last straw in trying out D features that sounded like they would be cool but then having some trouble with linking or not working because type info didn’t exist in betterC mode, etc.

https://www.reddit.com/r/programming/comments/c8hbo0/d_as_a_c_replacement_the_art_of_machinery/esnjk8y/

**Comment by dnadlinger** [comment]
Needs a test case.

**Comment by kinke** [comment]
Ah yes, too lazy to file an LDC issue but complaining on forums. :heart:

**Comment by kinke** [comment]
Not going anywhere.
