### ISSUE TITLE
Inlining from shared libraries can introduce unexpected symbol dependencies

### ISSUE THREAD

**Issue by myfreeweb** [ldc-developers/ldc#3111]
Let's say I have a D app that depends on GtkD, which is installed as a shared library. Meson with pkg-config is used.

So object files are built with GtkD on the include path: `-I/usr/local/include/d/gtkd-3/`.

And linking happens with GtkD linked dynamically `-L-L/usr/local/lib/ -L-lgtkd-3` — the C libraries aren't mentioned when linking the app, since `libgtkd-3.so` is already linked to those.

And the result is…

```
…(more similar errors)…
ld: error: undefined symbol: g_object_remove_toggle_ref
>>> referenced by actions.d
>>>               tilix@exe/source_gx_gtk_actions.d.o:(_D7gobject7ObjectGQi__T6opCastTC3gtk11ApplicationQnZQBdMFZQBb)

ld: error: undefined symbol: g_type_is_a
>>> referenced by cairo.d
>>>               tilix@exe/source_gx_gtk_cairo.d.o:(_D7gobject7ObjectGQi__T6opCastTC3gtk9ContainerQkZQBaMFZQy)
…(more similar errors)…
```

Which means that LDC has happily inlined some code from GtkD, introducing a *direct* dependency on the underlying C libraries, in addition to the transitive dependency via `libgtkd-3.so`.

- the obvious "solution" — Deal With It™: shared libraries just add their dependencies to `Requires:` in pkg-config, which makes depending applications link them too
  - document that requirement… somewhere?
  - to deal with overlinking, we need `-L-Wl,--as-needed` — I wonder if putting that in the pkg-config flags too is reasonable or [not](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)
    - `gmodule-1.0` brings `-Wl,--export-dynamic` via pkg-config, sooo…
- but… can LDC do something smart about this? When inlining, analyze the dependencies of the inlined code?
  - when building an object file, LDC is not yet aware of the flags the program will be linked with :(

**Comment by kinke** [comment]
I doubt this is LDC-specific; there's no inlining AFAICT from your snippet, just a template instantiation (`ObjectG.opCast(T)`), so IMO this ought to be handled by `GtkD`. As to how, a `pragma(lib, <C lib>)` might do the trick.

**Comment by myfreeweb** [comment]
> pragma(lib, <C lib>)

oh, interesting! Thanks, I'll definitely try adding that to the generator :)
