### ISSUE TITLE
Add PowerPC64 support for FreeBSD

### ISSUE THREAD

**Issue by lenoil98** [ldc-developers/ldc#3112]
Is there any interest into adding support for FreeBSD/PowerPC64?  I’ve been working on developing patches for PowerPC64 but haven’t been completely successful. Most of the tests fail with SegFault.  I would appreciate any advice or help.

Thanks in advance!

**Comment by redstar** [comment]
Yes, I am interested in this! Which LLVM version do you use? On Linux/PPC64, LLVM 4 does work and most of the test cases pass. With later LLVM versions most of the test cases crash. I did not yet find out what's wrong there. I suspect an LLVM regression with structs, but I am not sure about this.

**Comment by lenoil98** [comment]
Primarily I’m use LLVM 4. I’ve had some limited success with LLVM 6.  

While the compiler (LDC2) is working, the issue I’m encountering seems to be with the runtime (druntime).  I say this because segfaults occur when running apps that have been compiled with the compiler.

**Comment by myfreeweb** [comment]
- if you're on 12 or CURRENT, make sure your druntime is up to date for the 64-bit inode thing. Recently, my patch for using versioned symbols https://github.com/dlang/druntime/pull/2668 was merged, make sure you have it. (Before, there was a local patch in Ports that migrated to the new structs)
- you might be interested in patches for using `libexecinfo` for backtraces, instead of the arch-specific custom unwinder: #3108
- are you working with the new openpower ELFv2 ABI or the old one?

**Comment by lenoil98** [comment]
Thanks! 

I'm still using 11 as my development platform.  Version 12 isn't quite stable on the older ELFv1 ABI hardware (Apple PM G5) that I'm using.

I'm using the  llvmasm  work-around someone had added for using in execinfo.d. Will give the new patches a try.

I'm not a professional programmer and don't know if I did things properly.  I add PPC specific  code in core/sys/freebsd/sys/elf_common.d and core/sys/posix/ucontext.d.  I'm going to fork dlang/druntime and apply the patches I've developed, in hopes someone can double check my work.

**Comment by myfreeweb** [comment]
> llvmasm work-around someone had added for using in execinfo.d

I did that for AArch64 :) before realizing that it's silly and GDC already successfully uses libexecinfo exclusively on FreeBSD, so LDC should do the same.

> I added PPC specific code in core/sys/freebsd/sys/elf_common.d and core/sys/posix/ucontext.d

I've had to touch `src/core/sys/posix/setjmp.d` (https://github.com/dlang/druntime/pull/2269)

**Comment by lenoil98** [comment]
@redstar  You added PPC/PPC64 specific clauses in rt.sections_elf_shared.d for TLS.  But these seem to be specific for Linux on PPC.  FreeBSD uses __tls_get_addr versus __tls_get_addr_opt.
What if we change this to:
    version(linux)
        version(PPC)
        {
            extern(C) void* __tls_get_addr_opt(tls_index* ti);
            alias __tls_get_addr = __tls_get_addr_opt;
        }
        version(PPC64)
        {
            extern(C) void* __tls_get_addr_opt(tls_index* ti);
            alias __tls_get_addr = __tls_get_addr_opt;
        }
    else

**Comment by lenoil98** [comment]
The patches I made have been merged into [(dlang/druntime)](https://github.com/dlang/druntime/pull/2683)

**Comment by lenoil98** [comment]
I've been able to build ldc-1.15 with the changes submitted (see previous comment).  The test results are better than earlier results.  
The the test results are at the link below:

https://drive.google.com/file/d/1A1PhW0592xqIKeI1KbcyUymNxuM_FwmT/view?usp=sharing.

**Comment by lenoil98** [comment]
This issue is OBE.
