### ISSUE TITLE
Output path to ldc2.conf

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3116]
dmd is outputting the path to dmd.conf / sc.ini which becomes handy for IDEs to extract the source code paths to druntime / phobos.

```
> dmd
DMD64 D Compiler v2.086.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright

Documentation: https://dlang.org/
Config file: /etc/dmd.conf
```

I wonder whether want to align here and add the path to ldc2.conf while executing ```ldc2```?

**Comment by kinke** [comment]
Both DMD and LDC output that path as part of `-v`, in one of the first lines starting with `config`.

**Comment by andre2007** [comment]
Thanks that's really great.
