### ISSUE TITLE
openSUSE Leap 15.1: cannot find 'ld'

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3117]
On ```openSUSE Leap 15.1``` (Windows subsystem for linux) I installed ldc2 by extract the Linux archive. Package binutils (ld) and also development basis tools are installed (```sudo zypper install --type pattern devel_basis```).

ld can be found in /usr/bin:
> lrwxrwxrwx 1 root root         20 Apr 27 17:48 ld -> /etc/alternatives/ld

and this is also in $PATH
/opt/ldc2-1.16.0-linux-x86_64/bin/:/home/user/bin:/usr/local/bin:/usr/bin:/bin

also ```which ld``` is working fine.

But ldc2 fails with

> collect2: fatal error: cannot find 'ld'
> compilation terminated.
> Error: /usr/bin/gcc failed with status: 1

What is the issue here?

**Comment by kinke** [comment]
I don't know, but it's not related to LDC - we only invoke gcc, which invokes collect2, and that's the one complaining about not finding the linker.

**Comment by kinke** [comment]
[I might have been a bit too fast here - we default to gold on Linux (`-fuse=gold` in gcc cmdline), that might play a role, although the error msg would be very unclear in that case. You could retry with `-linker=bfd`.]

**Comment by andre2007** [comment]
@kinke you were right. ```ldc2 app.d -linker=bfd``` works.

**Comment by andre2007** [comment]
Installation of package binutils-gold immediately solves the issue.
