### ISSUE TITLE
warning about critical section size in wasm compile

### ISSUE THREAD

**Issue by skoppe** [ldc-developers/ldc#3118]
since ldc 1.16.0 I get this `Warning: Assuming critical section size = 40 bytes` when compiling for WebAssembly.

Dub treats warnings as errors by default, causing builds to fails unless you add allowWarnings (which I don't really want to).

I speculate that in a44c78fb88fdd9559d0f90fb6847b920a0cfd9ef the critical section check is move earlier in compilation, causing it to be evaluated, whereas before it didn't in wasm builds.

**Comment by kinke** [comment]
> I speculate [...]

You're absolutely right. We should return 0 for wasm in `getCriticalSectionSize()`, which then leads to a compilation error as soon as it is really used in `Target.critsecsize()`.

**Comment by kinke** [comment]
Fixed in #3119, thx again.
