### ISSUE TITLE
Support a few core.simd functions

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#3121]
Most of `core.simd` doesn't work with LDC, which is OK (the asm instructions), but some other more general functions can be made available. I mean these 3, `prefetch` `loadUnaligned` `storeUnaligned`. 

How about we simply do a `public import ldc.simd: loadUnaligned, storeUnaligned;` and add a small `prefetch` function that forwards to `ldc.intrinsics.llvm_prefetch`?

**Comment by JohanEngelen** [comment]
Inspired by the extra code needed to get things to work currently like here: https://github.com/dlang/druntime/pull/2687/files#diff-c2fcd73761ae6659ef91245ce1195b6dR70

**Comment by dnadlinger** [comment]
Yep, load/storeUnaligned were modelled after LDC.

**Comment by kinke** [comment]
load/storeUnaligned feature incompatible signatures though: `core.simd` can 1) infer the vector type parameter because 2) it takes a pointer to a vector, whereas `ldc.simd` needs an explicit vector type param and takes a pointer to a vector *element*. I prefer LDC's version, because the vector pointer is expected to be misaligned and so should IMO not be encouraged (and assuming the memory to be at least element-aligned seems reasonable).

**Comment by dnadlinger** [comment]
Ah yes, I forgot about that; iirc there was even a debate about this when it was added upstream. I prefer the LDC version too, unaligned pointers are a good candidate for UB.

**Comment by baziotis** [comment]
I'm interested in solving that. The procedure is to directly do a druntime PR or first in LDC's?

**Comment by kinke** [comment]
Upstream has nothing to do with it; LDC's `core.simd` needs to be slightly extended, that's all.

**Comment by baziotis** [comment]
Ok, I'll make a draft PR.
TBH, it doesn't make much sense for me to not have `version (LDC)` and `version (GDC)` as a high priority in `core.simd`.
I say this humbly as I may be missing something. I mean, in a SIMD library, one would take great care to support optimizing compilers as SIMD is a matter of optimization. But even if it wasn't, why not make the _standard_ library (well, druntime but ok) cross-platform anyway? (besides the work that it's needed).

**Comment by dnadlinger** [comment]
> Upstream has nothing to do with it

We should probably discuss adding signatures which don't require the user to create (arguably) illegal pointers upstream, though.

**Comment by kinke** [comment]
> TBH, it doesn't make much sense for me to not have version (LDC) and version (GNU) as a high priority in core.simd.

Users care about the interface (API), and not where the compiler-specifics reside. Putting these with `version (LDC)` in upstream `core.simd` would create an unwanted dependency from upstream to downstream druntime. So it's better if each compiler tries to fulfill the upstream interface as complete and optimal as it can, in its druntime/Phobos forks. E.g., if upstream `std.math` were to be the union of the current DMD, LDC and GDC versions, it'd probably be 3x as large and very tedious to read. And if we add some new LLVM math intrinsics here downstream, we'd have to make use of them in `std.math` upstream etc.
I just checked upstream druntime v2.087.1, it only contains 5 occurrences of `version (LDC)` (guarding tiny blocks). Here downstream, we are talking about 129 occurrences.

**Comment by dnadlinger** [comment]
Hasn't Iain been pushing in the opposite direction, putting all sorts of version (GNU) code upstream?

**Comment by kinke** [comment]
He did indeed (29 occurrences of `version (GNU)` in upstream druntime), but apparently selectively by some criteria (e.g., `std.math` is GDC-free). Not sure what his goals are, as going all the way and merging all compiler-specific forks with upstream would be ugly in some cases like `std.math`. Maybe he's just trying to reduce the risk of merge conflicts.
The only benefit for the user I can think of would be that one set of druntime/Phobos 'includes' would in theory suffice, but then the compilers are likely to be out-of-sync (DMD at bleeding edge, LDC one version behind, GDC somewhere else), so each compiler probably ships its druntime/Phobos source files anyway. The binary libraries are incompatible across compilers anyway, not just ABI-wise.

**Comment by baziotis** [comment]
> Users care about the interface (API), and not where the compiler-specifics reside. Putting these with `version (LDC)` in upstream `core.simd` would create an unwanted dependency from upstream to downstream druntime. So it's better if each compiler tries to fulfill the upstream interface as complete and optimal as it can, in its druntime/Phobos forks. E.g., if upstream `std.math` were to be the union of the current DMD, LDC and GDC versions, it'd probably be 3x as large and very tedious to read. And if we add some new LLVM math intrinsics here downstream, we'd have to make use of them in `std.math` upstream etc.
> I just checked upstream druntime v2.087.1, it only contains 5 occurrences of `version (LDC)` (guarding tiny blocks). Here downstream, we are talking about 129 occurrences.

I agree with that, yes. Indeed my proposal to add `version` everywhere is not good, although I did not mean to add the implementations but wrappers. However, the important point is as say:
> Users care about the interface (API), and not where the compiler-specifics reside.

Well, it indeed seems better to have specifics in each compiler's fork, but the API I think should be the same. Or have wrappers in each compiler. For example, here: https://github.com/dlang/druntime/pull/2687/files#diff-c2fcd73761ae6659ef91245ce1195b6dR65
I had to create my own wrapper for each of the 3 compilers.
Wouldn't that make sense to be done by the compiler and not the user?

**Comment by p0nce** [comment]
+1 for fixing the signature of loadAligned/storeAligned in DMD's core.simd! the signature in LDC are safer, and it's welcome fix. In the current situation, one cannot use the two functions polymorphically as their signature is different. Also, there doesn't seem to be a way to get T from a __vector(T)

**Comment by baziotis** [comment]
We didn't fix it, meaning, now LDC won't use the LDC signature if one uses `core.simd`'s `loadUnaligned`. The PR above provides wrappers that still use the DMD signature but forward to the `ldc.simd.loadUnaligned` ([code ref](https://github.com/ldc-developers/druntime/pull/163/files#diff-a0dc83445977b54e62e42f13a7a70e3eR675)). We can't really use the LDC signature in `core.simd` as that would not be good for generality (the thing that this issue tries to solve). The goal is to be able to use `loadUnaligned` from `core.simd` the same way no matter if it will be compiled with LDC or DMD.

**Comment by JohanEngelen** [comment]
> We can't really use the LDC signature in `core.simd` as that would not be good for generality (the thing that this issue tries to solve).

What p0nce meant is to change the signatures upstream in `core.simd` to match the current ones in `ldc.simd`.

**Comment by kinke** [comment]
> change the signatures upstream

I don't think that's feasible ad-hoc. Rather, adding our signature too and deprecating the old one, to prevent the breaking change.

**Comment by baziotis** [comment]
Ah, the wording confused me. I understood he meant we're _fixing_ itl. But he meant _to_ fix it. I don't think that will pass in the upstream. :/
