### ISSUE TITLE
pragma(inline, true) still doesn't fully work

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#3126]
a.d:
```D
pragma(inline, true)
void bar() {}
```

main.d:
```D
import a;
void main() { bar(); }
```

`ldc2 -c main.d` and `ldc2 -c -singleobj main.d a.d` - fine, `bar` call is inlined.

`ldc2 -c main.d a.d` (2 object files): `bar` is fwd-declared as `alwaysinline` in the `main` object file/IR module, but not emitted, and so not inlined.

**Comment by kinke** [comment]
This probably means that all these little `pragma(inline, true)` wrappers in druntime and Phobos are not cross-module inlined into other modules of the same druntime/Phobos library, as we build each library in a single cmdline by default...

**Comment by s-ludwig** [comment]
https://www.bountysource.com/issues/78459349-pragma-inline-true-still-doesn-t-fully-work

**Comment by CrazyPython** [comment]
@s-ludwig Does this mean that when multiple filenames (not multiple are passed to ldc2, you want things to be inlined across modules? 

I presume in the command `ldc2 -c main.d a.o`, where `a.o` is an object file, you are not requesting inlining be implemented.

**Comment by s-ludwig** [comment]
The particular case that I stumbled upon is when there are templated functions in `lib1.a` and those are used in `lib2.a`. In our case, `lib1.a` for example contains a small vector type and some performance critical math functions. We had issues with LTO, so compiling everything at once was the only solution, but that only worked on Windows. I'd have to check with the latest version whether this still applies.

**Comment by CrazyPython** [comment]
@s-ludwig Did `-cross-module-inlining` change anything?

**Comment by s-ludwig** [comment]
I'm pretty sure it didn't, but I'd have to recheck.

**Comment by CrazyPython** [comment]
Do you know if GDC (now GCC 10+) has this issue with not inlining functions between template instantiations across static libraries??

**Comment by s-ludwig** [comment]
Unfortunately I can't tell, because most of the code requires a newer frontend version.

**Comment by kinke** [comment]
Fixed by #3442. A beta2 is coming up, looking forward to some 3rd party testing! :)

**Comment by s-ludwig** [comment]
@kinke: That fixed our cases, thanks a lot! I do need an explicit `pragma(inline, true)` for several functions that should already be inlined by default, but I couldn't reproduce that in stripped down code so far.

**Comment by kinke** [comment]
Great, thx for testing.

> several functions that should already be inlined by default

Are you sure they are emitted in the same object file as the non-inlined calls, or do you use `-enable-cross-module-inlining`? In case they are templates, you probably already know that the compiler tries to codegen them only if it can't prove they are instantiated in non-root modules, and if it does codegen, it tries to emit them into a single root module.
