### ISSUE TITLE
Running compiled apps broken on fresh Windows 10 install without VC++ runtime

### ISSUE THREAD

**Issue by WebFreak001** [ldc-developers/ldc#3136]
I have downloaded the multilib archive of LDC 1.16.0 into a fresh Windows 10 VM without anything installed except VSCode and 7zip and extracted the contents to an unconventional location (Downloads folder) as some new users might do. I have then added the bin folder to the PATH variable and ldc2 is found and can be run.

Now when trying to compile some simple file like
```d
import std.stdio;

void main()
{
    writeln("hello world");
}
```
using
```
ldc2 test.d
```

it seems to run fine without any errors (LDC doesn't return any error) but when trying to run the resulting executable There seems to be some error running it:
```
PS C:\Users\webfreak\Downloads> ldc2 .\test.d
PS C:\Users\webfreak\Downloads> .\test.exe
PS C:\Users\webfreak\Downloads> echo $LASTEXITCODE
-1073741515
```

I found this because rdmd wasn't behaving properly and kept crashing with that error when trying to run the resulting executable. There should probably be some linking error or something like that instead of resulting in an invalid executable and then (silently, only with error code) failing to run it.

I would assume installing VC++ Build Tools would fix this, however there are users who want fully portable installations and only try out D. (The README in the download already says it ships with all dependencies so I assume it's a bug right now)

Tried (and failing) with ldc2-1.16.0-windows-x64 and ldc2-1.16.0-windows-multilib

**Comment by WebFreak001** [comment]
I think the issue is a missing VC++ runtime, but the VM is crashing too much now to verify so I kind of given up on finishing testing. It did work without recompiling after installing the VC++ Build Tools, but I wanted to try it on another instance without build tools then too

**Comment by kinke** [comment]
> I think the issue is a missing VC++ runtime

Yeah I think so too, and that should be covered by the README. IIRC, you don't get the usual Windows popup (`DLL not found`) when launching the console app in the console, but get it when double-clicking the executable in Windows Explorer, or something like that.

**Comment by kinke** [comment]
What do you expect to be fixed?

> The README in the download already says it ships with all dependencies so I assume it's a bug right now

I don't know where you found that; [it](https://github.com/ldc-developers/ldc/blob/master/packaging/README.txt) (IMO, clearly) states:

> In order to run the generated binaries, a Visual C++ 2015 runtime installation is required (vcruntime140.dll, ucrtbase.dll etc.).

**Comment by WebFreak001** [comment]
ah sorry guess this can be closed now
