### ISSUE TITLE
Windows: No default DllMain in MinGW-based libs

### ISSUE THREAD

**Issue by Teashrock** [ldc-developers/ldc#3142]
LDC 1.16.0 Multilib, Windows 10 x64

1. Set "betterC" and "dynamicLibrary" options.
2. Compiled with dmd -- got success.
3. Tried to compile with LDC -- got below:
![image](https://i.imgur.com/Yslz7GH.png)

**Comment by kinke** [comment]
Please specify the signature of your `DllMain` entry point.

**Comment by Teashrock** [comment]
How can I do it? And why is this necessary with LDC, but not with DMD?

**Comment by kinke** [comment]
You mean you don't have one? - There's no default `DllMain` in our MinGW-based libs, the libs used when you don't use the Microsoft toolchain (see README.txt).

**Comment by kinke** [comment]
A no-op DllMain looks like this:
```D
import core.sys.windows.windows;

extern(Windows) BOOL DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    return TRUE;
}
```

**Comment by Teashrock** [comment]
Thank you for advice, it's all worked. But i think, it will be good to add this advice to an error itself. Don't you think?
