### ISSUE TITLE
library flags handled differently to dmd causes significant ugliness

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#3145]
The escaping of quotes (necessary to handle paths with spaces in) seems to be handled differently by ldc and dmd, leading to disgustingness like this: https://github.com/ariovistus/pyd/pull/120 infecting our codebase.

**Comment by kinke** [comment]
And so you thought DMD's way is the correct one and that an LDC issue is the way forward? :] - DMD uses some totally unorthodox parsing, that's the reason LDC cannot even be built with a DMD host compiler on Windows. There's absolutely nothing special about our cmdline and we use LLVM facilities. On Windows, an argument with spaces needs to be enclosed in quotes (`"-LC:\My Libs"`), whereas for DMD, it needs to be something like `-L"C:\My Libs"` IIRC.

**Comment by kinke** [comment]
Oh, IIRC, DMD's strange behavior was considered a feature - being able to specify multiple paths at once, separated with a space: `-L"C:\My Libs" otherDir otherDir2`...

**Comment by kinke** [comment]
dub might not handle the linker flags correctly either; `"lflags-windows-x86_64-ldc": [ "\"\"/LIBPATH:C:\\My Libs\"\"" ]` is definitely ugly and should be a simple `...: [ "/LIBPATH:C:\\My Libs" ]`. I'll look into that sometime.

**Comment by kinke** [comment]
Some more findings:

* LDC args `-L""/LIBPATH:C:\My Libs""` and `-L"/LIBPATH:C:\My Libs"` are parsed by LLVM as `-L/LIBPATH:C:\My Libs`, so it apparently just strips all unescaped quotes.
* LDC arg `-L\"/LIBPATH:C:\My Libs\"` (DMD-style) is parsed as `-L"/LIBPATH:C:\My Libs"`, and the linker doesn't like a quoted raw arg `"/LIBPATH:C:\My Libs"`.

**Comment by kinke** [comment]
I'm going to close this as won't-fix and propose to let dub handle this, i.e., dub taking care of DMD's unorthodox `-L` handling - no more `"lflags": [ "\\\"/LIBPATH:foo bar\\\"" ]` dub.json madness.

**Comment by kinke** [comment]
=> https://github.com/dlang/dub/pull/1779

**Comment by kinke** [comment]
It's an outright DMD bug, handled correctly on Posix, but wrongly on Windows: https://issues.dlang.org/show_bug.cgi?id=16677
