### ISSUE TITLE
Link failure with `-dip1000` in release builds, Android/Termux

### ISSUE THREAD

**Issue by kettes-leulhetsz** [ldc-developers/ldc#3147]
Minimal test case [here](https://github.com/kettes-leulhetsz/ldc-termux-bug/tree/master/dip1000-linkfail).

Happens in release builds, not in debug or unittest. Other flags seem to have no effect on it.

(Apologies for the previous one, someone put the submit button right next to backspace...)

**Comment by kinke** [comment]
Which LDC version are you using? I don't think this is Android (or LDC) specific, so it may have been fixed already in case you are using the v1.13 or whatever the latest Termux package version is.

**Comment by kettes-leulhetsz** [comment]
This is termux-latest:

LDC - the LLVM D compiler (1.13.0):
  based on DMD v2.083.1 and LLVM 7.0.1
  built with LDC - the LLVM D compiler (1.13.0)
  Default target: aarch64--linux-android
  Host CPU: cortex-a53
  http://dlang.org - http://wiki.dlang.org/LDC

**Comment by kinke** [comment]
Were you able to resolve it? I'm currently trying to upgrade the Termux package (https://github.com/termux/termux-packages/pull/4246).

**Comment by kettes-leulhetsz** [comment]
Oh, wow! I put this project on hold because I've had way too many separate unrelated issues with pretty much every single dependency I've added. ldc, dub, dstep, dpp, automem, cmake-d, you name it.

I'd be happy to act as a Termux tester, as long as I don't have to build the binaries myself. Tried the aarch64 binaries, but they're not built for me. patchelf'd for Termux, but Android also requires `-fPIE`. Can we set up a testing repo?

**Comment by kettes-leulhetsz** [comment]
Alternatively, I might be able to build ldc-termux natively, but llvm is also broken (missing libraries) and I couldn't build it.

**Comment by kinke** [comment]
That PR has been merged, but I have no idea when the package will be available.

As for proper CI testing on Android, I've been kind of disillusioned wrt. required work. The Termux CI is nice, as they provide environments to cross-compile a project (in our case, our patched LLVM + LDC) for all 4 Android architectures, on a regular Linux x86 host AFAICT. We'd need something like that for our LLVM and LDC repos, and on top of that, set everything up for actually running the testsuite in an emulator...

**Comment by kettes-leulhetsz** [comment]
`-dip1000` is fixed.

**Comment by kinke** [comment]
So the new package is already available & working?
