### ISSUE TITLE
LDC: predefined version for "nogc" option

### ISSUE THREAD

**Issue by zelyony** [ldc-developers/ldc#3150]
LDC supports command option:
-nogc = Do not allow code that generates implicit garbage collector calls.

but I cannot find corresponding predefined version in https://dlang.org/spec/version.html#predefined-versions

need to add version LDC_nogc or D_nogc.
the one should be enabled for -betterC too.

**Comment by ZombineDev** [comment]
For [`-betterC`](https://dlang.org/spec/betterc.html), LDC is already defining `D_BetterC`, and *not* defining the more fine-grained versions: `D_Exceptions`, `D_ModuleInfo`, `D_TypeInfo`:

* https://run.dlang.io/gist/run-dlang/a6de0b247b02d6fd59eba340da9ffc17?compiler=ldc&args=-betterC
* https://run.dlang.io/gist/run-dlang/a6de0b247b02d6fd59eba340da9ffc17?compiler=ldc

**Comment by zelyony** [comment]
> For [`-betterC`](https://dlang.org/spec/betterc.html), LDC is already defining `D_BetterC`, and _not_ defining the more fine-grained versions: `D_Exceptions`, `D_ModuleInfo`, `D_TypeInfo`. Compare:

I know about "betterC" and its not same as "nogc".
and this 3 versions - Exceptions, ModuleInfo, TypeInfo - tells nothing about GC enabled or not.
when option "nogc" is enabled (and "betterC" disabled, not set) "Exceptions, ModuleInfo, TypeInfo" are shown too, but code cannot use GC. so, I asking some version for "nogc" option too.

**Comment by JohanEngelen** [comment]
Note: the specific name of this nogc-version should be aligned with DMD and GDC.

**Comment by kinke** [comment]
AFAIK, DMD doesn't have such a switch, gdc - no idea. So if DMD wants to adopt it (by detecting these calls in the front-end, not during codegen as we do IIRC), a predefined version may make sense. In the meantime, one can define his/her own version to be coupled with the `-nogc` compile option.

**Comment by zelyony** [comment]
> AFAIK, DMD doesn't have such a switch, gdc - no idea. So if DMD wants to adopt it (by detecting these calls in the front-end, not during codegen as we do IIRC), a predefined version may make sense. In the meantime, one can define his/her own version to be coupled with the `-nogc` compile option.

https://forum.dlang.org/post/rfewyhojfezdtvzoaajr@forum.dlang.org
maybe need another __traits( rtcompiles, ...) to take into account current options/conditions?

**Comment by kinke** [comment]
> __traits( rtcompiles, ...) 

If the calls were detected in the frontend and not during codegen, `__traits(compiles, ...)` would work.

What I meant was: just use a `-d-version=NoGC` or so for now when compiling with `-nogc` (dub config or whatever).

**Comment by dnadlinger** [comment]
I don't think we should support this switch any more/further, precisely because backend error messages break D's conditional compilation model. `-nogc` simply predates `@nogc`, which is the way to go now.

**Comment by zelyony** [comment]
ok. closing now.
LDC -nogc: deprecated.
workaround: -d-version=NoGC
rtcompiles: offtopic (issue for whole D)
