### ISSUE TITLE
Declarations of the same C struct conflict when imported.

### ISSUE THREAD

**Issue by kettes-leulhetsz** [ldc-developers/ldc#3155]
ldc 1.17.0, Android/Termux.

libarchive comes in two public header files: `archive.h` and `archive_entry.h`.

Both headers declare `struct archive;` and `struct archive_entry;`, faithfully
reproduced by dstep. Trying to import both yields a conflict immediately:

```
[  6%] Building D object CMakeFiles/wng.dir/src/wngbase/libarchive.o
/data/data/com.termux/files/home/weidu-ng/src/wngbase/libarchive.d(27): Error: `archive_h.archive` at /data/data/com.termux/files/home/weidu-ng/src/wngbase/binding/archive_h.d(122) conflicts with `archive_entry_h.archive` at /data/data/com.termux/files/home/weidu-ng/src/wngbase/binding/archive_entry_h.d(92)
/data/data/com.termux/files/home/weidu-ng/src/wngbase/libarchive.d(28): Error: `archive_h.archive_entry` at /data/data/com.termux/files/home/weidu-ng/src/wngbase/binding/archive_h.d(123) conflicts with `archive_entry_h.archive_entry` at /data/data/com.termux/files/home/weidu-ng/src/wngbase/binding/archive_entry_h.d(93)
```

Annoying, but alias can deal with it. The problem comes in actually using them. Annotated for clarity:

```D
int archive_read_next_header(archive_h.archive*, archive_h.archive_entry**);

const(char)* archive_entry_pathname_utf8(archive_entry_h.archive_entry*);
```

(I'm guessing this is the correct place to report this since this is a notable improvement from ldc 1.13, which didn't even understand pointer-to-opaque.)

**Comment by dnadlinger** [comment]
Could you provide a short test case that doesn't work on LDC, but works on the equivalent DMD version? I'm not sure I understand what the issue is here.

Generally, types defined in two modules are distinct in D, even if they share the same name, so some errors like that are expected (on DMD just the same as on LDC). The solution is to fix the binding generator not to emit forward declarations in a way not compatible with the D module system.

**Comment by kettes-leulhetsz** [comment]
The types are *declared*, not defined. A pointer to `extern(C) foo` is a pointer to `extern(C) foo`, no matter where or how many times you say it. There is no conflict.

The net result is that you explicitly have to cast a pointer to itself to satisfy a rule aimed at fixing the C++ overload madness. I do not think this is consistent with the spirit of [Interfacing to C](https://dlang.org/spec/interfaceToC.html).

**Comment by kinke** [comment]
I have nothing to add to what David said. If you find D could do better, then this shouldn't be discussed here.

**Comment by kettes-leulhetsz** [comment]
I will find a more appropriate place then. My apologies.

**Comment by dnadlinger** [comment]
> A pointer to extern(C) foo is a pointer to extern(C) foo, no matter where or how many times you say it. […] The net result is that you explicitly have to cast a pointer to itself

Just to clarify – we should indeed continue this discussion elsewhere –, this seems to be based on a misunderstanding of how the D type system works. `extern(C)` linkage doesn't change the fact that `module_a.foo` and `module_b.foo` are different types; it just affects name mangling (and, on some targets, other aspects of the ABI).
