### ISSUE TITLE
ICE on casting shared associative-array struct member

### ISSUE THREAD

**Issue by rracariu** [ldc-developers/ldc#3162]
The following will crash LDC, seems to bee an old bug as testing on http://godbolt.org shows it gets back to the beginnings of LDC.

DMD will compile the code.

```bug.d
struct Ref
{
    string val;
}

struct Token
{
    shared Ref r;
}

shared struct Queue
{
   shared Token[Ref] map; 
}

void main()
{
    auto queue = shared Queue();
    (cast(Token[Ref]) queue.map)[Ref("aaa")] = Token(Ref("bbb"));
}
```
Removing `cast(Token[Ref])` fixes the issue.

**Comment by JohanEngelen** [comment]
Simplified test case:
```d
shared struct Queue
{
    int[int] map; 
}

void main()
{
    auto queue = Queue();
    ( cast(int[int]) queue.map )[1] = 1;
}
```

**Comment by kinke** [comment]
We apparently need to switch to a reinterpret-cast when casting an AA lvalue (void**) to another AA type (void**) - we currently cast it to another AA rvalue (void*), so that it can't be updated when inserting elements by indexing (via druntime's `_aaGetY()`).
