### ISSUE TITLE
1.18-beta1 ldc-build-runtime fails for Android

### ISSUE THREAD

**Issue by puneet** [ldc-developers/ldc#3165]
While trying to build runtime for Android using command:

$ ldc-build-runtime --targetPreset=Android-aarch64 --buildDir=droid64

I get:

core/runtime.d(828): Error: undefined identifier `backtrace`

**Comment by kinke** [comment]
I've fixed this recently in https://github.com/dlang/druntime/pull/2796. [It's already in our `ldc` branch of druntime.]
