### ISSUE TITLE
How would you do that? Linking statically to Phobos/Druntime in a -shared library

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3168]
Hello,

So we build shared libraries with `-shared`. 

By an improbably succession of events, we'd rather link with `libphobos2-ldc.a` and `libdruntime-ldc.a` than `libphobos2-ldc-shared.so` and `libdruntime-ldc-shared.so`. 

(Yes this is on Linux and we do know the code won't all be -fPIC)

The reason we do this is that we need the `TypeInfo` and classes stuff. 
The other problem is when using a newer LDC, the end user may not be able to install the right `libphobos-dev` package, it seems the last one for Ubuntu is 2.078.

But:
- the `-shared` flags always append `-shared` to the lib filename which doesn't allow us to override those files
- `-link-defaultlib-shared` exists but not `-link-defaultlib-static`
- `-static` also wants the C runtime to be statically linked, but this isn't what we want, we'd rather just have Phobos and Druntime be statically linked

It turns out we can do it with DMD (with `-defaultlib=libphobos2`) and that works for our use case. **How would you do that with LDC?**

**Comment by kinke** [comment]
`-link-defaultlib-shared=false`.

**Comment by p0nce** [comment]
Thanks!
