### ISSUE TITLE
Issue with Dub in Termux

### ISSUE THREAD

**Issue by IdkGoodName** [ldc-developers/ldc#3170]
Since it's old issue, unnoticed and never fixed, I am posting issue here: https://github.com/termux/termux-packages/issues/4189

Dub hangs in Android 5.0.x in Termux, forever without any response.

**Comment by kettes-leulhetsz** [comment]
After a month of banging my head against Termux, I've come to the conclusion it's a lost cause. Nothing works, period. My latest batch of failure includes `cmake-d` somehow losing the `-of` prefix.

If you can't even trust string concatenation to work correctly, there's no point trying anything else.

My current best guess is called gentoo-arm64-musl-vanilla-20190908. `proot` works, at least, and there are several well-supported distros available at [AnLinux](https://play.google.com/store/apps/details?id=exa.lnx.a) and [UserLAnd](https://play.google.com/store/apps/details?id=tech.ula).

For my use case, I've relaxed my requirement that natively building the program should be easy for users. A Gentoo overlay will be enough for both of them for now. Static executables seems to be the only reasonable way to target Termux.

**Comment by kinke** [comment]
#3164 adds an official prebuilt Android armv7a package (API level 21), incl. dub. It's only cross-compiled and -linked for now, no tests whatsoever are run on Android. `libc++` is linked statically. Of course it still needs a C compiler and libs for linking. Tests/contributions are highly welcome; the .tar.xz archive can be downloaded as Azure artifact (https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=731, click on the top-right burger button -> Artifacts -> ...).

**Comment by PetarKirov** [comment]
Using Dub from the [1.22.0-beta2](https://github.com/ldc-developers/ldc/releases/download/v1.22.0-beta2/ldc2-1.22.0-beta2-android-aarch64.tar.xz) archive I ran dub's test suite and I got these results:
https://gist.github.com/PetarKirov/a66dfc56faf3c9e0cceb357853615f31
