### ISSUE TITLE
Shipping static runtime with -fPIC?

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3185]
On all OSes we ship dynamic libraries with static runtimes (for redistribution ease to end users) and think maybe we could enable (`Runtime.initialize`) that D runtime back. 
- It's possible on Windows
- and on macOS since everything is built with -fPIC there
- but not on Linux

I don't think I understand all consequences of this, but **would it be possible to ship Phobos and LDC built with -fPIC on Linux, as in the macOS target?** This would allow to use parts of the runtime in D shared libraries.

**Comment by dnadlinger** [comment]
I haven't checked, but isn't everything built with `-relocation-model=pic` by default anyway? Ubuntu and other distros have started defaulting to position-independent code for ASLR/… purposes a few years back.

There might potentially be some trouble with TLS lookup, though. (We can't use `__tls_get_addr` in the non-shared druntime binaries, as we want to support completely static binaries.)

**Comment by p0nce** [comment]
Interesting. We'll try and see.
In this case, that issue has no meaning left.
