### ISSUE TITLE
CMake swallows -Xlinker option from dmd.conf

### ISSUE THREAD

**Issue by mleise** [ldc-developers/ldc#3216]
In my `dmd.conf` I have:
```
[Environment]
DFLAGS=-I/usr/lib/dmd/2.087/import -L--export-dynamic -defaultlib=phobos2 -fPIC
[Environment32]
DFLAGS=%DFLAGS% -L-L/usr/lib/dmd/2.087/lib32 -L-rpath -L/usr/lib/dmd/2.087/lib32
[Environment64]
DFLAGS=%DFLAGS% -L-L/usr/lib/dmd/2.087/lib64 -L-rpath -L/usr/lib/dmd/2.087/lib64
```
That results in the following dmd linker line:
```
cc <name>.o -o <name> -m64 -Xlinker --export-dynamic -Xlinker -rpath -Xlinker /usr/lib/dmd/2.089/lib64 -L/usr/lib/dmd/2.089/lib64 -lphobos2 -lpthread -lm -lrt -ldl
```
As of ldc2 1.18.0 the CMake process outputs the following and swallows the library search path, thinking it is meant to be a library:
```
WARNING: Target "ldmd2" requests linking to directory "/usr/lib/dmd/2.087/lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ldc2-unittest" requests linking to directory "/usr/lib/dmd/2.087/lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ldc2" requests linking to directory "/usr/lib/dmd/2.087/lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ldc-build-runtime" requests linking to directory "/usr/lib/dmd/2.087/lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ldc-prune-cache" requests linking to directory "/usr/lib/dmd/2.087/lib64".  Targets may link only to libraries.  CMake is dropping the item.
```
As a result the build of these targets fails to locate `-lphobos2`:
```
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++  -march=native -O3 -pipe -fomit-frame-pointer -ffunction-sections -fdata-sections -Wl,-O1 -Wl,--as-needed -Wl,--sort-common -Wl,-z,relro -Wl,--gc-sections -Wl,--icf=safe -DDMDV2 -DHAVE_SC_ARG_MAX  -L-O1 -L--as-needed -L--sort-common -L-z -Lrelro -L--gc-sections -L--icf=safe    -rdynamic obj/ldmd2.o  -o bin/ldmd2  lib64/libldmd.a -lLLVMWindowsManifest -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMLibDriver -lLLVMOption -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMAsmParser -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMX86Desc -lLLVMObject -lLLVMMCParser -lLLVMBitReader -lLLVMCore -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBinaryFormat -lLLVMX86Utils -lLLVMSupport -lLLVMDemangle -L/usr/lib/llvm/8/lib64 -Wl,--export-dynamic -m64 -Xlinker --export-dynamic -Xlinker -rpath -Xlinker -L/usr/lib/dmd/2.087/lib64 -lphobos2 -lpthread -lm -lrt -ldl && :
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: cannot find -lphobos2
```
This occurred while attempting to version bump the ldc2 ebuild on Gentoo. Please advise.

**Comment by kinke** [comment]
What does your LDC CMake output list as 'D compiler linker flags'?
```
-- Host D compiler linker program: /usr/bin/cc
-- Host D compiler linker flags: -fuse-ld=gold;-Xlinker;--no-warn-search-mismatch;-L/home/vsts/work/1/host-ldc/bin/../lib;-L/home/vsts/work/1/host-ldc/bin/../lib32;-lphobos2-ldc;-ldruntime-ldc;-Wl,--gc-sections;-lrt;-ldl;-lpthread;-lm;-m64
```

Btw, are you using DMD as D host compiler for the LDC Gentoo package? That would obviously reduce the LDC performance and is definitely not recommended.

**Comment by kinke** [comment]
[As DMD apparently doesn't support `-L-Wl,-rpath,...`, you might want to try `-L-rpath=...` which IIRC works on Linux.]

**Comment by kinke** [comment]
To elaborate: LDC 1.18 switched from manually invoking the C(++) compiler as linker driver to regular C(++) CMake executable targets, adding the linker flags via [target_link_libraries()](https://cmake.org/cmake/help/v3.0/command/target_link_libraries.html). So linker driver options not starting with a dash, like your rpath value (`-Xlinker -rpath -Xlinker problematicValue`), are problematic.

[The reason for this switch was to simplify cross-compiling/linking LDC itself by relying on CMake cross-compiling facilities.]

**Comment by mleise** [comment]
To answer your questions, the `Host D compiler linker flags` were correctly determined by LDC, it was indeed CMake swallowing the argument. The ebuilds can all be compiled with any compatible host compiler, that's why I was routinely testing DMD.
I'll see if `rpath=...` by itself works. That should consolidate the 2 arguments into one and work around CMake's "feature".

**Comment by mleise** [comment]
Say I would like to suppress the linker flag `-flto=safe` for all linking of objects compiled by the D host compiler, would there be a variable to set? DMD compiled objects don't work well with gold's LTO options and the linker fails in get_section_contents. But C++ binaries could still be linked with LTO, so if there is already a less blunt method than to globally override LDFLAGS I'd use that first.

**Comment by kinke** [comment]
The host compiler compiles parts of ldc2, ldmd2 and some utils. The only pure C++ binaries, AFAIK, are `ldc-jit-rt.so` and 2 LLVM tools (`FileCheck` and `not`), so most likely it's not worth the effort to go with LTO with DMD.
