### ISSUE TITLE
Inline assembly on AVR target taking in registers produces invalid bitcast

### ISSUE THREAD

**Issue by WebFreak001** [ldc-developers/ldc#3217]
assuming this function on `-mtriple=avr`:
```d
// delay `count` cycles through a simple loop
pragma(inline, true) void loop8(ubyte count) @naked
{
	import ldc.llvmasm : __asm;

	__asm(`
		1: dec $0
		brne 1b
	`, "r", count);
}
```

I think that should work because I found similar code [here](https://github.com/outlandkarasu-sandbox/pidos/blob/master/pidos/kernel.d#L38) which does something like this too.

however this throws:
```
Invalid bitcast
  %1 = bitcast i8 %count_arg to i8*
in function _D3avr4util5delay5loop8FhZv
LLVM ERROR: Broken function found, compilation aborted!
```

The same issue happens when trying to use "=r,r" and "+r" too.

Maybe this is just a calling error though. I tried to pass `"=r"` as constraint first because the register containing count is modified to 0, however this gave me a hardly useful error "__asm constraint argument is invalid"

The same issue happens when using ushort, "w" as constraint and the sbiw instruction.

**Comment by kinke** [comment]
Have you tried this without `@naked`? Using that attribute for a function with parameters is tricky, as the prologue is skipped (e.g., params not dumped to stack), so the params should not be accessed directly like this in `@naked` functions (rather, in assembly instead, but then it must not be inlined...). `@naked` usually shouldn't be used in the hopes of increasing performance.

**Comment by WebFreak001** [comment]
ok removing naked at least made it compile, but the optimizer now generates invalid code because it doesn't notice that the register is modified after that instruction.

With `"=r"` and `"=&r"` it says "constraint argument is invalid" but that feels like the most correct thing here probably? `"+r"` also didn't seem to change it. But I'm pretty much just throwing in random syntax from the llvm docs in hopes to make it work right now.

(this is how it looks like for multiple calls:)
```
  8c:   8f ef           ldi     r24, 0xFF       ; 255
...
  94:   8a 95           dec     r24 ; <-- first one works properly
  96:   f1 f7           brne    .-4             ; 0x94 <LBB0_1+0x2>
  98:   8a 95           dec     r24 ; <-- is 0 here and doesn't initialize back to my passed argument
  9a:   f1 f7           brne    .-4             ; 0x98 <LBB0_1+0x6>
  9c:   8a 95           dec     r24
  9e:   f1 f7           brne    .-4             ; 0x9c <LBB0_1+0xa>
...
```

**Comment by WebFreak001** [comment]
alright not exactly sure how it works but I fixed it now and removing the `@naked` fixed the issue why I opened this

```
void loop8(ubyte count)
{
	import ldc.llvmasm : __asm;

	cast (void) __asm!ubyte(`
		1: dec $0
		brne 1b
	`, "=r,0", count);
}
```

**Comment by kinke** [comment]
I was just about to propose `=r,0`. ;)
