### ISSUE TITLE
ldc 1.18.0 fail to run `io` unittest

### ISSUE THREAD

**Issue by bioinfornatics** [ldc-developers/ldc#3219]
Dear,
ldc  core dump while running `io` unittest [CI log](https://travis-ci.org/MartinNowak/io/jobs/608874665?utm_medium=notification&utm_source=github_status)

unittest success with dmd-2.088.1 while ldc fail. 
full history, is readable here: https://github.com/MartinNowak/io/pull/28

thanks

**Comment by kinke** [comment]
https://github.com/MartinNowak/io/pull/30
