### ISSUE TITLE
The -gcc option should be documented

### ISSUE THREAD

**Issue by ErnyTech** [ldc-developers/ldc#3229]
Currently there is the "-gcc" option which allows you to change the C compiler to be used, unfortunately this option is not present in the LDC guide (https://wiki.dlang.org/Using_LDC) or even by executing "ldc2 -h ".

I use this option despite the lack of documentation in some of my projects where I need to choose to use avr-gcc directly in ldc2.conf in order to simplify the commands to type to compile my project that targets an AVR MCU.

It would be nice to add the option in the documentation or to clarify whether it should be considered experimental/without guarantees regarding its removal over time.

**Comment by kinke** [comment]
It is documented in master/v1.19. The `Using LDC` Wiki page is quite obviously outdated and IMO utterly pointless.

**Comment by ErnyTech** [comment]
I'm glad to hear this, so can I consider "-gcc" stable?

**Comment by kinke** [comment]
Yes; it's mentioned in the Wiki for a while and in the 1.19 release notes as well.
