### ISSUE TITLE
Debug configuration and release configuration result are different

### ISSUE THREAD

**Issue by loqix** [ldc-developers/ldc#3237]
```
	auto a = 1.203125f;
	auto zz =  cast(ubyte)(a * 255.0f);
```

debug zz = 50
release  zz = 0

**Comment by kinke** [comment]
It's exactly the same with clang; gcc returns 255 with `-O`, so I guess this is undefined behavior. https://d.godbolt.org/z/NaVKNF

**Comment by JohanEngelen** [comment]
the truncated float value is outside `ubyte` range of values, so UB in C++: https://stackoverflow.com/questions/48548598/what-float-values-could-not-be-converted-to-int-without-undefined-behavior-c
