### ISSUE TITLE
Needs LDC 1.19.0-beta2 or release because of regression fix since 1.16

### ISSUE THREAD

**Issue by 9il** [ldc-developers/ldc#3238]
https://d.godbolt.org/z/XER-DN

```d
extern(C++):
struct C
{
}

// _Z3fooRK1CS0_ wrong in 1.18, 1.19 beta1
// _Z3fooRK1CS1_ correct in 1.16 and master CI 
// according to https://d.godbolt.org/
void foo(ref const C, ref const C)
{

}
```
Please )

**Comment by kinke** [comment]
That's https://github.com/dlang/dmd/pull/10527 which unfortunately didn't make it into DMD 2.089.0 (after the original regression fix targeting the wrong branch). This alone is not enough reason for me to put out a new beta; DMD v2.089.1 will probably take 2 more weeks and that's when LDC 1.19 final is to be expected.

**Comment by 9il** [comment]
looking forward

**Comment by kinke** [comment]
[There might be a beta this weekend, I've been working on other things that would benefit from additional testing.]

**Comment by 9il** [comment]
It would be awesome, I can test it in a huge codebase with few targets.
