### ISSUE TITLE
Support LLD's new dependant-libraries feature via pragma(lib)

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#3245]
LLD 9 introduces support for library dependencies embedded in ELF object files, see https://reviews.llvm.org/rL360984, by listing the library names in a special `.deplibs` section. Not sure if it's really as useful as for Windows, where the embedded linker directives firstly aren't restricted to library names, but are arbitrary linker cmdline flags, and where the linker secondly isn't picky about the libraries order in the cmdline (a later lib depending on a prior one isn't an issue on Windows).

**Comment by MaskRay** [comment]
https://docs.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp?view=vs-2019
MSVC does not allow arbitrary linker options. Only `/DEFAULTLIB /EXPORT /INCLUDE /MANIFESTDEPENDENCY /MERGE /SECTION` are allowed.

.deplibs is for adding supplementary object files/shared objects/archives/bitcode files. If people reach consensus that arbitrary linker options are useful in the future, the new feature will probably get a new section type. In llvm, `#pragma comment(lib, ...)` has been used by libc++, libc++abi and libunwind to provide optional dependencies on certain system libraries. Some users don't want an unconditional dependency on libpthread.

> and where the linker secondly isn't picky about the libraries order in the cmdline (a later lib depending on a prior one isn't an issue on Windows).

The Windows situation motivated the new ELF port in lld. The lld rules can be simply understand as: every archive has the --start-group semantics. https://lld.llvm.org/NewLLD.html If libfoo.a depends on libbar.a, both `-lfoo -lbar` and `-lbar -lfoo` work. In one situation `-lbar0 -lfoo -lbar1`, if both bar0 and bar1 provide the same definition, libbar0.a will be picked by lld. libbar0.a or libbar1.a may be picked by GNU ld and gold, depending on whether the object file in libbar0.a resolves an earlier undefined reference.

**Comment by kinke** [comment]
> MSVC does not allow arbitrary linker options. Only `/DEFAULTLIB /EXPORT /INCLUDE /MANIFESTDEPENDENCY /MERGE /SECTION` are allowed.

Okay so not totally arbitrary, but they definitely also support undocumented `/alternatename`.

**Comment by kinke** [comment]
I gave it a quick test ride, but LLVM 9.0.0 errors out with `invalid llvm.linker.options` when trying to generate a Linux x64 object file from IR containing
```LL
!llvm.linker.options = !{!0}
!0 = !{!"mylib"}
```

The same mechanism seems to work for Mach-O though (as mentioned by @jacob-carlborg in the DMD PR); the textual assembly contains
```
	.linker_option "mylib"
```

for a `pragma(lib, "mylib")`, so for Mach-O we can apparently add arbitrary (?) linker cmdline flags (and so would need a `-l` prefix for the libs, but can also support other flags via `pragma(linkerDirective)`.

**Comment by kinke** [comment]
Oh, they reserved a separate identifier for these libs: `llvm.dependent-libraries` ([docs](http://llvm.org/docs/LangRef.html#dependent-libs-named-metadata)).
