### ISSUE TITLE
Generate `.debug_aranges` 

### ISSUE THREAD

**Issue by kubo39** [ldc-developers/ldc#3252]
1. Though I'm not sure why, dmd generates `.debug_aranges` but ldc doesn't.
2. `eu-addr2line` uses this to know which compilation unit to inspect to find the subprogram in.

```console
$ ldc2 -g helloworld.d
$ nm helloworld| grep _Dmain
000000000001f540 T _Dmain
$ eu-addr2line -e helloworld -f 1f540
_Dmain
??:0
```

**Comment by kinke** [comment]
There's a hidden switch (inherited by LLVM) for this: `--generate-arange-section`.

From https://bugs.llvm.org/show_bug.cgi?id=19006#c2:
> This behavior was changed recently in r201379.  The reason I heard was that we are already generating the same information in .debug_ranges, and gdb looks at that first.  If you need the old format, pass the flag.

**Comment by kubo39** [comment]
Thanks, closing now.
