### ISSUE TITLE
Applications won't link

### ISSUE THREAD

**Issue by ZILtoid1991** [ldc-developers/ldc#3267]
Here's the output of dub:

`dub build "pixelperfectengine:pixelperfecteditor" --compiler=ldc2 --arch=x86
Building package pixelperfectengine:pixelperfecteditor in L:\Users\laszl\Documents\GitHub\pixelperfectengine\
Performing "debug" build using ldc2 for x86.
bindbc-loader 0.2.1: target for configuration "noBC" is up to date.
bindbc-sdl 0.13.0: target for configuration "dynamic" is up to date.
bmfont 0.1.0: target for configuration "library" is up to date.
bitleveld 0.1.0-alpha: target for configuration "library" is up to date.
intel-intrinsics 1.2.2: target for configuration "library" is up to date.
cpublit 0.4.0-alpha: target for configuration "library" is up to date.
vfile 0.1.2: target for configuration "library" is up to date.
dimage 0.2.2: target for configuration "unittest" is up to date.
libpcm 0.2.2: target for configuration "library" is up to date.
taggedalgebraic 0.11.8: target for configuration "library" is up to date.
sdlang-d 0.10.5: target for configuration "library" is up to date.
stdx-allocator 2.77.5: target for configuration "library" is up to date.
std-experimental-xml 0.1.7: target for configuration "library" is up to date.
pixelperfectengine 0.9.4-beta3+commit.2.g06cb3c8: target for configuration "library" is up to date.
pixelperfectengine:pixelperfecteditor 0.9.4-beta3+commit.2.g06cb3c8: building configuration "application"...
Linking...
lld-link: error: undefined symbol: __D4core6thread8PAGESIZEyk
>>> referenced by L:\LDC\import\std\concurrency.d:1644
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1644
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1588
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1588
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1606
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvkZCQEzQEy__TQEoTQEhZQEw)>>> referenced by L:\LDC\import\std\concurrency.d:1662
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvkZCQEzQEy__TQEoTQEhZQEw)
lld-link: error: undefined symbol: __D4core6thread5Fiber6__ctorMFNbDFZvkkZCQBlQBjQBf
>>> referenced by L:\LDC\import\std\concurrency.d:1644
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1662
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvkZCQEzQEy__TQEoTQEhZQEw)>>> referenced by L:\LDC\import\std\concurrency.d:1683
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvkkZCQFaQEz__TQEpTQEiZQEx)

lld-link: error: undefined symbol: __D4core6thread5Fiber4callMFEQBaQyQt7RethrowZC6object9Throwable
>>> referenced by L:\LDC\import\std\concurrency.d:1645
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1589
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1607
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvkZCQEzQEy__TQEoTQEhZQEw)>>> referenced by L:\LDC\import\std\concurrency.d:1628
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvkkZCQFaQEz__TQEpTQEiZQEx)
>>> referenced by L:\LDC\import\std\concurrency.d:1663
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvkZCQEzQEy__TQEoTQEhZQEw)>>> referenced by L:\LDC\import\std\concurrency.d:1684
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFDFZvkkZCQFaQEz__TQEpTQEiZQEx)
>>> referenced by L:\LDC\import\std\concurrency.d:1700
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm8popFrontMFZv)

lld-link: error: undefined symbol: __D4core6thread5Fiber6__ctorMFNbPFZvkkZCQBlQBjQBf
>>> referenced by L:\LDC\import\std\concurrency.d:1588
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvZCQEyQEx__TQEnTQEgZQEv) 
>>> referenced by L:\LDC\import\std\concurrency.d:1606
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvkZCQEzQEy__TQEoTQEhZQEw)>>> referenced by L:\LDC\import\std\concurrency.d:1627
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm6__ctorMFPFZvkkZCQFaQEz__TQEpTQEiZQEx)

lld-link: error: undefined symbol: __D4core6thread5Fiber5stateMxFNaNbNdNiNfZEQBnQBlQBh5State
>>> referenced by L:\LDC\import\std\concurrency.d:1692
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm5emptyMFNdZb)
>>> referenced by L:\LDC\import\std\concurrency.d:1786
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T5yieldTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDiFKQDgZv)

lld-link: error: undefined symbol: __D4core6thread5Fiber7getThisFNbNiNfZCQBjQBhQBd
>>> referenced by L:\LDC\import\std\concurrency.d:1785
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T5yieldTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDiFKQDgZv)

lld-link: error: undefined symbol: __D4core6thread5Fiber5yieldFNbNiZv
>>> referenced by L:\LDC\import\std\concurrency.d:1789
>>>               sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T5yieldTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDiFKQDgZv)

lld-link: error: undefined symbol: __D4core6thread5Fiber7__ClassZ
>>> referenced by sdlang-d.lib(sdlang.parser.obj):(__D3std11concurrency__T9GeneratorTS15taggedalgebraicQr__T15TaggedAlgebraicTS6sdlang6parser16ParserEventUnionZQCaZQDm7__ClassZ)
Error: linking with LLD failed
ldc2 failed with exit code 1.`

No issues with version 1.18.0. Tried if it was a conflict with some other LLD-Link version (it tried to use an 8.0.0 version supplied with DMD), but the issue still exists.

I'm now downgrading yet again. Also how can I switch to MSVC linker instead if this error stays?

**Comment by rainers** [comment]
I suspect you copied the zip distribution over an existing installation, but some files need to be removed (at least core/thread.d has been migrated to a package). Please try a clean installation.

**Comment by kinke** [comment]
> Also how can I switch to MSVC linker instead if this error stays?

`-linker=path\to\link.exe`, but this has nothing to do with LLD.

**Comment by kinke** [comment]
> sdlang-d 0.10.5: target for configuration "library" is up to date.
> [...]
> undefined symbol: [...] referenced by [...] sdlang-d.lib(sdlang.parser.obj)

This looks more like a stale dub build cache instead of a corrupt LDC installation. I think dub should be able to detect a newer compiler version, so this is most likely a dub issue.

**Comment by kinke** [comment]
@ZILtoid1991: Any news?

**Comment by ZILtoid1991** [comment]
Sorry for the late new.
It seems it works now after I deleted the old files.
