### ISSUE TITLE
OSX: LDC linked against regular LLVM won't show line numbers in stack trace

### ISSUE THREAD

**Issue by Geod24** [ldc-developers/ldc#3280]
On OSX, the linker strips `.debug_lines`, which makes the backtrace code in Druntime non-functional.
LDC already has a workaround for this ([here](https://github.com/ldc-developers/ldc/blob/d13ae13308444849559c53a885ad1db127768c4d/driver/targetmachine.cpp#L39-L51)), however this workaround requires to compile against a modified version of LLVM.

So if one downloads the release from Github, things work correctly, but for Homebrew users (who build from source), line numbers aren't shown by default.

Is there any chance that the patch can be upstreamed so people linking against stock LLVM can benefit from it ?

**Comment by kinke** [comment]
I doubt they'll accept such a hack. The probably nicer proper solution would involve druntime being able to use the separate debuginfo files generated by default (IIRC, something similar to .pdb files).

**Comment by kinke** [comment]
Also, there are much things that only work with our LLVM fork, mainly cross-compiling to Android (another hack that surely won't be accepted) and `-link-internally` for some targets (well, those one-liners would be upstreamable).

**Comment by Geod24** [comment]
Opened https://issues.dlang.org/show_bug.cgi?id=20510, since the proper solution seems to be in Druntime. Thanks!

> `-link-internally` for some targets

Is Windows one of them ?

**Comment by kinke** [comment]
> Is Windows one of them ?

With recent LLVM, it only affects those targets for which it's most useful - Windows/MSVC and WebAssembly.

**Comment by JohanEngelen** [comment]
Fixed by https://github.com/ldc-developers/ldc/pull/4291
