### ISSUE TITLE
Cross compilation for Windows: "Error: failed to locate link.exe"

### ISSUE THREAD

**Issue by Yaisis** [ldc-developers/ldc#3281]
Compilation is carried out in Linux.
When using the compiler option --arch=x86_64-pc-windows-msvc
the following error is issued:

Error: failed to locate link.exe
/usr/bin/ldc2 failed with exit code 1.

How to fix it ?

**Comment by kinke** [comment]
Either specify an LLD executable via `-linker=lld-link`, or use an official prebuilt LDC package with implicit `-link-internally` usage.

> When using the compiler option --arch=x86_64-pc-windows-msvc

I guess you mean dub with `--arch`? For LDC, make sure to use `-mtriple`.

**Comment by Yaisis** [comment]
Yes, I use dub with --arch.

Thanks for the answer.
