### ISSUE TITLE
lld-link: error: could not open 'WS2_32.lib': No such file or directory

### ISSUE THREAD

**Issue by Yaisis** [ldc-developers/ldc#3284]
Compiling from Linux under Windows.
When linking produces an error:
"lld-link: error: could not open 'WS2_32.lib': No such file or directory"
Because the file names do not match.
The directory contains the following file: ws2_32.lib
where "ws" is lowercase.

**Comment by kinke** [comment]
You'll need to figure out where that reference comes from. The compiler doesn't add it as implicit library; druntime and Phobos contain one corresponding `pragma(lib, "ws2_32[lib]");` each, but both are in lowercase.

**Comment by Yaisis** [comment]
Probably in a third-party package error.
I will try to identify, and then write it to the creators.
Thanks.
