### ISSUE TITLE
Implicit Instantiation of Undefined Template

### ISSUE THREAD

**Issue by Robertorosmaninho** [ldc-developers/ldc#3289]
https://github.com/ldc-developers/ldc/blob/ebe1aec9f3f1970034d4dce3ae4b25e17d38103a/gen/ctfloat.cpp#L34

I'm trying to compile LDC with the last LLVM version available on GitHub(trunk), but unfortunately, I'm having problems with this snippet. Here is the error message:

ctfloat.cpp:34:21: error: implicit instantiation of undefined template 'llvm::Expected<llvm::APFloatBase::opStatus>'
  const auto r = ap.convertFromString(literal, APFloat::rmNearestTiesToEven);
                    ^
/lvm-project/llvm/include/llvm/ADT/APFloat.h:41:29: note: template is declared here
template <typename T> class Expected;
                            ^

**Comment by Robertorosmaninho** [comment]
well, import #include llvm/Support/Error.h fix the problem but create another one on 

https://github.com/ldc-developers/ldc/blob/ebe1aec9f3f1970034d4dce3ae4b25e17d38103a/gen/ctfloat.cpp#L36

error: invalid operands to binary expression ('const llvm::Expected<llvm::APFloatBase::opStatus>' and 'int')
    *isOutOfRange = (r & (APFloat::opOverflow | APFloat::opUnderflow)) != 0;
                     ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by kinke** [comment]
To be expected, as the `Expected` might contain an error, not just the expected enum. So you'll have to check for an error and handle it appropriately; you can also just ignore it for now and dereference the Expected (`*r`) in order to get the enum.

**Comment by kinke** [comment]
I'm going to close, we can still continue the discussion here if there are more annoyances. In the future, please post such questions either on Gitter or the forum, in order not to spam the GitHub issues tracker with questions.
