### ISSUE TITLE
reference to __aeabi_unwind_cpp_pr0 in -betterC object file

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3290]
Hi!

I am tried to compile empty test code for bare metal ARM MCU with -betterC
```D
extern(C) void main()
{
}
```
```
$ ldc2  -march=thumb -mcpu=cortex-m3 --betterC -c test.d
```
 and got this while linking:
```
arm-none-eabi-ld: test.o:(.ARM.exidx.text.main[main]+0x0): undefined reference to `__aeabi_unwind_cpp_pr0'
```
For some reason reference to __aeabi_unwind_cpp_pr0 is placed into object file produced by ldc2.

version   1.18.0 (DMD v2.088.1, LLVM 9.0.0)
version   1.20.0-git-cef4b3d (DMD v2.090.0, LLVM 9.0.1)

**Comment by denizzzka** [comment]
notabug

**Comment by kinke** [comment]
I don't see that reference anywhere: https://d.godbolt.org/z/n0VfD4

**Comment by kinke** [comment]
Well, running `nm test.o` should give insight whether the symbol is really emitted by LDC. [`arm-none-eabi-ld test.o` correctly complains about missing `_start`; C `main` requires a libc.]

**Comment by denizzzka** [comment]
```
$ nm -s test.o
00000000 t $t.0
00000000 t $t.1
         U __aeabi_unwind_cpp_pr0
00000001 T _D4test10gpio_setupFZv
         U gpio_set_mode
         U gpio_toggle
00000001 T main
         U rcc_periph_clock_enable

```

**Comment by denizzzka** [comment]
> [arm-none-eabi-ld test.o correctly complains about missing _start; C main requires a libc.]

(yep, this is not related to current issue)

**Comment by kinke** [comment]
Can you try this?
```D
import ldc.attributes;
extern(C) void main() @llvmAttr("nounwind") {}
```

Some background: http://lists.llvm.org/pipermail/llvm-dev/2017-March/111366.html

**Comment by Rogni** [comment]
like this ? https://travis-ci.org/Rogni/ldc_check/builds/640445463

**Comment by kinke** [comment]
It seems to works on my machine with that attribute (~master, LLVM 9.0.1; I don't have a linker, but I checked the .o symbols). The Travis job uses pretty old LDC v1.8.
```
ldc2 -mtriple=thumb-unknown-none-eabi -mcpu=cortex-m3 -betterC -c test.d -v && llvm-nm test.o
00000000 T main
```

**Comment by Rogni** [comment]
getted last version ldc from

**Comment by Rogni** [comment]
downloaded last version  ldc from https://github.com/ldc-developers/ldc/releases/tag/v1.20.0-beta1 

https://travis-ci.org/Rogni/ldc_check/jobs/640634765

**Comment by denizzzka** [comment]
Good morning!

`@llvmAttr("nounwind")` solves issue for me on all LDC versions.

**Comment by denizzzka** [comment]
...but here is one disadvantage: all my modules should be marked like this:

```D
import ldc.attributes;
@llvmAttr("nounwind"):

....
```

**Comment by denizzzka** [comment]
Upd: yep, disadvantage is that it is need to set @llvmAttr("nounwind") for whole module

**Comment by kinke** [comment]
I think the probably best solution for now is modifying the linker script, see https://lists.llvm.org/pipermail/llvm-dev/2019-March/130669.html.

**Comment by denizzzka** [comment]
It is better just to go to Dlang without betterC :-)
But at first it is need to build runtime.

**Comment by kinke** [comment]
Well if you don't need bare-metal, you could simply link against libunwind, which should provide that symbol.

**Comment by denizzzka** [comment]
> Well if you don't need bare-metal

But I need bare-metal... libunwind will not suitable for that?

**Comment by dnadlinger** [comment]
> But I need bare-metal... libunwind will not suitable for that? 

You can definitely use libunwind to implement unwinding on bare-metal system – I'm doing so on bare-metal ARM and even FPGA softcores.

**Comment by denizzzka** [comment]
@dnadlinger yes, thanks! :-) Today I already implemented it too into my project
