### ISSUE TITLE
ARM_SoftFloat is not raise

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3291]
I am try to cross compile some code with `version(ARM_SoftFloat)` inside of it (std.math from Phobos, for example) for MCU without FP.

Flags:
```
-DD_FLAGS="-march=thumb;-mcpu=cortex-m3"
```
```
<inline asm>:1:2: error: instruction requires: VFP2
        vmsr FPSCR, r0
        ^
LLVM ERROR: Error parsing inline asm
```
(ldc tried to build code from HF section)

Try to compile with `ARM_SoftFloat` version directive:
```
-DD_FLAGS="-march=thumb;-mcpu=cortex-m3;--d-version=ARM_SoftFloat"
```
```
Error: version identifier `ARM_SoftFloat` is reserved and cannot be set
```

`--float-abi=soft` option isn't helps with this too, it returns same inline asm error as at first try.

Compiler version 1.18.0 (DMD v2.088.1, LLVM 9.0.0)

**Comment by kinke** [comment]
On run.dlang.io, specifying `-march=thumb -float-abi=soft` [with LDC v1.18] does predefine version `ARM_SoftFloat`, see the `-v` output. So if you get inline asm errors, there's some code not guarded by that version check.

**Comment by denizzzka** [comment]
Sorry, I are right!

> some code not guarded by that version check.

Yes, this is issue of std.math
