### ISSUE TITLE
No error or warning when interfaces are only partially reimplemented

### ISSUE THREAD

**Issue by triplejam** [ldc-developers/ldc#3302]
If a class reimplements an interface, dmd and the spec requires all the methods to be reimplemented. LDC from what I can tell does not enforce this.

From the spec
```D
interface D
{
    int foo();
}

class A : D
{
    int foo() { return 1; }
}

class B : A, D
{
}       // error, no foo() for interface D
```

**Comment by kinke** [comment]
Thx for the report.

**Comment by jacob-carlborg** [comment]
https://github.com/dlang/dmd/pull/11191 should fix this in upstream.

**Comment by kinke** [comment]
Yes, fixed with master now, thx Jacob.
