### ISSUE TITLE
Deprecated header name and function name 

### ISSUE THREAD

**Issue by Robertorosmaninho** [ldc-developers/ldc#3319]
https://github.com/ldc-developers/ldc/blob/e4f71e775699c14f0cd8bcfc183cde9dcddf1c3a/driver/codegenerator.cpp#L26

LLVM10 renamed it to LLVMRemarkStreamer.h

https://github.com/ldc-developers/ldc/blob/e4f71e775699c14f0cd8bcfc183cde9dcddf1c3a/driver/codegenerator.cpp#L61

LLVM10 renamed it to setupLLVMOptimizationRemarks

**Comment by kinke** [comment]
Please, no issues about LLVM incompatibilities with unfinished versions; we'd have thousands of issues already otherwise.
