### ISSUE TITLE
LoadLibrary doesn't run gc_setProxy because not exported

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#3330]
```
> dumpbin /Directives "ldc-1.20.0\ldc2-1.20.0-windows-multilib\lib64\druntime-ldc.lib" | findstr EXPORT
>
```

v.s.

```
> dumpbin /Directives "dmd-2.090.1\dmd2\windows\lib64\phobos64.lib" | findstr EXPORT
   /EXPORT:gc_setProxy
   /EXPORT:gc_clrProxy
>
```

https://github.com/ldc-developers/druntime/commit/1fa60c4f5516e63a5050255c5757f48c31273ec3 introduced the difference, but I don't really understand the reasoning. All I know is that on windows, `Runtime.LoadLibrary` ends up behaving differently with dmd and ldc due to this (because it can't find `gc_setProxy` in the dll).

**Comment by kinke** [comment]
I don't think there have been any improvements to that 'shared GC' hack. IIRC, the thing is/was that DMD doesn't include those directives in a `proxy.obj`, but splits stuff out into separate objects, so the directives aren't pulled in by default, contrary to LDC. Back then, you had to explicitly pull them in via a .def file for DMD too, as noted in the commit msg; that should still work with LDC (as would putting those two functions into a separate D module => object file). And implicitly pulling them in for every binary leads to the mentioned issues (import lib + exp file generation, extra linker output line breaking lots of tests etc. etc.).

**Comment by kinke** [comment]
I've just retried this with DMD 2.091, and it looks like nothing has changed since then - neither executables nor DLLs export those 2 symbols by default, but adding `-L/EXPORT:gc_setProxy -L/EXPORT:gc_clrProxy` does, and that works with LDC too. So please recheck and close if confirmed.
