### ISSUE TITLE
Precompiled linux-x86_64 depends on libxml2

### ISSUE THREAD

**Issue by iMichka** [ldc-developers/ldc#3336]
Hi

Homebrew maintainer here. We are trying to build `ldc` on Linux: https://github.com/Homebrew/linuxbrew-core/pull/19652

Cmake fails with the following error:
```
CMake Error at cmake/Modules/FindDCompiler.cmake:68 (math):
  math cannot parse the expression: "*1000+": syntax error, unexpected
  exp_TIMES (1).
Call Stack (most recent call first):
  CMakeLists.txt:10 (include)
```

We are using a precompiled ldc as a bootstrap, to actually compile ldc from source:
https://github.com/ldc-developers/ldc/releases/download/v1.20.0/ldc2-1.20.0-linux-x86_64.tar.xz

Running this precompiled version fails:
```
/tmp/ldc-20200222-53920-1oj2xxg/ldc-1.20.0-src/ldc-bootstrap/bin/ldmd2
/tmp/ldc-20200222-53920-1oj2xxg/ldc-1.20.0-src/ldc-bootstrap/bin/ldmd2: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
```

```
ldd /tmp/ldc-20200222-53920-1oj2xxg/ldc-1.20.0-src/ldc-bootstrap/bin/ldmd2
	linux-vdso.so.1 =>  (0x00007ffc797de000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f52cb8ca000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f52cb6c2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f52cb4be000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f52cb2a1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f52caf98000)
	libxml2.so.2 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f52cad82000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f52ca9b8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f52cbae4000)
```

Our build docker container does not ship libxml2. Is this a needed dependency or some opportunistic linkage which happened when you built the binaries? Previous versions of ldc did not have this issues.

**Comment by thewilsonator** [comment]
That line is https://github.com/ldc-developers/ldc/blob/master/cmake/Modules/FindDCompiler.cmake#L68
`math(EXPR D_COMPILER_FE_VERSION ${CMAKE_MATCH_2}*1000+${CMAKE_MATCH_3}) # e.g., 2079` which seems that is has failed to match the regex on the line above 

`string(REGEX MATCH " (D Compiler|based on DMD) v([0-9]+)\\.([0-9]+)" D_COMPILER_FE_VERSION "${D_COMPILER_VERSION_STRING}")`
 
`D_COMPILER_VERSION_STRING ` is in turn is gotten from `$ldmd2 --version`. Can you please paste the output of `ldmd2 --version`?

**Comment by kinke** [comment]
> Is this a needed dependency or some opportunistic linkage which happened when you built the binaries?

This is a default dependency of LLVM and used automatically when found on the system building LLVM; last time I checked, it was required because of Windows manifest generation when cross-linking Windows binaries.

> Previous versions of ldc did not have this issues.

AFAIK, we've had this dependency for years now.

**Comment by iMichka** [comment]
> Previous versions of ldc did not have this issues.

We may have built ldc on a system with libxml2 before, so this is maybe why I got confused. Please disregard this statement.

> Can you please paste the output of ldmd2 --version?

```
$ ldmd2 --version
ldmd2: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory
```

The cmake error is not the real one, the real issue is that `libxml2` is missing.

We are using `ldmd2` as a compiler to build `ldc`. We could try to use another compiler, or see if we could remove the libxml2.so linkage when you build `ldmd2`.

**Comment by kinke** [comment]
I see a `depends_on "libconfig" => :build` in there; that lib hasn't been required for a while now. Can't you simply exchange that with `libxml2`? There's an according formula.

**Comment by iMichka** [comment]
I can remove `depends_on "libconfig" => :build`, no issue. We probably never noticed that it was not needed anymore.

I tried to add `depends_on "libxml2"`. But we install the library in `/home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.10/lib/libxml2.so`, so it does not get picked up.

**Comment by iMichka** [comment]
I found a solution. We use that technique for other formulae too (though quite rarely):
`ENV.prepend_path "LD_LIBRARY_PATH", Formula["libxml2"].lib`

This allows `ldmd2` to find the `libxml2` dependency.

This is now fixed on our side and, and people can `brew install ldc` on linux too.

Thank you for your help. Closing here as there is nothing more to do.
