### ISSUE TITLE
LDC 1.20.0 - Inconsistent static module constructors execution 

### ISSUE THREAD

**Issue by tripaneer** [ldc-developers/ldc#3343]
Greetings, I've noticed that with version 1.20 the module static constructors of imported library modules are not consistently executed.

I've made a test case showcasing this : [https://github.com/tripaneer/ldc-test](https://github.com/tripaneer/ldc-test)
 
Build/run with **1.20.0 on macOS** or **1.19.0 on ubuntu**, i see the constructor getting called : 

```
$ dub run -f --compiler=ldc2
Performing "debug" build using ldc2 for x86_64.
foo ~master: building configuration "library"...
ldc-test ~master: building configuration "application"...
Linking...
Running ./ldc-test
module foo static constructor executed
main() executed
```

but not in **1.20.0 on ubuntu** : 

```
$ dub run -f --compiler=ldc2
Performing "debug" build using ldc2 for x86_64.
foo ~master: building configuration "library"...
ldc-test ~master: building configuration "application"...
Linking...
Running ./ldc-test 
main() executed
```

**Comment by kinke** [comment]
An import alone isn't sufficient anymore, the object file needs to be pulled in by something else, see the changelog entry wrt. importedModules, bringing LDC in line with DMD.

**Comment by mario-tripaneer** [comment]
I see, but compiling with dmd 2.090.1 still has the constructor executed. In that case I shouldn't I expect to see the new behaviour also there? (as well in macOS?)

**Comment by kinke** [comment]
That behavior isn't new for DMD. In general, different linkers / linker flags might account for the difference; comparing the external symbol refs of the LDC/DMD object files should shed light on whether there's a real incompatibility to be fixed.

**Comment by kinke** [comment]
Should be fixed; please reopen if it isn't.
