### ISSUE TITLE
skipping definition of function caused by fullyQualifiedName

### ISSUE THREAD

**Issue by MrSmith33** [ldc-developers/ldc#3344]
`..\import\std\traits.d(730,19): Warning: skipping definition of function std.traits.fqnSym!(regex).adjustIdent due to previous definition for the same mangled name: _D3std6traits__T6fqnSymSQw5regexZ11adjustIdentFAyaZQe
`

version is ldc 1.20.0
win64

**Comment by kinke** [comment]
Please add a reproducible testcase.

**Comment by MrSmith33** [comment]
test case:
```D
import std;
void func() {
	Captures!string obj;
	typeId(obj);
	typeId(__traits(getMember, obj, "matches"));
}

auto typeId(T)(T value) {
	auto fqn = fullyQualifiedName!T;
}
```
compiled with `ldc2 -w -c test.d`

**Comment by kinke** [comment]
Confirmed, thx. Just to clarify: this is caused by a bad AST, containing multiple definitions for a particular  mangled D function name. I bet it's a problem with DMD as well, just that it doesn't warn about it.

**Comment by JohanEngelen** [comment]
related: https://github.com/ldc-developers/ldc/pull/2754

**Comment by kinke** [comment]
The testcase works with recent LDC versions and I was able to get rid of according workarounds in Symmetry's codebase. I assume the underlying issue was fixed in the frontend (or Phobos) in the meantime => closing.
