### ISSUE TITLE
Crosslinking problem

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3355]
(I am not sure about this is bug or not)

While linking (no sources used, only object files) EABI binaries
```
firmware.elf@exe/subprojects_freertos_event_groups.c.o: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), with debug_info, not stripped
```

linker stucks (command splitted by lines for comfort reading):
```
$ ldc2  -of=firmware.elf
'firmware.elf@exe/subprojects_freertos_croutine.c.o' 
'firmware.elf@exe/subprojects_freertos_event_groups.c.o' 
'firmware.elf@exe/subprojects_freertos_list.c.o' 'firmware.elf@exe/subprojects_freertos_queue.c.o' 
'firmware.elf@exe/subprojects_freertos_stream_buffer.c.o' 
'firmware.elf@exe/subprojects_freertos_tasks.c.o' 'firmware.elf@exe/subprojects_freertos_timers.c.o' 
'firmware.elf@exe/subprojects_freertos_portable_GCC_ARM_CM3_port.c.o' 
'firmware.elf@exe/subprojects_freertos_portable_MemMang_heap_1.c.o' 
'firmware.elf@exe/subprojects_libunwind_src_UnwindLevel1.c.o' 
'firmware.elf@exe/subprojects_libunwind_src_Unwind-sjlj.c.o' 
'firmware.elf@exe/subprojects_libunwind_src_libunwind.cpp.o' 
'firmware.elf@exe/subprojects_libunwind_src_Unwind-EHABI.cpp.o' 
'firmware.elf@exe/subprojects_libunwind_src_Unwind-seh.cpp.o' 
'firmware.elf@exe/subprojects_libunwind_src_UnwindRegistersRestore.S.o' 
'firmware.elf@exe/subprojects_libunwind_src_UnwindRegistersSave.S.o' 
-L=-L../subprojects/libopencm3/lib/ 
-L=--script=stm32/f1/stm32f103x8.ld -L=-L--allow-shlib-undefined 
--mtriple=arm-none-eabi 
-defaultlib= 
-L=--start-group 
'-L=d/libD code part.a'
-L=subprojects/druntime/libdruntime.a
-L=subprojects/picolibc/semihost/libsemihost.a 
-L=subprojects/libopencm3/libopencm3_stm32f1.a 
-L=subprojects/libopencm3/libreset_handler.a 
-L=subprojects/picolibc/newlib/libc/libc.a 
-L=subprojects/picolibc/newlib/libm/libm.a 
-L=-rpath 
-L=/home/denizzz/Dev/d_c_arm_test/builddir/d:/home/denizzz/Dev/d_c_arm_test/builddir/subprojects/druntime:/home/denizzz/Dev/d_c_arm_test/builddir/subprojects/picolibc/semihost:/home/denizzz/Dev/d_c_arm_test/builddir/subprojects/libopencm3:/home/denizzz/Dev/d_c_arm_test/builddir/subprojects/picolibc/newlib/libc:/home/denizzz/Dev/d_c_arm_test/builddir/subprojects/picolibc/newlib/libm  
-L=--end-group
```

Error message:
```
/usr/bin/ld: firmware.elf@exe/subprojects_freertos_event_groups.c.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: firmware.elf@exe/subprojects_freertos_event_groups.c.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: firmware.elf@exe/subprojects_freertos_event_groups.c.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: firmware.elf@exe/subprojects_freertos_event_groups.c.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: firmware.elf@exe/subprojects_freertos_event_groups.c.o: relocations in generic ELF (EM: 40)
/usr/bin/ld: firmware.elf@exe/subprojects_freertos_event_groups.c.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
```

Actually `ldc2` tries to link these EABI files into x86 binary.
I tried to change linker by `--linker` option with same result as above from any another linker.
Tried to pass `-m` `ld.lld` linker option (target emulation) without success - `armelf` causes "ld.lld: error: filename.c.o is incompatible with armelf", but "arm-none-eabi-ld -V" returns only this emulation name.
Also I tried to pass full path to `arm-none-eabi-ld` into --linker option also without success.

Don't know how to link these files into ELF by ldc2.

Why such method of "linking by compiler" is important: authors of Meson build system decided to abandon use of standalone linkers and always use the compiler call for linking. Reason is unknown to me.

```
LDC - the LLVM D compiler (1.20.1):
  based on DMD v2.090.1 and LLVM 9.0.1
  built with LDC - the LLVM D compiler (1.20.1)
  Default target: x86_64-pc-linux-gnu
  Host CPU: westmere
```

**Comment by kinke** [comment]
I'd suggest you try to figure out a working standalone ld cmdline first. Then compare that to the cmdline issued by LDC (add `-v` to see the gcc/clang cmdline, and `-Xcc=-v` to have gcc/clang output the linker cmdline).

**Comment by denizzzka** [comment]
ld says:
```
ld: unrecognised emulation mode: armelf
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu elf_l1om elf_k1om i386pep i386pe
```
Here is no appropriate emulation supported.

But `arm-none-eabi-ld` just works without any additional options.

**Comment by kinke** [comment]
Yeah that's not really surprising. ;) - You'll need to specify the accompanying C compiler then, e.g., `ldc2 -gcc=arm-none-eabi-gcc ...`, as mentioned in the Wiki pages. That will probably fail due to hardcoded C libs in LDC, but we'll see.

**Comment by denizzzka** [comment]
Oops, I watched "man ldc" so many times but did not notice this.

> That will probably fail due to hardcoded C libs in LDC, but we'll see.

Ye mean this?
```
/usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: cannot find -lstdc++
```

Yes, I faced with this now, `-L=-nostdlib` isn't helps.

**Comment by denizzzka** [comment]
Dirty solution: Debian provides `libstdc++-arm-none-eabi-newlib`, it can be used as `libstdc++` here.

**Comment by kinke** [comment]
I meant https://github.com/ldc-developers/ldc/blob/0ca4a2e2e707d5dd7b31aa34b93e4847376a4482/driver/linker-gcc.cpp#L619-L670, but these hardcoded libs are guarded by OS checks, so no problem. - `stdc++` isn't referenced by LDC/druntime/Phobos, that must come from somewhere else.
