### ISSUE TITLE
ldc2-1.20.1-linux-aarch64: file or folder not found

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3358]
I upgraded my raspbian (raspberry 4b) to aarch64 (validated by executing `uname -a`).

I thought I can now use ldc2 aarch64 version but I get error `file or folder not found while executing `ldc2`. I also to use `ldd` to check wheter a dependency is missing but `ldd` says it is a static linked executable. Also executable flag is set for all users.

What can I else check/do ?

**Comment by kinke** [comment]
Never heard of this before, but googling for 1 minute found this (missing ELF interpreter): https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/file-not-found-when-executing-assembled-program

The AArch64 package is built on Ubuntu 16.04, not Debian, no special linker flags.

**Comment by andre2007** [comment]
Thanks a lot. I close this issue as not ldc related.
