### ISSUE TITLE
ldc-build-runtime for mac and ios on linux?

### ISSUE THREAD

**Issue by MartinKrocek** [ldc-developers/ldc#3359]
.

**Comment by kinke** [comment]
32-bit Darwin isn't supported anymore (in druntime). AArch64 should newly work (see https://github.com/ldc-developers/ldc/issues/3329 if you haven't yet).

**Comment by MartinKrocek** [comment]
Yes, i did it. With darling shell it is possible to cross build runtime for ios on linux.

I saw some code from this repositories https://github.com/jacob-carlborg/druntime/tree/ios-ldc
https://github.com/jacob-carlborg/phobos/tree/ios-ldc was added to master, but I can't compile master for ios yet, it has some errors.

**Comment by kinke** [comment]
I don't think there's a real need to provide a workaround for Apple's closed eco-system and making ldc-build-runtime support building the Apple libs on Linux in some special shell. We should IMO rather focus on extending CI and cross-compiling the iOS libs for the Azure Pipelines Mac job, to have *some* tests catching regressions and to generate a little prebuilt package containing the libs.
