### ISSUE TITLE
external source file ( .obj ) + betterC = missing __chkstk

### ISSUE THREAD

**Issue by SrMordred** [ldc-developers/ldc#3360]
Windows 10
the LLVM D compiler (1.20.0):
based on DMD v2.090.1 and LLVM 9.0.1
built with LDC - the LLVM D compiler (1.20.0)
Default target: x86_64-pc-windows-msvc

When trying to use some external source that create chkstk calls ldc fail to compile:
`lld-link: error: undefined symbol: __chkstk`
But only with `-betterC` flag. 
Some solution to this ?

**Comment by MartinKrocek** [comment]
You can try to add this flags -fno-stack-check -fno-stack-protector -fno-stack-arg-probe to $CFLAGS when you compile external .obj for windows.
It helps me, when I compiled my D-code with libpcre

**Comment by kinke** [comment]
> Some solution to this ?

Either use the MS toolchain, or grep druntime/Phobos as it works without `-betterC`, which leads to https://github.com/ldc-developers/druntime/blob/85803508e9978c4b8806ed6c5dea64f5ae90f0c4/src/rt/msvc.c#L105-L111.
