### ISSUE TITLE
Internal Compiler Error with alias this of struct

### ISSUE THREAD

**Issue by kntroh** [ldc-developers/ldc#3367]
Occurs Internal Compiler Error when compilation this code:

    struct Bool {
        bool value;
        alias value this;
    }

    void main() {
        auto t = Bool(true);
        auto f = Bool(false);
        auto r1 = t ? true : false; // OK
        auto r2 = f ? true : false; // OK
        auto r3 = (t == f ? t : f) ? true : false; // Error: Internal Compiler Error: Invalid struct cast from Bool to bool
    }

Compiler version:

    LDC - the LLVM D compiler (1.20.1-git-9cc9604):
      based on DMD v2.090.1 and LLVM 9.0.1
      built with LDC - the LLVM D compiler (1.20.1-git-9cc9604)
      Default target: x86_64-pc-windows-msvc
      Host CPU: skylake
      http://dlang.org - http://wiki.dlang.org/LDC

**Comment by kinke** [comment]
Most likely a duplicate of https://github.com/ldc-developers/ldc/issues/3159, needs a frontend fix.

**Comment by kntroh** [comment]
Sure. I'll close issue because it is a duplicate.
