### ISSUE TITLE
Memory leak when throwing exceptions in threads on windows

### ISSUE THREAD

**Issue by tchaloupka** [ldc-developers/ldc#3369]
Hi, I've been figuring out some memory leaks lately and found this one.

```D
import core.memory;
import core.thread;
import std;

void main() {

	while (true) {
	
		auto t = new Thread(&threadFn).start();
		t.join();
		t.destroy();
		GC.collect();
		GC.minimize();
		// writeln(GC.stats());
	}
}

void threadFn() nothrow {
	try {
		throw new Exception("foo"); // comment this out and leak is gone
	}
	catch (Exception ex) {}
}

```

It's consuming memory pretty fast.
Tried with prebuilt `ldc2 v1.20.1` under Windows 10 x86_64. It doesn't seem to change the behaviour with debug/release builds.
And it works at least with `dmd v2.090.1` (same frontend)

Slightly related issue: https://issues.dlang.org/show_bug.cgi?id=20680

I've tried this also under Fedora 31 and it seems to be ok there, so probably just windows.

**Comment by kinke** [comment]
Thx for notifying.

> It's consuming memory pretty fast.

300 MB after 1 minute of CPU time in my case.

Looks like the culprit is https://github.com/ldc-developers/druntime/blob/85803508e9978c4b8806ed6c5dea64f5ae90f0c4/src/ldc/eh_msvc.d#L256 not being destructed (I've added a printf, haven't see any output). Is destruction of TLS vars supposed to work?

**Comment by rainers** [comment]
> Is destruction of TLS vars supposed to work?

The destructors are not run, also for shared globals. Although that seems unexpected if you are used to C++ semantics, a constructor is not run as well (or only at compile time).
As a workaround, the dtor could be called by a `static ~this`.

**Comment by rainers** [comment]
See https://github.com/ldc-developers/druntime/pull/181
