### ISSUE TITLE
Add an option to control if and which system libraries are added by default to the linker command line when using LDC2 for compile and link.

### ISSUE THREAD

**Issue by dbankov-vmware** [ldc-developers/ldc#3374]
It would be good to be possible to control which and if system libraries are linked by default when using ldc2 for compiling and linking a binary. The latter is desirable because the code in an application may not need some of these or may need none at all.

The particular use case that I have in mind is when building UEFI application/service/driver where UEFI binaries are built with 'x86_64-unknown-windows-coff' target triple but don't need any of the default windows system libraries. More important it is incorrect to link with these.

**Comment by kinke** [comment]
Yes, I think that's useful for baremetal usages. Something like our existing `-defaultlib` (for the default D libs), which can be used to clear (`-defaultlib=`) or override them (`-defaultlib=lib1,lib2`). [Adding the libs manually via `-L` would probably insert them in the wrong position (before the default D libs).]

Open for suggestions wrt. how to name the new switch, and what it should include *exactly* (I'd propose all non-default-D implicit libraries, except for LLVM compiler-rt libraries).

**Comment by dbankov-vmware** [comment]
Yes, that's exactly what I had in mind. I was thinking about (`-platformlib=`) based on the comment at: https://github.com/ldc-developers/ldc/blob/b56bef247431a4cad4b9b7cb8b0d86364787634a/driver/linker-msvc.cpp#L204-L220
And I think as a start it should include the libs that are listed at the above location which are not controlled with a switch at the moment.

BTW I was planning to send a pull request but decided to file an issue first to discuss the topic and then something urgent appeared so I had to postpone the pull request work. In any-case its great to discuss the details here because whoever makes the change will get less comments during the review ;).

Thanks a lot for taking a look at this!

**Comment by dbankov-vmware** [comment]
I've prepared a PR for this issue but since this is my first PR for LDC I am not sure if what I did is correct at all.
Please let me know if there is a better way to address this.
