### ISSUE TITLE
Error: unrecognized file extension a

### ISSUE THREAD

**Issue by muv1** [ldc-developers/ldc#3383]
If you have a simple C library:

~~~c
$ cat hello.c
#include <stdio.h>
void f1() {
   puts("Sunday");
}

$ cat hello.d
extern (C) void f1();

$ cat test.d
import hello;
void main() {
   f1;
}
~~~

You can get it running like this:

~~~
clang -c hello.c
ar r hello.lib hello.o
ldc2 test.d hello.lib
~~~

However in general, if you download a static C library that someone else
compiled, it will use the `.a` extension rather than `.lib`. So for example if
you try this instead:

~~~sh
clang -c hello.c
ar r hello.a hello.o
ldc2 test.d hello.a # Error: unrecognized file extension a
~~~

Interestingly, this seems to be specific to LDC, as if you link separately, it
works as expected:

~~~
ldc2 -c test.d

lld-link \
test.obj \
/libpath:C:/Root/ldc2/lib \
/libpath:C:/Root/ldc2/lib/mingw \
druntime-ldc.lib \
ldc_rt.builtins.lib \
vcruntime140.lib \
hello.a
~~~

**Comment by thewilsonator** [comment]
This is a frontend issue. DMD will exhibit the same behaviour.

**Comment by muv1** [comment]
I think the extension shouldnt matter, the files are identical:

~~~
$ sha256sum hello.lib hello.a
01b7b85621333e04461990338c3f2b1f7d314576474d2baf2e87bfa1477056f6 *hello.lib
01b7b85621333e04461990338c3f2b1f7d314576474d2baf2e87bfa1477056f6 *hello.a
~~~

**Comment by kinke** [comment]
LDC is picky about the extension, like DMD, and expects .lib for static libs when targeting MSVC, simple as that. Only MinGW uses .o and .a on Windows.

**Comment by muv1** [comment]
@kinke good idea! Thank you!

**Comment by kinke** [comment]
This is intended behavior, exactly to prevent people from trying to link MinGW stuff when targeting MSVC. On Linux, you don't link Android stuff built against the Bionic runtime with other stuff built against glibc either.
