### ISSUE TITLE
MinGW

### ISSUE THREAD

**Issue by muv1** [ldc-developers/ldc#3385]
It seems currently the MinGW ABI is not supported.

This is noticable in the fact that libraries with `.a` are not allowed, and they
have to be renamed to `.lib`. But then even when thats done, it can cause
problems because it seems LDC does not include the needed MinGW libraries for
proper linkage.

Does LDC support MinGW in any way? And if not, why not?

The MinGW ABI is hugely popular for Windows development, with at least these
projects supporting it:

- https://cygwin.com
- https://github.com/mstorsjo/llvm-mingw
- https://llvm.org
- https://msys2.org
- https://musl.cc

**Comment by kinke** [comment]
Good god, no it's not supported (has almost been at one time, 32-bit only though, and isn't anymore), and trust me, its market share isn't relevant compared to the MSVC environment. We have existing MinGW issues (and even PRs), so closing this unspecific one. I don't have the time to list the reasons why MinGW support isn't trivial.

**Comment by muv1** [comment]
@kinke thanks for the response.

It seems the lack of MinGW support is the root cause for my issues with LDC and
D in general. While it is nice that LDC now has proper LibCurl support, I dont
really want to fight that battle with every single C library I might be
interested in.

This seems like as good a time as any for me to stop using the D language. Again
I thank you and maybe MinGW support will be offered someday.

**Comment by kinke** [comment]
As long as you're not willing to install and use the MSVC toolchain (C++ build tools are enough, you don't need a full Visual Studio), that's probably the 2nd best way forward (the best obviously being working on MinGW support yourself). Note that most bigger open-source projects ship are MSVC compatible and ship with according Makefiles or Visual Studio projects, even GNU stuff, so there's no 'battle with every single C library'.

**Comment by muv1** [comment]
The problem I have with the MSVC toolchain, is that you cant (that I know of)
just download, extract and use the tools. Take for example my current C/C++
compiler:

https://github.com/mstorsjo/llvm-mingw

to use it, you just download this:

https://github.com/mstorsjo/llvm-mingw/releases/download/20191230/llvm-mingw-20191230-x86_64.zip

extract it, and its ready to go. Until something like that is offered for MSVC,
I dont want to use MSVC or any MSVC only projects. Again thanks for all the
help and advice youve given, I appreciate and others will to who read the
threads.

**Comment by kinke** [comment]
You're welcome. - Yes, I don't think that's possible (as it probably isn't with Xcode on Mac). On the other hand, all binaries targeting the MinGW runtime depend on an installed MSVC runtime (the DLLs); linking it statically requires an installed MSVC toolchain.

**Comment by muv1** [comment]
Only the Microsoft Visual C++ Redistributable is required.

**Comment by muv1** [comment]
I did a little research and found this:

<https://stackoverflow.com/questions/59868753>

using this command:

~~~
./vs_BuildTools \
--lang en-us \
--layout out \
--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
~~~

downloads `nmake.exe` among other tools. The package size is pretty large at
648 MB, but its the best option ive seen so far for getting Visual Studio
without giant size.
