### ISSUE TITLE
Optimization doesn't work for const array

### ISSUE THREAD

**Issue by anon17** [ldc-developers/ldc#3400]
```d
bool f(int[] b, ref const int[4] c)
{
    return b[0..4]==c;
}
```
If rhs value is const or immutable, the compiler produces comparison through _adEq2 and typeinfos.

**Comment by anon17** [comment]
Not sure who does this. Frontend or ldc?

**Comment by anon17** [comment]
A workaround is to slice the value `b[0..4]==c[0..4]`.

**Comment by kinke** [comment]
Thx for the report.
