### ISSUE TITLE
Bloat with run-time typed template alias parameters

### ISSUE THREAD

**Issue by jmh530** [ldc-developers/ldc#3425]
When compiling with typed template alias parameters, a different version of each function is included for each value. This may makes sense for when parameters are only available at compile-time since there is scope for optimization, but I think in many cases with run-time parameters only one version of the function is needed, unlike for untyped template alias parameters.

For instance, when using a typed template alias parameter with a bool, If you pass in run-time bools that are true and false, then two versions of the function are created. However, these are basically the same function and a comparable run-time only version of the same function will have similar assembly, though I did notice some differences.

I don't know if this only makes sense for simple types, like bool, int, etc., or not. 

I'm also filing this here rather than with D's bugzilla because I only noticed it by looking at LDC's godbolt output. I don't know if it is something that should be closed here and filed there. 

[Godbolt](https://d.godbolt.org/z/X52FN8). 

```

int foo(alias bool rtct)(int x) {
    if (rtct)
        return x;
    else
        return x + 1;
}

void main() {
    bool x = true;
    bool y = false;
    auto result0 = foo!x(1);
    auto result1 = foo!y(1);
}
```

**Comment by JohanEngelen** [comment]
building on your example and looking at the assembly of this:
```
    bool x = true;
    enum y = false;
    auto result0 = foo!x(1);
    auto result1 = foo!y(1);
```
you can see that it makes a difference whether `x` or `y` is a compile-time constant (using `enum`) or a runtime variable (`bool`). If the `foo` template is instantiated with a constant, then `rtct` is known at compile time and optimization can have its way. But if `foo` is instantiated with a runtime variable as template parameter, then a hidden parameter is added to foo: `foo!x(1) ---> foo(int x, void* hiddenparameter)`. The pointer is pointing to the calling function's stack frame where the `x` variable in the calling function is stored. In assembly, `rdi` is pointing to that variable, and the `if (rtct)` becomes `cmp     byte ptr [rdi], 0`. That's also why it is different for `foo!y`: `rdi+1` because y is stored one address higher than `x`.
You can even write to it!
```
int foo(alias bool rtct)(int x) {
    rtct = 1;
```
that works for `foo!x`, but not for `foo!true`.

So this is working as expected.
The only thing that we could do is mark `foo!x` as a private function in IR because external modules cannot call it (it is effectively a function-local function); which would enable removing the function by the optimizer instead of having the linker remove it.

**Comment by JohanEngelen** [comment]
The other thing we could do is change the hidden parameter to point directly to the variable instead of the stack frame. In that case, indeed only one function would need to be emitted for `foo!x` and `foo!y`.

**Comment by kinke** [comment]
I think this is how it should be; the param can be used to get name etc. of the original variable:
```D
int foo(alias bool rtct)(int x) {
    pragma(msg, rtct.stringof);
    return rtct ? x : x + 1;
}

void main() {
    bool x = true;
    bool y = false;
    foo!x(1);
    foo!y(1);
}
```
=> (compiler output)
```
x
y
```

DMD instantiates it twice too.

**Comment by jmh530** [comment]
@JohanEngelen Thanks for the explanation. I hadn't seen anything in the Spec about how it was implemented. I had seen the commands for pointers in the assembly, but I didn't really grok it. However, I was aware that `foo!true` would generate optimized code and would be treated like a compile-time variable. I posted something in the Learn forum, [here](https://forum.dlang.org/post/zvsiohqfxqnbbdicewsi@forum.dlang.org), taking advantage of `__traits(compiles, {static if (rtct) {enum val = rtct;}})`. 

The point about `foo!x` being private is also a good one that I hadn't considered. I haven't tried to call it from another module. In the 

To your second point, I would guess that the rationale for pointing to the stack frame is if you have multiple typed template alias parameters, then the implementation is a little easier. If it can be implemented without too much complication, then I think it would be good.

**Comment by jmh530** [comment]
@kinke I would think that `ragma(msg, rtct.stringof);` would print the same under @JohanEngelen's suggestion to point to the variable itself, rather than the stack frame.

**Comment by kinke** [comment]
This should be clearer:
```D
int foo(alias bool rtct)(int x) {
    import core.stdc.stdio;
    printf("Using var `%s` in `%s`\n", rtct.stringof.ptr, __traits(parent, rtct).stringof.ptr);
    return rtct ? x : x + 1;
}

void main() {
    bool x = true;
    bool y = false;
    foo!x(1);
    foo!y(1);
}
```

This and similar stuff cannot work with a single template instantiation/function (`statif if` introspection etc. etc.).

If I understand correctly, you'd like to see the compiler automagically optimize a poor template
```D
int foo(alias bool b)() { return b ? 1 : 2; }
```
to
```
int foo()(ref bool b) { return b ? 1 : 2; }
```

**Comment by JohanEngelen** [comment]
@kinke is right, so this can never be optimized into the same function.
Marking them as private is still possible though.

**Comment by jmh530** [comment]
@kinke I'll take your word for it, though it might take some time for me to understand. With respect to your last comment, I think my point is that foo!true/foo!false, and foo!x are two categories of problems. I wouldn't want to remove the ability of foo!true/foo!false to generate optimal code. Ideally, I would just want the compiler to be able to recognize that foo!x is being passed a run-time variable and not generate bloat. But if there are good reasons why this cannot happen, then I do not have an issue.

@JohanEngelen I don't see any issue with making them private.

**Comment by jmh530** [comment]
@JohanEngelen If I'm being honest, I'm not entirely sure I understand the private point. I took the original code snippet and split it between two modules so that foo was in one and the main was in the other. I didn't have any issue calling foo from another module.

**Comment by JohanEngelen** [comment]
private relates to LLVM linkage, not D. The template is only ever instantiated and called by the module that is being codegenned. So it is private to that codegen module.

**Comment by JohanEngelen** [comment]
>  Ideally, I would just want the compiler to be able to recognize that foo!x is being passed a run-time variable and not generate bloat.

The compiler _does_ recognize it is passed a runtime variable, and therefore it _has_ to generate a new function for each different variable that is passed. It's not bloat. ;)

**Comment by jmh530** [comment]
> private relates to LLVM linkage, not D. The template is only ever instantiated and called by the module that is being codegenned. So it is private to that codegen module.

Ah. I see.

**Comment by jmh530** [comment]
> The compiler _does_ recognize it is passed a runtime variable, and therefore it _has_ to generate a new function for each different variable that is passed. It's not bloat. ;)

Thanks. I also took a look at the AST viewer on godbolt and it makes yours and @kinke's point as well.

One question I have is do you have any idea of what something simple I could put in the if statements wouldn't get optimized away with -O. I wanted to confirm for myself that changing y from bool to an enum would actually do something, but with -O the functions calls are optimized out, even when throwing in some printf statements.

**Comment by JohanEngelen** [comment]
Disable inlining of the function, pragma(inline, false).

**Comment by jmh530** [comment]
Thanks. This generates the code I would expect.

```
pragma(inline, false)
int foo(int x, bool rtct) {
    if (rtct)
        return bar(x + 1);
    else
        return bar(x + 2);
}

pragma(inline, false)
int bar(int x) {
    return x + 1;
}

extern(C) int main()
{
    import core.stdc.stdio: printf;
    enum bool x = true;
    enum bool y = false;
    bool z = true;
    bool a = false;
    auto result0 = foo(0, x);
    printf("%i", result0);
    auto result1 = foo(5, y);
    printf("%i", result1);
    auto result2 = foo(10, x);
    printf("%i", result2);
    auto result3 = foo(15, y);
    printf("%i", result3);
    return 0;
}
```

**Comment by kinke** [comment]
Not an issue but working as intended.
