### ISSUE TITLE
ldc2 --checkaction=halt produces same binary as --checkaction=D

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3430]
(I want to halt if assertion occured.)

Tried on x86_64 and ARM32

Code for check:
```D
void main()
{
    assert(false, "Please, HLT me!");
}
```

**Comment by kinke** [comment]
Thx for the report. Looks like there's no DMD test for this...

**Comment by denizzzka** [comment]
@kinke Looks like for ARM it emits "undefined" TRAP instruction (0xDEFE) from LLVM's __builtin_trap.

This instruction causes immediate jump to `blocking_handler` vector value what typically contains infinity loop.

But `-checkaction=halt` described as "Halt the program execution (very lightweight)".
Also this jump leads to lose stack trace. Not exactly what is need for debug (To jump into `blocking_handler` it is possible to use more highlevel ways (abort() call, for example.)

Looks like ARM isn't have appropriate "Halt and Catch Fire" instruction?

**Comment by kinke** [comment]
The fix uses the `llvm.trap` intrinsic, just like an `assert(0)` with `-release`. For x86, that's `ud2`. See http://llvm.org/docs/LangRef.html#llvm-trap-intrinsic for the official description. Right below that one, there's `llvm.debugtrap`.

**Comment by denizzzka** [comment]
debugtrap looks as more appropriate at least for ARM - it adds BKPT instruction instead of undefined "TRAP".

From ARM manual:
The BKPT instruction causes the processor to enter Debug state. Debug tools can use this to investigate system state when the instruction at a particular address is reached.

While in debug state, the processor behaves as follows:

* The DBGDSCR[0] core halted bit is set.
* The DBGACK signal is asserted, see DBGACK.
* The DBGDSCR[5:2] method of entry bits are set appropriately.
* The processor is halted. The pipeline is flushed and no instructions are fetched.
* The processor does not change the execution mode. The CPSR is not altered.
* Exceptions are treated as described in Exceptions in debug state.
* Interrupts are ignored.
* New debug events are ignored.

**Comment by kinke** [comment]
Then please play around with it and see if it fits your needs. If it does, open a PR to discuss whether this should be the default, only used with `-g` or for ARM etc.

**Comment by denizzzka** [comment]
I’m afraid to touch ldc sources and don’t know how to test different platforms. I will just create a Issue ticket.

**Comment by kinke** [comment]
You can trivially substitute `trap` by `debugtrap` in https://github.com/ldc-developers/ldc/blob/9a92488007ef9db45b8dc23929ba49749a50b20b/gen/toir.cpp#L1688 (even with the GitHub editor) and then open a draft PR. CI will take care of building and testing everything; you can then download a prebuilt artifact from Azure Pipelines and test it with your code.

Yes, it's really that simple.

**Comment by denizzzka** [comment]
> Azure Pipelines

I am on linux

**Comment by kinke** [comment]
So what? Azure builds all packages.

**Comment by denizzzka** [comment]
Ok, will try it
