### ISSUE TITLE
requires dynamic R_X86_64_32 reloc against '__TMC_END__'

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3435]
I am unfortunately not able to find a solution for my problem. I want to create a SO which has phobos and druntime embedded.
Therefore I execute `ldc2 --static --shared strlenop.d vflow.d` but it causes error:

> /usr/bin/ld.gold: error: /usr/lib/gcc/x86_64-linux-gnu/7/crtbeginT.o: requires dynamic R_X86_64_32 reloc against '__TMC_END__' which may overflow at runtime; recompile with -fPIC
> collect2: error: ld returned 1 exit status

LDC - the LLVM D compiler (1.19.0):
Ubuntu 18.04

Also adding fPIC as DLFAGS or as LDC argument doesn't help. What do I need to add to get a full SO?

**Comment by kinke** [comment]
`-link-defaultlib-shared=false`.

**Comment by andre2007** [comment]
@kinke 
I also tried this parameter and it didn't helped. The same error is displayed.
I prepared now this Dockerfile for easily reproducing the issue:

```Dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl libxml2-dev gcc

RUN curl -LO https://github.com/ldc-developers/ldc/releases/download/v1.21.0/ldc2-1.21.0-linux-x86_64.tar.xz \
    && tar -xf /ldc2-1.21.0-linux-x86_64.tar.xz \
    && ln -s /ldc2-1.21.0-linux-x86_64/bin/dub /bin/dub && ln -s /ldc2-1.21.0-linux-x86_64/bin/ldc2 /bin/ldc2

RUN touch lib.d
RUN ldc2 --static --shared -link-defaultlib-shared=false lib.d
```

**Comment by kinke** [comment]
Get rid of the `-static`, I doubt that can work when generating an .so. The remaining issue has nothing to do with LDC, the problematic .o is from glibc.

**Comment by andre2007** [comment]
Thanks a lot.

For reference this is the correct Dockerfile

``` Dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl libxml2-dev gcc

RUN curl -LO https://github.com/ldc-developers/ldc/releases/download/v1.21.0/ldc2-1.21.0-linux-x86_64.tar.xz \
    && tar -xf /ldc2-1.21.0-linux-x86_64.tar.xz \
    && ln -s /ldc2-1.21.0-linux-x86_64/bin/dub /bin/dub && ln -s /ldc2-1.21.0-linux-x86_64/bin/ldc2 /bin/ldc2

RUN touch lib.d
RUN ldc2 --shared -link-defaultlib-shared=false lib.d
```

**Comment by andre2007** [comment]
@kinke 
Does it make sense to raise an error if  `-static` and `--shared` is passed together as command line arguments?

**Comment by kinke** [comment]
Nope, because that works totally fine with Windows MSVC targets for example (implying `-link-defaultlib-shared=false` and `-mscrtlib=libcmt`). It might also work fine when targeting musl, allowing to link the C runtime statically too, not just druntime and Phobos.
