### ISSUE TITLE
--checkaction=halt should emit call debugtrap instead of trap

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3454]
--checkaction=halt should emit call debugtrap instead of trap

Currently (at least for ARM) it intentionally emits undefined instruction called "TRAP" what causes undefined instruction exception. This leads to run special handler what typically is looks as infinity loop and also loses of stack. (I think purpose of this loop is avoid to disable interrupts handling if something goes wrong)

I affirm that this is not appropriate behaviour. It should emit debugtrap. I do not know about other platforms, but for ARM debugtrap emits BKPT instruction.

From ARM manual:
The BKPT instruction causes the processor to enter Debug state. Debug tools can use this to investigate system state when the instruction at a particular address is reached.

While in debug state, the processor behaves as follows:

* The DBGDSCR[0] core halted bit is set.
* The DBGACK signal is asserted, see DBGACK.
* The DBGDSCR[5:2] method of entry bits are set appropriately.
* The processor is halted. The pipeline is flushed and no instructions are fetched.
* The processor does not change the execution mode. The CPSR is not altered.
* Exceptions are treated as described in Exceptions in debug state.
* Interrupts are ignored.
* New debug events are ignored.

Thus, this is exactly of idea of halting of unrecoverable states. And this is single way to provide debuggable assert() functionality on low level or for bare-metal devices:
If my PCB stalls I just connect to it by something like openocd and gdb and look into stack trace and variables and will do something with this state.

Related: https://github.com/ldc-developers/ldc/issues/3430

**Comment by kinke** [comment]
gcc apparently does the same as LLVM, emitting an undefined instruction for AArch32: [godbolt]

The motivation is apparently a consistent a SIGILL:
https://gcc.gnu.org/legacy-ml/gcc-patches/2010-09/msg00876.html

**Comment by denizzzka** [comment]
What option is this for gcc? I can not find it

**Comment by kinke** [comment]
Oh, this won't work in general. `llvm.debugtrap` isn't `noreturn`. I think it's normally used for debugger breakpoints, which are resumable.

**Comment by denizzzka** [comment]
Huh :-(

Ok, maybe `--checkaction=` can be improved to support user-defined functions?

**Comment by denizzzka** [comment]
...Or jump againt into `llvm.debugtrap` if it exits?

**Comment by kinke** [comment]
druntime is already very flexible in this regard. You can override the `_d_assert*` functions invoked by the compiler, override `core.exception.onAssertError*`, set the `core.exception.assertHandler`...

**Comment by denizzzka** [comment]
> druntime is already very flexible in this regard

Cross-platform will suffer: it forsec me to write my own implementations of debugtrap.

> Edit: Ah, but your goal wrt. -checkaction=halt was to get rid of the unused msg and filename strings in the final binary, right?

No

**Comment by kinke** [comment]
Well if you don't care about the strings, this should be as trivial as:
```D
void myAssert(string file, size_t line, string msg)
{
    import ldc.intrinsics;
    llvm_debugtrap();
    llvm_trap();
}

// in druntime init:
core.exception.assertHandler = myAssert;
```

**Comment by denizzzka** [comment]
> jump again into llvm.debugtrap if it exits?

Thinking about this idea: it is much better than exception handler `while(1){}` provided for now by `llvm.trap` implementation for ARM.

And looks like --checkaction= is unique ldc option? Here is chanse to set up new de-facto standart :-)

**Comment by denizzzka** [comment]
> this should be as trivial as

Thanks, will try it

**Comment by kinke** [comment]
debugtrap followed by trap might actually work for `-checkaction=halt`, giving the debugger a chance to break, and otherwise yield a SIGTRAP instead of SIGILL on Linux.

**Comment by denizzzka** [comment]
Disadvantage of userOwnAssert function: it works only if assertion isn't thrown inside of druntime before D main started. Or user should replace functions by using some linker tricks (exclude one function, add another) or just patch druntime (my way for now)

> giving the debugger a chance to break (and immediately SIGILL when continuing

Sounds good. And if user don't want to deal with these lowlevel traps he just choises `-checkaction=C/D`

**Comment by kinke** [comment]
[The user can set the handler in a `pragma(crt_constructor)`, that will be executed before druntime is initialized.]

**Comment by denizzzka** [comment]
> giving the debugger a chance to break (and immediately SIGILL when continuing - or looping forever as in your case)

I changed my mind about this "chance". If CPU will continue run it will enable interrupts handling.
I.e., after a long period stop program will partially start working again. It mat cause unpredictable consequences.

Simple looping around debugtrap is better.

**Comment by kinke** [comment]
A static assert cannot be 'overridden' anyway, it's an instruction for the compiler only.

You might be focused at the wrong spot. Have you checked whether we have this infinite loop on regular Linux/ARM too? I doubt we could have missed this all this time if that'd happen for `assert(0)` with `-release`. So if Linux is okay, you might have to get to the bottom of the infinite loop.

**Comment by denizzzka** [comment]
> A static assert cannot be 'overridden' anyway, it's an instruction for the compiler only.

Yes. And I sucessfully redirect static asserts into libc by `--checkaction=C`. And it will be great if instead debugtrap will called if `=halt` used.

> You might be focused on the wrong spot.

Here is nothing wrong - this "infinity loop" is "behaviuor by design" for ARM MCUs. This is hardware  exception.

Pointer to this `blocking_handler` placed into CPU's interrupts table by Hardware Abstraction Library (libopencm3). CPU calls this handler if something like undefined instruction is catched. It works great.

But this exception is not designed for debugging: CPU isn't stopped and stack is loses

**Comment by kinke** [comment]
> And I sucessfully redirect static asserts into libc by --checkaction=C.

Lol, show me that. Or actually, don't.

> CPU calls this handler if something like undefined instruction is catched. It works great.
But this exception is not designed for debugging: CPU isn't stopped and stack is loses

So why don't you install your own handler for undefined instructions? You know the exact bytes emitted by `llvm.trap()` and can then halt the CPU or whatever you want. Then a debugtrap + trap combo should work nicely, right?

**Comment by denizzzka** [comment]
> So why don't you install your own handler for undefined instructions? 

Because:
* unjustified complication of handler what will be used temporary in many cases
* it is need to catch also really undefined instructions.
* I think what `=halt` means "CPU halt", not "recoverable hardware exception without stopping CPU"
* `=halt` isn't used anybody (it was fixed only days ago) and its behaviour can be fixed without pain

**Comment by kinke** [comment]
A loop around debugtrap simply isn't acceptable for all normal targets which don't continue after an invalid/trap instruction emitted by LLVM. I'm sympathetic to the idea of debugtrap + trap though.

**Comment by denizzzka** [comment]
Why do not to use debugtrap loop for all targets?

> I'm sympathetic to the idea of debugtrap + trap though.

With enough ingenuity this can be deadly in the case of some kind of built-in devices :-)

**Comment by denizzzka** [comment]
Idea: improve `--checkaction=` by `halt_debug` option
halt emits trap, halt_debug emits debugtrap

**Comment by denizzzka** [comment]
> Another disadvantage of using myAssert function: it isn't replaces static assert

haha :-) I don’t know why I wrote this, I need to get more sleep :-)

I worry only about "unconditional" assert errors at "dead end" branches what can be found in -release binaries too

**Comment by denizzzka** [comment]
So, since new release is coming, new threads code is merged from druntime upstream and also on the D forum detected activity regarding the launch of runtime on bare metal, can we get back to this question?

It is currently very inconvenient to debug druntime on tiny ARM MCU without something like this:

> Idea: improve --checkaction= by halt_debug option
> halt emits trap, halt_debug emits debugtrap loop

**Comment by kinke** [comment]
My opinion hasn't changed a bit, certainly not by 2.094 or some forum activity. A custom assert handler in druntime or a custom interrupt handler just makes much more sense to me.

**Comment by denizzzka** [comment]
1. Behavior is awkward to switch by this way
2. What is the point of all remaining --checkaction option values? They can be overridden in the same way

**Comment by kinke** [comment]
1. Completely subjective. As clang or gcc don't have such a thing AFAIK, a library solution seems to be *the* standard way of tackling this, and being able to override the assert handler in druntime is anything but awkward. [You can also use `-checkaction=C` and provide your own C assert function to link with if you prefer that one...]
2. They all make sense; `context` is for improved diagnostics, `C` required for `-betterC` anyway, and `halt` e.g. useful to eliminate static strings (assert messages and filenames). A loop around a non-`noreturn` intrinsic, to be emitted as inline code by the compiler instead of a trivial little library function, might seem the least painful way to you for your particular scenario, but a compiler is about genericity. You're free to implement it yourself, and if you can convince a lot of other people about its usefulness, I'm happy to merge it.

**Comment by kinke** [comment]
Something more generic would be something like `-checkaction=haltLib`, which would call some predefined hook in druntime (C function or a template) instead of emitting `llvm.trap` directly. Unlike the C/D assert hooks, it wouldn't receive any strings, thereby eliminating them from the object files, and at the same time give the user full control over what it should actually do, so that you could use your little loop around `llvm_debugtrap()`...
