### ISSUE TITLE
When compiling with LDC2 and MSVC 2019 toolchain, linker cannot find libcmt.lib

### ISSUE THREAD

**Issue by spikespaz** [ldc-developers/ldc#3458]
I have set `LDC_VSDIR`, `LDC_VSDIR_FORCE` and `VSINSTALLDIR` as appropriate. On LDC 1.20.1, this compiles fine. The problem occurred after upgrading to LDC 1.21.0 multilib. I was using multilib before.

```
ldc2 source/deflector.d -i -I source -J build/vars -of build/bin/deflector.exe -m32 -O3 -ffast-math -release -L/subsystem:windows -L/entry:mainCRTStartup -d-version free_version
libcmt.lib(exe_main.obj) : error LNK2019: unresolved external symbol _main referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
build\bin\deflector.exe : fatal error LNK1120: 1 unresolved externals
Error: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86\link.exe failed with status: 1120
```

**Comment by kinke** [comment]
The linker complains about something different, your narrow entry point. See https://github.com/ldc-developers/ldc/issues/3436#issuecomment-631089809.

**Comment by spikespaz** [comment]
For future reference, change `-L/entry:mainCRTStartup` to `-L/entry:wmainCRTStartup`. This difference between the old and new flags required is easy to overlook.
