### ISSUE TITLE
linker error with scope(exit) with betterC

### ISSUE THREAD

**Issue by CodeMyst** [ldc-developers/ldc#3479]
so i dont really know much about compilers or linkers but i managed to create a reproducible code snippet which breaks only when using ldc.

https://run.dlang.io/is/NH9MGM
```d
extern(C) int main() {
    int a = 5;
    scope(exit) a = 6;

    create(0, 1, "2");

    return 0;
}

void create(uint a, uint b, string c) {
}
```

the error is:
```
onlineapp-2f059b3.o:onlineapp.d:DW.ref._d_eh_personality: error: undefined reference to '_d_eh_personality'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
```

if you uncomment either the `scope(exit)` line or the `create` line everything compilers and works ok.

i dont know how to go even further with finding the cause of the issue so just gonna drop this here. this might be something obvious or an actual compiler/linker bug.

**Comment by CodeMyst** [comment]
also seems like marking `create` with `nothrow` fixes it

**Comment by kinke** [comment]
I've added this to https://issues.dlang.org/show_bug.cgi?id=20897.

**Comment by kinke** [comment]
Thx for the report.
