### ISSUE TITLE
ExceptionModel for bare metal targets?

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3483]
Hi!

When I trying to build binary for mtriple `thumbv7m-unknown-none-eabi` compiler uses ExceptionModel == None. (According to this PR: https://github.com/ldc-developers/ldc/pull/3481 It adds logging of currently used ExceptionModel.)

This is not suitable because I don't use -betterC.

Currently I use external build of LLVM's libunwind, what wants to receive ARM EHABI exceptions.
But actually I don't know how to solve this problem: it is possible what another bare metal project will use DWARF exceptions?

Also, it is possible to prohibit generating of exceptions at all if ExceptionModel == None? To prevent unwinding errors at compiling stage.

**Comment by kinke** [comment]
There's a (hidden) `-exception-model` cmdline option:
```
$ ldc2 -help-hidden
...
  --exception-model=<value>                                       - exception model
    =default                                                      -   default exception handling model
    =dwarf                                                        -   DWARF-like CFI based exception handling
    =sjlj                                                         -   SjLj exception handling
    =arm                                                          -   ARM EHABI exceptions
    =wineh                                                        -   Windows exception model
    =wasm                                                         -   WebAssembly exception handling
...
```

Our team doesn't feature any ARM experts at the moment, so you're probably better off researching/asking such in-depth stuff for LLVM/clang in general.

**Comment by kinke** [comment]
> Also, it is possible to prohibit generating of exceptions at all if ExceptionModel == None? To prevent unwinding errors at compiling stage.

I think exceptions cannot be used if object.d doesn't contain a `Throwable` class. IIRC, that was one of the steps towards a 'pay-as-you-go'-druntime a couple of years ago, just like suppressing TypeInfo and ModuleInfo emission if their classes aren't in object.d, independent from `-betterC`. JinShil (Mike Franklin) would have been your man at the time.

**Comment by denizzzka** [comment]
> I think exceptions cannot be used if object.d doesn't contain a Throwable class.

But it contains - I almost made work of a regular druntime on bare metal. (druntime unittests what deal with exceptions cause this issue.)

**Comment by denizzzka** [comment]
> There's a (hidden) -exception-model cmdline option:

Aha, tried it. It changes `targetOptions.ExceptionModel` value.
But unwinding isn't fixed with `--exception-model=arm`

Looks like this option isn't affects produced binary: binaries with `None` ExceptionModel and `ARM` are equal.

Interesting what `--exception-model=dwarf` option produces different binary.

**Comment by denizzzka** [comment]
Also I compared `$ ldc2 -vv` logs for DWARF and ARM builds - they are strictly identical

**Comment by denizzzka** [comment]
Addition: unwinding fails in libunwind with `_URC_FATAL_PHASE1_ERROR`

libunwind.cpp:
```C
/// Get unwind info at cursor position in stack frame.
_LIBUNWIND_HIDDEN int __unw_get_proc_info(unw_cursor_t *cursor,
                                          unw_proc_info_t *info) {
  _LIBUNWIND_TRACE_API("__unw_get_proc_info(cursor=%p, &info=%p)",
                       static_cast<void *>(cursor), static_cast<void *>(info));
  AbstractUnwindCursor *co = (AbstractUnwindCursor *)cursor;
  co->getInfo(info);
  if (info->end_ip == 0)
    return UNW_ENOINFO; // failed from here - all info struct is empty
  return UNW_ESUCCESS;
}
```

**Comment by denizzzka** [comment]
Need an idea how to check availability of information for unwind at stack. I suspect that this info is being created but in an improper format.

**Comment by kinke** [comment]
> > > Also, it is possible to prohibit generating of exceptions at all if ExceptionModel == None?
> >
> > I think exceptions cannot be used if object.d doesn't contain a Throwable class.
>
> But it contains

The idea is that e.g. people who don't want exceptions can simply get rid of that class in object.d.

> Also I compared $ ldc2 -vv logs for DWARF and ARM builds - they are strictly identical

Yeah, LDC doesn't use that option at all, that's an LLVM option. No diffs will show up in any LDC log or .ll IR. And that's why I suggested you should research/ask LLVM/clang in general if you suspect that option to be of relevance in your case.

---

I guess you aware of https://github.com/ldc-developers/druntime/blob/ldc/src/rt/dwarfeh.d and https://github.com/ldc-developers/druntime/blob/ldc/src/ldc/eh_asm.S. Note that exception chaining makes D EH considerably more complex than regular C++ EH. For debugging, make sure to uncomment https://github.com/ldc-developers/druntime/blob/cc97ccd00d4082221eee1d5afdbd775201d75877/src/rt/dwarfeh.d#L14. That's about as much assistance as I can give though.

**Comment by denizzzka** [comment]
> That's about as much assistance as I can give though.

Some more questions, please!

> Yeah, LDC doesn't use that option at all, that's an LLVM option.

LLVM infrastructure or libunwind must push unwinding info to stack?

`throw(some_exception_class)` immediately calls druntime's `_d_throw_exception` (I see this by walking using GDB step-by-step debug). Here is no any compiler intrisincs or additional libunwind call to put unwinding info of any format.

`_d_throw_exception` stores D-related info (pushes chain of exceptions to stack and sets exception cleanup callback) and then tries to unwind by calling
```D
auto r = _Unwind_RaiseException(&eh.exception_object);
```
Thats all! I don't see where is ARM or DWARF unwinding info was issued.

.ARM.extab and .ARM.exidx (or .eh_frame .eh_frame_hdr for DWARF) contains statical info what placed into ROM, so this is not all things what is need to unwind something what thrown on specific line.

**Comment by denizzzka** [comment]
Careful step by step debugging results:

Unwinding failing starts when it tries to get first needed function at address `0x80392ae`.
`.ARM.exidx` corresponds this adress to `_Unwind_SetGR` function.
And this function marked by a "sentinel" value `UNW_EXIDX_CANTUNWIND`

```
$ readelf -u  firmware.elf | grep cantunwind
0x80391e0 <_d_eh_GetIP>: 0x1 [cantunwind]
0x80391f2 <_Unwind_GetIP>: 0x1 [cantunwind]
0x803920a <_d_eh_SetIP>: 0x1 [cantunwind]
0x8039220 <_Unwind_SetIP>: 0x1 [cantunwind]
0x803924c <_d_eh_GetGR>: 0x1 [cantunwind]
0x8039262 <_Unwind_GetGR>: 0x1 [cantunwind]
0x8039294 <_d_eh_SetGR>: 0x1 [cantunwind]
0x80392ae <_Unwind_SetGR>: 0x1 [cantunwind]
0x803da20 <__aeabi_memcpy8>: 0x1 [cantunwind]
0x8049210 <reset_handler+0x90>: 0x1 [cantunwind]

```

**Comment by denizzzka** [comment]
This also isn't looks like index mismatch because before and after of _Unwind_SetGR also placed some unrelated functions:
```
0x8039262 <_Unwind_GetGR>: 0x1 [cantunwind]

0x8039294 <_d_eh_SetGR>: 0x1 [cantunwind]

0x80392ae <_Unwind_SetGR>: 0x1 [cantunwind]

0x803c9e4 <_D8external4core5abortQgFNbNiNfMAyaMQekZv>: @0x8055d68
  Compact model index: 1
  0x97      vsp = r7
  0x41      vsp = vsp - 8
  0x84 0x0b pop {r4, r5, r7, r14}
  0xb0      finish
  0xb0      finish

0x803ca04 <_D8external4core5abort16__moduleinfoCtorZ>: 0x80b0b0b0
  Compact model index: 0
  0xb0      finish
  0xb0      finish
  0xb0      finish
```

**Comment by denizzzka** [comment]
Probably, this issue is inspired by wrong value at IP (r12) register.

r12 is checked by LLVM libunwind. It should contain correct address of function before unwinding starts.

**Comment by denizzzka** [comment]
Current state of investigation:
looks like binary search of unwinding functions goes crazy because linker attaches .ARM.exidx sections by wrong way.

**Comment by kinke** [comment]
That sounds like a reasonable lead. After all, I remember the last test runs on ARMv6 (with hard-float ABI) on Linux being basically green, with a std.random unittest failure with enabled optimizations, which appeared to be caused by inlining messing with EH, but otherwise EH was no issue. After a quick glance, the only thing (from LDC/druntime side) that *might* but probably doesn't cause a divergence for your baremetal case is https://github.com/ldc-developers/druntime/blob/cc97ccd00d4082221eee1d5afdbd775201d75877/src/rt/dwarfeh.d#L929-L930.

**Comment by denizzzka** [comment]
> After a quick glance, the only thing (from LDC/druntime side) that might but probably doesn't cause a divergence for your baremetal case is https://github.com/ldc-developers/druntime/blob/cc97ccd00d4082221eee1d5afdbd775201d75877/src/rt/dwarfeh.d#L929-L930.

Execution does not reach to this place. It falls before, at the phase 1 of unwinding inside of libunwind.

My build uses Meson what creates hundreds object files. Although everything appropriate flags (SHF_LINK_ORDER) inside the files is there, but something is going wrong

**Comment by denizzzka** [comment]
Problem solved! It was on my side, not related to LDC or LLVM.

libunwind was built by clang with disabled exceptions (because I do not want to use C++ exceptions)
This leads to producing wrong .ARM.exidx tables (all C++ functions was marked as `cantunwind` in ELF object files and linker)

`-funwind-tables` added to `clang` solves this issue and unwinding works fine!
