### ISSUE TITLE
Compile time string concatenation with betterC fails to compile (DMD works with the same code)

### ISSUE THREAD

**Issue by dbankov-vmware** [ldc-developers/ldc#3488]
The following code:
``` D
import core.stdc.stdio;

///
string generateSubTypeDefinition()
{
    string result = "enum SubType : ubyte ";
    result ~= "{ a = 0 }";
    return result;
}

///
enum subTypeDefinition = generateSubTypeDefinition();
debug pragma(msg, subTypeDefinition);
mixin(subTypeDefinition);

extern(C) int main()
{
    printf("SubType.a = %d\n", SubType.a);
    return 0;
}
```
compiles successfully with DMD but fails with LDC and outputs the following (with LDC):
>Performing "debug" build using ldc2 for x86_64.
>dcatest ~master: building configuration "application"...
>enum SubType : ubyte { a = 0 }
>Error: TypeInfo cannot be used with -betterC
>ldc2 failed with exit code 1.
If the concatenation of the string in generateSubTypeDefinition is removed i.e. the following code:
``` D
import core.stdc.stdio;

///
string generateSubTypeDefinition()
{
    string result = "enum SubType : ubyte { a = 0 }";
    return result;
}

///
enum subTypeDefinition = generateSubTypeDefinition();
debug pragma(msg, subTypeDefinition);
mixin(subTypeDefinition);

extern(C) int main()
{
    printf("SubType.a = %d\n", SubType.a);
    return 0;
}
```
Compiles successfully with both DMD and LDC and produces the following output (with LDC):
>Performing "debug" build using ldc2 for x86_64.
>dcatest ~master: building configuration "application"...
>enum SubType : ubyte { a = 0 }
>Linking...
>Running ./dcatest 
>SubType.a = 0

**Comment by kinke** [comment]
A different CTFE behavior would be very surprising (all in the frontend), and according to run.dlang.io, DMD doesn't accept it either: https://run.dlang.io/is/fBz0aW

**Comment by dbankov-vmware** [comment]
I'm sorry must have missed to pass -betterC to DMD.

I'll file a bug for the frontend.

Thanks for taking a look and I'm sorry for my mistake.
