### ISSUE TITLE
Assertion triggered with separate compilation of interface methods

### ISSUE THREAD

**Issue by jpiles** [ldc-developers/ldc#3496]
When doing separate compilation, if an interface method is declared but not implemented it triggers an Assertion:

This happens both with `static` and with `final` methods:
```d
void bar() {
    I.foo;
}

interface I {
    static void foo();
}
```

```d
void bar() {
    (new class I{}).foo;
}

interface I {
    final void foo();
}
```

Trying to compile either version of the code with `ldc2 -c a.d` triggers:

```
ldc2: /build/ldc-h5SR24/ldc-1.21.0/ir/irfunction.cpp:79: llvm::Function* IrFunction::getLLVMCallee() const: Assertion `func != nullptr' failed.
```

Both versions compile properly using `dmd` and `gdc`. Tried with debian sid ldc:

```
LDC - the LLVM D compiler (1.21.0):
  based on DMD v2.091.1 and LLVM 9.0.1
  built with LDC - the LLVM D compiler (1.21.0)
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver1
  http://dlang.org - http://wiki.dlang.org/LDC
```

and also on run.dlang.io with the same results.

**Comment by kinke** [comment]
Thx for the report.
