### ISSUE TITLE
Building ldc with the old bootstrap do not works for any llvm version upper or equal to 10

### ISSUE THREAD

**Issue by bioinfornatics** [ldc-developers/ldc#3508]
As the reference line show, version >= to 10 do not enter at line 109 due to the range number between 4 to 9 included

https://github.com/ldc-developers/ldc/blob/911589c168cd28b7e0c7973083cbe455a64f029d/cmake/Modules/FindLLVM.cmake#L109

I suggest something like

```
 if(${LLVM_VERSION_STRING} MATCHES "^([4-9]|[1-9][0-9]\\.[\\.0-9A-Za-z]*") 
```

which should works up to llvm version 99

possible error encountered:

```
…
+ cmake -DLLVM_CONFIG:PATH=/usr/bin/llvm-config-64 ../ldc-0.17.6-src
-- The C compiler identification is GNU 10.1.1
-- The CXX compiler identification is GNU 10.1.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
llvm-config: unknown component name: ipa
CMake Error at cmake/Modules/FindLLVM.cmake:49 (message):
  Failed to execute llvm-config ('/usr/bin/llvm-config-64', result code: '1)'
Call Stack (most recent call first):
  cmake/Modules/FindLLVM.cmake:176 (_LLVM_FAIL)
  cmake/Modules/FindLLVM.cmake:223 (llvm_set_libs)
  CMakeLists.txt:18 (find_package)

...
```

**Comment by kinke** [comment]
That's just the first surfacing issue and wouldn't be enough by any means ltsmaster supports up to v7, but not anything newer. See #3109 and #3138.

**Comment by bioinfornatics** [comment]
Indeed :-)

Maybe put the bootstrap support as deprecated

**Comment by kinke** [comment]
Quoting README.md:
> (DMD, GDC and LDC are supported as host compilers. For bootstrapping purposes, we recommend GDC via its gdmd wrapper. Alternatively, LDC 0.17, the last version not to require a D compiler, is maintained to some degree in the ltsmaster branch.)

**Comment by kinke** [comment]
And the [Wiki](https://wiki.dlang.org/Building_LDC_from_source):
> If there's no suitable prebuilt D compiler for your platform: LDC 0.17 is the last version that does not need a D compiler to be built. Thus for bootstrapping, you can first build 0.17, and then use that to build newer compiler versions. [...] Note that it doesn't support the latest LLVM versions.

**Comment by bioinfornatics** [comment]
Thanks @kinke ;-)

and thanks again for all your works on ldc 
Have a nice day

**Comment by kinke** [comment]
Thx for the kind words, have a nice day too.
