### ISSUE TITLE
ubyte x; x >>= 8; is not zero on arm

### ISSUE THREAD

**Issue by Ewa-D** [ldc-developers/ldc#3514]
This simple unittest fails on -mtriple=armv7-none-linux-androideabi

```
unittest
{
	void test(T)(T v) if (T.sizeof == 1)
	{
		{
			T value = v;
			value >>= 8;
			assert(value == 0);
		}
		{
			T value = v;
			value <<= 8;
			assert(value == 0);
		}
	}

	test!ubyte(10);
	test!byte(10);
	test!char(10);
}

```

**Comment by kinke** [comment]
Shifting by N with N >= bit width of operand is undefined behavior IIRC. If you expected int promotion + truncation, then don't use `value >>= N`, but `value = value >> N`.

**Comment by Ewa-D** [comment]
value = cast(ubyte)(value >> 8); looks very ugly, why we can't make D language easy?

I think, value >>= 8 with type ubyte must be 0, it is not undefined behavior. In assembler it is not undefined behavior. LDC translate code to assembler.

If you release undefined behavior, this construction can generate potential errors.

**Comment by Ewa-D** [comment]
![image](https://user-images.githubusercontent.com/68651850/88204795-42a38f80-cc65-11ea-8110-bfc6a0c5b77c.png)
![image](https://user-images.githubusercontent.com/68651850/88204818-49ca9d80-cc65-11ea-9bb5-e21ee59f7f09.png)

**Comment by JohanEngelen** [comment]
It's illegal to shift by the same or more bits than the size of the quantity being shifted:
https://dlang.org/spec/expression.html#shift_expressions

For rationale, you can find a lot about it online. For example, https://stackoverflow.com/questions/19636539/arithmetic-right-shift-gives-bogus-result/19636588#19636588
