### ISSUE TITLE
unaligned float/double on arm

### ISSUE THREAD

**Issue by Ewa-D** [ldc-developers/ldc#3515]
-mtriple=armv7-none-linux-androideabi

```
unittest
{
	char[] data = [1, 2, 0xc9, 0x76, 0xbe, 0x9f, 0x0c, 0x24, 0xfe, 0x40, 5, 6, 7, 8];
	// aligned ulong OK
	writeln("ulong =", *cast(ulong *)((cast(void *)data.ptr) + 0));
	// unaligned ulong OK
	writeln("ulong =", *cast(ulong *)((cast(void *)data.ptr) + 2));
	// unaligned double FAIL with SIGBUS
	writeln("double =", *cast(double *)((cast(void *)data.ptr) + 2));
}

```

**Comment by kinke** [comment]
To be expected, isn't it?

**Comment by Ewa-D** [comment]
Do you think it is not bug?

**Comment by Ewa-D** [comment]
I know, arm is not supported read floating from unaligned memory, but compiler can do it, just change assembler code for this operation. As you can see, we can read unaligned ulong, and then compiler could translate it into float.

**Comment by JohanEngelen** [comment]
@Ewa-D This is a user error. You are forcing a read from an address that is only guaranteed to be valid for `char`, you are on your own here. All the pointer casting should be a clear sign that the compiler is not going to help you.

**Comment by dnadlinger** [comment]
Indeed, in D, pointers are always assumed to be aligned. (Otherwise, all memory access would be super slow – they'd need to be pieced together byte by byte!)

You might want to check out https://forum.dlang.org/group/learn for questions like these.
