### ISSUE TITLE
Great thanks to your community to call me "idiot" again.

### ISSUE THREAD

**Issue by ghost** [ldc-developers/ldc#3518]
Thank you mr. Dejan Lekic, to call me "idiot" and block all new messages on D forum.
You are great man.
You project have no future until you are allow this phrases.

**Comment by kubo39** [comment]
FWI: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by dnadlinger** [comment]
What somebody else did or did not say some other place really doesn't belong on the issue tracker.
