### ISSUE TITLE
LDC2 1.23.0-beta1 segfaults

### ISSUE THREAD

**Issue by uvm** [ldc-developers/ldc#3526]
The following code segfaults LDC2 1.23.0-beta1 release. Complies without error with dmd 2.093 release.

```d
class Foo {
  int[] _foo;
  size_t length () {
    return _foo.length;
  }
}
class Frop {
  static Frop get() {
    Frop _inst = new Frop();
    return _inst;
  }
  Bar _bar = new Bar();
  Foo _foo = new Foo();
}
class Bar {
  static Bar bar() {return Frop.get()._bar;}
  static Foo foo() {return Frop.get()._foo;}
}
void main() {
  if (Bar.bar.foo.length == 0) {}
}
```

**Comment by kinke** [comment]
This appears to be a frontend issue, although DMD requires e.g. `-vcg-ast` to crash. The v1.22/2.092 lowering with `-vcg-ast` is kinda weird (not just because of `return 0` for a main returning `void`...):
```D
void main()
{
	if ((bar() , foo)().length() == 0LU)
	{
	}
	return 0;
}
```

**Comment by kinke** [comment]
Filed upstream: https://issues.dlang.org/show_bug.cgi?id=21123
