### ISSUE TITLE
Bug: LDC has reverse unittests order than DMD

### ISSUE THREAD

**Issue by ClaraZetkin** [ldc-developers/ldc#3529]
Here's a simple example, just unpack and
run file "make.dmd" to see dmd result, and
run file "make.ldc" to see ldc result

[test_bug.tar.gz](https://github.com/ldc-developers/ldc/files/4990577/test_bug.tar.gz)

DMD result
```
a_test
b_test
c_test
3 unittests passed
```

LDC result
```
c_test
b_test
a_test
3 unittests passed
```

In this issue #3516
I told you just to divide this example to several packages, because your godbolt is not allowed it.
And you laughed at it. In this connection, the question arose, what actually was funny about that?

Why are you closed this issue https://github.com/ldc-developers/ldc/issues/3528 ?
Bug not fixed. Is this a form of discrimination?

**Attention!**
**In the case of insults, laughter, sarcasm, sexual harassment or racial discrimination,
a copy of your messages will be sent to the police.**

**Comment by dnadlinger** [comment]
Again, harassment and threats will not be tolerated here. Blocked.
