### ISSUE TITLE
Use a command file for linker arguments

### ISSUE THREAD

**Issue by rmanthorpe** [ldc-developers/ldc#3535]
On Windows I recently found the link command LDC was generating exceeded the command line length limit:

```
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe failed with status: -1
Error: message: Couldn't execute program 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe': The filename or extension is too long.  (0xCE)
```
The fix for this is writing the arguments to a file and supplying that file name as a linker argument instead. [DMD does it once the args exceed 7000 characters](https://github.com/dlang/dmd/blob/457710b09c1b2370a17b73b517d57c00636debf8/src/dmd/link.d#L432) which seems pretty sensible.

**Comment by kinke** [comment]
Thx for the report.

**Comment by rmanthorpe** [comment]
Thanks for the quick fix!
