### ISSUE TITLE
llvm 11 support

### ISSUE THREAD

**Issue by kalev** [ldc-developers/ldc#3543]
I'm doing my bi-yearly ldc update in Fedora (ahead of the upcoming F33 release) and noticed that the latest ldc version released yesterday doesn't support llvm 11. Fedora 33 main llvm version was bumped to 11.0.0 rc1 already.

Would it be possible to fix this and release ldc 1.23.1 follow-up release in a few weeks (so I can still get it in F33) with llvm 11 support, please? :) I would assume the ABI/API should be mostly stable from rc1 onwards.

**Comment by kinke** [comment]
Sorry, but I don't deal with pre-release LLVM versions. By the looks of it, v11 will be significantly delayed once again.

**Comment by kalev** [comment]
OK, fair enough. Thanks anyway!

**Comment by kinke** [comment]
Feel free to ping once the F33 window is about to close (maybe a week in advance); if the RC2 is available at that time, I might be willing to prepare our LLVM fork and check for API changes etc. - There's also (most likely outdated) and incomplete https://github.com/ldc-developers/ldc/pull/3322.

**Comment by kalev** [comment]
Sounds like a good plan. Thanks again!

**Comment by kalev** [comment]
OK, from Fedora's point of view, it would be good to get the llvm 11 support in soon if you have time to finalize this. F33 Beta Freeze is over and Final Freeze starts in 2 weeks.

**Comment by kinke** [comment]
See #3546, it's ready and with rc3 a test regression has been fixed as well. I'll merge it before releasing the next beta, most likely somewhen in the next 7 days.

**Comment by kalev** [comment]
Awesome, thanks! That's perfect timing for me.

**Comment by kinke** [comment]
There's still a high-impact [AArch64 regression](https://bugs.llvm.org/show_bug.cgi?id=47679) with LLVM 11-rc4; if that isn't fixed before the Fedora freeze, a workaround in druntime might be required.

**Comment by kinke** [comment]
The regression has been fixed, and LLVM 11 support is in master. You can use d33f6f9bbde88e2096a663b9d1aad490ce253d5b for a 2.093-based version (basically v1.23.0 + some non-dangerous fixes + LLVM 11 support) if you don't want to go with the upcoming beta.

**Comment by kalev** [comment]
Excellent, thanks! Any chance you could do a 1.23.1 release with it? :)

**Comment by kinke** [comment]
I don't really see the point; a distro using a non-final LLVM version is probably not a common scenario, and doesn't warrant an extra tag IMO, especially if the beta is around the corner.

**Comment by kalev** [comment]
OK, fair enough. Thanks again!

**Comment by kinke** [comment]
In case you're looking for the src tarball, it's here: https://github.com/ldc-developers/ldc/releases/download/CI/ldc-d33f6f9b-src.tar.gz - for now, those artifacts are cleaned up from time to time, so I cannot guarantee it's available for as long as you need it, so copy it in case.

**Comment by kalev** [comment]
That's useful, thanks. I've downloaded it now; I'll take a look at getting it built tomorrow.
