### ISSUE TITLE
Corrupted delegate context

### ISSUE THREAD

**Issue by rmanthorpe** [ldc-developers/ldc#3553]
Does this have something to do with dual-context? It needs the original delegate context and the context from inside `makeDelegate`.

```d
auto makeDelegate(alias fn)(long l) {
    auto callIt() {
        return fn() * l;
    }
    return &callIt;
}

void main()
{
    int i = 7;
    auto dg = makeDelegate!(() => i)(3);
    assert(dg() == 21); //Assertion failure
}
```

Interestingly if you wrap up `fn` in another template it's fine.

```d
auto makeDelegate(alias fn)(long l) {
    auto callIt() {
        return wrapIt!fn() * l;
    }
    return &callIt;
}

auto wrapIt(alias fn)()
{
    return fn();
}

void main()
{
    int i = 7;
    auto dg = makeDelegate!(() => i)(3);
    assert(dg() == 21);
}
```

**Comment by kinke** [comment]
Thx for the nicely reduced testcase. It has nothing to do with dual-context, this is just a normal chain of contexts, and `callIt` apparently forwards the wrong one (from `makeDelegate`) to the lambda, which actually needs the parent `main` context.
