### ISSUE TITLE
Calling a method of the outermost class from a class defined in a multiple stratum in a method causes a Segfault (LDC2 1.23.0)

### ISSUE THREAD

**Issue by kntroh** [ldc-developers/ldc#3556]
When I compile and run this code, I get a segfault. There was no problem with dmd 2.093.1.

```D
import std.stdio;

class C {
    void func() {
        writeln("hello world!");
    }
    void run1() {
        class C2 {
            class C3 {
                void run3() {
                    func();
                }
            }
            void run2() {
                auto c3 = new C3;
                c3.run3();
            }
        }
        auto c2 = new C2;
        c2.run2();
    }
}

void main() {
    auto c = new C;
    c.run1();
}
```

Windows 10 Pro (64-bit):

    $ ldc2-1.23.0-windows-multilib\bin\ldc2 -run test.d
    Error: C:\Users\***\AppData\Local\Temp\test-417097a-fa96f5.exe failed with status: -1073741819
    Error: program received signal 1073741819

Linux Mint 19.3 (64-bit):

    $ ldc2-1.23.0-linux-x86_64/bin/ldc2 -run test.d
    Error: /tmp/test-896560f-8a2e3b failed with status: -2
           message: Segmentation fault (core dumped)
    Error: program received signal 2 (Interrupt)

**Comment by kinke** [comment]
Thx for the nicely reduced testcase.

**Comment by kntroh** [comment]
Thanks for the fix.
