### ISSUE TITLE
Intermittent segfault crashes in std.experimental.logger

### ISSUE THREAD

**Issue by chances** [ldc-developers/ldc#3569]
OS: elementary OS 5.1.7 Hera (Ubuntu 18.04.4 LTS)

LDC - the LLVM D compiler (1.20.1):
  based on DMD v2.090.1 and LLVM 9.0.1
  built with LDC - the LLVM D compiler (1.20.1)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake

Linker: GNU ld (GNU Binutils) 2.34

It looks like my callback is run on a separate thread launched by [Ultralight](https://ultralig.ht/), but I don't think that is the issue because the `std.experimental.logger.info` call performs normally closer to the time the application starts.

I see this segfault after I let the application idle and then invoke the action that invokes my callback.

## Stack Trace

```
_D2rt8monitor_13ensureMonitorFNbC6ObjectZPOSQBqQBq7Monitor (Unknown Source:0)
_d_monitorenter (Unknown Source:0)
_D3std12experimental6logger4core6Logger__T15memLogFunctionsVEQChQCgQBvQBr8LogLeveli64Z__T7logImplVii143VAyaa30_736f757263652f75692f62696e64696e67732f63616c6c6261636b732e64VQCqa42_75692e62696e64696e67732e63616c6c6261636b732e67726f636572795f756c5f6f70656e5f66696c65VQGea92_65787465726e2028432920696e742075692e62696e64696e67732e63616c6c6261636b732e67726f636572795f756c5f6f70656e5f66696c6528766f69642a20706174682c20626f6f6c206f70656e5f666f725f77726974696e6729VQNoa21_75692e62696e64696e67732e63616c6c6261636b73TQPmZQQfMFNfLQPyZv (/home/chances/dlang/ldc-1.20.1/import/std/experimental/logger/core.d:961)
_D3std12experimental6logger4core__T18defaultLogFunctionVEQCdQCcQBrQBn8LogLeveli64Z__TQByVii143VAyaa30_736f757263652f75692f62696e64696e67732f63616c6c6261636b732e64VQCqa42_75692e62696e64696e67732e63616c6c6261636b732e67726f636572795f756c5f6f70656e5f66696c65VQGea92_65787465726e2028432920696e742075692e62696e64696e67732e63616c6c6261636b732e67726f636572795f756c5f6f70656e5f66696c6528766f69642a20706174682c20626f6f6c206f70656e5f666f725f77726974696e6729VQNoa21_75692e62696e64696e67732e63616c6c6261636b73TQPmZQRyFNfLQPxZv (/home/chances/dlang/ldc-1.20.1/import/std/experimental/logger/core.d:492)
<redacted> (<redacted>/source/ui/bindings/callbacks.d:143)
C_FileSystem::OpenFile(ultralight::String16 const&, bool) (Unknown Source:0)
WTF::Detail::CallableWrapper<WebCore::FileURLLoader::load(WTF::URL const&, WTF::Function<void (WTF::Optional<WebCore::FileURLLoader::Result>)>&&)::$_0, void>::call() (Unknown Source:0)
WTF::RunLoop::performWork() (Unknown Source:0)
WTF::RunLoop::runImpl(WTF::RunLoop::RunMode) (Unknown Source:0)
WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) (Unknown Source:0)
WTF::wtfThreadEntryPoint(void*) (Unknown Source:0)
start_thread (Unknown Source:0)
__GI___clone (/build/glibc-2ORdQG/glibc-2.27/sysdeps/unix/sysv/linux/x86_64/clone.S:95)
```

**Comment by kinke** [comment]
Is this really LDC-specific, i.e., have you tried this with the corresponding DMD version too? Anyway, please retry with the latest version, and if it still occurs *and* seems LDC-specific, make sure to provide something reproducible, otherwise there's no way we can help.

**Comment by chances** [comment]
I saw an old issue here about synchronization with the logger in `ensureMonitor` and thought this issue might be related. However, wrapping my log statements with `synchronized { }` seems to have resolved the issue, but I'm now more confused because I thought the logger is thread-safe on its own.

Regardless, thank you @kinke.
