### ISSUE TITLE
1.24.0-git-e8f331c: UNREACHABLE executed at SelectionDAGBuilder.cpp:1609

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3573]
Compiling for `thumbv7m-unknown-none-eabi` fails:

ldc2 -enable-color -wi -Os -g -d-debug '' --boundscheck=off --d-version=DruntimeAbstractRt --d-version=CRuntime_Abstract --d-version=AsmExternal --d-version=GENERIC_IO -release -O0 --checkaction=D --mtriple=thumbv7m-unknown-none-eabi --unittest --d-version=CoreUnittest --d-debug=SENTINEL --d-debug=INVARIANT -relocation-model=pic -I=../subprojects/picolibc/newlib/libc/include -I=subprojects/picolibc/newlib/libc/include -I=../subprojects/picolibc -I=subprojects/picolibc -I=../subprojects/picolibc/newlib/libc/tinystdio -I=subprojects/picolibc/newlib/libc/tinystdio -I=../subprojects/picolibc/newlib/libc/machine/arm -I=subprojects/picolibc/newlib/libc/machine/arm -I=../d/freertos_druntime_backend -I=../d/freertos_dpp_bindings -I=../subprojects/druntime/src -I=../d/freertos_druntime_backend -d-version=DruntimeAbstractRt -d-version=CRuntime_Abstract -d-version=ExternStackShell -d-version=AsmExternal -I=../d -I=d -I=d/libdruntime.a.p -I=d/libdruntime.a.p -of=d/libdruntime.a.p/freertos_druntime_backend_external_core_fiber.d.o -c ../d/freertos_druntime_backend/external/core/fiber.d
Can't get register for value!
UNREACHABLE executed at /home/vsts/work/1/s/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1609!
#0 0x0000000003a3fdc4 PrintStackTraceSignalHandler(void*) (/home/denizzz/bin/ldc2+0x3a3fdc4)
fish: 'ldc2 -enable-color -wi -Os -g -…' terminated by signal SIGABRT (Abort)

core dump:
```
           PID: 18217 (ldc2)
           UID: 1000 (denizzz)
           GID: 1000 (denizzz)
        Signal: 6 (ABRT)
     Timestamp: Fri 2020-10-02 06:17:53 +07 (44min ago)
  Command Line: ldc2 -enable-color -wi -Os -g -d-debug --boundscheck=off --d-version=DruntimeAbstractRt --d-version=CRuntime_Abstract --d-version=AsmExternal --d-version=GENERIC_IO -release -O0 --checkaction=D --mtriple=thumbv7m-unknown-none-eabi --unittest --d-version=CoreUnittest --d-debug=SENTINEL --d-debug=INVARIANT -relocation-model=pic -I=../subprojects/picolibc/newlib/libc/include -I=subprojects/picolibc/newlib/libc/include -I=../subprojects/picolibc -I=subprojects/picolibc -I=../subprojects/picolibc/newlib/libc/tinystdio -I=subprojects/picolibc/newlib/libc/tinystdio -I=../subprojects/picolibc/newlib/libc/machine/arm -I=subprojects/picolibc/newlib/libc/machine/arm -I=../d/freertos_druntime_backend -I=../d/freertos_dpp_bindings -I=../subprojects/druntime/src -I=../d/freertos_druntime_backend -d-version=DruntimeAbstractRt -d-version=CRuntime_Abstract -d-version=ExternStackShell -d-version=AsmExternal -I=../d -I=d -I=d/libdruntime.a.p -I=d/libdruntime.a.p -of=d/libdruntime.a.p/freertos_druntime_backend_external_core_fiber.d.o -c ../d/freertos_druntime_backend/external/core/fiber.d
    Executable: /home/denizzz/bin/ldc2
 Control Group: /user.slice/user-1000.slice/session-5.scope
          Unit: session-5.scope
         Slice: user-1000.slice
       Session: 5
     Owner UID: 1000 (denizzz)
       Boot ID: 72e882089250470bb80da99b89d17d91
    Machine ID: cb887893853d9496b8a2532700000db3
      Hostname: denpc
       Storage: /var/lib/systemd/coredump/core.ldc2.1000.72e882089250470bb80da99b89d17d91.18217.1601594273000000.lz4
       Message: Process 18217 (ldc2) of user 1000 dumped core.
                
                Stack trace of thread 18217:
                #0  0x00007f239133adb1 __GI_raise (libc.so.6)
                #1  0x00007f23913245ef __GI_abort (libc.so.6)
                #2  0x000000000399a4a1 n/a (/home/denizzz/bin/ldc2)
```

(ldc binary from azure)
```
ldc2 --version
LDC - the LLVM D compiler (1.24.0-git-e8f331c):
  based on DMD v2.094.0 and LLVM 11.0.0
  built with LDC - the LLVM D compiler (1.24.0-git-e8f331c)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: westmere
  http://dlang.org - http://wiki.dlang.org/LDC
```

With ldc2 1.23 compilation works ok.

**Comment by kinke** [comment]
Please try to reduce it to a trivial little cmdline and a single file, otherwise link at least the source repo, for reproducing, as the assertion occurs during LLVM codegen, so even if your stack trace was complete, it'd be totally useless.

**Comment by denizzzka** [comment]
Let's try this?

This is full sources directory. It uses "Meson build system" and configured to build on 64 bit Linux.
https://drive.google.com/file/d/19seGEGvkDn24gHSsc8LNz90nbzd7EKx4/view?usp=sharing (40 Mb)

If you on linux just `$ cd d_c_arm_test/builddir` and then run command from initial message above.

If you on Windows it is **more** complicated - it is need to use Meson from archive root directory and ninja, ldc2, clang, gcc and linker must be installed:
`meson setup --wipe --cross-file arm_cortex_m3_cross.ini builddir`
and then run:
`ninja -j10`

**Comment by kinke** [comment]
Sounds like way too much work for something which might be an LLVM regression. No offence, but I guess hardly anyone would dare creating such a bug report for clang etc. (hey, just download my huge project and invoke a 1K cmdline!); that's why compiler devs ask for some assistance by providing a *reduced* testcase. We have dustmite to automate the testcase reduction (but I don't like it and always reduce it manually).

**Comment by denizzzka** [comment]
it is just one ldc2 call what compiles one `fiber.d` file and for that purpose includes (-I) ~10 directories

**Comment by denizzzka** [comment]
>  reduced testcase

in progress, please wait

**Comment by kinke** [comment]
Each bug is 'just one ldc2 call'. To try to pinpoint it, the failing function needs to be identified, and as I'm no LLVM expert, it's just so much simpler if the code in question is a single file and as short as possible. Removing one function after the other and checking whether it still fails is what you could do too (or let dustmite do for you), you don't need to be a compiler dev for that. And dicussing things like this isn't exactly something I like either.

---

> in progress, please wait

Thx.

**Comment by kinke** [comment]
In case it takes you too much time, another option is that you share the produced IR (`-output-ll`), which I can then feed to LLVM's `bugpoint` tool, in the hopes of quickly identifying the problematic function.

**Comment by denizzzka** [comment]
Reduced sucessfully!

```D
module external.core.fiber;

import ldc.attributes;

void fiber_switchContext(size_t** for_store_curr_sp) @naked
{
    import ldc.llvmasm;

    __asm!()(
        `LDRH    r3, [$1]`,
        "r",
        for_store_curr_sp
    );
}
```
```
$ ldc2 --mtriple=thumbv7m-unknown-none-eabi ./external/core/fiber.d
Can't get register for value!
UNREACHABLE executed at /home/vsts/work/1/s/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1609!
#0 0x0000000003a3fdc4 PrintStackTraceSignalHandler(void*) (/home/denizzz/bin/ldc2+0x3a3fdc4)
fish: 'ldc2 --mtriple=thumbv7m-unknown…' terminated by signal SIGABRT (Abort)
```

**Comment by kinke** [comment]
Are you sure? This doesn't compile with v1.23 (with disabled assertions), and errors out instead (needs `$0`):
```
error: invalid operand in inline asm: 'LDRH    r3, [$1]' at line 1
```

**Comment by kinke** [comment]
It's an LLVM 11 regression:
```
>..\LLVM-x64.10\bin\llc feod.ll
error: invalid operand in inline asm: 'LDRH    r3, [$1]' at line 1
<inline asm>:1:15: error: register expected
        LDRH    r3, []
                     ^
note: !srcloc = 1

>..\LLVM-x64.11\bin\llc feod.ll
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ..\LLVM-x64.11\bin\llc feod.ll
1.      Running pass 'Function Pass Manager' on module 'feod.ll'.
2.      Running pass 'ARM Instruction Selection' on function '@_D4feod19fiber_switchContextFPPkZv'
 #0 0x00007ff661841e17 (C:\LDC\LLVM-x64.11\bin\llc.exe+0x1001e17)
...
```

Thx for reducing.

**Comment by denizzzka** [comment]
> Are you sure? This doesn't compile with v1.23 (with disabled assertions), and errors out instead (needs $0):

Oops, I just removed first argument while reducing instead of second. here is $0 should be

**Comment by kinke** [comment]
Yeah, `$0` still causes the crash, it's apparently related to `@naked` and the parameter being used. Filed as https://bugs.llvm.org/show_bug.cgi?id=47708. Closing here, as not related to LDC.
