### ISSUE TITLE
Option -disable-fp-elim removed in 1.24.0-beta1?

### ISSUE THREAD

**Issue by jondegenhardt** [ldc-developers/ldc#3576]
My CI pipeline for `tsv-utils` has started failing on the MacOS builds with the new 1.24.0-beta1 LDC compiler. The problem is clear from the error message:
```
ldc2: Unknown command line argument '-disable-fp-elim'.  Try: 'ldc2 --help'
```
The `-disable-fp-elim` switch is something I added to the builds of one of my tools on MacOS a while ago, when using LTO with druntime/phobos. It avoids unhandled exception issues. See issue #2585. I don't use the flag on Linux builds.

I don't know if it's still needed for the latest compiler versions (haven't tested it in at least a year), but it is needed on the older versions.

Before I precede with looking into this further, can you give me some info on changes to this option in the beta?

**Comment by kinke** [comment]
It's not available with LLVM 11+ anymore (and has been a legacy alias for `-frame-pointer=all` since LLVM 8 and undocumented for a while now). Still supporting this legacy option was made impossible by an LLVM 11 API change (see cacdc461543ab2cbebc4dad0dee5292704364f38 for some context).

**Comment by jondegenhardt** [comment]
Okay, thanks. I'll do some testing and find out if there are still uncaught exceptions errors without this flag.

**Comment by jondegenhardt** [comment]
Using 1.24.0-beta1 I was unable to reproduce the unhandled exception issues the `-disable-fp-elim` switch was guarding against. Closing this bug.
