### ISSUE TITLE
LLVM ERROR: Cannot select: intrinsic with optimizations on

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3577]
Consider the following program with LDC >= 1.18:

```d
import core.simd;

pragma(LDC_intrinsic, "llvm.aarch64.neon.addp.v4f32")
    float4 vpaddq_f32(float4 a, float4 b);

float4 _mm_hadd_ps (float4 a, float4 b) 
{
    return vpaddq_f32(a, b);
}
```

It works without optimizations:
`$ ldc2 -mtriple arm64`

but break with -O1 and above:
`$ ldc2 -mtriple arm64 -O1`

Result:
```
LLVM ERROR: Cannot select: intrinsic %llvm.aarch64.neon.addp
/opt/compiler-explorer/ldc-latest-ci/ldc/bin/ldc2[0x3a3fdc4]
Compiler returned: 255
```

Unfortunately there is no other way to implement _mm_hadd_ps  efficiently.
It also works when we go back to LDC < 1.18 (it seems it's a change between LLVM 9.0.1 vs LLVM 9.0.0)

Any idea what happens?

**Comment by kinke** [comment]
See https://reviews.llvm.org/D59655, they apparently changed it to **f**addp for floating-point vectors.

**Comment by p0nce** [comment]
Yes, this is it_ Thanks :)
