### ISSUE TITLE
A strange lack of vectorization

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3587]
Trying to implement a quick `_mm_packus_epi16` on ARM.
I get `vmaxq_s16` and `vminq_s16` to generate the right `smin`/`smax` instruction nicely in isolation, but once inside `_mm_packus_epi16` they do not translate to a single instruction anymore. 

**Source:** (see Godbolt output to see the problem)
```d
import core.simd;
import ldc.intrinsics;
import ldc.llvmasm;
import ldc.simd;
alias __m128i = int4;
alias byte8 = __vector(byte[8]);
alias short4 = __vector(short[4]);

short8 vmaxq_s16(short8 a, short8 b) pure @trusted
{
    short8 r;
    for(int i = 0; i < 8; ++i)
    {
        r[i] = a[i] >= b[i] ? a[i] : b[i];
    }
    return r;
}

short8 vminq_s16(short8 a, short8 b) pure @trusted
{
    short8 r;
    for(int i = 0; i < 8; ++i)
    {
        r[i] = a[i] < b[i] ? a[i] : b[i];
    }
    return r;
}

pragma(LDC_intrinsic, "llvm.aarch64.neon.addp.v16i8")
        byte16 vpaddq_s8(byte16 a, byte16 b) pure @safe;

__m128i _mm_packus_epi16 (__m128i a, __m128i b) pure @trusted
{
    short8 zero = [0, 0, 0, 0, 0, 0, 0, 0];
    short8 s255 = [255, 255, 255, 255, 255, 255, 255, 255];
    a = vmaxq_s16(a, zero);
    a = vminq_s16(a, s255);
    b = vmaxq_s16(b, zero);    
    b = vminq_s16(b, s255);
    return cast(__m128i) vpaddq_s8(cast(byte16)a, cast(byte16)b);
}
```

=> **Godbolt:** https://d.godbolt.org/z/s887nd

It's as if LLVM fusion the loop and then it misses the opportunity to vectorize. This seems really out of character for LLVM.

**Comment by kinke** [comment]
Making the `vmaxq_s16` param types *unsigned* reduces `_mm_packus_epi16` to 5 instructions...

**Comment by p0nce** [comment]
Yes but that's because LLVM turn `max(x, 0)` into `x` when x is unsigned.

**Comment by p0nce** [comment]
Either
```d
sa = vmaxq_s16(sa, zero);
sb = vmaxq_s16(sb, zero);
// sa = vminq_s16(sa, s255);
// sb = vminq_s16(sb, s255);
```
or
```d
// sa = vmaxq_s16(sa, zero);
// sb = vmaxq_s16(sb, zero);
sa = vminq_s16(sa, s255);
sb = vminq_s16(sb, s255);
```

will reduce to two `smin` / `smax` instructions, but when all are uncommented there is no vectorization anymore.

**Comment by kinke** [comment]
This seems to work:
```D
pragma(LDC_intrinsic, "llvm.aarch64.neon.smax.v8i16")
        short8 vmaxq_s16(short8 a, short8 b) pure @safe;

pragma(LDC_intrinsic, "llvm.aarch64.neon.smin.v8i16")
        short8 vminq_s16(short8 a, short8 b) pure @safe;
```

**Comment by p0nce** [comment]
Whoa, good catch! How do you find them names?

**Comment by kinke** [comment]
https://github.com/ldc-developers/llvm-project/blob/ldc-release/11.x/llvm/include/llvm/IR/IntrinsicsAArch64.td - I assumed that's how you found `llvm.aarch64.neon.addp.v16i8`. :)

**Comment by p0nce** [comment]
Well, rather trial and error.
