### ISSUE TITLE
--fthread-model=local-exec codegen bug for ARM?

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#3602]
This snippet isn't so small as anyone want (78 lines) but I couldn't reproduce this issue on x86 or ARM platform with OS. So here will be bare-metal example and most of these lines is need for initialize bare-metal execution.

Code above allocates struct S at heap an then calls method `initialize()` what changes internal struct V.
Expected that after `s.initialize()` call `ptr` will contain pointer to `magic`, but actually address used by generated code to update this `ptr` isn't contains TLS offset.

Reproduceable on 1.23 and 1.24 versions of ldc2.

This code is reduced example of druntime: https://github.com/ldc-developers/druntime/blob/ldc/src/gc/impl/conservative/gc.d#L170
```D
// betterC code

import ldc.attributes;

int magic = 123;

struct V
{
    int* ptr;

    void setPtr(int* p) @llvmAttr("nounwind")
    {
        int* intermediate_tmp = p;
        _assert(intermediate_tmp);

        ptr = intermediate_tmp;
        _assert(ptr);
    }
}

struct S
{
    V v;

    void initialize() @llvmAttr("nounwind")
    {
        v.setPtr(&magic);
    }
}

extern(C) extern __gshared void* _tdata;
extern(C) extern __gshared void* _tdata_size;

// main() is here:
extern(C) void reset_handler() @llvmAttr("nounwind")
{
    // init TLS
    {
        ubyte* tdata_start = cast(ubyte*)&_tdata;
        size_t tdata_size = cast(size_t)&_tdata_size;
        auto tls = cast(ubyte*) __aeabi_read_tp();
        foreach(i; 0 .. tdata_size)
            tls[i] = tdata_start[i];
    }

    S* s = cast(S*) (__aeabi_read_tp() + 1024); // like malloc, but without malloc :-)
    _assert(s);

    s.initialize();

    _assert(*s.v.ptr == 123); // fails here

    while(true) {}
}

void _assert(T)(T cond) @llvmAttr("nounwind")
{
    if(!cond)
        while(true) {}
}

extern(C) void* __aeabi_read_tp() @llvmAttr("nounwind")
{
    return cast(void*) 0x21900000; // somewhere at heap;
}

@section(".vectors")
immutable InterruptsVector interruptsVector;

immutable struct InterruptsVector
{
    void* initial_sp_value = &_stack;
    void* reset = &reset_handler;
    void* nmi_handler = &null_handler;
    void* hard_fault = &hard_fault_handler;
    void* memory_manage_fault = &hard_fault_handler;
    void* bus_fault = &hard_fault_handler;
    void* usage_fault = &hard_fault_handler;
    void* debug_monitor_handler = &null_handler;
    void* sv_call = &null_handler;
    void* pend_sv = &null_handler;
    void* systick = &null_handler;
    void* irq = &null_handler;
}

extern(C) extern immutable void* _stack;

extern(C) void null_handler() @llvmAttr("nounwind") { /* Do nothing. */ }
extern(C) void hard_fault_handler() @llvmAttr("nounwind") { while(true){} }
```

How to build:
```
$ ldc2 -c -static -betterC -O0 -gc --mtriple=thumbv7m-unknown-none-eabi --fthread-model=local-exec --defaultlib= app.d
```
How to link:
```
$ ld.lld -L/usr/lib/gcc/arm-none-eabi/8.3.1/thumb/v7-m/nofp/ -lgcc --script=linker_script.ld -z norelro app.o -o app
```
* libgcc provided by gcc-arm-none-eabi package on Debian
* Linker script is here: https://gist.github.com/denizzzka/ad81f6776034f48711b2cac327ab66fb

How to run and debug:
```
$ qemu-system-arm -machine mps2-an511 -nographic -semihosting -s -S -kernel app #will wait for gdb connection
```
Connect to QEMU by GDB:
```
gdb-multiarch --init-eval-command="set architecture armv7e-m" --init-eval-command="target remote localhost:1234" --eval-command="break reset_handler" ./app
```
(then in gdb just type `continue`)

**Comment by dnadlinger** [comment]
For bare metal use, wouldn't you need to set the TLS base offset somewhere manually? I'm not sure what the codegen is off the top of my head for ARMv7 and `local-exec`, but there will be some register/… used as the TLS base address for each thread.

**Comment by denizzzka** [comment]
Compiler invokes `__aeabi_read_tp()` calls to obtain current TLS pointer

**Comment by dnadlinger** [comment]
Ah yes, sorry. Clearly it's been too long since I've looked into TLS on ARM.

I don't have any good suggestions, and don't have a qemu/multiarch-gdb setup here to quickly test this. I'd suggest looking at the assembly with all the relocations in textual form, though (`-output-s`), and making sure the correct values appear in GDB at runtime. Does the issue also appear with -O3? At least there, the assembly for `initialize` looks sensible at a glance.

**Comment by dnadlinger** [comment]
Oh, but do you actually copy the TLS data to 0x21900000 on startup?

**Comment by denizzzka** [comment]
> I don't have any good suggestions, and don't have a qemu/multiarch-gdb setup here to quickly test this. 

I use provided by Debian packages `qemu-system-arm` and `gdb-multiarch`.

> I'd suggest looking at the assembly with all the relocations in textual form, though (-output-s), and making sure the correct values appear in GDB at runtime.

ASM is not my strong point :-)
Here is `-output-s` result: https://gist.github.com/denizzzka/e14c812c2a1bd6830a8d73f0f26b6c00

> Oh, but do you actually copy the TLS data to 0x21900000 on startup?

I updated sample to add `.tdata` copying. Nothing was changed.
(.tbss is zero sized, so I skip it)

**Comment by denizzzka** [comment]
With -O2 and -O3 gdb fails with fancy error:
```
reset_handler () at app.d:51
51	    _assert(*s.v.ptr == 123); // fails here
/build/gdb-abIZlw/gdb-9.2/gdb/inline-frame.c:155: internal-error: void inline_frame_this_id(frame_info*, void**, frame_id*): Assertion `frame_id_p (*this_id)' failed.
A problem internal to GDB has been detected,
```

I think this is same result as for -O0 but gdb goes crazy because optimizations applied.

**Comment by kinke** [comment]
I cannot imagine this having to do anything with LDC, this is all LLVM's doing and IMO almost certainly some error in your code.

> but actually address used by generated code to update this ptr isn't contains TLS offset.

Your asm shows that some offset is added to the result of `__aeabi_read_tp()`:
```asm
_D3app1S10initializeMFZv:
	...
	ldr	r1, .LCPI2_0 ; `magic` offset in r1
	str	r0, [sp, #4]
.Ltmp9:
	str	r1, [sp] ; dump to stack
	bl	__aeabi_read_tp
	ldr	r1, [sp] ; restore from stack
	add	r1, r0 ; r1 += <__aeabi_read_tp() result>
	ldr	r0, [sp, #4]
.Ltmp10:
	bl	_D3app1V6setPtrMFPiZv ; parameter p in r1 ('this' in r0)
...
.LCPI2_0:
	.long	_D3app5magici(TPOFF)
```

gdb can probably check whether `p` is fine (and allow to derive the offset manually). If it is, then the TLS init is probably wrong. Have you checked the value of `size_t tdata_size = cast(size_t)&_tdata_size;`? I haven't seen those magic linker symbols before; we use the `__{start,stop}_<section>` symbols in druntime.

**Comment by denizzzka** [comment]
> Your asm shows that (for &magic) some offset is added to the result of __aeabi_read_tp()

Huh, yes!
`&magic` returns 0x21900008, but actually `magic` value is placed at 0x21900000 by compiler.

> If it is, then the TLS init is probably wrong. 

tdata_start = 0x210001e4 
TLS contain only 4 bytes, same as in .tdata section of ELF file after initialization of TLS:
>>> x/wx __aeabi_read_tp()
0x21900000:	0x0000007b
(This is 123 value)

> Oh I see, you define them in the custom linker script.

Yep, this script is inherited from `libopencm3`.

>  What does the :ram_init do?

Unused attribute. I removed it and nothing changed.

**Comment by denizzzka** [comment]
> &magic returns 0x21900008, but actually magic value is placed at 0x21900000 by compiler.

0x08 is TCB block offset, specific for ARM.

sorry to bother you, I knew about this but forgot.

**Comment by JohanEngelen** [comment]
@denizzzka Hope you can find the time and energy to write up an article / howto with a full example once you've got things to work.

**Comment by denizzzka** [comment]
...The problem is still here - TCB case was a false trail. For now I unable to reproduce yet.

**Comment by denizzzka** [comment]
Gcx.initialize() asm code:
```asm
_D2gc4impl12conservativeQw3Gcx10initializeMFZv:
.Lfunc_begin6:
	.loc	2 1281 0 is_stmt 1
	.fnstart
	.cfi_startproc
	.save	{r7, lr}
	push	{r7, lr}
	.cfi_def_cfa_offset 8
	.cfi_offset lr, -4
	.cfi_offset r7, -8
	.setfp	r7, sp
	mov	r7, sp
	.cfi_def_cfa_register r7
	.pad	#8
	sub	sp, #8
	mov.w	r1, #832
.Ltmp26:
	.loc	2 1283 9 prologue_end
	str	r0, [sp, #4]
.Ltmp27:
	bl	__aeabi_memclr
	.loc	2 1284 9
	ldr	r0, [sp, #4]
	bl	_D2gc4impl12conservativeQw12LeakDetector10initializeFNbPSQCdQCdQCbQCm3GcxZv
	ldr	r0, [sp, #4]
	adds	r0, #192
	movw	r2, #2259
	movt	r2, #34211
	movw	r3, #27272
	movt	r3, #9279
	.loc	2 1285 9
	bl	_D2rt4util9container5treap__T5TreapTS4core2gc11gcinterface4RootZQBj10initializeMFNaNbNiNfmZv
	ldr	r0, [sp, #4]
	adds	r0, #208
	movw	r2, #29508
	movt	r2, #880
	movw	r3, #35374
	movt	r3, #4889
	.loc	2 1286 9
	bl	_D2rt4util9container5treap__T5TreapTS4core2gc11gcinterface5RangeZQBk10initializeMFNaNbNiNfmZv
	movs	r0, #0
	.loc	2 1287 9
	ldr	r1, [sp, #4]
	str.w	r0, [r1, #304]
	ldr.w	r2, [r1, #304]
	str.w	r2, [r1, #300]
	.loc	2 1288 9
	str.w	r0, [r1, #312]
	ldr.w	r2, [r1, #312]
	str.w	r2, [r1, #308]
	.loc	2 1289 9
	str.w	r0, [r1, #316]
	.loc	2 1306 5
	add	sp, #8
.Ltmp28:
	pop	{r7, pc}
.Ltmp29:
.Lfunc_end6:
	.size	_D2gc4impl12conservativeQw3Gcx10initializeMFZv, .Lfunc_end6-_D2gc4impl12conservativeQw3Gcx10initializeMFZv
	.cfi_endproc
	.fnend

	.globl	_D2gc4impl12conservativeQw3Gcx7reserveMFNbkZk
	.p2align	1
	.type	_D2gc4impl12conservativeQw3Gcx7reserveMFNbkZk,%function
	.code	16
	.thumb_func
```

**Comment by denizzzka** [comment]
huh, I found what gdb isn't correctly handles addresses at this case.
Actually asm code contains tls offset in r0 register
