### ISSUE TITLE
ARM do not convert float to integers in the same way as x86 or CTFE

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3603]
Finally something interesting in ARM-land.
Consider the following program:

```d
import core.stdc.stdio;

void main(string[] args)
{
   double d = 625935085.258525;   
   uint msu = cast(uint)(d * 1000.0);
   printf("msu = %d\n", msu);
   printf("msu at CTFE = %d\n", ctfeResult_uint);

   int msi = cast(int)(d * 1000.0);
   printf("msi = %d\n", msi);
   printf("msi at CTFE = %d\n", ctfeResult_int);

   // and the CTFE ones?

}

enum uint ctfeResult_uint = cast(uint)(625935085.258525 * 1000.0);
enum int ctfeResult_int = cast(int)(625935085.258525 * 1000.0);
```

In x86_64 the output is:
```d
msu = -1130139958
msu at CTFE = -1130139958
msi = -2147483648
msi at CTFE = -2147483648
```

In arm64 the output is:
```d
msu = -1
msu at CTFE = -1130139958
msi = 2147483647
msi at CTFE = -2147483648
```

So, if FCVTZ is to be used for this conversion, this would now be UB in D.

**Comment by p0nce** [comment]
In clang the same difference can be observed:

```c
#include <stdio.h>

int main(int argc, char** argv)
{
   double d = 625935085.258525;   
   unsigned int msu = (unsigned int)(d * 1000.0);
   printf("msu = %d\n", msu);

   int msi = (int)(d * 1000.0);
   printf("msi = %d\n", msi);
}
```

Output with arm64 arch:
```d
msu = -1
msi = 2147483647
```

Output with x86_64 arch:
```
msu = -1130139958
msi = -2147483648
```

**Comment by p0nce** [comment]
For reference, it is perfectly fine to me to leave it UB, it's just that being silent it's quite an easy trap.

**Comment by kinke** [comment]
I think this was discussed a while ago and deemed to be UB indeed. - CTFE behavior likely depends on the host, i.e., with a native AArch64 LDC, CTFE behavior will probably match AArch64 runtime.

**Comment by kinke** [comment]
If you want to have this caught for CTFE, you should file a DMD issue instead.

**Comment by p0nce** [comment]
It was rather in case it hadn't been discussed; The D spec is silent about it.

**Comment by p0nce** [comment]
https://issues.dlang.org/show_bug.cgi?id=21359
