### ISSUE TITLE
Invalid std.math.pow results

### ISSUE THREAD

**Issue by 89z** [ldc-developers/ldc#3619]
Using this program:

~~~d
import
   std.math,
   std.stdio;

void main() {
   // example 1
   float n1 = pow(9, .5);
   // example 2
   double n2 = pow(9, .5);
   // example 3
   real n3 = pow(9, .5);
   // print
   [n1 == 3, n2 == 3, n3 == 3].writeln;
}
~~~

With LDC 1.24 I get:

~~~
[true, false, false]
~~~

However with DMD 2.094.2 and LDC 1.12, I get:

~~~
[true, true, true]
~~~

Interestingly, if I change to `9 ^^ .5`, then I get `[true, true, true]` with
LDC as well.

**Comment by kinke** [comment]
I assume you're on Windows (with 64-bit `real` for LDC vs. 80-bit with DMD)?

**Comment by 89z** [comment]
sorry about that - yeah I am using this

https://github.com/ldc-developers/ldc/releases/download/v1.24.0/ldc2-1.24.0-windows-x64.7z

**Comment by 89z** [comment]
closing for lack of interest
