### ISSUE TITLE
Problem with Subsystem flag and gtkd

### ISSUE THREAD

**Issue by KonstantIMP** [ldc-developers/ldc#3625]
Hi!
I am writing GTKd program. ldmd2 compile it perfectly, but when I started the program CMD window opens.
To solve this problem I tried compile binaries by this command : **ldmd2 -m64 -Lgtkd.lib -release -L-subsystem:windows -L-entry:mainCRTStartup HelloWorld.d**
lld-link says problems...
**lld-link: error: undefined symbol: main
 referenced by vcruntime140.lib(msvcrt_stub1.obj):($LN3)
Error: linking with LLD failed**
But if I compile it with DMD :  **dmd -m64 -Lgtkd.lib -release -L-subsystem:windows -L-entry:mainCRTStartup HelloWorld.d** it works fine
Thank you!

**Comment by KonstantIMP** [comment]
Oh.. And of course code example

'module gtk.HelloWorld;
import gio.Application : GioApplication = Application;
import gtk.Application;
import gtk.ApplicationWindow;
import gtk.Label;
class HelloWorld : ApplicationWindow{
	this(Application application)	{
		super(application);
		setTitle("GtkD");
		setBorderWidth(10);
		add(new Label("Hello World"));
		showAll();
	}
}
int main(string[] args){
	auto application = new Application("org.gtkd.demo.helloworld", GApplicationFlags.FLAGS_NONE);
	application.addOnActivate(delegate void(GioApplication app) { new HelloWorld(application); });
	return application.run(args);
}'

**Comment by kinke** [comment]
Hi, use `-L/entry:wmainCRTStartup`, see #3436.

**Comment by KonstantIMP** [comment]
Yes. It works.
Thank you
