### ISSUE TITLE
Compile C/C++ code

### ISSUE THREAD

**Issue by RUSshy** [ldc-developers/ldc#3627]
Hello

I tried zig for few days last month, it was pretty fun, but D still remains my main language

However, one feature that is making me very jealous was the ability to compile c/c++ code and automatically link the lib, and cache all that

This made working with C libraries MUCH easier

Since both zig and LDC are based on clang, i was wondering if the same could be possible with LDC?

Example: https://github.com/yurapyon/maru/blob/master/build.zig#L8

Now imagine such feature, with DUB

You add:

```json
"c-sources": [
    {
        "file": "deps/stb/stb_image.c",
        "flags": "-std=c99"
    }
],
"c-headers": [
    "deps/stb/stb_image.h"
]
```

``c-sources`` to build the library

and 

``h-headers`` to resolve symbols

And LDC does all the job for you, so we do not need to depend on a local C/C++ compiler anymore!

**Comment by JohanEngelen** [comment]
This should be solved at buildsystem level, not at compiler level (LDC should not become a C compiler). Please open this feature request with DUB (or other build system that you'd want to use).

**Comment by kinke** [comment]
Agreed. See https://github.com/Syniurge/Calypso for an LDC fork with integrated clang.

**Comment by dnadlinger** [comment]
(Just for the sake of completeness: LDC doesn't depend on Clang, it is based on LLVM only. But yes, in the D ecosystem with multiple compilers/…, people have preferred to work on this in the form of separate projects, e.g. DStep and Calypso.)

**Comment by RUSshy** [comment]
> (LDC should not become a C compiler)

Why not? it's only a matter of including the clang library, this allows many possibilities, including easy and transparent C interop

That is a valuable feature that shouldn't be underestimated

Build system can only go so far as handling this as a separate process rather than a unified and more performant one

Or i fail to see what it would be a bad idea?

**Comment by JohanEngelen** [comment]
> > (LDC should not become a C compiler)
> 
> Why not? it's only a matter of including the clang library, this allows many possibilities, including easy and transparent C interop

It is already easy and transparent to do C interop.

Including clang is not easy and will be a maintenance burden. Because the next step is that you want a certain commandline switch, or the C standard library and runtime, or we should no longer call C compiler for linking, or bugs come in about bad integration with the system C compiler (clang and gcc are not completely interchangable), or...  The list is endless and there are already fine solutions for the problem of building C/D codebases.

**Comment by JohanEngelen** [comment]
(but if you think it is easy, go ahead and make it, you'll see)
