### ISSUE TITLE
Missing source location for betterC TypeInfo error

### ISSUE THREAD

**Issue by DaveP1776** [ldc-developers/ldc#3631]
Output of `ldc2 --version`:
```
LDC - the LLVM D compiler (1.24.0):                                                   
  based on DMD v2.094.1 and LLVM 11.0.0
  built with LDC - the LLVM D compiler (1.24.0)                                           
  Default target: x86_64-unknown-linux-gnu 
...
```
A minimal program, compiled with -betterC:

```D
extern(C) int main(){
    int[] foo = [1];
    return 0;
}
```
Yields the error message:
```
Error: TypeInfo cannot be used with -betterC
```

With dmd, the error message is:
```
bug.d(2): Error: TypeInfo cannot be used with -betterC
```

In other words, the error message indicates file and line.

This can be quite frustrating in larger source files.

It looks like this happens because a default constructed `Loc` is passed into `getOrCreateTypeInfoDeclaration` at https://github.com/ldc-developers/ldc/blob/master/gen/llvmhelpers.cpp#L1200

**Comment by kinke** [comment]
Fixed by #3632.
