### ISSUE TITLE
Struct inits not aligned enough (aarch64-none-elf)

### ISSUE THREAD

**Issue by John-Colvin** [ldc-developers/ldc#3635]
Essentially I think the problem is that struct init alignment isn't strict enough for the code that is being generated. 8-byte alignment is being used, but the init is being loaded with code like `ldp q0, q1, [x9]` which needs 16 byte alignment.

I ran in to this while building for bare-metal on a larger project (you would not believe how long I was convinced I hadn't enabled the fpu or something...sigh....). Here is a (somewhat nonsense) example that demonstrates the problem. See that `_D10test_align1S6__initZ` is at `0x200188`.

Maybe I'm just doing something wrong with the compiler invocation?

```
struct Q {
    char[100] a;
}

struct S {
    char[100] a;
    size_t b;
}

pragma(inline, false)
auto foo(uint x) {
    S s;
    while (x != 0) {
        s.a[s.b++] = x & 1;
        x >>= 1;
    }
    return s;
}

pragma(inline, false)
auto bar() {
    return Q();
}

extern(C) int main() {
    foo(3);
    bar();
    return 0;
}

extern(C) void _start() {
}
```

```
ldc2 -release -boundscheck=off -O3 -mtriple=aarch64-none-elf --betterC --link-internally test_align.d
```

```
% llvm-objdump -dt --arch-name=aarch64 test_align

test_align:	file format elf64-littleaarch64

SYMBOL TABLE:
0000000000000000 l    df *ABS*	0000000000000000 test_align.d
0000000000200120 l       .rodata	0000000000000000 $d.1
0000000000000080 l       .comment	0000000000000000 $d.2
00000000002101f8 l       .text	0000000000000000 $x.0
0000000000200120 g     O .rodata	0000000000000064 _D10test_align1Q6__initZ
0000000000200188 g     O .rodata	0000000000000070 _D10test_align1S6__initZ
000000000021025c g     F .text	000000000000001c _D10test_align3barFNaNbNiNfZSQBb1Q
00000000002101f8 g     F .text	0000000000000064 _D10test_align3fooFNaNbNiNfkZSQBc1S
00000000002102a4 g     F .text	0000000000000004 _start
0000000000210278 g     F .text	000000000000002c main

Disassembly of section .text:

00000000002101f8 <_D10test_align3fooFNaNbNiNfkZSQBc1S>:
  2101f8: 89 ff ff 90  	adrp	x9, #-65536
  2101fc: 29 21 06 91  	add	x9, x9, #392
  210200: 20 05 40 ad  	ldp	q0, q1, [x9]
......
.....
....
```

(in case you feel the need to check: `0x2101f8 - (0x2101f8 % 4096) - 65536 + 392  == 0x200188`)

**Comment by John-Colvin** [comment]
```
LLConstant *&IrAggr::getInitSymbol() {
  if (init) {
    return init;
  }

  // create the initZ symbol
  const auto irMangle = getIRMangledInitSymbolName(aggrdecl);

  auto initGlobal = declareGlobal(aggrdecl->loc, gIR->module, getLLStructType(),
                                  irMangle, /*isConstant=*/true);
  initGlobal->setAlignment(LLMaybeAlign(DtoAlignment(type)));

  init = initGlobal;

  return init;
}
```

Looks like they're just aligned to the same as the type.

Hmm.... now I look at other examples, it seems that I get instructions like `ldp q0, q1, [x9]` for *any* struct copy, not just with `init`s.

**Comment by John-Colvin** [comment]
Ok, so maybe there's something simpler wrong?

```
char[128] copy128(char[128]* src) {
    static assert((*src).alignof == 1);
    char[128] dst = *src;
    return dst;
}
```

produces this:

```
char[128] example.copy128(char[128]*):
        ldp     q0, q1, [x0]
        ldp     q2, q3, [x0, #32]
        stp     q2, q3, [x8, #32]
        stp     q0, q1, [x8]
        ldp     q0, q1, [x0, #64]
        ldp     q2, q3, [x0, #96]
        stp     q2, q3, [x8, #96]
        stp     q0, q1, [x8, #64]
        ret
```

Am I fundamentally misunderstanding the problem? I'm pretty sure those instructions require 16 byte alignment.

**Comment by John-Colvin** [comment]
I just learned about the `-mstrict-align` flag to clang. I'm guessing there would be some way to do the same in ldc? I tried `--arm-assume-misaligned-load-store` but it didn't seem to change much

**Comment by JohanEngelen** [comment]
We correctly emit IR saying that alignment is `1`: https://d.godbolt.org/z/f7f966   (`align 1` on the memcpy call arguments). Perhaps for the default AArch64 CPU, the instructions do not have alignment requirements? Otherwise it's an LLVM bug.

**Comment by JohanEngelen** [comment]
I don't see alignment requirements here: https://developer.arm.com/architectures/learn-the-architecture/aarch64-instruction-set-architecture/loads-and-stores-load-pair-and-store-pair

**Comment by JohanEngelen** [comment]
I found some more information here: https://community.arm.com/developer/ip-products/processors/f/cortex-a-forum/7557/when-and-where-will-the-ldp-instruction-trigger-an-exception . Contains some hints to dig deeper into the specific issue you may have.

You can use either `-mattr=+strict-align` on the commandline (or put a `@(ldc.attributes.target("strict-align"))` on specific functions) to get the strict alignment behavior of the clang `-mstrict-align` flag.

**Comment by JohanEngelen** [comment]
(so I think LDC does the right thing by default, but your baremetal usecase may require extra build flags to deviate from the default unaligned-access-is-OK)

**Comment by John-Colvin** [comment]
Yeah, I have the MMU disabled, that must be be the root cause. `-mattr=+strict-align` is working for me now.

Thanks for the help! I agree that the defaults make sense.
