### ISSUE TITLE
Naive question about -run flag

### ISSUE THREAD

**Issue by stefanos82** [ldc-developers/ldc#3636]
Greetings.

I have tried a very simple `hello world` product with 3 available compilers:

1. DMD
2. GDC
3. LDC

I have noticed a weird behavior only with LDC; when I execute `ldmd2 -run hello.d` and I have another terminal opened with `watch -n 0.1 ls -l /tmp`, only LDC retains its generated binary, whereas the other 2 compilers do not.

Is this the expected behavior?

**Comment by kinke** [comment]
I don't think it should be expected given https://github.com/ldc-developers/ldc/blob/29245c825507cf712bbe6948013384c585db0aa9/dmd/mars.d#L915 but can't test it myself right now.
