### ISSUE TITLE
Windows: weird linking problem with core.stdc.stdio and --betterC

### ISSUE THREAD

**Issue by icecoldtofu** [ldc-developers/ldc#3640]
Given:
```
//foo.d
import core.stdc.stdio;

extern(C) void main()
{
  fprintf(stderr, "foo!");
}
```

dmd runs it:
```
> dmd -betterC -run foo.d
foo!
```

ldc fails to link:
```
> ldc2 --betterC --run foo.d
lld-link: error: undefined symbol: stderr
>>> referenced by foo-b01a5a8.obj:(main)
Error: linking with LLD failed
```

When not using `-betterC` or manually including stdio `-i=core.stdc.stdio` ldc builds the exe, which crashes at runtime:
```
> ldc2 --run foo.d
Error: T:\Temp\foo-354358c-0da04f.exe failed with status: -1073740791
Error: program received signal 1073740791

> ldc2 -i=core.stdc.stdio --betterC --run foo.d
Error: T:\Temp\foo-e557fbf-58fde3.exe failed with status: -1073740791
Error: program received signal 1073740791
```

When I force it to use an external linker with `--linker=lld-link`, I can see the linker is being invoked with:
`"C:\ldc2\bin\lld-link.exe" /NOLOGO /OPT:REF /OPT:ICF /DEFAULTLIB:vcruntime140 "/OUT:T:\Temp\foo-fdde255-e3ebcf.exe" foo-fdde255.obj "C:/ldc2/bin/../lib\ldc_rt.builtins.lib" /LIBPATH:C:/ldc2/bin/../lib /LIBPATH:C:/ldc2/bin/../lib/mingw kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib oldnames.lib legacy_stdio_definitions.lib`

As far as I can tell everything else in `core.stdc.stdio` works. `printf`, `fprintf` to opened files etc. But `stdout`, `stderr`, `stdin` are not visible to the linker.
Any idea what's going on here?

OS: Windows 8.1 64 bit
(no MSVC toolchain installed)
```
> ldc2 --version
LDC - the LLVM D compiler (1.24.0):
  based on DMD v2.094.1 and LLVM 11.0.0
  built with LDC - the LLVM D compiler (1.24.0)
  Default target: x86_64-pc-windows-msvc
```

**Comment by kinke** [comment]
The MSVC runtime doesn't feature these symbols; MS defines them as macros, whereas druntime defines and sets them at startup for convenience. So won't work with `-betterC`, and I bet DMD only works with `-m32` and the DigitalMars runtime, not with `-m32mscoff` or `-m64`.

**Comment by Geod24** [comment]
Indeed: https://issues.dlang.org/show_bug.cgi?id=19933

**Comment by kinke** [comment]
This is just one of these `-betterC` things that don't work. Working around those one at a time is IMO not worth it; instead, I think we need a minimalist runtime library which is also linked with `-betterC`.

**Comment by kinke** [comment]
Closing due to proper druntime issue filed upstream.
