### ISSUE TITLE
Windows defender complains the x64 file contains a trojan Ymacco.AA5B

### ISSUE THREAD

**Issue by pepsakdoek** [ldc-developers/ldc#3642]
ldc2-1.23.0-windows-x64.7z

This file has the following report from Windows Security: (sorry for image, windows is not liking copy and pasting here)
![image](https://user-images.githubusercontent.com/65312601/104367079-fa35a200-5522-11eb-95dc-aa3d56f158da.png)

**Comment by kinke** [comment]
Duplicate of https://github.com/ldc-developers/ldc/issues/3472 and at least for now resolved with latest beta1.
