### ISSUE TITLE
 error: call to non-static member function without an object argument

### ISSUE THREAD

**Issue by SolarAquarion** [ldc-developers/ldc#3659]
/home/solaraquarion/ldc-git/src/ldc/gen/dibuilder.cpp:197:23: error: call to non-static member function without an object argument
      llvm::DebugLoc::get(loc.linnum, getColumn(loc), GetCurrentScope());
      ~~~~~~~~~~~~~~~~^~~
/home/solaraquarion/ldc-git/src/ldc/gen/dibuilder.cpp:205:23: error: call to non-static member function without an object argument
      llvm::DebugLoc::get(loc.linnum, getColumn(loc), GetCurrentScope());
      ~~~~~~~~~~~~~~~~^~~
/home/solaraquarion/ldc-git/src/ldc/gen/dibuilder.cpp:1206:23: error: call to non-static member function without an object argument
      llvm::DebugLoc::get(linnum, col, GetCurrentScope()));
      ~~~~~~~~~~~~~~~~^~~
3 errors generated.
make[2]: *** [CMakeFiles/LDCShared.dir/build.make:433: CMakeFiles/LDCShared.dir/gen/dibuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:368: CMakeFiles/LDCShared.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

**Comment by kinke** [comment]
I assume you're using some LLVM > 11. We don't support pre-release LLVM versions.

**Comment by SolarAquarion** [comment]
Yes, i am.

**Comment by SolarAquarion** [comment]
i guess keep this open for now

**Comment by kinke** [comment]
I'm going to close, otherwise our issue tracker would be flooded by breaking LLVM API changes.

**Comment by SolarAquarion** [comment]
true enough

**Comment by PetarKirov** [comment]
@SolarAquarion that said, once a new LLVM version is officially released, then the actual work of supporting it can begin. Usually the LDC team has always released new LDC versions that support the latest official LLVM release. If you really need LLVM 12 support, I think the team won't be opposite to merging PRs that add `#if LDC_LLVM_VER > = 1200` compatibility code where necessary.

**Comment by kinke** [comment]
Might work now with #3663 (possibly requiring a line like https://github.com/ldc-developers/druntime/blob/fb6a14bf006b6899d5ebeee1741e3a8e4be2323a/src/ldc/intrinsics.di#L29 if the master version is already 13).
