### ISSUE TITLE
Behavior of implicit vector conversion have changes somewhere along the lines

### ISSUE THREAD

**Issue by ZILtoid1991** [ldc-developers/ldc#3686]
When I try to build a project with the current (1.25.1) compiler version that contains my CPUblit library, I get the following errors:

`function inteli.emmintrin._mm_adds_epu16(__vector(int[4]) a, __vector(int[4]) b) is not callable using argument types (__vector(int[4]), immutable(__vector(short[8])))`

`cannot pass argument ALPHABLEND_SSE2_CONST1 of type immutable(__vector(short[8])) to parameter __vector(int[4]) b`

This isn't the case with 1.23.0 at least, in which the project just builds fine, but the matching version of DMD also had similar issues with implicit vector conversions.

I probably will do some workaround myself, but even if you won't plan to fix this it would be nice to indicate this behavior change somewhere in the version history.

**Comment by kinke** [comment]
See https://dlang.org/changelog/2.094.0.html#implicit-vector-conversions. Our changelog has never included changes inherited from frontend changes.

**Comment by ZILtoid1991** [comment]
Thanks for pointing this out!
