### ISSUE TITLE
Distributed LDC does not include file path for runtime modules

### ISSUE THREAD

**Issue by Geod24** [ldc-developers/ldc#3687]
```D
void main ()
{
    int a;
    assert(a);
}
```

```console
$HOME/dlang/ldc-1.25.1/bin/ldc2 -g --link-defaultlib-debug -run a.d
core.exception.AssertError@a.d(4): Assertion failure
----------------
exception.d:429 onAssertError [0x10ab09a00]
exception.d:595 _d_assert [0x10ab09f44]
a.d:4 _Dmain [0x10a8f4172]
Error: /var/folders/1_/wzk0c3d17t37j8r1q8_3zl840000gn/T/a-321895 failed with status: 1
```

Note how `exception.d` is just the file name, and not the file path. IDK if there's a way to represent a path relative to the binary, but at least having `core/exception.d` in there would be good. This triggers for any runtime module.

**Comment by kinke** [comment]
AFAIK, this is just one of many druntime backtrace shortcomings, not using some dirs DWARF table emitted by LLVM.

**Comment by Geod24** [comment]
Thanks, applied the patch in our fork and it works like a charm!
