### ISSUE TITLE
TypeInfo for interface gives invalid string for name

### ISSUE THREAD

**Issue by schveiguy** [ldc-developers/ldc#3693]
In the latest release (1.25.1), using typeid(SomeInterface) gives a TypeInfo_Interface that has a null name, and very incorrect length.

e.g.:

```d
import std.stdio;

interface I {}
void main() {
    auto n = typeid(I).toString;
    writeln(n.ptr, " ", n.length);
}
```

output on my system:

```
null 94194140254384
```

**Comment by schveiguy** [comment]
Note, I tested with 1.24.0 and it does not have this problem.

**Comment by schveiguy** [comment]
Looks like the `info` member is actually pointing back at itself instead of the embedded class.

Two screenshots from godbolt:

![Screen Shot 2021-04-03 at 12 11 09 PM](https://user-images.githubusercontent.com/580778/113484386-096b2280-9476-11eb-8f8a-ac53ab77af5f.png)
![Screen Shot 2021-04-03 at 12 11 18 PM](https://user-images.githubusercontent.com/580778/113484393-0ec86d00-9476-11eb-90e2-9e177a95d033.png)

**Comment by kinke** [comment]
Fixed in https://github.com/ldc-developers/ldc/pull/3678/commits/0d7d776032c1d1ebc369527094012baab06e693d.

**Comment by schveiguy** [comment]
When will this be released? I don't know when godbolt updates their "latest CI" version, so I'm not sure if this build includes the fix. I know that 1.25.1 does not.

The commit says it doesn't belong to any branch. What does that mean? Master doesn't seem to have this fix included.

**Comment by kinke** [comment]
It's part of #3678 & will be in the next beta, scheduled to be released soon.

**Comment by schveiguy** [comment]
OK, thanks!

**Comment by kinke** [comment]
It's in master now.
