### ISSUE TITLE
Attempting to build the same project with LDC 1.25.1 vs 1.26.0-beta1 results in a linker error

### ISSUE THREAD

**Issue by GavinRay97** [ldc-developers/ldc#3700]
The strange thing is that the file it says doesn't exist, actually does, and there are no permissions issues.

Maybe a problem with the length of the directory name in total?

1.25.1
![image](https://user-images.githubusercontent.com/26604994/114648640-2fca6280-9cad-11eb-914c-b525ee284c65.png)

1.26.0-beta1
![image](https://user-images.githubusercontent.com/26604994/114648652-32c55300-9cad-11eb-868c-d34d887cd3df.png)

Here's a video of me deleting the `dub` packages appdata folder and rebuilding, and showing that the file does indeed exist where it says it doesn't (both with `ls` and visually):

https://user-images.githubusercontent.com/26604994/114648803-643e1e80-9cad-11eb-8002-d250dad8dbd9.mp4

Hope this is useful -- thank you! =)

**Comment by kinke** [comment]
Hi,

> Maybe a problem with the length of the directory name in total?

Yes, most likely the 6 additional `-beta1` chars pushing it over the limit; we've just had similar Windows long-path issues with dub at work. If `link.exe` doesn't support the `\\?\` prefix for paths > 260 chars, there's nothing LDC can do.

**Comment by GavinRay97** [comment]
Ouch.

Let me do some more testing on this. I googled, and there's a registry value `LongPathsEnabled` which disables the 260 character path limit:

https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

I went to set this value to `1`, but found it was already set to that:
![image](https://user-images.githubusercontent.com/26604994/114796626-74aed180-9d5f-11eb-87b7-2af5670d9a90.png)

So it can't be that 🤔 

Let me try to build some other programs, or see if I can somehow narrow down what is causing this.
Any tips for debugging root cause of this -- or is this not even a LDC issue, but rather a `link.exe` one?

**Comment by GavinRay97** [comment]
Ah, once you mentioned the `LINK.exe` thing, I tried this in `dub.json`:
```json
{
  "dflags": ["-linker=lld-link"],
}
```

Problem gone. Superior LLVM toolchain saves the day -- `lld` is faster & has better errors anyways! 😅
Should have thought of that earlier.

I'm not sure if I would consider it solved ha, but it's not longer a problem at least 👍

**Comment by kinke** [comment]
I've hit this again (with a path significantly shorter than 260 chars); `link.exe` does support `\\?\` prefixes, so LDC could accommodate for the ridiculous MS linker limitation. Unfortunately, that still wouldn't prevent dub from superfluously rebuilding such projects every time: https://github.com/dlang/dub/issues/2143

**Comment by kinke** [comment]
With https://github.com/dlang/dub/pull/2144 and #3756, the bundled dub now supports paths up to 260 chars (absolute, normalized), independent from the current working directory when invoking dub. I expect this to fix almost all cases. As the MS linker doesn't support longer paths, we cannot do anything from the LDC side - we already have `-link-internally` and `-linker=lld-link` etc.
