### ISSUE TITLE
Support multiple LDC installations on one system

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#3715]
I'll work on improving the default installation folder structure to support multiple versions of LDC on the same system (also such that it does not conflict with gdc or dmd installations).

I think basically _all_ installation paths should add version identifier to `${CMAKE_INSTALL_PREFIX}`.
For example:
- instead of `${CMAKE_INSTALL_PREFIX}/lib` --> `${CMAKE_INSTALL_PREFIX}/lib/ldc/1.24.0`
- instead of `${CMAKE_INSTALL_PREFIX}/include/d` --> `${CMAKE_INSTALL_PREFIX}/include/ldc/1.24.0`

Also, the binaries should be versioned `ldc2-1.24.0`, and a symlink created `ldc2 --> ldc2-1.24.0`.  This is how `clang` is installed, afaik.

The lib/include path installation is more urgent because of 'strange' errors for the user if one installation is installed on top of another (e.g. when a new druntime contains a renamed or removed file, make install will not rename/remove that file...)

**Comment by dnadlinger** [comment]
I'm not sure this is the way to go. LDC already installs cleanly into separate prefixes. The user can always add versioned symlinks to e.g. `/opt/ldc2-.../bin/ldc2`. (I tend to use PATHs, not symlinks.)

**Comment by JohanEngelen** [comment]
I'm open for other solutions. But right now, simply `make install` will not do the right thing. 
What I described is what I see GCC and Clang do (they even include triples, which would help with cross compiling).

**Comment by kinke** [comment]
> The lib/include path installation is more urgent because of 'strange' errors for the user if one installation is installed on top of another (e.g. when a new druntime contains a renamed or removed file, make install will not rename/remove that file...)

Hmm, I thought we had a warning in place if the include dir already exists, but haven't found it after a quick glance, so I guess it remained an idea. ;) - The main problem here is when a module is split up into a package with a newer version, as the compiler silently prefers the old module over `newpackage.package`.

**Comment by JohanEngelen** [comment]
I'm now wondering if we need to support the case of a user manually doing `make install` on several LDC versions without explicit prefix set, or whether this is an issue for package managers...

A related issue is how to more easily support cross compilation. A small help could be if ldc-build-runtime would automatically write the files to a "correct" place (using triples in folder names like clang does)...

**Comment by JohanEngelen** [comment]
> Hmm, I thought we had a warning in place if the include dir already exists

Yeah, perhaps that is a sufficient solution. Just error (warn?) if an installation already exists and only install when user provides an extra flag?

**Comment by dnadlinger** [comment]
> I'm now wondering if we need to support the case of a user manually doing make install on several LDC versions without explicit prefix set, or whether this is an issue for package managers...

Exactly, this is my suspicion as well. Cross-compilation might be a real reason to switch to a different directory structure, though.

**Comment by kinke** [comment]
> A related issue is how to more easily support cross compilation. A small help could be if ldc-build-runtime would automatically write the files to a "correct" place (using triples in folder names like clang does)...

The lib dir alone isn't sufficient; e.g., `-link-defaultlib-shared` needs to be set according to the availability of the static/shared libs in that dir. `-gcc` also to the corresponding C compiler etc. - We've been promised a little tool to download & extract the libs from a prebuilt package + ldc2.conf fiddling multiple times already…

**Comment by JohanEngelen** [comment]
I'm closing this for now, no concrete actionable plan.
