### ISSUE TITLE
Segfault and status code -2 when calling delegate of bound JIT'ed function

### ISSUE THREAD

**Issue by GavinRay97** [ldc-developers/ldc#3722]
I'm interested in potential ways to do runtime-evaluation + JIT of D code. (Something like `cling` essentially)
One interesting application for this would be to create tools like this in D:

[Audio Programming Environment 0.5.0: C++ DSP directly in your DAW!](https://www.kvraudio.com/forum/viewtopic.php?f=33&t=560622)
http://www.jthorborg.com/index.html?ipage=ape

I can see from the docs that:

<hr>

- In generateBitcodeForDynamicCompile first recursively search functions calls inside functions body, starting with @dynamicCompile functions.
- After that we have two lists of functions:
	- Directly marked by user @dynamicCompile
	- Not marked by user but used by @dynamicCompile functions directly or indirectly and with body available
- Both lists are subject to dynamic compilation. For the first list dynamic version will be always used. For the second static version will be used when called from static code and dynamic version when called from dynamic code.

<hr>

I am trying to create functions which can JIT arbitrary D methods and `eval()` D strings, but the below causes a segfault.

Is this because the delegate is called after `scope (exit) destroyCompilerContext(context);`?
If so, how do I clone the delegate to make it outlive the JIT scope?

Thank you! 😃

```sh
tmp/dlang-dynamic-compile-test
❯ ldc2 -enable-dynamic-compile -run source/app.d
Calling jited()
Error: /tmp/app-91856b failed with status: -2
       message: Segmentation fault
Error: program received signal 2 (Interrupt)
```

```d
import std.stdio;
import std.string;
import ldc.attributes;
import ldc.dynamic_compile;

auto createJITedDelegate(T)(T originalFn)
{
	auto context = createCompilerContext();
	scope (exit) destroyCompilerContext(context);

	auto boundFn = bind(originalFn);
	compileDynamicCode(context);

	return boundFn.toDelegate();
}

void main(string[] args)
{
	auto jited = createJITedDelegate({
		writeln("Hello from JIT'ed");
		return 42;
	});
	writeln("Calling jited()");
	jited();
}
```

---

**Edit:** apparently there are other problems, because this assertion is failing if I try to call the delegate inside of the create-JIT function:

```d
auto boundDelegate = boundFn.toDelegate();
writeln("Calling JIT'ed inside of createJITedDelegate()");
boundDelegate();
```

```d
  auto opCall(FuncParams args)
  {
	// ldc/dynamic_compile.d(505)
    assert(isCallable());
    return func(args);
  }
```

```sh
❯ ldc2 -enable-dynamic-compile -run source/app.d
Calling JIT'ed inside of createJITedDelegate()
core.exception.AssertError@/home/user/dlang/ldc-1.26.0/bin/../import/ldc/dynamic_compile.d(505): Assertion failure
----------------
??:? [0x55fdc5b7d7d5]
??:? [0x55fdc5b7f256]
??:? [0x55fdc5b6253f]
??:? [0x55fdc5b5ac1c]
??:? [0x55fdc5b31018]
??:? [0x55fdc5b2f8bc]
??:? [0x55fdc5b2f7fb]
??:? [0x55fdc5b6222b]
??:? [0x55fdc5b62127]
??:? [0x55fdc5b61f7d]
??:? [0x55fdc5b2fa74]
??:? __libc_start_main [0x7f4fa75840b2]
??:? [0x55fdc5b2f70d]
Error: /tmp/app-4c48b2 failed with status: 1
```

**Comment by JohanEngelen** [comment]
@Hardcode84 Perhaps you can help here?

**Comment by Hardcode84** [comment]
I didn't look into dynamic compile code for years :)

1. You don't need `createCompilerContext()` here, if you call `bind` without explicitly passing context as first parameter it will use default global context, which lives until program is terminated.
2.  Delegate lifetime bound both to context lifetime and `boundFn` lifetime, there is no way to extend it for now.
3. Not sure about the assert failure, is it work if you call `boundFn()` directly?

**Comment by Hardcode84** [comment]
+ `boundFn` is reference-counted internally and can be copied

**Comment by GavinRay97** [comment]
Wow, this is incredible -- thank you!! With your feedback and help from adr on Discord, I was able to get it to work!
Now I just have to see if it'll work with strings as `mixin()`'s =D

![image](https://user-images.githubusercontent.com/26604994/118378592-ef5b4e80-b5a2-11eb-8869-1b7690ec8e16.png)


```d
auto createJITedDelegate(T)(T originalFn)
{
    auto boundFn = bind(originalFn);
    compileDynamicCode();
    return boundFn;
}

void main(string[] args)
{
    auto boundJited = createJITedDelegate({
        writeln("Hello from JIT'ed");
        return 42;
    });
    auto jited = boundJited.toDelegate();
    writeln("Calling jited()");
    jited();
	auto jitedResult = jited();
	writeln("Result of jited() is: ", jitedResult);
}
```

**Comment by GavinRay97** [comment]
Ahh I actually do not think I can do dynamic string/`mixin` evaluation =/
