### ISSUE TITLE
Use space-separated flags in D_EXTRA_FLAGS (instead of semicolon)

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#3731]
@kinke   I just discovered that our CMake variable D_EXTRA_FLAGS requires a semi-colon `;` to separate commandline flags. You also see this in ldc-build-runtime commandline with `--dFlags`, for example: `CC=mipsel-linux-gcc ldc-build-runtime --ninja --dFlags="-mtriple=mipsel-linux;-mcpu=mips32" --cFlags="-march=mips32"`

I find this counter-intuitive, and would rather have our CMake script accept space-separated flags.
Do you agree?

**Comment by kinke** [comment]
IIRC, the separator is mentioned in both CMakeLists.txt and the ldc-build-runtime help. I very much prefer CMake lists over space-separated pseudo-lists (as used by CMake itself for C flags etc.), especially when having to deal with spaces in those args and according quoting madness.
