### ISSUE TITLE
Add extra allocator lib when linking LDC

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#3737]
At weka we've found that using mimalloc (https://microsoft.github.io/mimalloc/index.html) gives a huge LDC performance boost. We can use LD_PRELOAD, but I'd rather build this into the LDC executable. We can do this by linking an extra object file (`mimalloc.o`) when linking LDC.
It's not clear to me how best to add this as an option to our CMake script. A generalized option to add object files to the link line would be sufficient).
Something like this in `BuildDExecutable.cmake`:
```diff
    # Link to an executable.
    if(LDC_LINK_MANUALLY)
-        add_executable(${target_name} ${object_files})"
+        add_executable(${target_name} "${user_supplied_object_files};${object_files})"
```

Shall I add a general cmake option for this?
`cmake -DLINK_WITH_EXTRA_OBJECT_FILES="/usr/local/lib/mimalloc-1.7/mimalloc.o"`
Or a (mi)malloc-specific option? (other allocators use the same trick)

**Comment by kinke** [comment]
Might be feasible by setting `D_LINKER_ARGS` instead of detecting them; those flags are the last ones being appended AFAICT, so if the order is still okay, it should work.

**Comment by JohanEngelen** [comment]
Adding it to `D_LINKER_ARGS` fails building `ldmd2` because first `libldmd` is created (with the object file added) and then again the object file is added when linking `ldmd2`.  But it does work to build `ldc2` that way (with correct override of malloc).

**Comment by JohanEngelen** [comment]
Perhaps add a `D_EXTRA_LINKER_ARGS` option that is only used for the final links?

**Comment by JohanEngelen** [comment]
I'm at a loss. For some reason, `D_LINKER_ARGS` is _partly_ copied twice on the linker line for `ldmd2` and not for `ldc2`. So LDC links correctly and LDMD doesn't. I've tried a bunch of hacks to our CMake script but can't get it to behave different.

```
[125/283] Linking CXX executable bin/ldmd2
FAILED: : && /usr/bin/c++   -DDMDV2 -DHAVE_SC_ARG_MAX -O3 -DNDEBUG   obj/ldmd2.o  -o bin/ldmd2  -rdynamic lib/libldmd.a -llldDriver -llldMinGW -llldCOFF -llldELF -llldMachO -llldWasm -llldYAML -llldReaderWriter -llldCommon -llldCore -lLLVMSymbolize -lLLVMWindowsManifest -lLLVMLTO -lLLVMPasses -lLLVMCoroutines -lLLVMObjCARCOpts -lLLVMExtensions -lLLVMLibDriver -lLLVMOption -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMFrontendOpenMP -lLLVMDebugInfoPDB -lLLVMAsmParser -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Utils -lLLVMAArch64Info -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMCFGuard -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoDWARF -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMTextAPI -lLLVMMCParser -lLLVMBitReader -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBinaryFormat -lLLVMX86Info -lLLVMSupport -lLLVMDemangle -L/usr/local/lib -lz -lrt -ldl -ltinfo -lpthread -lm -Wl,--export-dynamic -fuse-ld=gold /usr/local/lib/mimalloc-1.7/mimalloc.o -L/tmp/ldcbootstrap/bin/../lib -lphobos2-ldc -ldruntime-ldc -Wl,--gc-sections -lrt -ldl -lpthread -lm -m64 -ltinfo /usr/local/lib/mimalloc-1.7/mimalloc.o -lphobos2-ldc -ldruntime-ldc

LDC link line:
[3/3] : && /usr/bin/c++   -DDMDV2 -DHAVE_SC_ARG_MAX -O3 -DNDEBUG   obj/ldc2.o  -o bin/ldc2  -rdynamic lib/libldc.a -llldDriver -llldMinGW -llldCOFF -llldELF -llldMachO -llldWasm -llldYAML -llldReaderWriter -llldCommon -llldCore -lLLVMSymbolize -lLLVMWindowsManifest -lLLVMLTO -lLLVMPasses -lLLVMCoroutines -lLLVMObjCARCOpts -lLLVMExtensions -lLLVMLibDriver -lLLVMOption -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMFrontendOpenMP -lLLVMDebugInfoPDB -lLLVMAsmParser -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Utils -lLLVMAArch64Info -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMCFGuard -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoDWARF -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMTextAPI -lLLVMMCParser -lLLVMBitReader -lLLVMCore -lLLVMRemarks -lLLVMBitstreamReader -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBinaryFormat -lLLVMX86Info -lLLVMSupport -lLLVMDemangle -L/usr/local/lib -lz -lrt -ldl -ltinfo -lpthread -lm -Wl,--export-dynamic -fuse-ld=gold /usr/local/lib/mimalloc-1.7/mimalloc.o -L/tmp/ldcbootstrap/bin/../lib -lphobos2-ldc -ldruntime-ldc -Wl,--gc-sections -lrt -ldl -lpthread -lm -m64 -ldl -ltinfo -lpthread -lm
```

**Comment by kinke** [comment]
Another option *could* be setting `DFLAGS=/usr/local/lib/mimalloc-1.7/mimalloc.o` when invoking CMake (but not when building later via make/ninja!) as a way to add it to `D_LINKER_ARGS` (I'm not sure at which position though).

**Comment by JohanEngelen** [comment]
I've modified CMakeLists to get what I want, I'll see about upstreaming, it's useful and a simple change.

**Comment by kinke** [comment]
> gives a huge LDC performance boost

Do you have some rough numbers? If it's really significant, we should employ it for the official packages.

**Comment by kinke** [comment]
Btw, completely off-topic, but have you seen https://forum.dlang.org/thread/s95nmg$vbk$1@digitalmars.com ('Any way to peek at the exception currently being thrown?'). Somehow I seem to recall some efforts from your side to get something like that into druntime...

**Comment by JohanEngelen** [comment]
The CMake addition: https://github.com/ldc-developers/ldc/pull/3758
Compile time is 30% faster in total with codegen at Weka!

**Comment by JohanEngelen** [comment]
> Btw, completely off-topic, but have you seen https://forum.dlang.org/thread/s95nmg$vbk$1@digitalmars.com ('Any way to peek at the exception currently being thrown?'). Somehow I seem to recall some efforts from your side to get something like that into druntime...

Yes, I remember that too ;-)  Need to go and dig it up...

**Comment by kinke** [comment]
> Compile time is 30% faster in total with codegen at Weka!

What?! Okay you got me definitely interested now. :D

**Comment by JohanEngelen** [comment]
@kinke Probably good to test for yourself to see if the 30% is real ;-)  (the speed boost was also very big for frontend code, but that was because the frontend has a perf bug that Eyal fixed by caching, to be upstreamed soon)
