### ISSUE TITLE
Windows: No Structured Exception Handling support (for hardware faults like access violations)

### ISSUE THREAD

**Issue by warmlufterzeuger** [ldc-developers/ldc#3742]
Hello LDC developers,

I face an annoying problem with a D DLL which calls C code (using a function pointer) on Windows.
ldc2 version is 1.25.0-beta1, I also tested on 1.26.0. Both show this problem.
If this external c code causes an exception, the D DLL won't catch it. Instead the program just ends, looking normal.
I also used the reference D compiler DMD 2.093.1-dirty - that is working.
I'm avoiding the DMD because it produces binaries that are much slower.

I prepared a minimalistic example:
- save the snippets to files
- run ldc2 -m32 -g -O -d-debug -ofSlim.dll slim.d dmd_dll.def dmd_dll_wrapper.d
- run dlltool -d slim.def -l libSlim.a
- run gcc -g -o test.exe test.c -L. -lSlim
- run test.exe

**expected result on console:**
 try calling
 abnormal exit, object.Error@(0): Access Violation
 <stack dump>
 some cleanup
 C:\>

**actual result on console:**
 try calling
 C:\>
 that's it!

**result if no crash is forced:**
 try calling
 done
 some cleanup
 C:\>

---
The D DLL code "slim.d":
>>>
```
import std.stdio;
import std.string;
import std.conv;

alias extern(C) void function()  c_fn_type;

export extern(C)
{
	void dcall(c_fn_type init_fn)
	{
		try
		{
			std.stdio.writefln("try calling");
			init_fn();
			std.stdio.writefln("done");
		}
		catch (Throwable o) {
			std.stdio.writefln("abnormal exit, " ~ o.toString()); // this catch is working on DMD but not on LDC
		}
		finally {
			std.stdio.writefln("some cleanup");
		}
	}
}
```
---
DLL wrapper dmd_dll_wrapper.d:
>>>
```
version (Windows)
{
        import core.sys.windows.windows;
        import core.sys.windows.dll;
        import std.stdio;
        __gshared HINSTANCE g_hInst;
        extern (Windows)
        BOOL DllMain(HINSTANCE hInstance, ULONG ulReason, LPVOID pvReserved)
        {
                try
                {
                        switch (ulReason)
                        {
                        case DLL_PROCESS_ATTACH:
                                g_hInst = hInstance;
                                dll_process_attach( hInstance, true );
                                break;
                        case DLL_PROCESS_DETACH:
                                dll_process_detach( hInstance, true );
                                break;
                        case DLL_THREAD_ATTACH:
                                dll_thread_attach( true, true );
                                break;
                        case DLL_THREAD_DETACH:
                                dll_thread_detach( true, true );
                                break;
                        default:
                                assert(0);
                        }
                }
                catch (Throwable e)
                {
                        writefln("Caught exception in DLL, aborting (%s)", e.toString()); // this catch is working on DMD but not on LDC
                }
                return true;
        }
}
```
---
DEF file slim.def:
>>>
```
LIBRARY slim.dll

EXPORTS
dcall
```
---
DLL def for linking dmd_dll.def:
>>>
```
LIBRARY "slim.dll"
EXETYPE NT
SUBSYSTEM WINDOWS
CODE SHARED EXECUTE
DATA WRITE
```
---
The c code test.c: 
>>>
```
#include <stdio.h>
#include <string.h>

typedef void call_ctype();
extern void dcall(call_ctype init_fn);

void demo_init()
{
		int i=1, j=2;
		int *p;
		p = (int *)(i-j+1);
		*p = 1; // force crash
}

int main()
{
	dcall(&demo_init);
	return 0;
}
```
---

**Comment by warmlufterzeuger** [comment]
Hi kinke,

thanks, the throw indeed works that way. This is not the problem I'm trying to solve, since when I cause an exception (i.e. pointer write to invalid location), it will still just exit without any trace of the problem.

```
void demo_init()
{
    int *p;
	p = (int*)0x00000004;
	*p = 1;
}

```

Best Regards,
wle

**Comment by kinke** [comment]
I don't think we'll ever revert to SEH like DMD. On Linux, segfaults cannot be caught either.

**Comment by kinke** [comment]
Workaround in `test.cpp`:
```C++
#include <exception>
#include <windows.h>

using VoidFn = void (*)();

void dcall(VoidFn init_fn);

void demo_init()
{
    __try
    {
        int *p;
        p = (int*)0x00000004;
        *p = 1;
    }
    __except(EXCEPTION_EXECUTE_HANDLER)
    {
        throw std::exception("Ooops");
    }
}

int main()
{
    dcall(&demo_init);
    return 0;
}
```

**Comment by warmlufterzeuger** [comment]
Hi kinke,

thanks,
that works indeed.
Takes a little effort to prepare all the callbacks, and I need to figure out how to convert the old code as c++, though.
But it's possible.
Best Regards,
wle

**Comment by kinke** [comment]
Okay, I'll close this as WONTFIX then; Microsoft recommends C++ EH too, from https://docs.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-160:
> Although Windows and Microsoft C++ support SEH, we recommend that you use ISO-standard C++ exception handling.

**Comment by warmlufterzeuger** [comment]
Hi again, 
I found a workaround for C, too.
Perhaps it makes sense to document it here.
Using e4c (exceptions for C - [E4C](https://github.com/guillermocalvo/exceptions4c)), I can have the same behavior, also I'm using gcc and not the VS C compiler.
```
#include <stdio.h>
#include <string.h>
#include "e4c.h"

typedef void call_ctype();
extern void dcall(call_ctype init_fn);

void demo_init()
{
	e4c_using_context(E4C_TRUE){
		int i=1, j=2;
		int *p;
		p = (int *)(i-j+1);
		
		try{
			*p = 1; // force crash
		} catch( RuntimeException ){
			printf("bad pointer in c\n");
		} finally{
			printf("finalize\n");
		}
	}
}

int main()
{
	dcall(&demo_init);
	return 0;
}
```
I set the export back to C in slim.d.

Then build:
ldc2 -m32 -g -O -d-debug -ofSlim.dll slim.d -shared
gcc -g -o test.exe test.c e4c.c -L. -lSlim -DE4C_THREADSAFE

Output:
try calling
bad pointer in c
finalize
done
some cleanup
C:\>

So all exception handlers are triggered. Just how I expect it to be.
Have a nice day!
wle

**Comment by kinke** [comment]
Well, that's all in C land then, no exception makes it across the language boundary, and `done` is printed. If that's all you need - fine. :)
