### ISSUE TITLE
Can't compile LLVM 12

### ISSUE THREAD

**Issue by Fatmice** [ldc-developers/ldc#3743]
Downloaded LLVM 12 from
https://github.com/ldc-developers/llvm-project/releases/download/ldc-v12.0.0/llvm-12.0.0.src.tar.xz

Run build with
```
#!/bin/bash

set -e

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

if ! [ -d build-llvm ] ; then
	mkdir build-llvm
fi

cd build-llvm
cmake -G Ninja ../llvm-12.0.0.src \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=${SCRIPTPATH}/install-llvm \
  -DLLVM_BINUTILS_INCDIR=/usr/include \
  -DLLVM_TARGETS_TO_BUILD='AArch64;ARM;Mips;MSP430;NVPTX;PowerPC;RISCV;WebAssembly;X86' \
  -DCOMPILER_RT_INCLUDE_TESTS=OFF \
  -DLLVM_INCLUDE_TESTS=OFF \
  -DLLVM_STATIC_LINK_CXX_STDLIB=ON

#  -DLLVM_LIBDIR_SUFFIX=64 \
ninja
rm -rf ../install-llvm
ninja install
ninja clean
cd $SCRIPTPATH
rm -rf build-llvm
rm -rf llvm-12.0.0.src
```

FAILED: tools/lld/MachO/CMakeFiles/lldMachO2.dir/UnwindInfoSection.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/lld/MachO -I/home/ocelot/LLVM/llvm-12.0.0.src/tools/lld/MachO -I/home/ocelot/LLVM/llvm-12.0.0.src/tools/lld/include -Itools/lld/include -Iinclude -I/home/ocelot/LLVM/llvm-12.0.0.src/include -I/home/ocelot/LLVM/llvm-12.0.0.src/../libunwind/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2 -DNDEBUG    -fno-exceptions -fno-rtti -std=c++14 -MD -MT tools/lld/MachO/CMakeFiles/lldMachO2.dir/UnwindInfoSection.cpp.o -MF tools/lld/MachO/CMakeFiles/lldMachO2.dir/UnwindInfoSection.cpp.o.d -o tools/lld/MachO/CMakeFiles/lldMachO2.dir/UnwindInfoSection.cpp.o -c /home/ocelot/LLVM/llvm-12.0.0.src/tools/lld/MachO/UnwindInfoSection.cpp
In file included from /home/ocelot/LLVM/llvm-12.0.0.src/tools/lld/MachO/UnwindInfoSection.cpp:9:
/home/ocelot/LLVM/llvm-12.0.0.src/tools/lld/MachO/UnwindInfoSection.h:15:10: fatal error: mach-o/compact_unwind_encoding.h: No such file or directory
   15 | #include "mach-o/compact_unwind_encoding.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by kinke** [comment]
This sounds exactly like https://groups.google.com/g/llvm-dev/c/gIY5COm6V5E.

**Comment by Fatmice** [comment]
If that is the case how did you compile against your own LLVM 12 src ?

**Comment by kinke** [comment]
Using the monorepo directly, and enabling the desired extra projects explicitly; fully automated as CI jobs: https://github.com/ldc-developers/llvm-project/blob/0ae541f11a609224c3e682b7d3c1ec21da5d86bf/.azure-pipelines/posix.yml#L16

**Comment by Fatmice** [comment]
So you are saying that the LLVM 12 src
https://github.com/ldc-developers/llvm-project/releases/download/ldc-v12.0.0/llvm-12.0.0.src.tar.xz

Is incomplete and that I should not use it and should wait until upstream releases a newer version?

**Comment by kinke** [comment]
After a quick glance at the linked post, it seems like the LLD 12.0.0 source unconditionally expects libunwind to be there as extra project, and adding it manually (via https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/libunwind-12.0.0.src.tar.xz) is required to make it compile. Another option would be to exclude LLD if you don't need it (by just removing it from the `projects` subdir).

**Comment by Fatmice** [comment]
Where do I add this libunwind directory?
There google group post did not specify where they added it only that "Extracting it to the appropriate directory made the build happy."  This is vague and unhelpful.

If I add libunwind to the llvm-12.0.0.src/projects/, then CMake will emit
```
-- Performing Test C_SUPPORTS_WERROR_IMPLICIT_FUNCTION_DECLARATION
-- Performing Test C_SUPPORTS_WERROR_IMPLICIT_FUNCTION_DECLARATION - Success
-- Performing Test C_SUPPORTS_WERROR_GLOBAL_CONSTRUCTOR
-- Performing Test C_SUPPORTS_WERROR_GLOBAL_CONSTRUCTOR - Failed
-- Performing Test CXX_SUPPORTS_WERROR_GLOBAL_CONSTRUCTOR
-- Performing Test CXX_SUPPORTS_WERROR_GLOBAL_CONSTRUCTOR - Failed
CMake Error at projects/libunwind/CMakeLists.txt:2 (message):
  libunwind requires being built in a monorepo layout with libcxx available


-- Configuring incomplete, errors occurred!
See also "/home/ocelot/LLVM/build-llvm/CMakeFiles/CMakeOutput.log".
See also "/home/ocelot/LLVM/build-llvm/CMakeFiles/CMakeError.log".
```
What is a "monorepo" layout?  I didn't have to mess around with your LLVM-11 release.  This is why I always hesistate to update.

**Comment by Fatmice** [comment]
Okay, on a hunch, I went ahead and added all three libunwind, libcxx, libcxxabi to the `llvm-12.0.0.src/projects/`

CMake went through it motion then emit
```
CMake Error at projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:557 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2224 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:642 (ExternalProject_Add_Step)
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:557 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:557 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2224 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:642 (ExternalProject_Add_Step)
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:557 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:557 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:2224 (add_custom_command):
  Error evaluating generator expression:

    $<TARGET_FILE:clang>

  No target "clang"
Call Stack (most recent call first):
  projects/compiler-rt/cmake/Modules/AddCompilerRT.cmake:642 (ExternalProject_Add_Step)
  projects/compiler-rt/lib/tsan/CMakeLists.txt:250 (add_custom_libcxx)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
So, it appears now it wants to pull in `clang`....no thanks.

**Comment by Fatmice** [comment]
This seems to work.
Download and extract https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.0/libunwind-12.0.0.src.tar.xz
Download and extract https://github.com/ldc-developers/llvm-project/releases/download/ldc-v12.0.0/llvm-12.0.0.src.tar.xz
Copy everything under `libunwind-12.0.0.src/include` to `llvm-12.0.0.src/tools/lld/include`
Run my script again.  Everything compiled.  However, I do not know if this is right and will yield a good instance of llvm-12

**Comment by kinke** [comment]
Wrt. libunwind extraction dir, your 1st failing command-line includes `-I/home/ocelot/LLVM/llvm-12.0.0.src/../libunwind/include`. - The proper bug report is https://bugs.llvm.org/show_bug.cgi?id=49228, and apparently it's not fixed yet.
