### ISSUE TITLE
RVO not done when return statement expression is a constructor call

### ISSUE THREAD

**Issue by ibuclaw** [ldc-developers/ldc#3778]
A variant of https://godbolt.org/z/e9xEhb6xa from GDC bugzilla report https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101273
```
struct S
{
    int x;
    S* impl; 
    this(int x)
    {
        this.x = x;
        this.impl = &this;
    }
    ~this() { }
}

S makeS()
{
    return S(2);
}

S nrvo()
{
    S ret = makeS();
    return ret;
}

S rvo()
{
    return makeS();
}

void main()
{
    auto nrvo = nrvo();
    assert(&nrvo is nrvo.impl);

    auto rvo = rvo();
    assert(&rvo is rvo.impl);
}
```

What happens is that - because of the presence of a constructor - a temporary is created by the DMD front-end in the form of:
```
S makeS()
{
    return ((S __slS58 = S(0);) , __slS58).this(2);
}
```

The fix was to detect the declaration of a new temporary _inside_ a ReturnStatement and swap the temporary for the hidden return slot/pointer.

**Comment by kinke** [comment]
Oh thanks for filing the issue. My heartbeat stopped for a second as you mentioned NRVO, but `nrvo()` works fine, it's just RVO in `makeS()`. ;)

**Comment by kinke** [comment]
[Need to check why this isn't caught by https://github.com/ldc-developers/ldc/blob/a469b7e07d39dfbe985a56c1afb05073be3684b8/gen/toir.cpp#L2795-L2811.]

**Comment by ibuclaw** [comment]
> https://github.com/ldc-developers/ldc/blob/a469b7e07d39dfbe985a56c1afb05073be3684b8/gen/toir.cpp#L2795-L2811

That's the simple check.  With a temporary it's more convoluted.  After [this block](https://github.com/ldc-developers/ldc/blob/a469b7e07d39dfbe985a56c1afb05073be3684b8/gen/toir.cpp#L2799-L2809), you would doing something like:

```
else if (auto ce = dve->e1->isCommaExp()) {
  if (
    ce->e1->isDeclarationExp() != NULL &&
    ce->e2->isVarExp() != NULL &&
    ce->e2->isVarExp()->var == ce->e1->isDeclarationExp()->declaration &&
    ce->e2->isVarExp()->var->storage_class & STCtemp
  ) {
    Logger::println("success, in-place-constructing temporary and "
                    "invoking ctor");
    // do magic here.
  }
}
```
Add some local variables to avoid repeating the same side-effects.
