### ISSUE TITLE
ldc reject code when I try to init pointer with array

### ISSUE THREAD

**Issue by j123123** [ldc-developers/ldc#3800]
Testcase:
```D
/*
// with -betterC this works only in ldc
char test1(char ind)
{
  char *a = (cast(char[3])[2,4,8]).ptr;
  return a[ind];
}
*/


// works in gdc, dmd, doesnt work in ldc
// Error: `['\x02', '\x04', '\x08'][0]` is not an lvalue and cannot be modified
char test2(char ind) 
{
  char *a = &(cast(char[3])[2,4,8])[0];
  return a[ind];
}
```
https://godbolt.org/z/MbMhzs8dK

I'm not sure, maybe this is not a bug, but then this code must be also rejected in gdc and dmd.

**Comment by kinke** [comment]
This is a 2.095 frontend change/fix; you're comparing LDC v1.26 based on v2.096 against DMD v2.094 and GDC based on v2.076. (See `pragma(msg, __VERSION__);`).
