### ISSUE TITLE
LDC and Clang use different default target features/ABI for riscv64-linux

### ISSUE THREAD

**Issue by jacob-carlborg** [ldc-developers/ldc#3814]
I'm not sure what the default is for LDC, but it doesn't match Clang, at least not when it comes to floating point. For example, when compiling an empty main:

```d
extern (C) void main() {}
```

With: `ldc2 -mtriple riscv64-linux -c main.d -betterC` and linking on a Debian riscv64-linux system I get the following error:

```
can't link soft-float modules with double-float modules
```

If I pass `--target-abi lp64d --mattr=+d` as well to LDC when compiling the program successfully links.

By default, the Clang driver passes the following target feature and target ABI related flags to the frontend:

```
-target-feature +m -target-feature +a -target-feature +f -target-feature +d -target-feature +c -target-feature +relax -target-feature -save-restore -target-abi lp64d
```

**Comment by kinke** [comment]
With the exception of #3812 for MIPS and PowerPC (and some min CPU assumptions for x86 depending on OS), LDC simply defaults to the LLVM defaults. Copying and keeping in sync all extra stuff from clang is almost certainly infeasible.

**Comment by jacob-carlborg** [comment]
That's unfortunate. But I guess in this case it's a minor issue since the behavior can be configured.
