### ISSUE TITLE
LDC release no longer runs on 16.04

### ISSUE THREAD

**Issue by FeepingCreature** [ldc-developers/ldc#3815]
```
.../ldc-1.27.1/ldc2-1.27.1-linux-x86_64/bin/ldc2: /lib/x86_64-linux-gnu/libm.so.6:
  version `GLIBC_2.27' not found
```

This is that hilariously dumb glibc issue where the GNU people somehow forgot how their own versioned symbol support worked and broke backwards compatibility for no reason.

\- Anyway, did you recently change your build system? If possible, unless you need newer features, could you configure it to run on Ubuntu 16.04 or something compatible with 16.04, ie. using glibc <2.27? 16.04 is not EOL until 2024.

It's not a big issue, I can change ldc to build from source instead, it's just a bit annoying.

**Comment by Geod24** [comment]
> 16.04 is not EOL until 2024.

Well it's in [ESM](https://ubuntu.com/security/esm) right now, but past standard support.
On the one hand I agree that this is a widespread (and not necessary, AFAIK) breakage, on the other keeping the build for an additional 3 years might lead to additional work.
Does d-apt still update LDC for 16.04 ?

**Comment by kinke** [comment]
ESM is EOL to me, and I don't plan any changes wrt. the base image policy for our CI and thus prebuilt packages. The bump to Ubuntu 18 is mentioned in the release/change log.

**Comment by FeepingCreature** [comment]
Ah, didn't see, thanks. I'll build manually then.

I'll try to dig out the build process from the CI to reproduce.

**Comment by kinke** [comment]
If you want perfect package equivalents and Azure Pipelines is an option for your company, I suggest forking LDC and minimally adapting the YAML like this: https://github.com/symmetryinvestments/ldc/commit/5ba305a718520d08c9d45e3c241c101037a4fe98. (The `gitHubConnection` thing will need work in the Azure Pipelines GUI.) Then just push a tag and wait for the packages to get uploaded to GitHub.

Then you can trivially extend the dlang install bash script too, switching to your GitHub repo URL if the version matches some company-specific suffix.

**Comment by FeepingCreature** [comment]
We have an internal deploy setup, but I'll use that as a basis, thanks.

**Comment by kinke** [comment]
[Oh the above won't work with our latest prebuilt LLVM packages, those are also built on Ubuntu 18 (since v12.0.0 or v12.0.1, don't remember exactly, but it's all in the Azure Pipelines YAML). So you'd either have to use an older version or fork that too (and adapt the LDC YAML accordingly, downloading prebuilt LLVM from your fork).]

**Comment by FeepingCreature** [comment]
Okay, since I couldn't work out how to get Ubuntu's system LLVM to link statically, and we *should* be using 18.04 everywhere anyways, I'm gonna save myself half a morning and just stick with the official release.

Thanks for all the advice!
