### ISSUE TITLE
test suite is slow

### ISSUE THREAD

**Issue by Apteryks** [ldc-developers/ldc#3828]
Hello,

While working on updating this package in GNU Guix, I noticed that running the test suite takes a lot of time (~15 minutes on a very fast machine), with most of the time seemingly spent in building the test runners (sequentially, on a single processor core).

Is there anything that can be done to parallelize it or make it faster?  I'm already running with `make -j24 test`.

Thanks!

**Comment by kinke** [comment]
Hi; I've never tried the `test` target myself. Using `ninja` would probably use all cores for the library unittest runners too. For CI, we build everything in one go, incl. LDC and ~all test runners, e.g., `make -j24 all ldc2-unittest all-test-runners` (https://github.com/ldc-developers/ldc/blob/36198b36ba7b2483a3e98d07c129aba39152e988/.azure-pipelines/2-posix-build_native.yml#L44). The library-unittest runners (`all-test-runners`) are memory-hungry though, so you may have to reduce the number of jobs for those.

**Comment by Apteryks** [comment]
Hi, and thanks for the reply!

I'm trying with ninja now, and the compilation of the test binaries occur in parallel now, nice!  It'd be nice though if every binary could be built as part of 'all' or a distinct target such as 'test-binaries' or similar before running 'test', so that when running the tests only execution of tests would happen, not lengthy compilation of them.  There's some benefit to keeping these concerns separate to provide better diagnostic (was it an error during the build?  during the execution of the test suite?) at the packaging level.

**Comment by kinke** [comment]
IIUC, what you propose as `test-binaries` is `ldc2-unittest all-test-runners`. As said, I have 0 experience with `ninja|make test`;  I guess it's equivalent to `ctest`, which is most likely way too coarse-grained wrt. parallelization and output clutter - that's primarily why CI runs the 4 testsuites separately, with separate tailored `ctest` cmdlines.

**Comment by Apteryks** [comment]
Oh, I see.  So the 'test' target must have been pulling `ldc2-unittest` and `all-test-runners` as prerequisites.  I'm starting to see things clearly now, thank you.  Will experiment some more and close this if everything is OK.

**Comment by kinke** [comment]
Yes, some tests have ninja/make build dependencies as prerequisites, which are probably just built via `ninja|make <prerequisite>`, and so serially with `make`.

**Comment by dnadlinger** [comment]
Yep, unless my memory fails me, the reason for the separate ahead-of-time build step is precisely the parallelism issue.

**Comment by Apteryks** [comment]
Yep, also building the ldc2-unittest and all-test-runners targets (along `all`) seemingly makes things faster.

Thank you! Closing.
