### ISSUE TITLE
There is no warning for wrong inline assembly instructions

### ISSUE THREAD

**Issue by rempas** [ldc-developers/ldc#3872]
Let's say that I'm having the following code:

```D
void main() {
  const char *msg = "Hello world!\n";
  int len = 14;
  asm {
    mov RAX, 1;
    mov RDI, 1;
    mov RSI, msg;
    mov RDX, len;
    syscall;
  }
}
```
When trying to compile with DMD, I will get the following error message:

```
Error: integer constant expression expected instead of `"Hello world!\x0a"`
Error: bad type/size of operands `mov`
```
If I change the type of "len" to `long` or `ulong`, it will compile. Now on LDC, I will not get the error and it will compile normally. However, when I execute it, it will not show anything. I think it should bring up an error just like DMD. I haven't write any extreme assembly, other cases my be up as well...

**Comment by JohanEngelen** [comment]
I don't think LDC should be implementing an assembler that does type checking on individual instructions like that. LDC supports vastly more assembly instructions than DMD on x86, and also supports other architectures. When the user is writing inline assembly, I think we can assume that he knows what he is doing.

**Comment by rempas** [comment]
> When the user is writing inline assembly, I think we can assume that he knows what he is doing

I mean you are not wrong... Maybe this can indeed be the case. I will close me issue and maybe if they developers re think about that, they can re-open it

**Comment by JohanEngelen** [comment]
I recommend using the GDC-style inline assembly with LDC; besides the better constraints and optimization potential, perhaps you'll get some type checking. https://wiki.dlang.org/Using_GDC#Extended_Assembler
