### ISSUE TITLE
ldc does not zero unused upper bits when calling c functions with arguments smaller than 32 bits

### ISSUE THREAD

**Issue by eyal-horn-weka** [ldc-developers/ldc#3884]
clang seems to rely on those bits being zeroed.

For example, the following D binding is used:
int wdpdk_flow_isolate(ushort port_id, int set, rte_flow_error *error);

This is the C function:
int wdpdk_flow_isolate(uint16_t port_id, int set, struct rte_flow_error *error);

LDC 1.24.0
clang 11.0.1

**Comment by JohanEngelen** [comment]
I think Clang is to blame here, it should not assume that 16bit numbers are sign/zero extended to 32bit. GCC and ICC do not seem to make that assumption (for array indexing at least):
https://c.godbolt.org/z/6q6afrzPr

Related discussion: https://stackoverflow.com/questions/36706721/is-a-sign-or-zero-extension-required-when-adding-a-32bit-offset-to-a-pointer-for/36760539#36760539

**Comment by JohanEngelen** [comment]
I think LDC should be cautious here and apply zero/sign extension to 32-bit for smaller parameters.

https://www.reddit.com/r/C_Programming/comments/89h5lj/til_icc_and_clang_are_not_abicompatible_on_x8664/

**Comment by JohanEngelen** [comment]
@eyal-horn-weka I have a reproducer for the C side (where zero-extension is indeed assumed), but I do not have a reproducing testcase for the D side, where LDC does _not_ zero extend.

**Comment by kinke** [comment]
Yeah, this should be handled by https://github.com/ldc-developers/ldc/blob/370dc7ea81ab348f13ebd4ddaf1ed7d5d6d19264/gen/tollvm.cpp#L57-L63

**Comment by JohanEngelen** [comment]
I think we found out that the issue only occurs for a 16-bit struct, which was a mismatch in extern(C) bindings.
For structs, Clang does not assume zero extension to 32bit: https://c.godbolt.org/z/fa3fEdMfj

All is good!

**Comment by eyal-horn-weka** [comment]
Thanks @JohanEngelen for the quick response!
