### ISSUE TITLE
Insufficient some asset hashes in sha256sums.txt

### ISSUE THREAD

**Issue by dragoon2014** [ldc-developers/ldc#3909]
ldc2-1.28.1.sha256sums.txt looks like forget to add following file hashes:

- ldc2-1.28.1-freebsd-x86_64.tar.xz
- ldc2-1.28.1-linux-aarch64.tar.xz

Could you add preceding file hashes (in next release)?

**Comment by kinke** [comment]
See https://github.com/ldc-developers/ldc/issues/3395 - the checksums are generated by Azure CI, which generates all artifacts except for the 2 mentioned above.

**Comment by dragoon2014** [comment]
Sure, are there no plan to add these hashes?

**Comment by kinke** [comment]
Nope, otherwise I'd have tackled it long ago.

**Comment by dragoon2014** [comment]
OK, thanks.

**Comment by kinke** [comment]
They should be included now, see https://github.com/ldc-developers/ldc/issues/3395#issuecomment-1126063870 for details (the FreeBSD artifact is generated & uploaded by Cirrus CI).
