### ISSUE TITLE
LDC 1.29.0-beta1: importC can’t find `__builtins.d`

### ISSUE THREAD

**Issue by drpriver** [ldc-developers/ldc#3939]
With the new LDC 1.29.0-beta1, trying to compile this trivial C program:

```c
void foo(void){
    __builtin_va_list v;
}
```

Fails with:
```
Error: cannot find input file `__builtins.d`
```

**Comment by kinke** [comment]
Thx for the report!

**Comment by drpriver** [comment]
The new  LDC 1.29.0 just released is missing these files for the osx-arm64 tar file. osx-x64 version seems to have them.

**Comment by kinke** [comment]
Argh yeah, all cross-compiled packages.
