### ISSUE TITLE
Enable all targets

### ISSUE THREAD

**Issue by jacob-carlborg** [ldc-developers/ldc#3941]
It would be great if LDC could enabled all targets that LLVM supports. LDC is missing the following targets that LLVM supports:

```
bpf     - BPF (host endian)
bpfeb   - BPF (big endian)
bpfel   - BPF (little endian)
hexagon - Hexagon
lanai   - Lanai
sparc   - Sparc
sparcel - Sparc LE
sparcv9 - Sparc V9
systemz - SystemZ
xcore   - XCore
```

**Comment by kinke** [comment]
Ah right, I forgot that (promise) with the latest LLVM 13 bump. I just wanted to check the ldc2 executable size increase first. The next LLVM 14 opportunity will probably come soon anyway, with upstream v14.0.0-rc2 being available for just over a week.

**Comment by kinke** [comment]
I've just checked the `ldc2` exe size on Linux with LLVM 14.0.0, a release build without assertions. It increases from 120 MB with the previously enabled targets to 131 MB with all targets, so by about 10% => I'll enable them all for our LLVM 14 builds.

**Comment by jacob-carlborg** [comment]
Thanks 👍.

**Comment by kinke** [comment]
Master uses LLVM 14 now, with all enabled targets (except for the Android builds with just `AArch64;ARM;WebAssembly;X86` - I guessed size might be an issue there).
