### ISSUE TITLE
Tail recursion does not work for struct on Windows

### ISSUE THREAD

**Issue by andy-hanson** [ldc-developers/ldc#3968]
```d
import core.stdc.stdio : printf;

extern(C) void main() {
	printf("Test f:\n");
	f(0, 0, 1_000_000);
	printf("Test g:\n");
	g(0, Range(0, 1_000_000));
}

void f(ulong acc, ulong cur, ulong end) {
	if (cur < end) {
		acc += cur;
		cur++;
		return f(acc, cur, end);
	} else
		printf("Result of f is %llu\n", acc);
}

struct Range {
	ulong cur;
	ulong end;
}

void g(ulong acc, Range range) {
	if (range.cur < range.end) {
		acc += range.cur;
		range.cur++;
		return g(acc, range);
	} else
		printf("Result of g is %llu\n", acc);
}
```

This code runs correctly on Linux and prints:
```
Test f:
Result of f is 499999500000
Test g:
Result of g is 499999500000
```

On Windows, it breaks after `Test g:`. Using a debugger I confirmed that it is failing due to too many copies of `g` on the stack.
In both cases, I'm testing with LDC2 version 1.29.0.

As far as I know, passing `Range` in to a function should be exactly the same as passing two `ulong`s separately.

Possibly related to https://github.com/ldc-developers/ldc/issues/960 .

**Comment by kinke** [comment]
> As far as I know, passing Range in to a function should be exactly the same as passing two ulongs separately.

Nope; ABI/calling convention details. E.g., on Win64, it's passed as a pointer to a caller-allocated struct, whereas it's passed in 2 registers for Posix x64.

Your example segfaults on run.dlang.io for Linux x64, with both LDC and DMD.

**Comment by andy-hanson** [comment]
Is there no way to specify that the struct must be passed by-value?
Also, the struct is modified, but that shouldn't affect the copy the caller has; doesn't that force it to pass by value?

**Comment by kinke** [comment]
> Is there no way to specify that the struct must be passed by-value?

These *are* the Win64 ABI by-value semantics for structs > 64 bit.

> Also, the struct is modified, but that shouldn't affect the copy the caller has; doesn't that force it to pass by value?

The caller has no *copy*, the callee mutates the caller's allocation directly. - This is none of LDC's business really, it's an LLVM optimizer thing if you expect this recursion to be handled. If clang handles it on Windows, be sure to let me know. :)

**Comment by kinke** [comment]
clang seems to behave identically: https://cpp.godbolt.org/z/9z85s8vfK

**Comment by kinke** [comment]
Let's close this then.
