### ISSUE TITLE
LDC crashing on compiling code in 32-bit mode

### ISSUE THREAD

**Issue by naydef** [ldc-developers/ldc#3990]
Add `-m32` or `--arch=x86`
```
struct Vector
{
    float x, y, z;
}

struct QAngle
{
    float x, y, z;

    QAngle opOpAssign(string op)(const(QAngle))
    {
        return this;
    }
}

void OnUserCmdPre()
{
    Vector ss;
    QAngle dd;
    dd -= cast(QAngle)ss;
}

void main() {}

```

Error message
```
#0 0x0000000005303243 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ndf/dlang/ldc-1.30.0-beta1/bin/ldc2+0x5303243)
/home/ndf/dlang/ldc-1.30.0-beta1/bin/ldc2 failed with exit code -11.
```
Tested with LDC 1.30.0 beta1 and with LDC-nightly and they both crash.

**Comment by kinke** [comment]
Thx for the report. - The issue is a general poor handling of type repaints, in this case an implicit `QAngle` to `const(QAngle)` repaint of the cast expression. We apparently don't expect structs to ever end up in `DtoPaintType()`.
