### ISSUE TITLE
document how to import from specific wasm modules

### ISSUE THREAD

**Issue by redthing1** [ldc-developers/ldc#3998]
when using LDC for wasm, how do you import a function from an arbitrary module name?

like say I wanted to import test.foo, a function foo from a module test

**Comment by JohanEngelen** [comment]
@skoppe  Can you help?

**Comment by redthing1** [comment]
LLVM has this, btw https://clang.llvm.org/docs/AttributeReference.html#import-module

wondering if we have something similar

**Comment by redthing1** [comment]
maybe it's possible with `llvmAttr`

**Comment by redthing1** [comment]
> Maybe this can help: https://github.com/skoppe/druntime/blob/bffaff347d5bc600599eefa3dbaaa982ae15442e/src/core/sys/wasi/core.d#L372

That's exactly what I wanted, much thanks. I can edit the wiki about this as well.
