### ISSUE TITLE
DustMite shipped with `ldc-latest-ci` corrupts files

### ISSUE THREAD

**Issue by CyberShadow** [ldc-developers/ldc#4134]
Not sure what exactly is the problem but I think LDC might be miscompiling DustMite.

Reproducer:
```
$ ~/dlang/install.sh install ldc-latest-ci
...

$ cat test.d
extern(C) int printf(const scope char*, ...);
 
void main()
{
    printf("This text should be shown!\n");
}

$ ~/dlang/ldc-69a54c94/bin/dustmite --no-redirect test.d 'cat test.d ; exit 1'
Loading test.d
None => ;

{
;
}
No
Hint: read https://github.com/CyberShadow/DustMite/wiki#initial-test-fails
object.Exception@DustMite/dustmite.d(367): Initial test fails: Test script "cat test.d ; exit 1" exited with exit code 1 (failure)
----------------
??:? [0x55a4b1a01406]
??:? [0x55a4b1a02a06]
??:? [0x55a4b1a01cdf]
??:? [0x55a4b18fe7bd]
??:? [0x55a4b1a011bb]
??:? [0x55a4b1a010b5]
??:? [0x55a4b1a00f0d]
??:? [0x55a4b1927591]
??:? [0x7f12e793f2cf]
??:? __libc_start_main [0x7f12e793f389]
??:? [0x55a4b18ea369]
```

So, DustMite reads in:

```d
extern(C) int printf(const scope char*, ...);
 
void main()
{
    printf("This text should be shown!\n");
}
```

but when it should write out the same file with no changes for the initial test, it instead writes:

```d
;

{
;
}
```

Seems to be a recent regression.
Downstream issue: https://github.com/dlang/dub/pull/2446#issuecomment-1242714549

**Comment by kinke** [comment]
Ouch, this seems *really* bad then. According to https://github.com/dlang/dub/pull/2445, this has shown up with b0eab59b1baf8d2618d47efaf39aa52082808a52, so I guess it was introduced by that or another earlier commit around that time.

**Comment by thewilsonator** [comment]
Eeeep, (probably) Mea culpa. Will try `git-bisect` tomorrow.

**Comment by thewilsonator** [comment]
Hmm, that was easier than I thought it was going to be. 
`git bisect` blames 37aca9c9405226d10bb0aeb082ffeb508da78b9e
