### ISSUE TITLE
FreeBSD produces "unknown symbols".

### ISSUE THREAD

**Issue by devosalain** [ldc-developers/ldc#4193]
Installing the binary and running dub with "gtkd" produces "unknown symbols error".
That looks much like a linker problem.

**Comment by thewilsonator** [comment]
More information please: 
which platform? which linker?
 what is the linker command used? 
where are the expected to be used libraries on the filesystem?

**Comment by thewilsonator** [comment]
What is the linker command issued by ldc? (you may need to run `dub` with `-v` to get the LDC command and then do the same thing with LDC to get the linker command)

**Comment by devosalain** [comment]
I had by accident configured a wrong compiler/linker in dub.json.
After removing that line everything seems to work fine.
"dub -v --force"  creates a correct gtkd application, so this issue can be closed.
