### ISSUE TITLE
LDC CLI bug when using -I=. (Windows)

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4241]
This error only happens on Powershell. The Command Prompt is okay. I have the same issue on DMD which I've just filed: https://issues.dlang.org/show_bug.cgi?id=23454

`Error: Expected argument to '-I'` is what I get when executing this command on Powershell.

**Comment by kinke** [comment]
Sounds like PowerShell is doing something funky. Is there a change when quoting the flag?

**Comment by MrcSnm** [comment]
Yes, quoting the argument actually solves that problem

**Comment by kinke** [comment]
This is definitely a PowerShell quirk and has nothing to do with the compilers:
```d
void main(string[] args)
{
    import std.stdio;
    writeln("args: ", args);
    readln();
}
```

![image](https://user-images.githubusercontent.com/1889215/200125080-3851e47f-ce9e-4ef9-8f63-8fc37bf48d4d.png)

It's also visible from the colors that the `.` is treated specially. `-I.` shouldn't be required btw.
