### ISSUE TITLE
does this work with llvm 14.0.6?

### ISSUE THREAD

**Issue by adcdam** [ldc-developers/ldc#4243]
just want to know that

**Comment by thewilsonator** [comment]
Yes, and with 15. The latest releases are with 14. 16 support is in progress.

**Comment by adcdam** [comment]
i did the wrong question what i mean is if version 1.30.0 work with llvm 14.0.0, i dont know if your answer is for the git version or for the latest release 1.30.0 version.

**Comment by adcdam** [comment]
Answering my own question yes it work, i was able to buidl tilix terminal.

**Comment by JohanEngelen** [comment]
> i did the wrong question what i mean is if version 1.30.0 work with llvm 14.0.0, i dont know if your answer is for the git version or for the latest release 1.30.0 version.

The release notes always have a Platform section where you can check the supported LLVM versions.
