### ISSUE TITLE
Where to get latest CI/CD artifacts (binaries or docker images)?

### ISSUE THREAD

**Issue by GavinRay97** [ldc-developers/ldc#4262]
Heya Martin,

I had a look through the Actions workflow output, as well as some of the other CI runner sites. I couldn't manage to find any downloadable, published artifacts from the CI runs anywhere, or URL's to them in the build logs.

Are there currently any artifacts that get produced from commits for folks that want to try out the current state of LDC prior to next release, or is it best to build from source?

Thank you =)

**Comment by JohanEngelen** [comment]
Yes, they are here: https://github.com/ldc-developers/ldc/releases/tag/CI

https://d.godbolt.org also has it. https://d.godbolt.org/z/vG5KxEW3z

**Comment by kinke** [comment]
FWIW, these CI builds are linked in the 2nd paragraph of https://github.com/ldc-developers/ldc#from-a-pre-built-package.

The artifacts can always be downloaded from a GH Actions workflow summary, for PRs too, e.g., https://github.com/ldc-developers/ldc/actions/runs/3463442863 (at the bottom).

**Comment by GavinRay97** [comment]
I saw that but it said that the last release was on Dec. 2018 so I thought they had gone unmaintained for some reason:

![image](https://user-images.githubusercontent.com/26604994/201763520-c87da773-7ee1-46a4-b94c-00800ebb7a10.png)

Maybe some weirdness with how GH does the date generation?

**Comment by kinke** [comment]
![image](https://user-images.githubusercontent.com/1889215/201790471-2a87c3bc-9d19-4da1-b568-80c900d91b44.png)

:)
