### ISSUE TITLE
Invalid asm constraints with asmtuple

### ISSUE THREAD

**Issue by zyedidia** [ldc-developers/ldc#4269]
I have the following code which uses some inline assembly to make an environment call that has multiple return values:

```d
struct SbiRet {
    ulong error;
    ulong value;
}

SbiRet ecall(int ext, int fid, ulong a0,
                      ulong a1, ulong a2,
                      ulong a3, ulong a4,
                      ulong a5) {
    SbiRet ret;

    import ldc.llvmasm;
    auto result = __asmtuple!(ulong, ulong) (
        "ecall",
        "={a0}, ={a1}, {a7}, {a6}, {a0}, {a1}, {a2}, {a3}, {a4}, {a5}",
        ext, fid, a0, a1, a2, a3, a4, a5
    );
    ret.error = result.v[0];
    ret.value = result.v[1];

    return ret;
}
```

It seems like according to the documentation and inline assembly examples, this should be valid but the compiler gives the error:

```
Error: inline asm constraints are invalid
```

with no additional information.

I compiled with `ldc2 -mtriple=riscv64-unknown-elf file.d -c`.

**Comment by thewilsonator** [comment]
LDC built with LLVM15+ will tell you what went wrong https://github.com/ldc-developers/ldc/blob/fc979b36c154d4a90acb815b611ddfc4455fc776/gen/naked.cpp#L506-L518 we don't currently have a GitHub release based on LLVM 15. 

You can either build your own LDC, or try translating the example to C++ and extract the error message from clang.

**Comment by zyedidia** [comment]
I discovered what the issue is: I had a space between `={a0}, ={a1}`. If I put `={a0},={a1}` then it works properly.

I'm not sure if that's intended or not.

**Comment by thewilsonator** [comment]
LLVM does the verification of the inline ASM, not LDC. I'd ask on the LLVM discourse/discord as there's not a lot we can do about that here.
