### ISSUE TITLE
`static` doesn't work correctly on Android + `srand`

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4277]
I don't understand correctly what is happening. I have a random number generator using C stdlib as a base. For returning a random number between min and max, that was my code: `(cast(float)rand() / (RAND_MAX+1)) * max + min;` This same code works on every other platform, on Android it was returning a negative number.

I think it is related on how `static` (read in case of a `static` property in a class) works on Android (doesn't). Currently for every static property I had, I just changed them to `__gshared`. 

My `srand` is initialized at app `Main`. Which is being executed on the GLThread in Android. That rand() code is returning a negative number and currently the solution seems to use std.random, a solution that I preferred not using as I prefer doing a code as simple as possible.

**Comment by JohanEngelen** [comment]
To avoid any ambiguity, can you post a full working code example? (and your LDC version)

**Comment by MrcSnm** [comment]
LDC 1.29.0

```d
class Random
{
    static void initialize()
    {
        srand(cast(uint)time(null));
    }
    static float rangef(float min, float max)
    {
        return (cast(float)rand() / (RAND_MAX+1)) * max + min;
    }
}
```

Trying to print this number, is printing a negative number. Initialize it where it makes sense in your codebase

**Comment by MrcSnm** [comment]
Seems like this was a problem with platform specific code as on Windows RAND_MAX has a different value (I think short.max and probably the code didn't errored out before because of integer promotion).
