### ISSUE TITLE
Functions without bodies are not getting DllImported

### ISSUE THREAD

**Issue by rikkimax** [ldc-developers/ldc#4280]
Windows 10, ldc 1.30-beta1

I'm trying to cut down compile times for my Unicode string builder, one thing I attempted was to create a .di file (di generator was absolutely useless for this, complete garbage output). That lead to functions without bodies, it wasn't until the end that I found that without the body it wasn't getting DllImported, here is a small example:

```d
module main;
import mylib;

void main() {
        import std.stdio;
        func;
        writeln("end");
}
```

```d
module mylib;

export:

version(Compiling) {
        void func() {
                import std.stdio;
                writeln("Hello!");
        }
} else {
        void func();
}
```

Adding ``{ assert(0); }`` body to func when not ``Compiling`` does make this work.

```
$ ldc2 -shared --d-version=Compiling mylib && ldc2 main.d mylib --fvisibility=public
   Creating library mylib.lib and object mylib.exp
   Creating library main.lib and object main.exp
main.obj : error LNK2019: unresolved external symbol _D5mylib4funcFZv referenced in function _Dmain
main.exe : fatal error LNK1120: 1 unresolved externals
Error: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\link.exe failed with status: 1120
```

**Comment by kinke** [comment]
`ldc2 -shared --d-version=Compiling mylib && ldc2 main.d mylib --fvisibility=public`

First of all, I had no idea `ldc2 mylib` actually works and compiles the `.d` file. But note that in the 2nd invocation, you have that `mylib` too, just like in the first command - so you're actually compiling and linking that module again, without `-d-version=Compiling`. So a proper `ldc2 -shared --d-version=Compiling mylib.d && ldc2 main.d mylib.lib --fvisibility=public` works as expected.

**Comment by rikkimax** [comment]
Hmm, so I failed to replicate my attempted di file failures, dangit.

**Comment by kinke** [comment]
.di doesn't really change anything. When splitting up your `mylib.d` into a .d and .di, this works too:
```
ldc2 -shared mylib.d && ren mylib.d mylib.bak && ldc2 main.d mylib.lib --fvisibility=public && ren mylib.bak mylib.d
```

Though the whole point of `-fvisibility=public` was to avoid the .di cumbersomeness / `version` stuff mimicking the dllexport/import macro ugliness required for C++, making everything work out of the box as on Posix targets.

**Comment by rikkimax** [comment]
Ideally yes, my concern is it's taking too long to compile.

I am happy for the shared library to take a long time, it just can't be slow to be used.

However, I figured out why it didn't work thanks to your prompting. Dub is being smart. It is placing importPaths before all arguments including your own packages imports. So the .di file is the only one actually being looked at for compilation... oops. No wonder symbols were missing!

Now I have a ton of missing symbols so that's an improvement? I think.
