### ISSUE TITLE
Globals are never marked as dso_local

### ISSUE THREAD

**Issue by zyedidia** [ldc-developers/ldc#4292]
It seems like it is not possible to force a global to be marked as `dso_local`. This means that LDC will generate accesses to globals through a global offset table, even in cases where it is not necessary. This hurts performance and uses extra space for the table. It seems like #3713 tried to address this, but was closed because of concerns about shared objects. My use-case is bare-metal, so I can guarantee that it will be impossible for the symbol to be overridden at runtime. It would be nice if this optimization (marking globals as dso_local) could be enabled using a flag or maybe via a relocation model.

The current behavior isn't a huge problem but it would be nice to avoid using a GOT if possible. Thanks!

**Comment by JohanEngelen** [comment]
Have you already tried this?
```d
import ldc.attributes;
@llvmAttr("dso_local") int your_variable;
```

**Comment by zyedidia** [comment]
That doesn't seem to change anything, I think because `@llvmAttr` applies only to functions.

**Comment by kinke** [comment]
Is `@hidden` (from `ldc.attributes`) enough? Alternatively, `-fvisibility=hidden` to make everything hidden by default (and `export` D visibility for explicit exports then).

**Comment by zyedidia** [comment]
Using `-fvisibility=hidden` reduces the size of the table but does not eliminate it. It seems to remove normal globals from the table, but globals provided by the linker (defined in D as `extern (C) extern __gshared foo` for example) are still looked up in the GOT. I did notice that using full LTO (not thin) caused the GOT to be removed though.

**Comment by kinke** [comment]
Yes, `-fvisibility=hidden` only affects *definitions*. So external globals still need an explicit `@hidden`.

**Comment by zyedidia** [comment]
Alright thanks!
