### ISSUE TITLE
RISC-V target triple isn't recognized properly

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#4316]
```bash
ldc2 --mtriple=rv32imc-unknown-none-ilp32 -of=freertos.d.o -c freertos.d
Error: unable to get target for 'rv32imc-unknown-none-ilp32', see -version and -mtriple.
```
If I add `--march=riscv32` to CLI ldc2 compiles code properly.

Actually, in word `rv32imc` (or `riscv32imc`) RISC-V 32 architecture is already encoded.

(For ARM such triple format work well. For example: `--mtriple=thumbv7em-unknown-none-eabi`)

**Comment by JohanEngelen** [comment]
Clang also does not recognize `rv32imc-unknown-none-ilp32` as triple , but it does recognize `riscv32-unknown-none-ilp32` and LDC does too.
Do you have a reference of how a C/C++ compiler is to recognize your triple/arch ?

**Comment by denizzzka** [comment]
You're right! Here I thought by analogy with ARM, with all its "thumb" with/without floats, etc...
For RISC-V Is just a different approach here.

**Comment by denizzzka** [comment]
Working sample for future searchers to avoid time wasting:
```
$ ldc2 --mtriple=riscv32-unknown-none-ilp32 --mattr=+m,+c [other options]

$ clang -target riscv32-unknown-none-ilp32 -march=rv32imc [other options]
```
