### ISSUE TITLE
No options to control the RISC-V ABI

### ISSUE THREAD

**Issue by zyedidia** [ldc-developers/ldc#4321]
The latest release of LDC changed the default ABI of RISCV64 to `lp64d` (default used to be `lp64`). Unfortunately this value is not currently configurable via a command-line flag (with GCC one would use `-mabi=lp64`). I would like to continue using `lp64` (because I am not using float/double support), but can't do so with the latest release of LDC. It would be great to have a new option (`-mabi`) to let the user configure the ABI.

Alternatively, the RISCV ABI could be set to `lp64` by default, and automatically change to `lp64d` if the `+d` attribute is passed in.

**Comment by kinke** [comment]
There's an existing `-mabi` already - but unfortunately it's ignored for RISC-V: https://github.com/ldc-developers/ldc/blob/95ac5cadb89e2fde1d9501f3aac2dc8a077c5278/driver/targetmachine.cpp#L63-L95 (*and* not used for the cc linking cmdline...)

**Comment by zyedidia** [comment]
Ah alright, so fixing this should just be a matter of making that option not ignored for RISC-V? Also it doesn't seem like that option shows up in `ldc2 --help`, which is why I didn't realize it exists.

**Comment by kinke** [comment]
Yep, for setting up LLVM codegen. And for avoiding/changing the cc linker flag, that `getABI()` function should probably be exported (not a 'hidden' `static` in .cpp).

Use `-help-hidden` for (almost) all options [mentioned in https://wiki.dlang.org/Using_LDC].
