### ISSUE TITLE
All gccbuiltins_xxxx.di files are empty in 1.32

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#4347]
Is this intentional? This is probably a good idea, but this is very much breaking to do it all at once for everyone.
EDIT: I means it probably breaks mir-ion and Dcompute

![image](https://user-images.githubusercontent.com/1067485/225123560-f92960c4-6083-44f6-ae88-0d4c49da08cc.png)

**Comment by JohanEngelen** [comment]
LLVM15 renamed GCCBuiltin to ClangBuiltin: https://github.com/llvm/llvm-project/commit/d0a4450ecdaf124f9d422dbcba8cbdbeb50c836a

**Comment by JohanEngelen** [comment]
Thanks for reporting, I made a fix for it. It's unfortunate, but we'll have to release a .1 version.

**Comment by p0nce** [comment]
Thanks! Nothing urgent :)

**Comment by kinke** [comment]
Argh yeah too bad this wasn't caught in the 2-weeks beta period.

**Comment by p0nce** [comment]
Sorry I was a bit busy but indeed I could be a bit more attentive.

**Comment by kinke** [comment]
[I meant in general, not directed at you personally.]
