### ISSUE TITLE
ImportC: Error: C preprocessor directive `#include` is not supported

### ISSUE THREAD

**Issue by katyukha** [ldc-developers/ldc#4359]
Hi,

Are there any plans to support `#include` directives in imported C files?
DMD already supports this feature.
For example, it could allow to easily use libgit2 or other C libs.

Thanks

**Comment by katyukha** [comment]
Hi,

Thank you for information.

**Comment by Temtaime** [comment]
Hello. Why are you trying to reinvent the wheel?
Just use code from dmd that calls the preprocessor.

**Comment by kinke** [comment]
Implemented in #4417.
