### ISSUE TITLE
Error: module logger is in file 'std/logger.d' which cannot be read

### ISSUE THREAD

**Issue by vnayar** [ldc-developers/ldc#4414]
Input File:
```d
// dummy.d
import std.logger : info;
void main() { }
```

Executed Command:
```sh
$ ldc2 dummy.d
dummy.d(1): Error: module logger is in file 'std/logger.d' which cannot be read
import path[0] = /snap/ldc2/170/bin/../import
```

Observed Behavior: The compiler claims that the file std/logger.d cannot be read, which is part of the standard D library described here: https://dlang.org/phobos/std_logger.html

Expected Behavior: The same file compiles without error using `dmd`  v2.101.2, which is the expected behavior.

Compiler information:  The bug has been observed in both LDC 1.24 and 1.30.

LDC - the LLVM D compiler (1.24.0):
  based on DMD v2.094.1 and LLVM 11.0.0
  built with LDC - the LLVM D compiler (1.24.0)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge
  http://dlang.org - http://wiki.dlang.org/LDC

**Comment by kinke** [comment]
`std.logger` is available since Phobos v2.101 (https://dlang.org/changelog/2.101.0.html#logger), not earlier, so starting with LDC v1.31.

> https://dlang.org/phobos/std_logger.html

Note that there's a version-dropdown on the top-right (=> 404 for v2.094).
