### ISSUE TITLE
Build against LLVM that enables SPIRV for releases

### ISSUE THREAD

**Issue by thewilsonator** [ldc-developers/ldc#4416]
now that SPIRV is a proper target for LLVM we should enable it for the LLVM we build against for releases. 
LCD 1.32.1 does not have SPIRV as a target and _also_ does not build against the library precursor of the target meaning that DCompute OpenCL does not work out of the box.

**Comment by kinke** [comment]
If it is a proper target (since which version?), it should already be enabled in our llvm-project fork, as we build with `-DLLVM_TARGETS_TO_BUILD=all` for a while.

> and also does not build against the library precursor of the target

Nothing has changed in that regard for a while either, so our LLVM build includes the SPIR-V submodule and libs.

**Comment by thewilsonator** [comment]
Ah, it might have been an experimental target now that I think about it

**Comment by kinke** [comment]
With LLVM v16 (and latest SPIRV-LLVM-Translator for v16) I see this in the CMake output (https://github.com/ldc-developers/llvm-project/actions/runs/5458959614/jobs/9934516420):
```
-- SPIR-V Headers location is not specified. Will try to download
          spirv.hpp from https://github.com/KhronosGroup/SPIRV-Headers into
          /home/runner/work/llvm-project/build/projects/SPIRV-LLVM-Translator/SPIRV-Headers
-- Building SPIRV-Header examples
-- Installing SPIRV-Header
-- Checking for one of the modules 'SPIRV-Tools'
CMake Warning at projects/SPIRV-LLVM-Translator/CMakeLists.txt:119 (find_package):
  By not providing "FindSPIRV-Tools.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "SPIRV-Tools", but CMake did not find one.
  Could not find a package configuration file provided by "SPIRV-Tools" with
  any of the following names:
    SPIRV-ToolsConfig.cmake
    spirv-tools-config.cmake
  Add the installation prefix of "SPIRV-Tools" to CMAKE_PREFIX_PATH or set
  "SPIRV-Tools_DIR" to a directory containing one of the above files.  If
  "SPIRV-Tools" provides a separate development package or SDK, be sure it
  has been installed.
CMake Warning at projects/SPIRV-LLVM-Translator/CMakeLists.txt:120 (find_package):
-- SPIRV-Tools not found; project will be built without --spirv-tools-dis support.
  By not providing "FindSPIRV-Tools-tools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "SPIRV-Tools-tools", but CMake did not find one.
  Could not find a package configuration file provided by "SPIRV-Tools-tools"
  with any of the following names:
    SPIRV-Tools-toolsConfig.cmake
    spirv-tools-tools-config.cmake
  Add the installation prefix of "SPIRV-Tools-tools" to CMAKE_PREFIX_PATH or
  set "SPIRV-Tools-tools_DIR" to a directory containing one of the above
  files.  If "SPIRV-Tools-tools" provides a separate development package or
  SDK, be sure it has been installed.
  ```
  
  Related: https://github.com/KhronosGroup/SPIRV-LLVM-Translator#build-with-spirv-tools

**Comment by kinke** [comment]
Oh, I now see a `llvm/lib/Target/SPIRV` directory since LLVM 15. But it's apparently still an experimental target in v16 (while e.g. LoongArch was promoted to a stable target in v16): https://github.com/llvm/llvm-project/blob/release/16.x/llvm/CMakeLists.txt#L426-L446

**Comment by kinke** [comment]
Oh looks like it's experimental for a reason - SPIRV fails to compile on Windows, using clang v16.0.0 - pretty embarrassing: https://github.com/ldc-developers/llvm-project/actions/runs/5461460185

**Comment by kinke** [comment]
The experimental target is enabled in newly used LDC-LLVM v16.0.6.
