### ISSUE TITLE
LDC only compiles with /LARGEADDRESSAWARE:NO on Win64

### ISSUE THREAD

**Issue by dymk** [ldc-developers/ldc#442]
This makes it impossible to use of 2gb of memory, which is very unfortunate given one of the main reasons for compiling 64 bit is to be able to use more than the 32 bit address space. 

I've tried passing the flag -L"/LARGEADDRESSAWARE" and -L"-LARGEADDRESSAWARE", however LDC turns the first into a file to link with, and the second into a /LIBPATH argument, so I've had no luck overriding by passing in an additional flag. 

Is there a way to get around this limitation?

**Comment by JohanEngelen** [comment]
Reopening this issue.
LDC needs `-L"/LARGEADDRESSAWARE"` for debug `-g` builds.
See LLVM bug: https://llvm.org/bugs/show_bug.cgi?id=15393

**Comment by kinke** [comment]
Finally obsolete due to CodeView debug infos and fixed by #1880.
