### ISSUE TITLE
ldc2-1.33.0-beta1: cross-compile linux -> windows fails to link

### ISSUE THREAD

**Issue by quickfur** [ldc-developers/ldc#4424]
Setup:
- Host is Linux x86-64 system.
- Unpack ldc2-1.33.0-beta1-linux-x86_64.tar.xz to `/usr/src/d/ldc/ldc2-1.33.0-beta1-linux-x86_64/`
- Unpack ldc2-1.33.0-beta1-windows-x64.7z to `/usr/src/d/ldc/ldc2-1.33.0-beta1-windows-x86/`
- Edit `/usr/src/d/ldc/ldc2-1.33.0-beta1-linux-x86_64/etc/ldc2.conf` and add the following stanza:

````
"(i686|x86_64)-.*-windows.msvc":
{
    switches = [
        "-defaultlib=phobos2-ldc,druntime-ldc",
        "-link-defaultlib-shared=false",
    ];
    lib-dirs = [
        "/usr/src/d/ldc/ldc2-1.33.0-beta1-windows-x64/lib",
    ];
};
````

Create test source code:
````
import std;
void main() {
	foreach (line; stdin.byLine) {
		writeln(line);
	}
}
````

Compile with this command:
````
/usr/src/d/ldc/ldc2-1.33.0-beta1-linux-x86_64/bin/ldc2 -L/subsystem:windows -L/entry:wmainCRTStartup -mtriple=x86_64-windows-msvc -of=/tmp/test.exe /tmp/test.d
````

Compiler output:
````
lld-link: error: undefined symbol: _D3std5stdio10readlnImplFNfPOS4core4stdcQBi6_iobufKAawEQCbQCa4File11OrientationZm
>>> referenced by /tmp/test.obj:(_D3std5stdio4File__T6readlnTaZQkMFNfKAawZm)
Error: linking with LLD failed
````

Expected output: compile and link should not fail.

**Comment by kinke** [comment]
Yeah, this regressing doesn't sound very likely. Due to the different lib dirs for Win x86 and x64 (with identical file names in there), a common ldc2.conf section `(i686|x86_64)-.*-windows.msvc` won't work either.

**Comment by quickfur** [comment]
You're right, I must have messed up my paths.  Deleted the current installation and tested again with 1.33.0-beta2, now everything works as expected.  Sorry for wasting your time.
