### ISSUE TITLE
Assert Failure/Out of bounds error inside DLL on Windows doesn't throw stack traces and shows no message

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4426]
Tested with 1.33.0-beta1

Since I have been developing mostly inside a DLL, it gets very frustrating since all it does is halting.
Those errors can only be checked when inside a debugger. Would be nice to get the default behavior which is throwing a stack trace together with exiting the program.

**Comment by MrcSnm** [comment]
Also, it shows no message assertion message. Basically all of those are produces the errors but doesn't does anything besides halting:

Visual Studio debugger shows "Unhandled exception at 0x00007FFEB104CD29 in hipreme_engine.exe: Microsoft C++ exception: core.exception.AssertError "
```d
assert(false);
assert(false, "Some error occurred");
int[] arr;
arr[10] = 500;
arr[0..10] = 50;
```

**Comment by MrcSnm** [comment]
Oh yea, I'm using `mixin SimpleDLLMain` for the DLL entry point.

**Comment by MrcSnm** [comment]
Update 1: The error is catchable. But toString can't be called on them too

**Comment by kinke** [comment]
> Oh yea, I'm using mixin SimpleDLLMain for the DLL entry point.

Shouldn't be required when linking both DLL and the .exe against shared druntime/Phobos via `-link-defaultlib-shared`. I guess that's missing for your .exe.

**Comment by kinke** [comment]
Yep, `-link-defaultlib-shared` makes this work:

`dlldummy.d`:
```D
export void myDllDummy(int[] a) {
    a[5] = 123;
}
```

`app.d`:
```D
import dlldummy;

void main() {
    int[5] a;
    myDllDummy(a);
}
```

```
> ldc2 -shared dlldummy.d
> ldc2 app.d dlldummy.lib -link-defaultlib-shared
> app.exe

core.exception.ArrayIndexError@dlldummy.d(2): index [5] is out of bounds for array of length 5
----------------
0x00007FF8B2562F02 in onArrayIndexError
0x00007FF8B2563525 in d_arraybounds_index
0x00007FF8CE69105D in void dlldummy.myDllDummy(int[])
0x00007FF7531D1026
0x00007FF8B2590184 in void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll()
0x00007FF8B258FCB0 in d_run_main2
0x00007FF8B258FFE4 in d_wrun_main
0x00007FF7531D1054
0x00007FF7531D1930
0x00007FF8E44C7034 in BaseThreadInitThunk
0x00007FF8E4A3CEC1 in RtlUserThreadStart
```

**Comment by MrcSnm** [comment]
Humm I was able to also reproduce this functionality by using `Runtime.loadLibrary`.
Though when I test with my project (and dub), I get a lot of linker errors.
I remember Adam saying that the problem was the usage of a DFLAG which changes any kind of global state (such as boundscheck or even this one).

So, you said "it should not be required". Then the only way to actually share the druntime is with `-link-defaultlib-shared`?

**Comment by kinke** [comment]
For a dub .exe with static-lib dependencies, see https://github.com/dlang/dub/pull/2660 - you'll currently need to set `DFLAGS=-link-defaultlib-shared` for the dub invocation building the .exe.

> Then the only way to actually share the druntime is with -link-defaultlib-shared?

Yes, for Posix too.

**Comment by MrcSnm** [comment]
Updated the wiki here: https://wiki.dlang.org/Win32_DLLs_in_D#Shared_D_Runtime.28LDC.29
Thanks for the help

**Comment by JohanEngelen** [comment]
> Updated the wiki here: https://wiki.dlang.org/Win32_DLLs_in_D#Shared_D_Runtime.28LDC.29 Thanks for the help

thank _you_ for updating the wiki!
