### ISSUE TITLE
No way to specify seperate LINK64 and LINK executables on Windows

### ISSUE THREAD

**Issue by dymk** [ldc-developers/ldc#443]
On Windows, it's difficult to compile 64 and 32 bit programs back to back, because LDC assumes that the first link.exe it finds on the path is the correct linker to use. Can a configuration option in etc/ldc2.conf be added to specify what linker executable should be used for 32 and 64 bit binaries separately?

**Comment by kinke** [comment]
I'm closing this as the `ldc2.conf` now supports different triples (for the differing lib directories) and auto-detects Visual Studio and sets up the required x86/x64 environment. See the [downloadable multilib CI build](https://github.com/ldc-developers/ldc/releases/tag/LDC-Win64-master).
