### ISSUE TITLE
Function pointers don't work on Harvard architechture

### ISSUE THREAD

**Issue by dukc** [ldc-developers/ldc#4432]
Compile this with flags `-betterC -mtriple=avr  -mcpu=atmega328p --gcc=avr-gcc --Xcc=-mmcu=atmega328p`

```D
void function() fPtr;

extern(C) void main()
{   fPtr = {fPtr = null;};
}
```

Results in (stack trace omitted): 
```
Invalid bitcast
void ()* bitcast (void () addrspace(1)* @_D5delay4mainUZ9__lambda1FNbNiNfZv to void ()*)
in function main
LLVM ERROR: Broken function found, compilation aborted!
```

Tested version 1.30.0.

**Comment by kinke** [comment]
FWIW, the current problem is that the frontend has this lower bound, but in various codegen sites, we expect `size_t` to match the pointer size, based on: https://github.com/ldc-developers/ldc/blob/cf32bac668540f3dd022493b3ba89b598a485dfb/gen/tollvm.cpp#L334-L349
