### ISSUE TITLE
Undefined symbols initZ by TypeInfo but is available

### ISSUE THREAD

**Issue by rikkimax** [ldc-developers/ldc#4434]
Okay this is a fun little bug.

-betterC DLL, two structs, a RC'ing wrapper, around another struct (Logger).

The initZ symbol for Logger is definitely exported, (manually exported, duplicate symbol warning).

In full D executable, put RC wrapper type into a global variable, ok. Put into a struct, error.

```
lld-link: error: undefined symbol: initializer for sidero.base.logger.Logger
>>> referenced by .dub\build\executable-debug-windows-x86_64-ldc_v1.31.0-C3959C8DE81CAB38D564CEFC81022C0AF08DE70E42F03C8CED11A8196C452F57\sidero_eventloop.obj:(initializer for TypeInfo_S6sidero4base6logger6Logger)
```

I confirmed with MSVC link, it's the initZ symbol for Logger that is missing.

**Comment by kinke** [comment]
The compiler needs to know which D modules are or might be in different binaries to make Windows DLLs work, so if the admittedly blunt `-fvisibility=public` + `-dllimport=all` combo doesn't handle the vast majority of these use cases, we'd probably need some new compiler switch to specify root packages to be dllimported, yes.

**Comment by rikkimax** [comment]
I want to get us off of the override switches. As they are overrides, and should be last resort once we are at 100% support.

I'll update the bug report for the switch, would you like to inform Walter that we now have a compelling case for the switch? I'm sure he'll be absolutely giddy.

**Comment by kinke** [comment]
I'm still not convinced we need that extra complexity. Coupled with the Windows 64k exported-symbols limit, I still think that we should focus on 2 cases:
* few large DLLs with few manual exports, not compiled with `-fvisibility=public` and with a clear plugin-like DLL interface for manual loading.
* *every* dub dependency being compiled with `-fvisibility=public -dllimport=all`, so lots of small DLLs all depending on each other, similar to a Linux distro.

**Comment by rikkimax** [comment]
I do all my exports manually for dmd, the public visibility override just means I don't have a linker script to make generated symbols exported.

However in this case, the problem wasn't the DLL itself, it was the executable that depended on it, not being compiled with dllimport switch, which is what my proposed switch would resolve.

**Comment by kinke** [comment]
My point is that your example doesn't seem to suffer from existing, simple and working `-dllimport=all`. Its drawback is that it implies that *static*-lib-deps linked into the same binary (exe or DLL) need to be compiled with `-fvisibility=public`, and its symbols might get dllimported locally (with according linker warning). So the 64k symbol limits is reached pretty quickly, hence this mode makes especially sense when every project is in its own DLL anyway, no static libs. So your proposed switch would only accomodate for more complex hybrid shared/static lib dependencies.

**Comment by rikkimax** [comment]
Yes but it does have drawbacks:

1. All users of my stuff now need to add the flag manually
2. Linker warnings as you mentioned, however, this just makes us look incompetent (not good)
3. It is incredibly easy to trigger

As for the 64k limit, you really have to work hard to get to that sort of number. For 110k LOC, I've reached something like 9k of exports. Even with the big projects, you really have to make them big and do some crazy stuff like export template instances to get to the point where it is a worry.

Also I'm not using static libraries, because dub not supporting ``objectFile`` target type (which I'm waiting for you to respond to the bug report before starting work on). It's all DLL or executable, that's it.

Right now, there just isn't a pathway off the override switches. You are stuck using them even in end-user builds.

**Comment by rikkimax** [comment]
My concern here is that it is one thing to affect library code, its another to affect user code. I have very strong opinions about the latter ;)

Anyway, thanks for the help.
