### ISSUE TITLE
stdio doesn't compile for riscv

### ISSUE THREAD

**Issue by anon17** [ldc-developers/ldc#4436]
[Complains](https://forum.dlang.org/post/zpfoilqdlkfhimmavcta@forum.dlang.org) about `pragma(printf)`. I guess `pragma(printf)` is platform dependent and not implemented for riscv?

**Comment by anon17** [comment]
```
Error: function `core.stdc.stdio.vfprintf` `pragma(printf)` functions must be `extern(C) int vfprintf([parameters...], const(char)*, va_list)`
```

**Comment by JohanEngelen** [comment]
With target-specific bug reports, it helps if you specify the exact triple that you are using (or better, the full commandline)

**Comment by kinke** [comment]
I guess this is 32-bit RISC-V specific and related to the `va_list` alias: https://github.com/ldc-developers/ldc/blob/d4f2bed3a45688b32434d429e39c22dea5a9ffda/runtime/druntime/src/core/stdc/stdarg.d#L134-L139

but we only have a 64-bit RISC-V ABI implementation in `gen/abi/riscv64.cpp` using that `void*` type.

**Comment by anon17** [comment]
I guess it worked for risc64.
