### ISSUE TITLE
no property `emptyObject` for type `std.json.JSONValue`

### ISSUE THREAD

**Issue by Ryhon0** [ldc-developers/ldc#4438]
It seems like LDC's phobos does not include `JSONValue.emptyObject`. I've been using DMD to develop my app and it's been compiling fine but when I wanted to compile a release build with LDC, I got the following error:
```
Error: no property `emptyObject` for type `std.json.JSONValue`
```
LDC version:
```
LDC - the LLVM D compiler (1.32.2):
  based on DMD v2.102.2 and LLVM 15.0.7
  built with LDC - the LLVM D compiler (1.32.2)
```
DMD version:
```
DMD64 D Compiler v2.104.0
```

**Comment by kinke** [comment]
Yep, this was added in Phobos v2.104, so you'll have to wait for LDC v1.34, or stick to an older Phobos API.
