### ISSUE TITLE
What makes ldc detects the MSVC linker to use it instead of lld

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4441]
I wanted to know where and when that happens. There doesn't seem to be any relevant stuff on the ldc.conf file, I found out only some 
flags being added to the msvc linker when using it, but nothing about detection.

The only thing I know is that it detects if the windows sdk was installed before ldc. But that is not enough for me in the case someone had ldc but not windows sdk.

I'm trying to completely automate this stuff since my program is not compatible with lld on windows.

**Comment by kinke** [comment]
MSVC++ (2015 and above) detection usually happens just before invoking the linker, as it might involve setting some environment variables for the linker. It's triggered from [here](https://github.com/ldc-developers/ldc/blob/d4f2bed3a45688b32434d429e39c22dea5a9ffda/driver/linker-msvc.cpp#L97); detection is based on https://github.com/ldc-developers/ldc/blob/d4f2bed3a45688b32434d429e39c22dea5a9ffda/driver/tool.cpp#L265-L412 and https://github.com/ldc-developers/ldc/blob/d4f2bed3a45688b32434d429e39c22dea5a9ffda/dmd/vsoptions.d.

With an existing MSVC++ installation, you can use `-link-internally -mscrtlib=vcruntime140` to simulate the behavior for users without an MSVC installation, i.e., defaulting to integrated LLD and the bundled MinGW-based libs.

Out of interest, are you sure it's LLD that doesn't work for your program (i.e., `-link-internally`)? I've been using it for a while on Windows, as drop-in replacement for the MS linker, and haven't noticed any issues so far - but much better error messages and somewhat faster.

**Comment by MrcSnm** [comment]
Yes, it doesn't work because of the issue I had with the ms linker flag `/WHOLEARCHIVE`, also, I didn`t had a way to identify the currently used linker.
I remember I got errors with LLD before in my program related to calling `writeln`, something like crashing on a thread lock on this function, which made me use `println`  instead.

I believe that since I'm using shared library, it puts me in a pretty bad spot for most of the time when not using mslinker.

**Comment by MrcSnm** [comment]
I just found out that:

![image](https://github.com/ldc-developers/ldc/assets/10136262/dc0d0974-8748-4c26-adb2-a631df384a1e)

Basically I have both VS2019INSTALLDIR and 2022, but no VSINSTALLDIR, do you think maybe those should be checked as well?

**Comment by kinke** [comment]
The default lookup via COM (for both DMD and LDC), IIRC similar to how `vswhere.exe` (https://github.com/microsoft/vswhere) works, should return the latest VS installation with the Visual C++ components installed. See DMD's `dmd.vsoptions` module linked earlier.

**Comment by MrcSnm** [comment]
I'll close that and also updated the LDC wiki to include that information here. Thanks for helping!
