### ISSUE TITLE
The app binary does not have proper segment alignment

### ISSUE THREAD

**Issue by calvin2021y** [ldc-developers/ldc#4447]
I build a ios app run fine for development test, then upload to app store for distribute they give this warning.

What flags I can use with ldc2 to make sure  segment alignment is meet the ios store requirement?

**Comment by JohanEngelen** [comment]
We need some more detail.
What compiler version did you use? What are the compile flags? Can you copy-paste the exact error (and surrounding error log context if any) ?

**Comment by calvin2021y** [comment]
I use ldc 1.33.0-beta2.  There is no error for development test on ios device. just warning when you submit app for ios store.

I guess this is because I use fat binary format, after submit without fat binary it seems no error any more.
