### ISSUE TITLE
Impossible to build libdexed-d.dll since v1.31

### ISSUE THREAD

**Issue by SixthDot** [ldc-developers/ldc#4453]
Most recent LDC2 versions fail to build on windows while this worked for years.

Here is how to reproduce

```bash
git clone https://gitlab.com/basile.b/dexed
cd dexed
git submodule update --init
cd dexed-d
dub build --compiler=ldc2
```

To get a huge amount of [lld-link error messages](https://ci.appveyor.com/project/BBasile/dexed/builds/46360105#L300).

As noted in the [project-specific issue](https://gitlab.com/basile.b/dexed/-/issues/116) Apparently the problem started from v1.31.0

I dont say this is a bug in the toolchain... but at least that this is a breaking change that I cant handle, so any help would be welcome

**Comment by kinke** [comment]
This is caused by a dub v1.30 change. See https://github.com/dlang/dub/pull/2660#issuecomment-1589354210 for some context; you'd currently need to build the DLL with env var `DFLAGS=-fvisibility=hidden -dllimport=none` (`none` because you have `-link-defaultlib-shared=false`).

**Comment by SixthDot** [comment]
thanks, that has helped.
