### ISSUE TITLE
Question: Release binary for Linux aarch64

### ISSUE THREAD

**Issue by tom-tan** [ldc-developers/ldc#4456]
Until LDC 1.32.1, a release binary for Linux aarch64 is provided in the [release page](https://github.com/ldc-developers/ldc/releases/tag/v1.32.1).
On the other hand, it is not provided in LDC 1.33.0.

Is it just delayed or is it officially dropped from the release binaries?
If it is dropped, it would be nice if it is described in the release note.

**Comment by kinke** [comment]
I mentioned this in the announcement on https://forum.dlang.org/thread/clelngkqvihzybpxgldq@forum.dlang.org. The problem is our CI provider; I hope they fix their problem, so that the artifact can be added at a later time.
