### ISSUE TITLE
pragma(lib) doesn't work with static libraries

### ISSUE THREAD

**Issue by ryuukk** [ldc-developers/ldc#4459]
Let's take this example

- app.d

```d
import std.stdio;

pragma(lib, "lib.a");

extern(C) int lib_get_int(); 

void main() {
    writeln(lib_get_int());
}
```

- lib.d

```d
module lib;

export extern(C) int lib_get_int() {
    return 42;
}

```

1. build the static lib: ``ldmd2  -betterC -lib lib.d``
2. build the program: ``ldmd2  -betterC -run app.d``

# Expected:

It should build, link, run and print: ``42``

# What happen instead?:

It doesn't compile:

```
$ ldmd2 -run app.d
/usr/bin/ld: cannot find -llib.a: No such file or directory
collect2: error: ld returned 1 exit status
```

With DMD it all works as expected

System:

OS: Linux x64
LDC: 

```
LDC - the LLVM D compiler (1.32.2):
  based on DMD v2.102.2 and LLVM 15.0.7
  built with LDC - the LLVM D compiler (1.32.1)
  Default target: x86_64-pc-linux-gnu
  Host CPU: skylake
  http://dlang.org - http://wiki.dlang.org/LDC
```

I suspect the reason is it puts the ``-l`` on the ``.a`` file, it should just pass the path without the ``-l``

**Comment by kinke** [comment]
> I suspect the reason is it puts the `-l` on the `.a` file, it should just pass the path without the `-l`

That's the reason, yes; DMD apparently special-cases. - Fun fact: it works when compiling + linking separately with the lld linker:
```bash
$ ldmd2 -betterC lib.d
$ ldmd2 -c app.d
$ ldmd2 app.o
$ ./app
42
```
This means that embedding `lib.a` in the object file (`app.o`) already works (see #3259 for that feature).

**Comment by kinke** [comment]
Yep, on Linux only supported by lld AFAIK (since v9).
