### ISSUE TITLE
macOS release package does not export all D symbols thus plugins do not work

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#4462]
This is probably related to cross building the package.

I'm testing now by applying `--export-dynamic` to any linker that supports it (so not only on UNIX but for all platforms).

**Comment by JohanEngelen** [comment]
`--export-dynamic` is not supported by the linker that we use for macos arm64 cross build

**Comment by JohanEngelen** [comment]
I think I remember seeing an attempt to use native M1 (arm64) github CI system (using "runs-on: ..."), or was that not tested yet?

**Comment by kinke** [comment]
> I think I remember seeing an attempt to use native M1 (arm64) github CI system (using "runs-on: ..."), or was that not tested yet?

The `macOS arm64` Cirrus CI jobs are native jobs. GitHub Actions have no native AArch64 runners at all, neither Linux nor Mac.

**Comment by JohanEngelen** [comment]
Brute force linking with `-Wl,-exported_symbol;-Wl,'__*'` does work, but gives a ton of warnings like:
`ld: warning: cannot export hidden symbol llvm::ms_demangle::StructorIdentifierNode::~StructorIdentifierNode() from /Users/johan/llvm/install14/lib/libLLVMDemangle.a(MicrosoftDemangleNodes.cpp.o)
`

**Comment by kinke** [comment]
I don't think it's related to cross-building it on an x64 macOS box; especially for the D parts, which basically just get an extra `-mtriple=arm64-apple-macos`. I'd rather check whether `-flto=full` changes the behavior (we also use PGO using an x64 profile, but I don't think that plays a role).

**Comment by kinke** [comment]
Or maybe check `LDC_LINK_MANUALLY=OFF` - it's used by most CI jobs incl. the GHA macOS arm64 cross-build job, meaning that the D host compiler (`ldmd2`) is used for linking, not the CMake C++ compiler. I set DFLAGS for the GHA cross-builds: `DFLAGS=-mtriple=arm64-apple-macos -L-L/Users/runner/work/ldc/build-cross-libs/lib -Xcc=-target -Xcc=arm64-apple-macos -Xcc=-isysroot -Xcc=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`, to set it up for cross-linking.

**Comment by kinke** [comment]
Well, the native Cirrus jobs are using `LDC_LINK_MANUALLY=OFF` too. They use macOS 12 though with a more recent Xcode, maybe that plays a role as well.

**Comment by JohanEngelen** [comment]
> I don't think it's related to cross-building it on an x64 macOS box; especially for the D parts, which basically just get an extra `-mtriple=arm64-apple-macos`. I'd rather check whether `-flto=full` changes the behavior (we also use PGO using an x64 profile, but I don't think that plays a role).

You are right. Building with `-flto=full` on my local machine indeed reproduces the issue.
