### ISSUE TITLE
issue while building android project unity

### ISSUE THREAD

**Issue by tayyabb741** [ldc-developers/ldc#4464]
my builds were working fine before but after activating the required settings for google play store these errors keep showing up   

Building Library\Bee\artifacts\Android\libunity\armeabi-v7a\unstripped\libunity.so failed with output:
ld.lld: error: failed to write to the output file: Permission denied
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Building Library\Bee\artifacts\Android\libunity\arm64-v8a\unstripped\libunity.so failed with output:
ld.lld: error: failed to write to the output file: Permission denied
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Building Library\Bee\artifacts\Android\iz17e\libil2cpp.so failed with output:
ld.lld: error: failed to write to the output file: Permission denied
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Building Library\Bee\artifacts\Android\d8kzr\libil2cpp.so failed with output:
ld.lld: error: failed to write to the output file: Permission denied
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by JohanEngelen** [comment]
This is not an LDC problem. Unity is not D code.
