### ISSUE TITLE
Cannot import `ldc.llvmasm` on certain targets

### ISSUE THREAD

**Issue by TheGag96** [ldc-developers/ldc#4467]
Hi. I'm using LDC to compile for the target `-mtriple=armv6k-none-eabi -float-abi=hard -mcpu=mpcorenovfp -mattr=+vfp2`. If I as much as import `ldc.llvmasm` in my program, I get the following error:

```
<...>/ldc/bin/../import/ldc/llvmasm.di(45): Error: the `LDC_inline_ir` pragma template must have three (string, type and type tuple) or five (string, string, string, type and type tuple) parameters
```

But, if I try compiling a simple inline assembly example for x64, this error doesn't show.

I'll see if I can make a simplified repro soon, but I'm guessing this has to do with the target architecture.

Any ideas? I was testing this with LDC 1.33.0 on x64 Linux. Thanks!

**Comment by JohanEngelen** [comment]
I can't reproduce it: https://d.godbolt.org/z/8Gd46sx4Y

**Comment by TheGag96** [comment]
Whoops, this was just an issue with my hacked-up `object.d`. Closing!
