### ISSUE TITLE
advapi32. undefined identifier `HMODULE

### ISSUE THREAD

**Issue by vitalfadeev** [ldc-developers/ldc#4479]
LDC\bin\..\import\std\internal\windows\advapi32.d(36,9): Error: undefined identifier `HMODULE`, did you mean alias `HMODULE`?

See patch in attached file
[advapi32.d.patch](https://github.com/ldc-developers/ldc/files/12448048/advapi32.d.patch)

**Comment by kinke** [comment]
This is probably https://issues.dlang.org/show_bug.cgi?id=23818, and needs to be fixed in the upstream [dmd](https://github.com/dlang/dmd/) repo.
