### ISSUE TITLE
Windows multilib ldc2.conf "default" problem when using in WASM

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4480]
Ldc version: 1.33.0-beta

When using the release binary for windows multilib, we have the following default field for ldc2.conf:

```ini
default:
{
    // default switches injected before all explicit command-line switches
    switches = [
        "-defaultlib=phobos2-ldc,druntime-ldc",
    ];
    // default switches appended after all explicit command-line switches
    post-switches = [
        "-I%%ldcbinarypath%%/../import",
    ];
    // default directories to be searched for libraries when linking
    lib-dirs = [
        "%%ldcbinarypath%%/../lib64",
    ];
    // default rpath when linking against the shared default libs
    rpath = "%%ldcbinarypath%%/../lib64";
};
```

The problem with that is when trying to link for webassembly, I get the errors:

```
lld: error: unknown argument: -rpath
lld: error: cannot open C:/ldc2/bin/../lib64: is a directory
Error: linking with LLD failed
```

**Comment by kinke** [comment]
The `rpath` isnt' overridden in the explicit wasm section, because the assumption is that noone tries to link some wasm stuff with `-link-defaultlib-shared` (there's no druntime/Phobos for wasm anyway). So if you somehow need it, just override it to an empty string in the wasm section.

**Comment by MrcSnm** [comment]
Hey! Thanks a lot! I simply had this flag in the project which I should not have and then got stuck in this error. I'll probably try looking into overriding it somehow since someone could end up doing the same mistake as me
