### ISSUE TITLE
Bundled rdmd is returning error with "version `GLIBC_2.29' not found"

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4482]
`/media/hipreme/Programming_Storage3/HipremeEngine/tools/user/build_selector/D/ldc2-1.33.0-beta1-linux-x86_64/bin/rdmd releasegame.d`

Resulted in 
```
/media/hipreme/Programming_Storage3/HipremeEngine/tools/user/build_selector/D/ldc2-1.33.0-beta1-linux-x86_64/bin/ldc2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /media/hipreme/Programming_Storage3/HipremeEngine/tools/user/build_selector/D/ldc2-1.33.0-beta1-linux-x86_64/bin/ldc2)
```

**Comment by kinke** [comment]
As said to you in person ;), the problem is that your distro's glibc is too old - the prebuilt binaries are compiled on a Ubuntu 20 box nowadays.
