### ISSUE TITLE
Result of float-vector comparison has inconsistent type

### ISSUE THREAD

**Issue by KytoDragon** [ldc-developers/ldc#4492]
If two float-vectors are compared (using ==, <, >, <=, >=) the result cannot be used for further vector-operations, unless the intermediate value is stored in a variable. Example:
```
import core.simd;
void foo() {
        float4 value1 = 0;
        float4 value2 = 1;
        //  Error: incompatible types for '(value1 == value2) & (value1 < value2)': '__vector(uint[4])' and '__vector(uint[4])'
        uint4 mask = ((value1 == value2) & (value1 < value2));

        uint4 equal = (value1 == value2);
        uint4 less = (value1 < value2);
        uint4 mask2 = (equal & less); // works, even though the same types are used
}
```
Tested on Windows 10 x64 with LDC 1.33.0 and 1.32.0.
Cannot be tested on DMD or older versions of LDC as they do not support comparison of float-vectors (`Error: incompatible types for '(value1) < (value2)': both operands are of type '__vector(float[4])'`).

**Comment by KytoDragon** [comment]
Just noticed that casting the intermediate values to the types they already are can be used as another workaround:
`uint4 mask = (cast(uint4)(value1 == value2) & cast(uint4)(value1 < value2));`

**Comment by kinke** [comment]
Thx for the report. This can be tested with recent DMD (e.g. v2.105 on run.dlang.io) and yields exactly the same error, so this is a frontend issue; please file it upstream.

**Comment by KytoDragon** [comment]
Submitted upstream: https://issues.dlang.org/show_bug.cgi?id=24189
