### ISSUE TITLE
--ftime-trace on Windows has unescaped slashes (again)

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4506]
I think this is related to LDC path being in a different disk drive.

C:\ has LDC

D:\ is where I'm executing ldc with --ftime-trace from.

**Comment by kinke** [comment]
Any chance you can figure out the JSON field containing the unescaped backslash?

**Comment by MrcSnm** [comment]
It is right in the beginning

```json

"beginningOfTime":864860194230,
"traceEvents": [
{"ph":"M","ts":0,"args":{"name":"C:\D\ldc2\ldc2-1.35.0-beta1-windows-multilib\bin\ldc2.exe"},"name":"process_name","pid":101,"tid":101},
{"ph":"M","ts":0,"args":{"name":"C:\D\ldc2\ldc2-1.35.0-beta1-windows-multilib\bin\ldc2.exe"},"cat":"","name":"thread_name","pid":101,"tid":101},
```

**Comment by kinke** [comment]
Thx, then almost certainly https://github.com/ldc-developers/ldc/blob/5a158843b51b309bf13b764643d30431e3ea557e/driver/timetrace.d#L292
