### ISSUE TITLE
arm release

### ISSUE THREAD

**Issue by f8chicken** [ldc-developers/ldc#4519]
linux arm compiler needed. it should be low hanging fruit as both ldc2 android arm compiler and ldc2 linux arm arch64 compiler are avaiable.

**Comment by JohanEngelen** [comment]
> linux arm compiler needed. 
>ldc2 linux arm arch64 compiler are available.

Can you be more specific? Your second sentence seems to satisfy the first.

**Comment by kinke** [comment]
Closing as duplicate of #3665, please see rationale there. - Wrt. low-hanging fruit: AArch32 and AArch64 are quite different, and AArch64 support mature. The 32-bit Android package is firstly using bionic as C runtime, and has a well-defined ISA flavour.
