### ISSUE TITLE
LDC1.35.0/macOS/AArch64: Incorrect long/ulong mangling

### ISSUE THREAD

**Issue by ichordev** [ldc-developers/ldc#4525]
`extern(C++)` mangles `long`/`ulong` as `l`/`m` (`long`/`unsigned long`) respectively, which causes linker errors when linking against C++ code compiled with Apple clang-1500.0.40.1 that uses `int64_t` and `uint64_t`, as they are mangled as `x`/`y` (`long long`/`unsigned long long`) respectively.

The assumption that `int64_t` and `uint64_t` are defined as `long long`s only on 32-bit platforms is incorrect—they may arbitrarily be defined as either `long`s or `long long`s on 64-bit platforms. There's probably no nice way of fixing this in the long-term without an addition to D's C++ interoperability, but for now it would be nice if this could be handled by adding some platform checks to the relevant mangling generation code: https://github.com/ldc-developers/ldc/blob/f847af0cb615cb3907168d19903d22892df0470c/dmd/cppmangle.d#L1776-L1781

**Comment by ichordev** [comment]
> There's probably no nice way of fixing this in the long-term without an addition to D's C++ interoperability

(Ideally something along the lines of `void exampleFn(@mangleAs("x", long));`)

**Comment by kinke** [comment]
That's exactly why there's https://github.com/ldc-developers/ldc/blob/master/runtime/druntime/src/core/stdc/stdint.d , and a `core.stdc.config` defining `cpp_long`.

This isn't LDC-specific; DMD changed the D mangling to `long long` for 64-bit macOS for 2-3 release (2.079-2.080 or so), but that broke the much more commonly required `ptrdiff_t/size_t` interop between D and C++, so was reverted.
