### ISSUE TITLE
Add Sampling Profile-Guided Optimization (PGO) support

### ISSUE THREAD

**Issue by zamazan4ik** [ldc-developers/ldc#4527]
Sampling PGO (also known as [AutoFDO](https://github.com/google/autofdo)) is a PGO technique when instead of programs instrumentation `perf` profiles (or profiles from any other profiler) are used to gather information for the PGO optimization phase.

One of the biggest wins with AutoFDO is that with this tool is possible to gather actual workload profiles from the production environment without affecting much the production performance. That's why Google uses the AutoFDO approach as its main way to use PGO for its services.

Implementing sampling PGO in LDC can improve PGO adoption across the D ecosystem.

**Comment by JohanEngelen** [comment]
See https://clang.llvm.org/docs/UsersManual.html#using-sampling-profilers

**Comment by zamazan4ik** [comment]
yep, I know about sampling PGO support in Clang. But I want to have this support in LDC too. Is it possible right now to use sampling PGO with LDC? If yes, could you please me an example? I didn't find a reference anywhere that Clang command line documentation can be used for LDC either.

**Comment by JohanEngelen** [comment]
>  Is it possible right now to use sampling PGO with LDC?

No.
The link is there for reference to anyone who wants to implement it.

**Comment by JohanEngelen** [comment]
#4531
