### ISSUE TITLE
ldc 1.35.0 fails to build with llvm 17

### ISSUE THREAD

**Issue by mandian** [ldc-developers/ldc#4532]
Hi,

I'm trying to build ldc with llvm 17 (it is the default at OpenMandriva) but it fails as looks for non existent header files:

https://file-store.openmandriva.org/api/v1/file_stores/5c9dbbf41e7e943619cbe76bf68c43a490f31c62.log?show=true

**Comment by kinke** [comment]
Hi! The bump to v17 implies fixing https://github.com/ldc-developers/ldc/issues/4261 as it makes opaque IR pointers mandatory, so it's more than just adapting to the API changes this time.

**Comment by mandian** [comment]
I confirm it works. Thank you!
