### ISSUE TITLE
LDC druntime calls private dyld API, which is not allowed by Apple.

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [ldc-developers/ldc#4547]
The DSO handling code of ldc is currently calling the _dyld_get_image_slide API, which is private, this is not allowed by apple for release on the AppStore.

from
https://github.com/ldc-developers/ldc/blob/dc393dcfc345e2a0dd123725521eef97f161d61b/runtime/druntime/src/rt/sections_elf_shared.d#L1045
```d
else static if (SharedDarwin) void scanSegments(mach_header* info, DSO* pdso)
    {
        immutable slide = _dyld_get_image_slide(info);
        foreachDataSection(info, slide, (sectionData) { pdso._gcRanges.insertBack(sectionData); });

        version (Shared)
        {
            void[] text = getSection(info, slide, "__TEXT", "__text");
            if (!text)
                assert(0, "Failed to get text section.");
            pdso._codeSegments.insertBack(text);
        }
    }
```

This should be changed to call public API by Apple. such as `dladdr` or `_dyld_get_image_vmaddr_slide`

**Comment by JohanEngelen** [comment]
Thanks for the report.
Are you able to provide the fix yourself and test it?

**Comment by LunaTheFoxgirl** [comment]
> Thanks for the report. Are you able to provide the fix yourself and test it?
Working on making a PR, yes.

Just need to get LLVM compiling on my mac mini first heh

**Comment by LunaTheFoxgirl** [comment]
I've run out of time to work on this, with christmas being tomorrow I'll try to make a PR at a later time after christmas

**Comment by jacob-carlborg** [comment]
`_dyld_get_image_vmaddr_slide` should be avoided if possible. If `dladdr` doesn't provide the slide, you can calculate it manually: https://github.com/ldc-developers/ldc/blob/dc393dcfc345e2a0dd123725521eef97f161d61b/runtime/druntime/src/rt/sections_darwin_64.d#L134.

**Comment by luismarques** [comment]
> `_dyld_get_image_vmaddr_slide` should be avoided if possible. If `dladdr` doesn't provide the slide, you can calculate it manually: https://github.com/ldc-developers/ldc/blob/dc393dcfc345e2a0dd123725521eef97f161d61b/runtime/druntime/src/rt/sections_darwin_64.d#L134.

Just curious, why should it be avoided?

**Comment by jacob-carlborg** [comment]
> Just curious, why should it be avoided?

@luismarques it's not thread safe: https://github.com/apple-oss-distributions/dyld/blob/d1a0f6869ece370913a3f749617e457f3b4cd7c4/include/mach-o/dyld.h#L45-L57
