### ISSUE TITLE
Error: multiple source files, but only one .obj name

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#455]
When using -o-, I shouldn't get errors asking for -oq, since I'm not requesting object files

$ldc_X -oq -of=main -I=. main.d foo.d bar/foo.d =>works

$ldc_X -of=main -I=. main.d foo.d bar/foo.d
Error: Output file 'foo.o' for module 'bar.foo' collides with previous module 'foo'. See the -oq option

ldc_X -o- -of=main -I=. main.d foo.d bar/foo.d
Error: multiple source files, but only one .obj name

----files:

cat bar/foo.d
module bar.foo;
void fun(){}

cat foo.d
public import bar.foo;

cat main.d
import foo;
import bar.foo;
void main(){fun;}

**Comment by kinke** [comment]
Fixed by #1771.
