### ISSUE TITLE
Re: Error: Instruction does not dominate all uses!

### ISSUE THREAD

**Issue by renatoathaydes** [ldc-developers/ldc#4560]
Hi, I've reported this problem on the D Forum: https://forum.dlang.org/post/jqisddaxinqwpsvrjepw@forum.dlang.org

And I was asked to report it here as well.

With the help of Dustmite, I was able to find a minimum reproducible source file:

```d
import std : peek, Endian;
import std : SysTime;

T peeks(T, size_t lo, size_t hi)(ubyte[] bytes) =>
    peek!(T, Endian.littleEndian)(bytes[lo .. hi]);

void parseCd(ubyte[] bytes)
{
    toSysTime(peeks!(ushort, 14, 16)(bytes), peeks!(ushort, 12, 14)(bytes));
}

SysTime toSysTime(ushort date, ushort time)
{
    return SysTime((date << 16) + time);
}
```

Compile with:

```
ldc2 -lib -O3 main.d
```

Result:

```
Error: Instruction does not dominate all uses!
  %10 = getelementptr inbounds i8, i8* %7, i64 12
  %8 = bitcast i8* %10 to i32*
```

I got the exact same error on Linux and on Mac.

Using `-O2` the code compiles fine.

**Comment by kubo39** [comment]
On ldc-1.36.0(based on LLVM 17.0.6) I can't reproduce this.
This may have been fixed in the upgrade to LLVM 17.

**Comment by renatoathaydes** [comment]
I can confirm it works on my real project with 1.36.0. Great timing :).

**Comment by thewilsonator** [comment]
I would double check that the reduction and your project do exactly what you think it should, 1.36 uses opaque pointers, which previous versions of LDC did not. 

Can you try a previous version of LDC and see if setting `--opaque-pointers=true` (I think) and see if that fixes it?

**Comment by renatoathaydes** [comment]
@thewilsonator the reduction compiles fine with LDC 1.35.0 and this command:

```
▶ ldc2 -lib -O3 instruction_error.d --opaque-pointers=true
```

The real app also compiles and seems to run correctly.
