### ISSUE TITLE
libLTO-ldc.dylib missing in 1.36 Release for osx-arm64

### ISSUE THREAD

**Issue by cyrusmsk** [ldc-developers/ldc#4565]
Also you can see the changes in archive sizes for the image ldc2-1.36.0-osx-arm64.tar.xz:

1.35 - 63 MB
1.36 beta1 - 67.8 MB
1.36 - 48.6 MB

**Comment by JohanEngelen** [comment]
Thank you for the report. This is related to this PR: https://github.com/ldc-developers/ldc/pull/4548

fix https://github.com/ldc-developers/ldc/pull/4566

**Comment by JohanEngelen** [comment]
@cyrusmsk  Please test again in a few hours with the CI package here: https://github.com/ldc-developers/ldc/releases/tag/CI
(should have git commit hash `ff6ac6b` in the file name).  Thanks!
