### ISSUE TITLE
ASan regression on Windows with MSVC 14.38.33130

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#4586]
See https://github.com/llvm/llvm-project/issues/82450 and https://stackoverflow.com/a/77577172

Once fixed (upstream), apply same fix (if needed) to LDC, and re-enable CI testing (https://github.com/ldc-developers/ldc/pull/4585)

**Comment by kinke** [comment]
Probably fixed by https://github.com/llvm/llvm-project/pull/68910 landing in LLVM 18, which fixed our CI regressions (#4644).
