### ISSUE TITLE
[Feature Request] Non-constant static initialized nested delegate literal expression better error message

### ISSUE THREAD

**Issue by MrcSnm** [ldc-developers/ldc#4610]
The commit 4abf1d3 added some code which throws an error `non-constant nested delegate literal expression`.

I have tried minimally reproducing this error, but I've been unable to. This does not happen on DMD.

What I'm doing is:

```d

Feature FeatureMakeRubyGem(
    string gemName, 
    string purpose, 
    VersionRange supportedVersion = VersionRange.init, 
    OS[] requiredOn = null, 
    Feature*[] dependencies = null
)
{
    import std.process;
    return Feature("Ruby Gem: "~gemName, purpose, ExistenceChecker([], [], (ref Terminal t, TargetVersion v, out ExistenceStatus where)
    {
        if(executeShell("gem list | grep "~gemName).status)
        {
            where = ExistenceStatus(ExistenceStatus.Place.notFound);
            return false;
        }
        where = ExistenceStatus(ExistenceStatus.place.inPath);
        return true;
    }), Installation([], (ref Terminal t, ref RealTimeConsoleInput input, TargetVersion ver, Download[] content)
    {
        return wait(spawnShell("sudo gem install "~gemName)) == 0;
    }), null, supportedVersion, requiredOn, dependencies);
}
```

It is basically a delegate inside a struct which is inside another struct.
I don't know how much this helps, but I have been trying for quite some time to understand and was unable to find anything

**Comment by MrcSnm** [comment]
@kinke Some update on that: Although it compiles with DMD, it starts crashing randomly on a later step function return... Maybe this have an alternative?

**Comment by kinke** [comment]
Well in that case LDC might be doing the right thing, contrary to DMD. ;) - Your code somehow requires the delegate as a static constant, as part of an initializer for a global or so. And that cannot work if the delegate uses an outer context, e.g., the outer `gemName` parameter in your snippet, as that context is obviously dynamic.

**Comment by kinke** [comment]
You can use `-vv` when compiling with LDC, to see what it's doing right before the error; that could help.

**Comment by MrcSnm** [comment]
> Well in that case LDC might be doing the right thing, contrary to DMD. ;) - Your code somehow requires the delegate as a static constant, as part of an initializer for a global or so. And that cannot work if the delegate uses an outer context, e.g., the outer `gemName` parameter in your snippet, as that context is obviously dynamic.

I opened an issue on DMD: https://issues.dlang.org/show_bug.cgi?id=24469

What is a static constant delegate? I'm pretty sure I'm not using any kind of fancy keywords with delegates. Maybe is it possible to create a better error message like showing why have it turned to be required to be static constant?

I'll test with `-vv` and comment again

**Comment by MrcSnm** [comment]
@kinke I was able to reduce the error after looking in all my code:

```d
struct ExistenceChecker
{
    ///Optional. 
    bool delegate() checkExistenceFn;

}
ExistenceChecker makeExistenceChecker(string gemName)
{
    return ExistenceChecker(()
    {
        return executeShell("gem list | grep "~gemName).status == 0;
    });
}

ExistenceChecker[] chks = [
    makeExistenceChecker("test")
];
```

**Comment by MrcSnm** [comment]
Maybe is it possible to put in the error that because of the array syntax there, it can't access the outer variables?

**Comment by kinke** [comment]
It doesn't have anything to do with the array syntax, it's just an invalid non-constant initializer for a global as expected. I've added a full example in https://issues.dlang.org/show_bug.cgi?id=24469#c2. And it's actually a DMD regression (since v2.079).

**Comment by MrcSnm** [comment]
I'll put this as a feature request for showing which part requested for static initialization of a non constant delegate

**Comment by kinke** [comment]
I suggest you ask for better diagnostics (agreed; what would IMO be very helpful is knowing where the problematic initializer is) upstream, not here.

**Comment by kinke** [comment]
Wrt. how to work around this - create the array at runtime, not at compile-time, in a module ctor or so.

**Comment by MrcSnm** [comment]
Okay, I'll put there, thanks for the help :)

**Comment by MrcSnm** [comment]
@kinke Btw I was checking that:
```d
int delegate() makeClosure(int start)
{
    return (){return start+1;};
}

auto b = makeClosure(1);

void main()
{
}
```

You can see it shows from where it comes from. Does that also requires to be asked on upstream? Because the upstream doesn't even show an error 🤔

**Comment by kinke** [comment]
With run.dlang.io's current DMD v2.105, it shows the same CTFE error as LDC for your example above, nicely including the initializer line:
```
onlineapp.d(3): Error: closures are not yet supported in CTFE
onlineapp.d(6):        called from here: `makeClosure(1)`
```

This doesn't come from LDC directly, but the frontend's CTFE interpreter. The original error with the struct container seems to slip through there, and that's most likely where the fix should land (so in the DMD frontend, that's why I asked for the upstream issue).
