### ISSUE TITLE
[x86] segmentation fault with aligned struct parameters

### ISSUE THREAD

**Issue by the-horo** [ldc-developers/ldc#4614]
I'm not 100% sure if the title is the real cause but the following code crashes:
```d
align(8) struct Cent { }

void udivmod(Cent, int) { }

void main (){
    udivmod(Cent(), 0);
}
```

It's a reduction from  [this line](https://github.com/ldc-developers/ldc/blob/e170ca51e673c258437915a8aff3feb31ea6802b/dmd/common/int128.d#L881) in the int128 unittest.

dmd and gdc don't fail. I've only hit this on x86.

**Comment by kinke** [comment]
This is a duplicate of #1356; see in particular https://github.com/ldc-developers/ldc/issues/1356#issuecomment-1054295164.

**Comment by kinke** [comment]
You do have this existing workaround, right? https://github.com/ldc-developers/ldc/blob/e170ca51e673c258437915a8aff3feb31ea6802b/runtime/druntime/src/core/int128.d#L37-L40

**Comment by the-horo** [comment]
That's in druntime, I was hitting it in https://github.com/ldc-developers/ldc/blob/e170ca51e673c258437915a8aff3feb31ea6802b/dmd/common/int128.d#L23-L27
which I found out by running `ldc2-unittest` on x86 when compiling with another ldc2 installation.

**Comment by kinke** [comment]
Ah okay, that 'copy'. It's unused, except for `ldc2-unittest`.

**Comment by the-horo** [comment]
Alright then, if it's unused and the underlying issue was already reported then I can ignore it. Thank you again for your help.
