### ISSUE TITLE
betterC - alloca - missing __chkstk

### ISSUE THREAD

**Issue by sDIMMaX** [ldc-developers/ldc#4621]
Version:
`
Win64; LDC2 1.35-1.37
`
Code:
`
extern(C) int main() @nogc nothrow
{
    auto x = alloca(int.sizeof);
    return 0;
}
`
Error:
`
lld-link: error: undefined symbol: __chkstk
`
Workaround (in dub):
`
"lflags": ["=/alternatename:__chkstk=___chkstk_ms"],
`

**Comment by kinke** [comment]
Explanation and solution for non-betterC: https://github.com/ldc-developers/ldc/blob/908a2e3d816f3e21d82b61d4b0624de92f871feb/runtime/druntime/src/rt/msvc.d#L76-L87

This won't be fixed for betterC; a non-issue when using the MS libs.
