### ISSUE TITLE
LDC sets both never-inline and always-inline on inline functions containing DMD-style inline assembly.

### ISSUE THREAD

**Issue by just-harry** [ldc-developers/ldc#4630]
If a D function has `pragma(inline, true)` applied to it, or a C function is `inline`, and the function contains DMD-style inline assembly, LDC will end up setting both always-inline and never-inline on the function, causing an error during compilation.

I think it would be better for the inline attribute to be ignored if a function contains DMD-style inline assembly, like DMD does, if only to allow third-party code with the conflicting attributes to be compiled. (Examples of such code include `Int64ShllMod32` in `winnt.h`, which is included by `windows.h`)

**Comment by just-harry** [comment]
A proposed fix: https://github.com/ldc-developers/ldc/pull/4631

**Comment by kinke** [comment]
> If a D function has pragma(inline, true) applied to it, or a C function is inline

Ideally, we'd be able to discriminate these 2 cases, and error out properly for an invalid `pragma(inline, true)` (upstream, in the frontend directly). But if importC translates `inline` to the same AST representation, then that's firstly not really correct, but probably works in most cases, and so I agree that we should just ignore it.

There's a `Dsymbol::isCsymbol()` method that we could use to restrict this 'hack' to functions in C files only.

**Comment by just-harry** [comment]
> > If a D function has pragma(inline, true) applied to it, or a C function is inline
> 
> Ideally, we'd be able to discriminate these 2 cases, and error out properly for an invalid `pragma(inline, true)` (upstream, in the frontend directly). But if importC translates `inline` to the same AST representation, then that's firstly not really correct, but probably works in most cases, and so I agree that we should just ignore it.
> 
> There's a `Dsymbol::isCsymbol()` method that we could use to restrict this 'hack' to functions in C files only.

Mhm, ImportC just sets `FuncDeclaration.inlining` to `PINLINE.always` for `inline` functions (though it doesn't emit a `PragmaDeclaration`).

I've changed https://github.com/ldc-developers/ldc/pull/4631 to ignore always-inline when DMD-style inline assembly is present only for C functions.
