### ISSUE TITLE
lit test broken for Python >= 3.12

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#4671]
Python 3.12 no longer has the `distutils` package.
```
❯ ./runlit.py -v .
Lit version:  18.1.6
runlit.py: /Users/johan/.pyenv/versions/3.12.2/lib/python3.12/site-packages/lit/TestingConfig.py:152: fatal: unable to parse config file '/Users/johan/ldc/build17/tests/lit.site.cfg', traceback: Traceback (most recent call last):
  File "/Users/johan/.pyenv/versions/3.12.2/lib/python3.12/site-packages/lit/TestingConfig.py", line 140, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/Users/johan/ldc/build17/tests/lit.site.cfg", line 10, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

See https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1641#issue-1972609354 for possible fixes. I don't have `gdb` so can't really test what replacement works for the version testing.

**Comment by the-horo** [comment]
The testsuite has been forking fine for me with pythont3.12 (though I don't run the gdb or the valgrind tests). Perhaps you need `pip install setuptools`?

**Comment by kinke** [comment]
Depending on a package for two little version-string comparisons seems pretty silly IMO. Especially for nowadays uber-ancient gdb versions < 8. Ubuntu 20 has v9, Debian 10 v8. I guess we can simply remove those checks.
