### ISSUE TITLE
Memory leak in rt.minfo according to ASAN

### ISSUE THREAD

**Issue by rikkimax** [ldc-developers/ldc#4675]
Ldc 1.37.0 on Linux.

Using address sanitizer enabled for a shared library, it appears that there may be a memory leak in rt.minfo.

While it may be an upstream bug, I'm reporting here first because its ASAN that is catching it.

```
==57995==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x7f72159386b6 in realloc /home/runner/work/llvm-project/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:85:3
    #1 0x561f327a4e13 in _D2rt5minfo11ModuleGroup9sortCtorsMFNbAyaZ6doSortMFNbmKAPyS6object10ModuleInfoZb (/home/rikki/projects/ProjectSidero/eventloop/examples/networking/example_networking+0xb0e13) (BuildId: 08ee12abadfb191c7201255e72848f7ccb6710e9)

SUMMARY: AddressSanitizer: 80 byte(s) leaked in 2 allocation(s).
```

**Comment by kinke** [comment]
> While it may be an upstream bug, I'm reporting here first because its ASAN that is catching it.

Not sure I get the rationale wrt. ASan and then filing here, the 'issue' is almost certainly upstream, just like other little leaks in https://github.com/ldc-developers/ldc/issues/4617.

**Comment by rikkimax** [comment]
That is my instinct too, but I thought it was better to report here first to make sure there is no additional context that I may not be aware of.

**Comment by rikkimax** [comment]
https://issues.dlang.org/show_bug.cgi?id=24578
