### ISSUE TITLE
Time trace large amounts of time spent in writing of files

### ISSUE THREAD

**Issue by rikkimax** [ldc-developers/ldc#4676]
The majority of time in my builds with ldc is spent in ``Write file(s)``.

I would like to know what exactly is slow.

10s on a 15s build being a black box isn't a good thing.

**Comment by thewilsonator** [comment]
That time trace comes from https://github.com/ldc-developers/ldc/blob/master/driver/toobj.cpp#L385 I'm not sure what any more granularity you would reasonably get more information from, assuming that you are just writing object files xor LLVM bitcode. 

Have you tried using object cacheing (`--cache=<cache dir>?`)

**Comment by rikkimax** [comment]
I haven't tried caching.

However, there certainly is more granularity left i.e. linking isn't measured. Plus there could be a "and everything else after write" stage.

**Comment by thewilsonator** [comment]
That function only does object file writing, not linking. There is a time trace-point https://github.com/ldc-developers/ldc/blob/master/driver/linker.cpp#L292 for linking. Is that insufficient?

**Comment by rikkimax** [comment]
Very insufficient.

![Capture](https://github.com/ldc-developers/ldc/assets/992755/52f18801-42e5-4c48-a54f-fbf577d84cc0)

[tt.txt](https://github.com/user-attachments/files/15525063/tt.txt)

**Comment by thewilsonator** [comment]
all the rest of that is LLVM though, I'm not sure there in much we can do. and that is with to without cache?

**Comment by kinke** [comment]
Ths *is* LLVM codegen. IIRC, the first version of `-ftime-trace` did include the LLVM traces too, but Johan then rewrote it so that we only have LDC's own traces.

**Comment by rikkimax** [comment]
Turning on cache does indeed allow non-clean builds to be sped up significantly thanks!

However, I do think that something isn't right with it taking that long.
Without additional measurements there is no way to know what is causing it.

I'll close for now.

**Comment by JohanEngelen** [comment]
> Ths _is_ LLVM codegen. IIRC, the first version of `-ftime-trace` did include the LLVM traces too, but Johan then rewrote it so that we only have LDC's own traces.

This.

We can't (yet) easily hook into LLVM's timetracing together with LDC's own...
