### ISSUE TITLE
ldc expects shared libraries even thought explicitly asks for a static build

### ISSUE THREAD

**Issue by ryuukk** [ldc-developers/ldc#4702]
``ldmd2 -L-static  ...``

```
/usr/bin/ld: cannot find -lphobos2-ldc-shared: No such file or directory
/usr/bin/ld: cannot find -ldruntime-ldc-shared: No such file or directory
```

Why does it complain about SHARED when passing STATIC? don't error

**Comment by JohanEngelen** [comment]
`-L...` passes a flag to the linker only, it is ignored by the compiler. So you are actually not asking the compiler for a static build.

**Comment by kinke** [comment]
I.e., there's a `-static` switch for LDC itself, which implies `-L-static` and defaults to `-link-defaultlib-shared=false`.
