### ISSUE TITLE
Support for newer LLVM versions for C++ bootstrap branch?

### ISSUE THREAD

**Issue by dukc** [ldc-developers/ldc#4713]
A Nix maintainer much better than me wants to [bootstrap dmd and ldc](https://github.com/NixOS/nixpkgs/pull/324982). The problem is that NixPkgs does not support LLVM 8 anymore. Having the bootstrap compiler to support a newer LLVM would therefore help. Any chance of that happening?

Certainly with enough effort bootstrapping can be done via gdmd too but as NixPkgs currently stands it'd be more effort to do so.

ping @jtbx.

**Comment by thewilsonator** [comment]
Use GDC?

**Comment by jtbx** [comment]
Using GDC was the original plan, but the GDC package in Nixpkgs has a few issues: GDC 12 is apparently "broken" and GDC 11 fails to link in C/C++ libraries. It's very much our own problem.

**Comment by thewilsonator** [comment]
Your other option is to pick the last C++ DMD frontend, and bootstrap that forward.

**Comment by jtbx** [comment]
I've tried using the sources in DMD's `dmd-cxx` branch (which should work for x86 platforms), but what do you mean by the last C++ *frontend*? Is the C++ frontend supposed to fit in to LDC's build system?

**Comment by dukc** [comment]
The backend in LDC is still c++, and was in c++ in dmd back in times when it's frontend was.

**Comment by kinke** [comment]
> Any chance of that happening?

No. The branch is `ltsmaster`, ancient, doesn't support AArch64 etc., miscompiles newer compilers (#3354), has other issues like #2926, and I'm skeptical it can build latest master (since DMD upstream requires v2.076+, and ltsmaster is based on v2.068).

It's dead.

**Comment by dukc** [comment]
Unfortunate but understandable.
