### ISSUE TITLE
Wish: implement %ldccurrentpath% variable for ldc2.conf

### ISSUE THREAD

**Issue by denizzzka** [ldc-developers/ldc#4714]
This would allow to make few standalone standard libraries versions and switch them by selecting desired config file containing compiler options and relative paths to all necessary things

(I can implement this, of course)

**Comment by kinke** [comment]
With which semantics?

**Comment by denizzzka** [comment]
Let's say make a `d-stdlibs-freertos` dir containing library files (in `lib/`), imports (in `import/`) and `ldc2.conf` configuration file in root of dir:
```ini
default:
{
    switches = [
        "--mtriple=thumbv7em-unknown-none-eabi",
        "-defaultlib=druntime-ldc,phobos2-ldc"
    ];
    post-switches = [
        "-I%ldccurrentpath%/import/src/",
        "-I%ldccurrentpath%/import/tagged/",
        "-I%ldccurrentpath%/import/phobos/"
    ];
    lib-dirs = [
        "%ldccurrentpath%/lib",
    ];
    rpath = "%ldccurrentpath%/lib";
};
```

Then, using `ldc2 --conf=path/to/d-stdlibs-freertos/ldc2.conf app.d` we can compile `app.d`

**Comment by kinke** [comment]
So the directory containing the ldc2.conf file. I guess that would be fine, but I'd call it `%%ldcconfigpath%%` then, analogous to `%%ldcbinarypath%%`.
