### ISSUE TITLE
Incorrect LLVM type for struct with single align(1) member

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#4719]
This test case triggers the assert: https://github.com/ldc-developers/ldc/blob/48c1dff0466f5231619356ae33ef1a181888a1ff/ir/irtypeaggr.cpp#L43

```d
pragma(msg, TraceBuf.alignof); // prints 1
struct TraceBuf {
    align(1) uint args;
}

void foo() {
    byte[2] fixDescs;
    TraceBuf fixLog;

    auto dlg = delegate() {
        fixDescs[0] = 1;
        fixLog.args = 1;
    };
}
```

This is a minimized testcase, that no longer crashes LDC. The original case ran into the error
`Error: variable ... overlaps previous field. This is an ICE, please file an LDC issue.`

The reason is that the LLVM type is wrong since 1.31.0.

Used to be:
`%example.TraceBuf = type <{ i32 }>`
but now is:
`%example.TraceBuf = type { i32 }`, i.e. alignment is not 1 but 4.

**Comment by JohanEngelen** [comment]
Regression due to d16fba30306b4d8993c0b5e0f22bbbc43b8135e7  (note the changes in the gh2346.d testcase)

**Comment by JohanEngelen** [comment]
Seems to only go wrong for delegates, but I don't yet see where it actually goes wrong in codegen  (i.e. for release builds without the assert, does it actually result in a crashing program)

**Comment by JohanEngelen** [comment]
@kinke Do you remember whether there was anything bad about having `%example.TraceBuf = type <{ i32 }>` be packed that lead to your change in https://github.com/ldc-developers/ldc/commit/d16fba30306b4d8993c0b5e0f22bbbc43b8135e7? Seems like a good thing to keep D type alignment the same as LLVM IR type alignment in this case, no?

**Comment by kinke** [comment]
> Do you remember whether there was anything bad about having %example.TraceBuf = type <{ i32 }> be packed that lead to your change in https://github.com/ldc-developers/ldc/commit/d16fba30306b4d8993c0b5e0f22bbbc43b8135e7? Seems like a good thing to keep D type alignment the same as LLVM IR type alignment in this case, no?

I think I came to the conclusion that the alignnent cannot be represented for an IR type anyway, e.g., something exotic like `struct S { align(2) int x; }`. So I opted for only making *containers* packed, if their field offsets aren't naturally aligned, for types like that `TraceBuf` struct which aren't affected themselves by their alignment.

Looks like there's something missing for closures then. Note that making sure the heap-allocated closures themselves are aligned sufficiently (to the max of their member alignments) is something pretty recent; `_d_allocmemory` is extended by some bytes, and the pointer potentially aligned, all done by the compiler.

**Comment by kinke** [comment]
In the LDC v1.38 IR, the problem is that the closure type somehow isn't packed, although a struct `Container` with those 2 fields is:
```LL
%onlineapp.TraceBuf = type { i32 }
%nest.foo = type { [2 x i8], %onlineapp.TraceBuf }
%onlineapp.Container = type <{ [2 x i8], %onlineapp.TraceBuf }>
```

**Comment by kinke** [comment]
Ah, looks like that assertion in `AggrTypeBuilder::addType()` should just be converted to setting `m_packed` in that case - looks like this function is only used for stuff where we assumed (at least) natural alignment so far, incl. closure members.
