### ISSUE TITLE
Make it easier to build static libraries

### ISSUE THREAD

**Issue by ryuukk** [ldc-developers/ldc#4729]
I propose adding a shortcut for `--link-defaultlib-shared=false`

Make it `-staticLibrary`

Not obfuscated, easy to grep from `--help`

https://forum.dlang.org/thread/ltupmaoakmhjhhnnzaze@forum.dlang.org

https://forum.dlang.org/thread/yguvdwlqtyvmjrdsjkzo@forum.dlang.org

**Comment by kinke** [comment]
Generating static libraries has nothing to do with linking, so `-link-defaultlib-shared` doesn't apply to `-lib`. And FWIW, `-link-defaultlib-shared=false` is the default setting, unless specified in `ldc2.conf`.

**Comment by kinke** [comment]
See https://forum.dlang.org/post/qvugztmdjppixbyzroqe@forum.dlang.org for more context, and https://forum.dlang.org/post/oqsskjmowwsvzinzyjxq@forum.dlang.org for how to use the D compiler to merge static libraries.
