### ISSUE TITLE
Missing intrinsic lrint

### ISSUE THREAD

**Issue by rikkimax** [ldc-developers/ldc#4754]
Someone on Discord needs ``lrint`` to generate ``CVTSS2SI``.

```d
pragma(LDC_intrinsic, "llvm.lrint.i64.f#")
    long llvm_lrint(T)(T val)
        if (__traits(isFloating, T));
```

I was able to find that this is a missing intrinsic. It is not hooked up to core.stdc.math or std.math.

**Comment by JohanEngelen** [comment]
While at it, these are missing intrinsics:
- `llvm.roundeven`
- `llvm.lround`
- `llvm.llround`
- `llvm.lrint`
- `llvm.llrint`
All are available since at least LLVM 11.
