### ISSUE TITLE
Inline assembly constraints doesn't match Clang

### ISSUE THREAD

**Issue by jacob-carlborg** [ldc-developers/ldc#4765]
I'm trying to port the following C function which uses inline assembly to D:

```d
static __inline void outsb(unsigned short __port, const void *__buf, unsigned long __n)
{
    __asm__ volatile ("cld; rep; outsb"
                  : "+S" (__buf), "+c" (__n)
                  : "d" (__port));
}
```

I've ported that to this D code:

```d
extern (C) void outsb(ushort __port, const(void)* __buf, uint __n)
{
    asm { "cld; rep; outsb"
                  : "+S" (__buf), "+c" (__n)
                  : "d" (__port); }
}
```

I compiled it with LDC like this: `ldc2 -mtriple i386-freestanding main.d` and I get the following error:

```
error: couldn't allocate output register for constraint '{+S}' at line 1
```

The same thing happens with the `+c` constraint as well. Compiling the above C code with Clang 17.0.6 works perfectly fine.

**Comment by kinke** [comment]
The problem here is the `+`; looking at the clang asm, it apparently means something like: 'read it as input, and store the final register value back to that variable'. Now if that is really the real-world function, the result (in `__buf` and `__n`) is discarded anyway.

So I guess this should work as well, only using them as inputs:
```D
extern (C) void outsb(ushort __port, const(void)* __buf, uint __n)
{
    asm { "cld; rep; outsb"
                  : : "d" (__port), "S" (__buf), "c" (__n); }
}
```

This yields the same optimized asm as with clang: [D](https://d.godbolt.org/z/ns5eo7js4), [C](https://cpp.godbolt.org/z/oT1z9b7xf)
```asm
outsb:
        push    esi
        movzx   edx, word ptr [esp + 8]
        mov     esi, dword ptr [esp + 12]
        mov     ecx, dword ptr [esp + 16]
        cld
        rep
        outsb   dx, byte ptr [esi]
        pop     esi
        ret
```

**Comment by kinke** [comment]
Oh and in case the result is actually used in real-world, mentioning these as pairs of in- and outputs seems to be equivalent (same unoptimized asm with clang and LDC):
```D
extern (C) void outsb(ushort __port, const(void)* __buf, uint __n)
{
    asm { "cld; rep; outsb"
                  : "S" (__buf), "c" (__n)
                  : "S" (__buf), "c" (__n), "d" (__port); }
}
```

**Comment by jacob-carlborg** [comment]
> Now if that is really the real-world function

That's a copy paste from `/usr/include/sys/io.h` on Alpine IIRC. 

Thanks I'll try without the `+`.

**Comment by jacob-carlborg** [comment]
> So I guess this should work as well, only using them as inputs

That worked, thanks. I'm closing this one since there's a pretty simple workaround.
