### ISSUE TITLE
ARM: Provide scripts for setting up a cross-compilation tool chain

### ISSUE THREAD

**Issue by dnadlinger** [ldc-developers/ldc#490]
We need to test cross compiling for ARM and should provide scripts to make it easy to set up such a toolchain.

**Comment by joakim-noah** [comment]
I realized [when writing up some instructions on how to try out cross-compiling with ldc for ARM embedded systems](http://forum.dlang.org/post/kxumawpigmacwjubibzp@forum.dlang.org), that we're actually not that far off from finishing this issue, provided llvm supports the arch and we have some support for the arch/OS in druntime.

Really all you need to get going is to specify a C cross-compiler for your platform, for the few C/asm files in the stdlib, and assuming that cross-compiler invokes the appropriate cross-linker, you just need to add whatever other C and linker flags you need.  That's all that's left for me to cross-compile for Android/ARM, as you can see from the gist linked from the instructions above.

I'll look at getting that merged in a general way, where it can be used for Android and other platforms people want to cross-compile to.  @smolt, any chance we can make it easy for those wanting to build for iOS too?

**Comment by joakim-noah** [comment]
Now that we provide `ldc-build-runtime` and [instructions on how to use it](https://wiki.dlang.org/Building_LDC_runtime_libraries), we can close this, right?

**Comment by kinke** [comment]
Yeah let's close this, we have that tool for easy cross-compilation of druntime and Phobos and a Wiki page detailing how to set up cross-compilation to pretty much arbitrary targets.
