### ISSUE TITLE
Create Fedora/RHEL package

### ISSUE THREAD

**Issue by redstar** [ldc-developers/ldc#574]
We currently do not have a Fedora/RHEL package.

Required are:
- create the (static?) files (.spec file etc) required to produce a package
- add a script to https://github.com/ldc-developers/ldc-scripts/tree/master/ldc2-packaging to be able to create the package during the release process

**Comment by kinke** [comment]
The community takes care of the distro packages now, for Fedora it's @kalev at the moment.
