### ISSUE TITLE
strange behavior of static asserts

### ISSUE THREAD

**Issue by x539** [ldc-developers/ldc#585]
I noticed the following strange behavior, when playing around with new platform support for ldc. 
/the druntime uses the pattern below for "static assert(false, "platform not supported");/

test.d:
```d
version (abc)
  alias int fooBar;
else
  static assert(false, "bad configuration");

version (bug) {

  fooBar abc;

} else {

  int functionA() {
     fooBar abc;
  }

}
```

```sh
ldc2 -c -d-version=bug test.d
```
gives:
```
test.d(7): Error: undefined identifier fooBar
```
expected output is (as it is for the no-bug version)
```
test.d(4): Error: static assert  "bad configuration"
```

**Comment by 9rnsr** [comment]
At least there's no spec for the evaluation timing of `static assert`, so there's no issue about that the semantic failure of invalid variable declaration `fooBar abc;` is detected first.

More precise information: In dmd frontend, senamtic analysis is separated to three sub-stages - semantic1, semantic2, and semantic3. They're normally invoked in the order of their numbers.
On a variable declaration, its type analysis will be done in semantic1. On the other hands, static assert evaluation is done in semantic2. With the case code, the module level semantic1 stage fails on `fooBar abc;`, then semantic2 is not invoked.

**Comment by kinke** [comment]
Thanks for digging out this old issue. I'm closing it as it has nothing to do with LDC itself.
