### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by etcimon** [ldc-developers/ldc#609]
I'd like to build LDC on Windows but the docs seem outdated and I get plenty of CMake errors. Has this been done recently?

I installed LLVM 3.4.1 (Clang for Windows) from [here](http://llvm.org/releases/download.html) and copied mingw64 from [here](http://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.8.0/64-bit/threads-win32/seh/) into some sane paths and added them to my env variables, and with CMake 2.8.12.2 from [here](http://www.cmake.org/cmake/resources/software.html) ..gasp.. 

So I run `mkdir build && cd build && cmake ..`

The errors are:

`-- The C compiler identification is unknown` from CMAKE_DETERMINE_COMPILER_ID

I tried setting `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` to a path but I still get this error. 

So, any ideas or no-brainer solutions?

**Comment by redstar** [comment]
I'm closing this issue. The Win64 MSVC version is now part of the release. For MinGW problems see #1121.
