### ISSUE TITLE
ldc doesn't support unicode on Windows

### ISSUE THREAD

**Issue by Trass3r** [ldc-developers/ldc#611]
For example put ldc into a folder with umlauts in it and call it from outside that folder.
It will try to read the config file using the exe path and fail.

The only proper solution on Windows is to compile with /D_UNICODE,  directly and exclusively use the suffix W API functions and convert from/to utf8. Note that the suffix A functions have various other restrictions aside from string encoding as well like maximum path length.

**Comment by kinke** [comment]
*Should* be fixed by #3086; not sure whether *all* problematic narrow WinAPI and MSCRT function calls have been replaced.
