### ISSUE TITLE
Check unnecessary vtbl emissions

### ISSUE THREAD

**Issue by redstar** [ldc-developers/ldc#662]
Reported by temtaine in news group (http://forum.dlang.org/post/yephpwnmvkcpyjnpbzti@forum.dlang.org). Look at the following modules:

A.d

```
import B;
```

B.d

```
import C;
import D;

import std.range;

class Font {
public:
    mixin RCounted;

    auto makeTextData(string s) {
        // split text by spaces
        auto arr = s.splitter.array;
    }    
}

class Engine {
    RC!Font font;
}
```

C.d

```
import A;
```

D.d

```
template RCounted() {
        void release() { this.destroy; }
}

struct RC(T) {
    ~this() {  _rc_ptr.release; }
    T _rc_ptr;
}
```

`ldc2 -c A.d B.d C.d D.d` works but `ldc2 -c A.d` produces an error message.

**Comment by kinke** [comment]
The original symptoms should be worked around by #1709.

> When we codegen object.destroy!(Font) (dmd does this too), we call IrTypeClass:get() for B.Font and that generates the vtbl for that class (I don't think dmd does that).

Still needs to be looked into.

**Comment by kinke** [comment]
Vtables are emitted once into the CU owning the class declaration. They are needed for the class init symbol, which is also emitted in that CU, so definitely not superfluous.

The testcase (nowadays requiring `import std.algorithm, std.array;`) works with LDC v1.27.
