### ISSUE TITLE
Use internal/private linkage for private symbols?

### ISSUE THREAD

**Issue by Trass3r** [ldc-developers/ldc#681]
``` d
private immutable string sss = "abcd";

private int strlen_utf8(string s)
{
    int i = 0, j = 0;
    while (s[i])
    {
        if ((s[i] & 0xc0) != 0x80)
            ++j;
        ++i;
    }
    return j;
}
int bar()
{
    return strlen_utf8("1234567890");
}
int baz()
{
    return strlen_utf8(sss);
}
```

Since strings are always immutable this one worked out of the box (unlike other arrays). Both bar and baz are reduced to 1 ret constant.
But strlen is kept even though it's private.

Is that intentional?
Seems more like DtoLinkage is rather limited and returns ExternalLinkage in most of the cases.

**Comment by MartinNowak** [comment]
I don't think it can be made working due to templates.
The "official" D plan is to fix export and then use -visibility=hidden for non-exported symbols, but that only makes symbols internal to a DSO (shared library, executable) not internal to a module. But hopefully could be used together with LTO.

**Comment by kinke** [comment]
I can't imagine how to get this working either due to template *declarations* in some module being able to access private symbols in that module, while the template *instantiation* can be in arbitrary other modules and DSOs.
