### ISSUE TITLE
Crash when compiling dbox (also compiling forever on release)

### ISSUE THREAD

**Issue by vova616** [ldc-developers/ldc#699]
trying to compile 
http://code.dlang.org/packages/dbox

using 0.14.0-alpha1 on windows 7

dub build --compiler=ldc2 --build=release
compiling forever

dub build --compiler=ldc2
...
0x00767197 (0x00000000 0x00000001 0x11A9FDF8 0x00000000)
0x00793520 (0x15D27958 0x0028F310 0x771D71F5 0x0867B4C2)
0x00799DA7 (0x77193CFE 0x0040FFFC 0x00000001 0x00000004)
0x77193CD3 (0x0040FFFC 0x00000001 0x00000004 0x0028F4A8), RtlImageNtHeader() + 0
xB3F bytes(s)
0x77193CFE (0x771934A2 0x0028F1FC 0x0028F21C 0x0028F23C), RtlImageNtHeader() + 0
xB6A bytes(s)
0x771938AA (0x0028F1FC 0x0028F21C 0x0028F23C 0x15D275F8), RtlImageNtHeader() + 0
x716 bytes(s)
0x771934A2 (0xFFFFFFFF 0x0028F250 0x0028F250 0x00000010), RtlImageNtHeader() + 0
x30E bytes(s)
0x77192B4C (0x15D27958 0x0028F4A8 0x160E4F5C 0x15D27958), RtlGetCurrentProcessor
NumberEx() + 0xD3 bytes(s)
0x771938AA (0x15D27958 0x00000000 0x15EF0020 0x15EF0020), RtlImageNtHeader() + 0
x716 bytes(s)
0x007B8EDB (0x01A00000 0x00000000 0x75A898DA 0x014092C4)
0x75A898CD (0x15EF0020 0x000B4F50 0x00000000 0x15D27958), free() + 0x39 bytes(s)

0x00764D44 (0x15D27958 0x00000000 0x00000004 0x7F57895E)
0x007B9BCF (0x00100000 0x00074FB7 0x000090D1 0x0E1D849C)
0x16510020 (0x0E7579A0 0x0E77A6C8 0x0E84C640 0x0E845C38) <unknown module>
0x0E845CC8 (0x0E77A6C8 0x0E84C640 0x0E845C38 0x0E84BCF8) <unknown module>
0x0E7579A0 (0x0E84C640 0x0E845C38 0x0E84BCF8 0x0E7591D0) <unknown module>
0x0E77A6C8 (0x0E845C38 0x0E84BCF8 0x0E7591D0 0x0E773B10) <unknown module>
0x0E84C640 (0x0E84BCF8 0x0E7591D0 0x0E773B10 0x0E847F18) <unknown module>
0x0E845C38 (0x0E7591D0 0x0E773B10 0x0E847F18 0x0E84BBD8) <unknown module>
0x0E84BCF8 (0x0E773B10 0x0E847F18 0x0E84BBD8 0x0E759A40) <unknown module>
0x0E7591D0 (0x0E847F18 0x0E84BBD8 0x0E759A40 0x0E845A88) <unknown module>
0x0E773B10 (0x0E84BBD8 0x0E759A40 0x0E845A88 0x0E8482C0) <unknown module>
0x0E847F18 (0x0E759A40 0x0E845A88 0x0E8482C0 0x0E848350) <unknown module>
0x0E84BBD8 (0x0E845A88 0x0E8482C0 0x0E848350 0x0E774140) <unknown module>
0x0E759A40 (0x0E8482C0 0x0E848350 0x0E774140 0x0E8333C8) <unknown module>
0x0E845A88 (0x0E848350 0x0E774140 0x0E8333C8 0x0E758768) <unknown module>
0x0E8482C0 (0x0E774140 0x0E8333C8 0x0E758768 0x0E7557E0) <unknown module>
0x0E848350 (0x0E8333C8 0x0E758768 0x0E7557E0 0x0EBE5020) <unknown module>
0x0E774140 (0x0E758768 0x0E7557E0 0x0EBE5020 0x0E846340) <unknown module>
0x0E8333C8 (0x0E7557E0 0x0EBE5020 0x0E846340 0x0E773DE0) <unknown module>
0x0E758768 (0x0EBE5020 0x0E846340 0x0E773DE0 0x0E84CE20) <unknown module>
0x0E7557E0 (0x0E846340 0x0E773DE0 0x0E84CE20 0x0EBFDFC8) <unknown module>
0x0EBE5020 (0x0E773DE0 0x0E84CE20 0x0EBFDFC8 0x0E847BB8) <unknown module>
0x0E846340 (0x0E84CE20 0x0EBFDFC8 0x0E847BB8 0x0E848980) <unknown module>
0x0E773DE0 (0x0EBFDFC8 0x0E847BB8 0x0E848980 0x0E774968) <unknown module>
0x0E84CE20 (0x0E847BB8 0x0E848980 0x0E774968 0x0E846580) <unknown module>
0x0EBFDFC8 (0x0E848980 0x0E774968 0x0E846580 0x0E773F00) <unknown module>
0x0E847BB8 (0x0E774968 0x0E846580 0x0E773F00 0x0E7743C8) <unknown module>
0x0E848980 (0x0E846580 0x0E773F00 0x0E7743C8 0x0E84C010) <unknown module>
0x0E774968 (0x0E773F00 0x0E7743C8 0x0E84C010 0x0E758A38) <unknown module>
0x0E846580 (0x0E7743C8 0x0E84C010 0x0E758A38 0x0E8487D0) <unknown module>
0x0E773F00 (0x0E84C010 0x0E758A38 0x0E8487D0 0x0E8450F8) <unknown module>
0x0E7743C8 (0x0E758A38 0x0E8487D0 0x0E8450F8 0x0E755AB0) <unknown module>
0x0E84C010 (0x0E8487D0 0x0E8450F8 0x0E755AB0 0x0E845728) <unknown module>
0x0E758A38 (0x0E8450F8 0x0E755AB0 0x0E845728 0x0E84C5B0) <unknown module>
0x0E8487D0 (0x0E755AB0 0x0E845728 0x0E84C5B0 0x0E84BEA8) <unknown module>
0x0E8450F8 (0x0E845728 0x0E84C5B0 0x0E84BEA8 0x0E77ABD8) <unknown module>
0x0E755AB0 (0x0E84C5B0 0x0E84BEA8 0x0E77ABD8 0x0E759890) <unknown module>
0x0E845728 (0x0E84BEA8 0x0E77ABD8 0x0E759890 0x0E833698) <unknown module>
0x0E84C5B0 (0x0E77ABD8 0x0E759890 0x0E833698 0x0E757FD0) <unknown module>
0x0E84BEA8 (0x0E759890 0x0E833698 0x0E757FD0 0x0E774848) <unknown module>
0x0E77ABD8 (0x0E833698 0x0E757FD0 0x0E774848 0x0E757520) <unknown module>
0x0E759890 (0x0E757FD0 0x0E774848 0x0E757520 0x0E755750) <unknown module>
0x0E833698 (0x0E774848 0x0E757520 0x0E755750 0x0E77AC68) <unknown module>
0x0E757FD0 (0x0E757520 0x0E755750 0x0E77AC68 0x0EBCB028) <unknown module>
0x0E774848 (0x0E755750 0x0E77AC68 0x0EBCB028 0x0E848080) <unknown module>
0x0E757520 (0x0E77AC68 0x0EBCB028 0x0E848080 0x0EBFE0E8) <unknown module>
0x0E755750 (0x0EBCB028 0x0E848080 0x0EBFE0E8 0x0E759B60) <unknown module>
0x0E77AC68 (0x0E848080 0x0EBFE0E8 0x0E759B60 0x0E846220) <unknown module>
0x0EBCB028 (0x0EBFE0E8 0x0E759B60 0x0E846220 0x0EBCB0B8) <unknown module>
0x0E848080 (0x0E759B60 0x0E846220 0x0EBCB0B8 0x0E7667D8) <unknown module>
0x0EBFE0E8 (0x0E846220 0x0EBCB0B8 0x0E7667D8 0x0E84B5A8) <unknown module>
0x0E759B60 (0x0EBCB0B8 0x0E7667D8 0x0E84B5A8 0x0EBCB148) <unknown module>
0x0E846220 (0x0E7667D8 0x0E84B5A8 0x0EBCB148 0x0E8478E8) <unknown module>
0x0EBCB0B8 (0x0E84B5A8 0x0EBCB148 0x0E8478E8 0x0E766238) <unknown module>
0x0E7667D8 (0x0EBCB148 0x0E8478E8 0x0E766238 0x0E757760) <unknown module>
0x0E84B5A8 (0x0E8478E8 0x0E766238 0x0E757760 0x0E847C48) <unknown module>
0x0EBCB148 (0x0E766238 0x0E757760 0x0E847C48 0x0E84B998) <unknown module>
0x0E8478E8 (0x0E757760 0x0E847C48 0x0E84B998 0x0EBE4F00) <unknown module>
0x0E766238 (0x0E847C48 0x0E84B998 0x0EBE4F00 0x0E84C490) <unknown module>
0x0E757760 (0x0E84B998 0x0EBE4F00 0x0E84C490 0x0E7587F8) <unknown module>
0x0E847C48 (0x0EBE4F00 0x0E84C490 0x0E7587F8 0xFFFFFFFF) <unknown module>
0x0E84B998 (0x0E84C490 0x0E7587F8 0xFFFFFFFF 0x16920020) <unknown module>
0x0EBE4F00 (0x0E7587F8 0xFFFFFFFF 0x16920020 0x16B1820C) <unknown module>
0x0E84C490 (0xFFFFFFFF 0x16920020 0x16B1820C 0x16D3001C) <unknown module>
0x0E7587F8 (0x16920020 0x16B1820C 0x16D3001C 0x0E1D849C) <unknown module>
0xFFFFFFFF (0x16B1820C 0x16D3001C 0x0E1D849C 0x0E845CC8) <unknown module>
0x16920020 (0x16D3001C 0x0E1D849C 0x0E845CC8 0x0E7579A0) <unknown module>
0x16B1820C (0x0E1D849C 0x0E845CC8 0x0E7579A0 0x0E77A6C8) <unknown module>
0x16D3001C (0x0E845CC8 0x0E7579A0 0x0E77A6C8 0x0E84C640) <unknown module>
0x0E1D849C (0x0E7579A0 0x0E77A6C8 0x0E84C640 0x0E845C38) <unknown module>
0x0E845CC8 (0x0E77A6C8 0x0E84C640 0x0E845C38 0x0E84BCF8) <unknown module>
0x0E7579A0 (0x0E84C640 0x0E845C38 0x0E84BCF8 0x0E7591D0) <unknown module>
0x0E77A6C8 (0x0E845C38 0x0E84BCF8 0x0E7591D0 0x0E773B10) <unknown module>
0x0E84C640 (0x0E84BCF8 0x0E7591D0 0x0E773B10 0x0E847F18) <unknown module>
0x0E845C38 (0x0E7591D0 0x0E773B10 0x0E847F18 0x0E84BBD8) <unknown module>
0x0E84BCF8 (0x0E773B10 0x0E847F18 0x0E84BBD8 0x0E759A40) <unknown module>
0x0E7591D0 (0x0E847F18 0x0E84BBD8 0x0E759A40 0x0E845A88) <unknown module>
0x0E773B10 (0x00000000 0x0D18E7C8 0x00000000 0x00000000) <unknown module>
0x007EC650 (0x0E1D8480 0x0108154E 0x15D28018 0x00000000)
0x007ECBE3 (0x0CFCD3C4 0x0CF6D100 0x0028F858 0x7718E38C)
0x007EE2DA (0x7F578456 0x0DBC72E8 0x0CFCD3C4 0x0DBD7C68)
0x7718E38C (0x0028F87B 0x0D07DFD4 0x01408FB8 0x007BE574), RtlInitUnicodeString()
 + 0x164 bytes(s)
0x00645F5D (0xFFFFFFFF 0x0114B794 0x00000012 0x0C155618)
0x007BE574 (0x0D07DF90 0x0D18E7C8 0x0D9214C8 0x00C8891A)
0x007EFB6C (0x0E75A148 0x00000040 0x01A02FE8 0x00000200)
0x00C8891A (0x014091A8 0x00000000 0x01373D6C 0x00000040)
0x00C61129 (0x01376B60 0x00000040 0x00000001 0x0E1F3DC8)
0x00C61088 (0x0DBC72E8 0x0CB34D50 0x00000000 0x00DDEAC7)
0x00C656D6 (0x00000016 0x0028FA0C 0x0DF29F8C 0x0E1F3DC8)
FAIL .dub\build\library-debug-windows-x86-ldc2-8DF547EC8C61CED29CF8F1F3065FFB47\
 dbox staticLibrary
Error executing command build: ldc2 failed with exit code -1073741819.

**Comment by vova616** [comment]
still crashing(on debug and forever on release) with ldc mingw 0.15.1 on windows
looks like different crash now?

```
0x00734DF7 (0x00000000 0x00000001 0x12A9C918 0x00000000)
0x0077386D (0xFFFFFFFF 0x0028F0EC 0x00000000 0x0028F120)
0x76F056B3 (0x0028F448 0x00207FFC 0x00000000 0x00000000), RtlDeleteAtomFromAtomTable() + 0x136 bytes(s)
0x76ED3CD3 (0xFFFFFFFF 0x0028F14C 0x0028F148 0x00008000), RtlImageNtHeader() + 0xB3F bytes(s)
0x76ED2B4C (0xFFFFFFFF 0x0028F14C 0x0028F148 0x76ED38AA), RtlGetCurrentProcessorNumberEx() + 0xD3 bytes(s)
0x76F057E9 (0x0028F2C0 0xFFFFFFFF 0x00000040 0x158A43C0), RtlDeleteAtomFromAtomTable() + 0x26C bytes(s)
0x00F821D9 (0x00000000 0x00000000 0x03000000 0x0028F470)
0x032CD334 (0x00000000 0x03000000 0x0028F470 0x15E70020) <unknown module>
```

**Comment by kinke** [comment]
MinGW support was dropped a while ago.
