### ISSUE TITLE
Vararg functions does not compile on x86_64

### ISSUE THREAD

**Issue by redstar** [ldc-developers/ldc#702]
The following module

    import core.vararg;
    import core.stdc.stdio;
    
    void log(const(char)* str, ...)
    {
        va_list args;
        version(LDC)
            va_start(args, str);
        else
            va_start(args, __va_argsave);
        vprintf(str, args);
        va_end(args);
    }
    
    void main()
    {
        log("%d %d %d\n", 1, 2, 3);
    }

compiles with dmd but gives an error with ldc:

    ldc_github.d(11): Error: function core.stdc.stdio.vprintf (const(char*) format, __va_list* arg) is not callable using argument types (const(char)*, void*)

Only on x86_64. The implementation of `core.vararg` is wrong.

**Comment by kinke** [comment]
Fixed by https://github.com/ldc-developers/ldc/pull/768 and https://github.com/ldc-developers/druntime/issues/14.
