### ISSUE TITLE
Test supported CMake variables (LIB_SUFFIX, …) as part of Travis runs

### ISSUE THREAD

**Issue by dnadlinger** [ldc-developers/ldc#714]
A build system regression recently went unnoticed (#712) because it only occurred when both BUILD_SHARED_LIBS was on and a custom LIB_SUFFIX was set. We should just add random flags to the different Travis run configs to increase our coverage.

**Comment by kinke** [comment]
With #2074, I think our coverage is about as good as it gets wrt. what Travis currently offers.

**Comment by kinke** [comment]
I'd say we have some coverage with various CI jobs now, but handling all permutations is of course absolutely infeasible with our high number of options.
