### ISSUE TITLE
Offer -ffast-math option(s)

### ISSUE THREAD

**Issue by Trass3r** [ldc-developers/ldc#722]
Important for auto-vectorization for example.

**Comment by kinke** [comment]
LDC 1.5 uses the default LLVM codegen options, among which there are `-fp-contract`, `-enable-unsafe-fp-math`, `-enable-fp-mad`, `-enable-no-infs-fp-math`, `-enable-no-nans-fp-math`, `-enable-no-trapping-fp-math`, `-denormal-fp-math`, `-recip`.
