### ISSUE TITLE
Issue with -lib and -of on windows. (and dub)

### ISSUE THREAD

**Issue by vova616** [ldc-developers/ldc#725]
When using "ldc2 -lib -of./name.a"
ldc2 created the file with the name "libname.a.lib" although I specified "name.a".
its a problem because when I'm continuing the compilation with
ldc2 -I./libname.a.lib it failes with the error:
"unrecognized file extension lib"
(and thats funny because ldc2 just created a file with the extension .lib.)

Its probably not a good idea to change the file name if the user specified one.

Thats the reason dub and ldc is not working on windows for me, I'm not sure if its ldc or dub or me doing something wrong.

I'm using LDC 0.14.0.

**Comment by vova616** [comment]
as a temporary solution I replaced .a.lib with .a on dub,

build.d:
```
private void copyTargetFile(Path build_path, BuildSettings buildsettings, BuildPlatform platform)
	{
		auto filename = getTargetFileName(buildsettings, platform);
		auto src = build_path ~ filename;
		if (filename[filename.length-2] == '.' && filename[filename.length-1] == 'a') {
			auto chk = build_path ~ ("lib" ~ filename ~ ".lib");
			if (existsFile(chk)) {
				logDiagnostic("Fixing src target from %s to %s", src.toNativeString(), chk.toNativeString());
				src = chk;
			}
			else {
				chk = src ~ ".lib";
				if (existsFile(chk)) {
					logDiagnostic("Fixing src target from %s to %s", src.toNativeString(), chk.toNativeString());
					src = chk;
				}
			}
		}
		logDiagnostic("Copying target from %s to %s", src.toNativeString(), buildsettings.targetPath);
		if (!existsFile(Path(buildsettings.targetPath)))
			mkdirRecurse(buildsettings.targetPath);
		copyFile(src, Path(buildsettings.targetPath) ~ filename, true);
	}
```

So is the problem in ldc?

**Comment by redstar** [comment]
See https://github.com/D-Programming-Language/dub/issues/618.

**Comment by kinke** [comment]
Should be fixed by now.
