### ISSUE TITLE
ARM float-abi=soft

### ISSUE THREAD

**Issue by Kozzi11** [ldc-developers/ldc#829]
I am trying to compile ldc on tizen-common arm-wayland image. But I have some error on std.math on line [4496](https://github.com/ldc-developers/phobos/blob/ldic/std/math.d#L4496). Something like statement is not reachable. I guess it is because ARM_SoftFloat version return 0. So when I edit ldc2.conf and add float-abi=hard everything works OK and I have druntime and phobos compiled. But I cannot link against them because all system lib seems are softfp only.

So it is softfp on ARM supposed to work or it is does not implemented yet?

**Comment by redstar** [comment]
I changed the offending line. ARM softfp should work but it is completely untested. (I have a hard float system.)

**Comment by smolt** [comment]
I have a fix for ARM float-abi=softfp working locally on my dev machine for iOS.  Let me see if I can get it into my github fork later today.  What it does is fixes the ARM_SoftFP version in ldc and allows the inline asm in std.math to be compiled, because that is what you want with softfp.

**Comment by redstar** [comment]
The fix smolt mentions is now in 0.15.2-beta1. Therefore I am closing this issue.
