### ISSUE TITLE
repeatable crash with vague error message

### ISSUE THREAD

**Issue by liamwhite** [ldc-developers/ldc#837]
…not sure what else to call it, the abort message isn't giving much context.
Steps:
<ol><li><code>$ git clone https://github.com/liamwhite/dgeom.git</code></li>
<li><code>$ cd dgeom</code></li>
<li><code>$ git reset --hard 44474033</code></li>
<li><code>$ dub test --compiler=ldc2</code></li></ol>

Output:
<pre>
$ dub test --compiler=ldc2
Generating test runner configuration '__test__library__' for 'library' (library).
Building dgeom ~master configuration "__test__library__", build type unittest.
Running ldc2...
Stored value type does not match pointer operand type!
  store [4 x %geom.point.Point]* %1, [4 x %geom.point.Point]* %5, !dbg !5781
 [4 x %geom.point.Point]LLVM ERROR: Broken function found, compilation aborted!
FAIL .dub/build/__test__library__-unittest-linux.posix-x86_64-ldc_0-A932BA27B3129F8BBAE87769E6F7DCDA/ __test__library__ executable
Error executing command test:
ldc2 failed with exit code 1.
</pre>

Expected output:
<pre>
$ dub test --compiler=dmd
Generating test runner configuration '__test__library__' for 'library' (library).
Building dgeom ~master configuration "__test__library__", build type unittest.
Compiling using dmd...
Linking...
Running ./__test__library__ 
All unit tests have been run successfully.
</pre>

LDC Version:
<pre>
$ ldc2 --version
LDC - the LLVM D compiler (0.15.1):
  based on DMD v2.066.1 and LLVM 3.5.0
  Default target: x86_64-unknown-linux-gnu
  Host CPU: core-avx2
  http://dlang.org - http://wiki.dlang.org/LDC
</pre>
<pre>
$ uname -a
Linux liam-Desktop 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release | grep DESC
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
</pre>

**Comment by redstar** [comment]
Confirmed. The simple way to reproduce it to replace step 4 with

    cd source
    ldc2 -c geom/bezier_fitting.d

**Comment by redstar** [comment]
Fixed in master.
