### ISSUE TITLE
Continuous integration should include OS X

### ISSUE THREAD

**Issue by dmakarov** [ldc-developers/ldc#866]
Many tests are failing on OS X, although they pass on Linux
With current state of the master branch the failures are
```
The following tests FAILED:
	 19 - core.thread (SEGFAULT)
	208 - std.file (SEGFAULT)
	219 - std.parallelism (SEGFAULT)
	572 - dmd-testsuite-debug (Failed)
	574 - dmd-testsuite (Failed)
```

**Comment by dmakarov** [comment]
Travis-ci does have multi system support, but they do not currently accept requests to enable it for new projects.  See this document http://docs.travis-ci.com/user/multi-os/

**Comment by redstar** [comment]
It seems that this Travis-CI feature is now enabled. Who can step in and try it?

**Comment by Jebbs** [comment]
This is implemented already, right?

**Comment by kinke** [comment]
That's right, let's close this issue.
