### ISSUE TITLE
Reminder: -conf switch for ldmd2

### ISSUE THREAD

**Issue by mleise** [ldc-developers/ldc#879]
If possible blanking the configuration with this switch should work for 2.067 ldmd2. That would allow me to have the *dman* tool build with ldc2 on Gentoo. I'm trying to keep everything as compiler agnostic as possible for what it's worth.
Setting and parsing a specific configuration file is not required at this time. It seems like the primary use case for -conf= is to not specify a configuration at all.

**Comment by kinke** [comment]
> It seems like the primary use case for -conf= is to not specify a configuration at all.

That's what I was thinking too. But DMD treats it as if there was no -conf switch at all, defaulting to an auto-located configuration file. In case you really need a switch to disable loading a config file, we could use some magic string like `null` for that.

**Comment by mleise** [comment]
What? That changes everything. I'll leave dman out then. Thanks for the info.
