### ISSUE TITLE
Assertion failed: (isIrVarCreated(vd) && "Variable not resolved."), function DtoSymbolAddress, file ldc/gen/llvmhelpers.cpp, line 1773.

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#953]
ldmd2 -release -c -of/tmp/z02 main.d

main.d:
----
```d
void fun(string arg){
    import std.regex;
    assert(arg.match(``));
}
```
----

it works if we remove '-release' or if we have this:
    auto temp=arg.match(``);
    assert(temp);
instead of 
    assert(arg.match(``));

ldc2 --version
LDC - the LLVM D compiler (cf0589):
  based on DMD v2.066.1 and LLVM 3.6.1
  Default target: x86_64-apple-darwin14.3.0
  Host CPU: core-avx2

**Comment by timotheecour** [comment]
with -vv:

* * * * * * * * Expression::toElemDtor(): assert((RegexMatch!(string, ThompsonMatcher) __tmpfordtor4035 = match(arg, regex("", ""));
 , __tmpfordtor4035).opCast(), cast(const(char)[])arg)
* * * * * * * * * AssertExp::toElem: assert((RegexMatch!(string, ThompsonMatcher) __tmpfordtor4035 = match(arg, regex("", ""));
 , __tmpfordtor4035).opCast(), cast(const(char)[])arg)
* * * * * * * * * CallExp::toElem: __tmpfordtor4035.~this() @ void
* * * * * * * * * * DotVarExp::toElem: __tmpfordtor4035.~this @ nothrow @nogc @trusted void()
* * * * * * * * * * * VarExp::toElem: __tmpfordtor4035 @ RegexMatch!(string, ThompsonMatcher)
* * * * * * * * * * * * DtoSymbolAddress ('__tmpfordtor4035' of type 'RegexMatch!(string, ThompsonMatcher)')
* * * * * * * * * * * * * a normal variable
Assertion failed: (isIrVarCreated(vd) && "Variable not resolved."), function DtoSymbolAddress, file ldc/gen/llvmhelpers.cpp, line 1773.

**Comment by redstar** [comment]
Confirmed with GitHub master.

**Comment by redstar** [comment]
The `__tmpfordtor` is a generated variable which is used to call the destructor of `RegexMacth!()`. In release mode, the expression inside `assert()` is never evaluated/codegened. The `__tmpfordtor` variable is not initialized but still present in the AST - therefore we try to call the destructor.

The workaround does not have equal semantics. Here the call is always evaluated and the destructor is always run.

**Comment by redstar** [comment]
I created a fix for this issue. Would be nice if someone could create a test case which does not depend on the standard library. (E.g. the test case does not compile with dmd from trunk.)
