### ISSUE TITLE
equivalent of dmd -conf=path for ldc and ldmd ?

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#972]
is there an equivalent flag?
what's the recommended way to set it ?

it would be a lot more convenient than the instructions given at http://wiki.dlang.org/Using_LDC (too many search paths for this IMO)

**Comment by redstar** [comment]
`ldmd2 -conf=` is currently a dummy, implementation is pending.

**Comment by kinke** [comment]
Implemented by #1143, analogous to DMD.
