### ISSUE TITLE
duplicate symbol when using -lib (works with dmd)

### ISSUE THREAD

**Issue by timotheecour** [ldc-developers/ldc#978]
Please see simple test case here: https://github.com/timotheecour/dsnippet/blob/master/static_lib/

with dmd, this works:
make clean && make lib2 && make reexe2

with ldc, the same thing fails:
make clean && make lib2 && make reexe2

I need to be able to recompile a single file and update my static library/executable with the modified file.
dmd allows this but right now I'm getting errors with ldc:

duplicate symbol _main in:
    /tmp/d31//fun1.o
    /tmp/d31//libfun.a(libfun.o)

This is a major blocker for efficient partial recompilation.

NOTE:
I tried many alternatives for ldc without success, eg:
* http://www.manpages.info/macosx/ld.1.html (-multiply_defined suppress)
* using shared library instead with '-undefined supress -flat_namespace' (works great in simple cases; but in many cases gives obscure undefined errors when building the final executable without -undefined supress, eg on _aaApply)
* using 'ar -rcs libmylib.a *.o' followed after recompiling some object (eg fun1.o) by 'ar -rs libmylib.a fun1.o' => ignores the newly modified object files

**Comment by timotheecour** [comment]
friendly ping? is there any thought on this?
That's a blocker for efficient partial recompilation, which prevents me from switching to ldc.

**Comment by redstar** [comment]
Sorry for the delay - I was busy the last 2 weeks.
The problem is here: https://github.com/ldc-developers/ldc/blob/master/driver/main.cpp#L499
If `-of` and `-lib` are specified then this implies `-singleobj`. dmd does not make this implication but creates a lot of object files.

**Comment by redstar** [comment]
Fixed in master now. (I want happy LDC users!)

**Comment by timotheecour** [comment]
thanks!!
